import { Component, Input, OnInit, ViewEncapsulation } from '@angular/core';
import { FormControl } from '@angular/forms';

@Component({
  selector: 'app-fuel-details-item',
  templateUrl: './fuel-details-item.component.html',
  styleUrls: ['./fuel-details-item.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class FuelDetailsItemComponent implements OnInit {
  @Input() data: any;
  public noteControl: FormControl = new FormControl();
  public dummyDataVehicle: any[] = [];
  public dummyDataFuel: any[] = [];
  public dummyData: any;
  public tabsFuel: any[] = [];
  public selectedTab: number;
  constructor() {}

  ngOnInit(): void {
    this.initTableOptions();
    this.dummyDataVeh();
    this.dummyDataRep();
    this.noteControl.patchValue('Neki note fuel');
    this.tabsFuel = [
      {
        id: 221,
        name: '1M',
      },
      {
        id: 511,
        name: '3M',
      },
      {
        id: 416,
        name: '6M',
      },
      {
        id: 511,
        name: '1Y',
      },
      {
        id: 1224,
        name: 'YTD',
      },
      {
        id: 1902,
        name: 'ALL',
      },
    ];
  }
  /**Function for dots in cards */
  public initTableOptions(): void {
    this.dummyData = {
      disabledMutedStyle: null,
      toolbarActions: {
        hideViewMode: false,
      },
      config: {
        showSort: true,
        sortBy: '',
        sortDirection: '',
        disabledColumns: [0],
        minWidth: 60,
      },
      actions: [
        {
          title: 'Edit',
          name: 'edit',
          class: 'regular-text',
          contentType: 'edit',
        },

        {
          title: 'Delete',
          name: 'delete-item',
          type: 'driver',
          text: 'Are you sure you want to delete driver(s)?',
          class: 'delete-text',
          contentType: 'delete',
        },
      ],
      export: true,
    };
  }
  public dummyDataVeh() {
    this.dummyDataVehicle = [
      {
        unit: 'R53202',
        icon: 'assets/svg/truckassist-table/trailer/container.svg',
        key: '24',
        cost: '132,567,25',
      },
      {
        unit: 'R53202',
        icon: 'assets/svg/truckassist-table/trailer/gray-icons/car-hauler.svg',
        key: '54',
        cost: '132,567,25',
      },
      {
        unit: 'R53202',
        icon: 'assets/svg/truckassist-table/trailer/dumper.svg',
        key: '234',
        cost: '132,567,25',
      },
      {
        unit: 'R53202',
        icon: 'assets/svg/truckassist-table/trailer/gray-icons/reefer.svg',
        key: '42',
        cost: '132,567,25',
      },
    ];
  }
  public changeTab(ev: any) {
    this.selectedTab = ev.id;
  }
  public dummyDataRep() {
    this.dummyDataFuel = [
      {
        unit: 'R53201',
        driver: 'A. Djordjevic',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: false,
      },
      {
        unit: 'R53201',
        driver: 'A. Djordjevic',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: true,
      },
      {
        unit: 'R53201',
        driver: 'Angello Trotter',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: false,
      },
      {
        unit: 'R53201',
        driver: 'A. Djordjevic',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: true,
      },
      {
        unit: 'R53201',
        driver: 'Angello Trotter',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: false,
      },
      {
        unit: 'R53201',
        driver: 'A. Djordjevic',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: true,
      },
      {
        unit: 'R53201',
        driver: 'Angello Trotter',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: false,
      },
      {
        unit: 'R53201',
        driver: 'A. Djordjevic',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: true,
      },
      {
        unit: 'R53201',
        driver: 'Angello Trotter',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: false,
      },
      {
        unit: 'R53201',
        driver: 'A. Djordjevic',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: true,
      },
      {
        unit: 'R53201',
        driver: 'Angello Trotter',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: false,
      },
      {
        unit: 'R53201',
        driver: 'A. Djordjevic',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: true,
      },
      {
        unit: 'R53201',
        driver: 'Angello Trotter',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: false,
      },
      {
        unit: 'R53201',
        driver: 'A. Djordjevic',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: true,
      },
      {
        unit: 'R53201',
        driver: 'Angello Trotter',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: false,
      },
      {
        unit: 'R53201',
        driver: 'A. Djordjevic',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: true,
      },
      {
        unit: 'R53201',
        driver: 'Angello Trotter',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: false,
      },
      {
        unit: 'R53201',
        driver: 'A. Djordjevic',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: true,
      },
      {
        unit: 'R53201',
        driver: 'Angello Trotter',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: false,
      },
      {
        unit: 'R53201',
        driver: 'A. Djordjevic',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: true,
      },
      {
        unit: 'R53201',
        driver: 'Angello Trotter',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: false,
      },
      {
        unit: 'R53201',
        driver: 'A. Djordjevic',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: true,
      },
      {
        unit: 'R53201',
        driver: 'Angello Trotter',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: false,
      },
      {
        unit: 'R53201',
        driver: 'A. Djordjevic',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: true,
      },
      {
        unit: 'R53201',
        driver: 'Angello Trotter',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: false,
      },
      {
        unit: 'R53201',
        driver: 'A. Djordjevic',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: true,
      },
      {
        unit: 'R53201',
        driver: 'Angello Trotter',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: false,
      },
      {
        unit: 'R53201',
        driver: 'A. Djordjevic',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: true,
      },
      {
        unit: 'R53201',
        driver: 'Angello Trotter',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: false,
      },
      {
        unit: 'R53201',
        driver: 'A. Djordjevic',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: true,
      },
      {
        unit: 'R53201',
        driver: 'Angello Trotter',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: false,
      },
      {
        unit: 'R53201',
        driver: 'A. Djordjevic',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: true,
      },
      {
        unit: 'R53201',
        driver: 'Angello Trotter',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: false,
      },
      {
        unit: 'R53201',
        driver: 'A. Djordjevic',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: true,
      },
      {
        unit: 'R53201',
        driver: 'Angello Trotter',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: false,
      },
      {
        unit: 'R53201',
        driver: 'A. Djordjevic',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: true,
      },
      {
        unit: 'R53201',
        driver: 'Angello Trotter',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: false,
      },
      {
        unit: 'R53201',
        driver: 'A. Djordjevic',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: true,
      },
      {
        unit: 'R53201',
        driver: 'Angello Trotter',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: false,
      },
      {
        unit: 'R53201',
        driver: 'A. Djordjevic',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: true,
      },
      {
        unit: 'R53201',
        driver: 'Angello Trotter',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: false,
      },
      {
        unit: 'R53201',
        driver: 'A. Djordjevic',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: true,
      },
      {
        unit: 'R53201',
        driver: 'Angello Trotter',
        fuel_card: '8732...233',
        date: '08/10/20',
        time: '10:01 AM',
        category: 'Diesel ● DEF ● Scale Tick…',
        fuel_g: '25.74',
        ppg: '4.55',
        icon: 'assets/svg/common/round_blue_light.svg',
        cost: '785.53',
        blue_back: false,
      },
    ];
  }
}
