export enum ConfirmationModalStringEnum {
    ARE_YOU_SURE = 'Are you sure you want to',
    DELETE_SELECTED = 'delete selected',
    SELECTED = 'selected',
    REPAIRS_ORDERS = 'repairs / orders',
    REPAIR_ORDER = 'repair / order',
    REPAIR_SHOPS = 'repair shops',
    REPAIR_SHOP = 'repair shop',
    DELETE_REPAIR = 'Delete Repair',
    DELETE_ORDER = 'Delete Order',
    DELETE_BROKER = 'Delete Broker',
    DELETE_SHIPPER = 'Delete Shipper',
    REPAIR_SHOP_REVIEW = 'repair shop review',
    BROKER_REVIEW = 'broker review',
    SHIPPER_REVIEW = 'shipper review',
    QUESTION_MARK = '?',
    VOID_CDL = 'Void CDL',
    ACTIVATE_CDL = 'Activate CDL',
    SELECTED_DRIVER = 'selected driver',
    DELETE_DEDUCTION = 'Delete Deduction',
    DELETE_CREDIT = 'Delete Credit',
    DELETE_BONUS = 'Delete Bonus',
    DELETE_FUEL = 'Delete Fuel'
}
