export class LoadStoreConstants {
    static COMPONENT_NAME_KEY = '[Load Store]';
    public static ACTION_DISPATCH_LOAD_LIST = `${this.COMPONENT_NAME_KEY} ACTION_DISPATCH_LOAD_LIST`;
    public static ACTION_LOAD_LIST_SUCCESS = `${this.COMPONENT_NAME_KEY} ACTION_LOAD_LIST_SUCCESS`;

    //#region Toolbar actions
    public static ACTION_DISPATCH_LOAD_TYPE_CHANGE = `${this.COMPONENT_NAME_KEY} ACTION_DISPATCH_LOAD_TYPE_CHANGE`;
    public static ACTION_DISPATCH_VIEW_MODE_CHANGE = `${this.COMPONENT_NAME_KEY} ACTION_DISPATCH_VIEW_MODE_CHANGE`;
    public static ACTION_SET_TOOLBAR_DROPDOWN_MENU_COLUMNS_ACTIVE = `${this.COMPONENT_NAME_KEY} ACTION_SET_TOOLBAR_DROPDOWN_MENU_COLUMNS_ACTIVE`;
    public static ACTION_TOGGLE_COLUMN_VISIBILITY = `${this.COMPONENT_NAME_KEY} ACTION_TOGGLE_COLUMN_VISIBILITY`;
    public static ACTION_TABLE_UNLOCK_TOGGLE = `${this.COMPONENT_NAME_KEY} ACTION_TABLE_UNLOCK_TOGGLE`;
    public static ACTION_RESET_COLUMNS = `${this.COMPONENT_NAME_KEY} ACTION_RESET_COLUMNS`;
    public static ACTION_TOGGLE_CARD_FLIP_VIEW_MODE = `${this.COMPONENT_NAME_KEY} ACTION_TOGGLE_CARD_FLIP_VIEW_MODE`;
    //#endregion

    //#region Filters
    public static ACTION_FILTER_CHANGED = `${this.COMPONENT_NAME_KEY} ACTION_FILTER_CHANGED`;
    public static ACTION_SET_FILTER_DROPDOPWN_LIST = `${this.COMPONENT_NAME_KEY} ACTION_SET_FILTER_DROPDOPWN_LIST`;
    //#region

    //#region Search
    public static ACTION_SEARCH_FILTER_CHANGED = `${this.COMPONENT_NAME_KEY} ACTION_SEARCH_FILTER_CHANGED`;
    //#region

    //#region Modal
    public static ACTION_OPEN_LOAD_MODAL = `${this.COMPONENT_NAME_KEY} ACTION_OPEN_LOAD_MODAL`;
    //#endregion

    //#region Load details
    public static ACTION_GO_TO_LOAD_DETAILS = `${this.COMPONENT_NAME_KEY} ACTION_GO_TO_LOAD_DETAILS`;
    public static ACTION_GET_LOAD_BY_ID = `${this.COMPONENT_NAME_KEY} ACTION_GET_LOAD_BY_ID`;
    public static ACTION_GET_LOAD_BY_ID_SUCCESS = `${this.COMPONENT_NAME_KEY} ACTION_GET_LOAD_BY_ID_SUCCESS`;
    public static ACTION_GET_LOAD_BY_ID_ERROR = `${this.COMPONENT_NAME_KEY} ACTION_GET_LOAD_BY_ID_ERROR`;
    public static ACTION_TOGGLE_MAP = `${this.COMPONENT_NAME_KEY} ACTION_TOGGLE_MAP`;
    public static ACTION_GET_MAP_ROUTING = `${this.COMPONENT_NAME_KEY} ACTION_GET_MAP_ROUTING`;

    //#endregion

    //#region Change load status
    static ACTION_UPDATE_LOAD_STATUS = `${this.COMPONENT_NAME_KEY} ACTION_UPDATE_LOAD_STATUS`;
    static ACTION_UPDATE_LOAD_STATUS_SUCCESS = `${this.COMPONENT_NAME_KEY} ACTION_UPDATE_LOAD_STATUS_SUCCESS`;
    static ACTION_UPDATE_LOAD_STATUS_ERROR = `${this.COMPONENT_NAME_KEY} ACTION_UPDATE_LOAD_STATUS_ERROR`;

    static ACTION_REVERT_LOAD_STATUS = `${this.COMPONENT_NAME_KEY} ACTION_REVERT_LOAD_STATUS`;
    static ACTION_REVERT_LOAD_STATUS_SUCCESS = `${this.COMPONENT_NAME_KEY} ACTION_REVERT_LOAD_STATUS_SUCCESS`;
    static ACTION_REVERT_LOAD_STATUS_ERROR = `${this.COMPONENT_NAME_KEY} ACTION_REVERT_LOAD_STATUS_ERROR`;

    static ACTION_OPEN_CHANGE_STATUS_DROPDOWN = `${this.COMPONENT_NAME_KEY} ACTION_OPEN_CHANGE_STATUS_DROPDOWN`;
    static ACTION_OPEN_CHANGE_STATUS_DROPDOWN_SUCCESS = `${this.COMPONENT_NAME_KEY} ACTION_OPEN_CHANGE_STATUS_DROPDOWN_SUCCESS`;
    static ACTION_OPEN_CHANGE_STATUS_DROPDOWN_ERROR = `${this.COMPONENT_NAME_KEY} ACTION_OPEN_CHANGE_STATUS_DROPDOWN_ERROR`;
    //#endregion
    
    //#region List
    public static ACTION_ON_ONE_LOAD_SELECT = `${this.COMPONENT_NAME_KEY} ACTION_ON_ONE_LOAD_SELECT`;
    public static ACTION_ON_SELECT_LOAD_ALL = `${this.COMPONENT_NAME_KEY} ACTION_ON_SELECT_LOAD_ALL`;
    //#endregion

    //#region Delete
    public static ACTION_ON_DELETE_LOAD_LIST = `${this.COMPONENT_NAME_KEY} ACTION_ON_DELETE_LOAD_LIST`;
    public static ACTION_ON_DELETE_LOAD_LIST_SUCCESS = `${this.COMPONENT_NAME_KEY} ACTION_ON_DELETE_LOAD_LIST_SUCCESS`;
    public static ACTION_ON_DELETE_LOAD_TEMPLATE = `${this.COMPONENT_NAME_KEY} ACTION_ON_DELETE_LOAD_TEMPLATE`;
    public static ACTION_ON_DELETE_LOAD_TEMPLATE_SUCCESS = `${this.COMPONENT_NAME_KEY} ACTION_ON_DELETE_LOAD_TEMPLATE_SUCCESS`;

    //#endregion
}
