export class BrokerDetailsSvgRoutes {
    static clockIcon = 'assets/svg/common/ic_clock.svg';
    static searchIcon = 'assets/svg/common/ic_search.svg';
    static brokerUserIcon = 'assets/svg/common/ic_broker-user.svg';
    static halfCircleIcon = 'assets/svg/common/ic_broker-half-circle.svg';
    static locationIcon = 'assets/svg/truckassist-table/location-icon.svg';
    static dollarIcon = 'assets/svg/common/ic_dollar.svg';
    static editIcon = 'assets/svg/truckassist-table/dropdown/content/edit.svg';
    static plusIcon = 'assets/svg/common/ic_plus.svg';
    static avatarIcon = 'assets/svg/truckassist-table/customer/contact-column-avatar.svg';
    static reviewIcon = 'assets/svg/common/review-pen.svg';
    static disableStatusIcon = 'assets/svg/common/ic_disable-status.svg';
    static shareIcon = 'assets/svg/common/share-icon.svg';
    static printIcon = 'assets/svg/common/ic_fax.svg';
    static closeBusinessIcon = 'assets/svg/common/close-business-icon.svg';
    static deleteIcon = 'assets/svg/common/ic_trash_updated.svg';
    static profileIcon = 'assets/svg/common/ic_profile.svg';
    static hazardousInfoIcon = 'assets/svg/common/ic_hazardous-info.svg';
}
