/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CdlReviewResponse } from './cdlReviewResponse';
import { CdlLicenseResponse } from './cdlLicenseResponse';


export interface CdlFeedbackResponse { 
    id?: number;
    cdlDenied?: boolean;
    cdlDeniedExplanation?: string | null;
    reviewed?: boolean | null;
    approved?: boolean | null;
    licences?: Array<CdlLicenseResponse> | null;
    cdlInformationReview?: CdlReviewResponse;
    applicantId?: number;
}

