/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoadRequirementsCommand { 
    id?: number | null;
    truckTypeId?: number | null;
    trailerTypeId?: number | null;
    doorType?: number | null;
    suspension?: number | null;
    trailerLengthId?: number | null;
    year?: number | null;
    liftgate?: boolean | null;
    driverMessage?: string | null;
}

