import { ICardValueData } from '@shared/interfaces';
import { CardDefaultValuesHelper } from '@shared/utils/helpers';

export class LoadCardDataConfig {
    static CARD_ALL_DATA: ICardValueData[] = [
        {
            title: 'Type',
            key: 'truckType.name',
            image: 'truckType.logoName',
            template: 'textWithImage',
            format: 'text',
        },
        {
            title: 'Dispatcher',
            key: 'truckType.name',
            image: 'truckType.logoName',
            template: 'textWithImage',
            format: 'text',
        },
        {
            title: 'Company',
            key: 'revenue',
            template: 'textWithTitle',
        },
        {
            isDropdown: true,
            title: 'Broker Detail',
            values: [
                {
                    title: 'Broker Detail • Business Name',
                    secondTitle: 'Name',
                    key: 'stopsCount',
                    template: 'textWithTitle',
                },
                {
                    title: 'Broker Detail • Contact',
                    secondTitle: 'Contact',
                    key: 'stopsCount',
                    template: 'textWithTitle',
                },
                {
                    title: 'Broker Detail • Phone',
                    secondTitle: 'Phone',
                    key: 'stopsCount',
                    template: 'textWithTitle',
                },
            ],
        },
        {
            title: 'Ref Number',
            key: 'loadCount',
            template: 'textWithTitle',
        },
        {
            title: 'Commodity',
            key: 'loadCount',
            template: 'textWithTitle',
        },
        {
            title: 'Weight',
            key: 'loadCount',
            template: 'textWithTitle',
        },
        {
            isDropdown: true,
            title: 'Assigned',
            values: [
                {
                    title: 'Assigned • Driver',
                    secondTitle: 'Driver',
                    key: 'fuelGalons',
                    template: 'textWithTitle',
                    format: 'number',
                },
                {
                    title: 'Assigned • Truck',
                    secondTitle: 'Truck',
                    key: 'fuelCost',
                    template: 'textWithTitle',
                    format: 'currency',
                },
                {
                    title: 'Assigned • Trailer',
                    secondTitle: 'Trailer',
                    key: 'fuelMpg',
                    template: 'fuelMpg',
                    format: 'number',
                },
            ],
        },
        {
            title: 'Status',
            key: 'stopsCount',
            template: 'loadStatus',
            format: 'data',
        },
        {
            title: 'Pickup',
            key: 'pickup',
            template: 'pickupDelivery',
            format: 'data',
        },
        {
            title: 'Delivery',
            key: 'delivery',
            template: 'pickupDelivery',
            format: 'data',
        },
        {
            isDropdown: true,
            title: 'Requirement',
            values: [
                {
                    title: 'Requirement • Truck Type',
                    secondTitle: 'Truck Type',
                    key: 'milesLoaded',
                    template: 'textWithTitle',
                    format: 'number',
                },
                {
                    title: 'Requirement • Trailer Type',
                    secondTitle: 'Trailer Type',
                    key: 'milesLoaded',
                    template: 'textWithTitle',
                    format: 'number',
                },
                {
                    title: 'Requirement • Length',
                    secondTitle: 'Length',
                    key: 'milesLoaded',
                    template: 'textWithTitle',
                    format: 'number',
                },
                {
                    title: 'Requirement • Door Type',
                    secondTitle: 'Door Type',
                    key: 'milesLoaded',
                    template: 'textWithTitle',
                    format: 'number',
                },
                {
                    title: 'Requirement • Suspension',
                    secondTitle: 'Suspension',
                    key: 'milesLoaded',
                    template: 'textWithTitle',
                    format: 'number',
                },
                {
                    title: 'Requirement • Year',
                    secondTitle: 'Year',
                    key: 'milesLoaded',
                    template: 'textWithTitle',
                    format: 'number',
                },
                {
                    title: 'Requirement • Liftgate',
                    secondTitle: 'Liftgate',
                    key: 'milesLoaded',
                    template: 'textWithTitle',
                    format: 'number',
                },
            ],
        },
        {
            isDropdown: true,
            title: 'Miles',
            values: [
                {
                    title: 'Miles • Loaded',
                    secondTitle: 'Loaded',
                    key: 'milesLoaded',
                    template: 'textWithTitle',
                    format: 'number',
                },
                {
                    title: 'Miles • Empty',
                    secondTitle: 'Empty',
                    key: 'milesEmpty',
                    template: 'textWithTitle',
                    format: 'number',
                },
                {
                    title: 'Miles • Total',
                    secondTitle: 'Total',
                    key: 'milesTotal',
                    template: 'textWithTitle',
                    format: 'number',
                },
            ],
        },
        {
            isDropdown: true,
            title: 'Billing',
            values: [
                {
                    title: 'Billing • Pay Term',
                    secondTitle: 'Pay Term',
                    key: 'milesLoaded',
                    template: 'textWithTitle',
                    format: 'number',
                },
                {
                    title: 'Billing • Age - Unpaid',
                    secondTitle: 'Age - Unpaid',
                    key: 'milesLoaded',
                    template: 'textWithTitle',
                    format: 'number',
                },
                {
                    title: 'Billing • Age - Paid',
                    secondTitle: 'Age - Paid',
                    key: 'milesLoaded',
                    template: 'textWithTitle',
                    format: 'number',
                },
                {
                    title: 'Billing • Rate Per Mile',
                    secondTitle: 'Rate Per Mile',
                    key: 'milesLoaded',
                    template: 'textWithTitle',
                    format: 'number',
                },
                {
                    title: 'Billing • Layover',
                    secondTitle: 'Layover',
                    key: 'milesLoaded',
                    template: 'textWithTitle',
                    format: 'number',
                },
                {
                    title: 'Billing • Lumper',
                    secondTitle: 'Lumper',
                    key: 'milesLoaded',
                    template: 'textWithTitle',
                    format: 'number',
                },
                {
                    title: 'Billing • Fuel Surcharge',
                    secondTitle: 'Fuel Surcharge',
                    key: 'milesLoaded',
                    template: 'textWithTitle',
                    format: 'number',
                },
                {
                    title: 'Billing • Escort',
                    secondTitle: 'Escort',
                    key: 'milesLoaded',
                    template: 'textWithTitle',
                    format: 'number',
                },
                {
                    title: 'Billing • Detention',
                    secondTitle: 'Detention',
                    key: 'milesLoaded',
                    template: 'textWithTitle',
                    format: 'number',
                },
                {
                    title: 'Billing • Rate',
                    secondTitle: 'Rate',
                    key: 'milesLoaded',
                    template: 'textWithTitle',
                    format: 'number',
                },
                {
                    title: 'Billing • Paid',
                    secondTitle: 'Paid',
                    key: 'milesLoaded',
                    template: 'textWithTitle',
                    format: 'number',
                },
                {
                    title: 'Billing • Due',
                    secondTitle: 'Due',
                    key: 'milesLoaded',
                    template: 'textWithTitle',
                    format: 'number',
                },
            ],
        },
        {
            title: 'Invoice Date',
            key: 'revenue',
            template: 'textWithTitle',
            format: 'date',
        },
        {
            title: 'Paid Date',
            key: 'revenue',
            template: 'textWithTitle',
            format: 'date',
        },
        {
            title: 'Date Added',
            key: 'revenue',
            template: 'textWithTitle',
            format: 'date',
        },
        {
            title: 'Date Edited',
            key: 'revenue',
            template: 'textWithTitle',
            format: 'date',
        },
    ];
}
