// enums
import { DashboardStringEnum } from '@pages/dashboard/enums/dashboard-string.enum';

// models
import { DashboardTab } from '@pages/dashboard/models/dashboard-tab.model';
import { PerformanceDataItem } from '@pages/dashboard/pages/dashboard-performance/models/performance-data-item.model';

export class DashboardPerformanceConstants {
    static PERFORMANCE_TABS: DashboardTab[] = [
        {
            name: DashboardStringEnum.TODAY,
            checked: false,
        },
        {
            name: DashboardStringEnum.WTD,
            checked: false,
        },
        {
            name: DashboardStringEnum.MTD,
            checked: false,
        },
        {
            name: DashboardStringEnum.QTD,
            checked: false,
        },
        {
            name: DashboardStringEnum.YTD,
            checked: false,
        },
        {
            name: DashboardStringEnum.ALL,
            checked: true,
        },
        {
            name: DashboardStringEnum.CUSTOM,
            checked: false,
            custom: true,
        },
    ];

    static TREND_LIST: string[] = [
        DashboardStringEnum.NET_INCOME,
        DashboardStringEnum.REVENUE_2,
        DashboardStringEnum.LOAD_2,
        DashboardStringEnum.MILES,
        DashboardStringEnum.ROADSIDE_INSP,
        DashboardStringEnum.DRIVER_2,
        DashboardStringEnum.TRUCK_2,
        DashboardStringEnum.TRAILER,
        DashboardStringEnum.OWNER_2,
        DashboardStringEnum.USER_2,
        DashboardStringEnum.REPAIR_SHOP_2,
        DashboardStringEnum.BROKER_2,
        DashboardStringEnum.SHIPPER_2,
    ];

    static TREND_LIST_2: string[] = [
        DashboardStringEnum.EXPENSES,
        DashboardStringEnum.FUEL_GALLON,
        DashboardStringEnum.FUEL_COST,
        DashboardStringEnum.REPAIR_COST,
        DashboardStringEnum.VIOALTION,
        DashboardStringEnum.ACCIDENT,
    ];

    static PERFROMANCE_DATA: PerformanceDataItem[] = [
        {
            title: DashboardStringEnum.NET_INCOME,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [
                2, 8, 3, 3, 7, 0, 0, 8, 7, 5, 7, 1, 1, 3, 4, 6, 1, 1, 5, 5, 9,
                0, 2,
            ],
        },
        {
            title: DashboardStringEnum.REVENUE_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: DashboardStringEnum.LOAD_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: DashboardStringEnum.MILES,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: DashboardStringEnum.FUEL_GALLON,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: DashboardStringEnum.FUEL_COST,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: DashboardStringEnum.REPAIR_COST,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: DashboardStringEnum.ROADSIDE_INSP,
            isSelected: false,
            isHovered: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: DashboardStringEnum.VIOALTION,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: DashboardStringEnum.ACCIDENT,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: DashboardStringEnum.EXPENSES,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [
                23, 8, 3, 11, 7, 0, 44, 45, 46, 5, 7, 13, 18, 33, 42, 6, 10, 19,
                5, 5, 9, 40, 22,
            ],
        },
        {
            title: DashboardStringEnum.DRIVER_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: DashboardStringEnum.TRUCK_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: DashboardStringEnum.TRAILER,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: DashboardStringEnum.OWNER_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: DashboardStringEnum.USER_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: DashboardStringEnum.REPAIR_SHOP_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: DashboardStringEnum.BROKER_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: DashboardStringEnum.SHIPPER_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
    ];
}
