export enum DropdownMenuStringEnum {
    // titles
    EDIT_LOAD = 'Edit Load',
    EDIT_PAYROLL = 'Edit Payroll',
    SHARE = 'Share',
    PRINT = 'Print',
    PREVIEW_REPORT = 'Preview Report',
    DOWNLOAD = 'Download',
    RESEND_REPORT = 'Resend Report',
    EDIT = 'Edit',
    DELETE = 'Delete',
    GO_TO_LINK = 'Go to Link',
    NO_LINK = 'No Link',
    COPY_USERNAME = 'Copy Username',
    COPY_PASSWORD = 'Copy Password',
    VIEW_DETAILS = 'View Details',
    DEACTIVATE = 'Deactivate',
    ACTIVATE = 'Activate',
    SEND_MESSAGE = 'Send Message',
    ADD_NEW = 'Add New',
    CDL = 'CDL',
    TEST = 'Test (Drug, Alcohol)',
    MEDICAL_EXAM = 'Medical Exam',
    MVR = 'MVR',
    REQUEST = 'Request',
    BACKGROUND_CHECK = 'Background Check',
    REGISTRATION = 'Registration',
    FHWA_INSPECTION = 'FHWA Inspection',
    TITLE = 'Title',
    LEASE_RENT = 'Lease / Rent',

    // types
    EDIT_LOAD_TYPE = 'edit-load',
    EDIT_PAYROLL_TYPE = 'edit-payroll',
    SHARE_TYPE = 'share',
    PRINT_TYPE = 'print',
    PREVIEW_REPORT_TYPE = 'preview-report',
    DOWNLOAD_TYPE = 'download',
    RESEND_REPORT_TYPE = 'resend-report',
    EDIT_TYPE = 'edit',
    DELETE_TYPE = 'delete',
    GO_TO_LINK_TYPE = 'go-to-link',
    NO_LINK_TYPE = 'no-link',
    COPY_USERNAME_TYPE = 'copy-username',
    COPY_PASSWORD_TYPE = 'copy-password',
    VIEW_DETAILS_TYPE = 'view-details',
    DEACTIVATE_TYPE = 'deactivate',
    ACTIVATE_TYPE = 'activate',
    SEND_MESSAGE_TYPE = 'send-message',
    ADD_NEW_TYPE = 'add-new',
    CDL_TYPE = 'cdl',
    TEST_TYPE = 'test',
    MEDICAL_EXAM_TYPE = 'medical-exam',
    MVR_TYPE = 'mvr',
    REQUEST_TYPE = 'request',
    BACKGROUND_CHECK_TYPE = 'background-check',
    REGISTRATION_TYPE = 'registration',
    FHWA_INSPECTION_TYPE = 'fhwa-inspection',
    TITLE_TYPE = 'title',
    LEASE_RENT_TYPE = 'lease-rent',

    // svg classes
    REGULAR = 'regular',

    // conditions
    ACTIVE = 'active',
    ADD_NEW_DRIVER = 'add-new-driver',
    ADD_NEW_TRUCK_TRAILER = 'add-new-truck-trailer',
    DRIVER = 'driver',

    // additional
    BLANK = '_blank',
    SHOW_MORE = 'show-more',
    CREATE_LABEL = 'create-label',
    UPDATE_LABEL = 'update-label',
}
