export enum DropActionsStringEnum {
    // Actions
    EDIT = 'edit',
    DELETE = 'delete',
    DELETE_ITEM = 'delete-item',
    ACTIVATE = 'activate',
    ACTIVATE_2 = 'Activate',
    DEACTIVATE = 'deactivate',
    DEACTIVATE_ITEM = 'deactivate-item',
    ACTIVATE_ITEM = 'activate-item',
    OPEN_BUSINESS = 'open-business',
    CLOSE_BUSINESS = 'close-business',
    VOID = 'void',
    RENEW = 'renew',
    FAVORITE = 'favorite',
    MOVE = 'move',
    REMOVE = 'remove',

    // Templates
    INFO = 'info',
    CDL = 'cdl',
    CDL_2 = 'CDL',
    MEDICAL = 'medical',
    MVR = 'mvr',
    TEST = 'test',
    INSPECTION = 'inspection',
    REGISTRATION = 'registration',
    TITLE = 'title',
    TRUCK = 'truck',
    TRAILER = 'trailer',
    DRIVER = 'driver',
    REPAIR = 'repair',
    REPAIR_2 = 'Repair',
    REPAIR_DETAIL = 'repair-detail',
    REPAIR_SHOP = 'repair shop',
    REPAIR_SHOP_2 = 'Repair Shop',
    SPECIFIC_REPAIR_SHOP = 'specific-repair-shop',
    ORDER = 'Order',
    COMPANY_PARKING = 'Company Parking',
    COMPANY_OFFICE = 'Company Office',
    COMPANY_REPAIR_SHOP = 'Company Repair Shop',
    COMPANY_TERMINAL = 'Company Terminal',
    TEMPLATE = 'template',
    TEMPLATES = 'templates',

    // Delete titles
    DELETE_MEDICAL_TITLE = 'Delete Medical',
    DELETE_TEST_TITLE = 'Delete Test',
    DELETE_CDL_TITLE = 'Delete CDL',
    DELETE_MVR_TITLE = 'Delete MVR',

    // Delete actions
    DELETE_CDL = 'delete-cdl',
    DELETE_MEDICAL = 'delete-medical',
    DELETE_MVR = 'delete-mvr',
    DELETE_TEST = 'delete-test',
    DELETE_INSPECTION = 'delete-inspection',
    DELETE_REGISTRATION = 'delete-registration',
    DELETE_TITLE = 'delete-title',
    DELETE_REPAIR = 'delete-repair',
    DELETE_REPAIR_DETAIL = 'delete-repair-detail',
    DELETE_REPAIR_SHOP = 'delete-repair-shop',
    DELETE_PARKING = 'delete-parking',
    DELETE_OFFICE = 'delete-office',
    DELETE_TERMINAL = 'delete-terminal',

    // Edit actions
    EDIT_LICENCE = 'edit-licence',
    EDIT_DRUG = 'edit-drug',
    EDIT_MEDICAL = 'edit-medical',
    EDIT_MVR = 'edit-mvr',
    EDIT_REGISTRATION = 'edit-registration',
    EDIT_INSPECTION = 'edit-inspection',
    EDIT_TITLE = 'edit-title',
    EDIT_REPAIR = 'edit-repair',
    EDIT_PARKING = 'edit-parking',
    EDIT_OFFICE = 'edit-office',
    EDIT_REPAIR_SHOP = 'edit-repair-shop',
    EDIT_TERMINAL = 'edit-terminal',

    // Favourite actions
    ADD_FAVOURITES = 'add-favourites',
    REMOVE_FAVOURITES = 'remove-favourites',
    REMOVE_FROM_FAVOURITE = 'remove-from-favourite',
    MOVE_TO_FAVOURITE = 'move-to-favourite',

    // Other
    RENEW_LICENCE = 'renew-licence',
    CDL_VOID = 'cdl void',
    VOID_CDL = 'void cdl',
    NEW = 'New',
    RENEW_2 = 'Renew',
    EMPTY_SPACE_STRING = ' ',
    TERMINAL = 'terminal',
    PARKING = 'parking',
    OFFICE = 'office',

    // Size
    SMALL = 'small',
    LARGE = 'large',
}
