export enum eGeneralActions {
    ADD = 'add',
    UPDATE = 'update',
    DELETE_LOWERCASE = 'delete',
    DELETE = 'Delete',
    EDIT = 'Edit',
    EDIT_LOWERCASE = 'edit',
    CANCEL = 'cancel',
    CANCEL_CAPITALIZED = 'Cancel',
    ENTER = 'Enter',
    ESCAPE = 'Escape',
    CONFIRM = 'Confirm',
    CONFIRM_LOWERCASE = 'confirm',
    CONFIRM_EDIT = 'Confirm Edit',
    ACTIVATE = 'activate',
    DEACTIVATE = 'deactivate',
    CLOSE = 'close',
    OPEN = 'open',
    OPEN_CAPITALIZED = 'Open',
    SAVE = 'save',
    NEXT = 'Next',
    NEXT_LOWERCASE = 'next',
    PREVIOUS = 'Previous',
    PREVIOUS_LOWERCASE = 'previous',

    SELECT_ALL = 'Select All',
    SELECT_REMAINING = 'Select Remaining',
    CLEAR_SELECTED = 'Clear Selected',

    SHOW_MORE = 'show more',

    OPEN_MODAL = 'open-modal',
    RESET_MODAL = 'reset modal',
    RESET = 'reset',
    TAB_SELECTED = 'tab-selected',
    VIEW_MODE = 'view-mode',

    DOWNLOAD = 'Download',

    SAVE_AND_ADD_NEW = 'save and add new',
    CONVERT_TO_LOAD = 'Convert to Load',
    CONVERT_TO_TEMPLATE = 'Convert To Template',
}
