export enum ModalTableTypeEnum {
    PHONE = 'PHONE',
    EMAIL = 'EMAIL',
    REPAIR_BILL = 'REPAIR_BILL',
    REPAIR_ORDER = 'REPAIR_ORDER',
    CONTACT = 'CONTACT',
    DEPARTMENT_CONTACT = 'DEPARTMENT_CONTACT',
    PM_TRUCK = 'PM_TRUCK',
    PM_TRAILER = 'PM_TRAILER',
    OFF_DUTY_LOCATION = 'OFF_DUTY_LOCATION',
    FUEL_CARD = 'FUEL_CARD',
    PREVIOUS_ADDRESSES = 'PREVIOUS_ADDRESSES',
    LOAD_ITEMS = 'LOAD_ITEMS',
}
