export enum ModalTableSubTypeEnum {
    BROKER_CONTACTS = 'BROKER_CONTACTS',
    SHIPPER_CONTACTS = 'SHIPPER_CONTACTS',
    REPAIR_SHOP_CONTACTS = 'REPAIR_SHOP_CONTACTS',
    SETTINGS_OFFICE_CONTACTS = 'SETTINGS_OFFICE_CONTACTS',
}
