export enum eStringPlaceholder {
    EMPTY = '',
    WHITESPACE = ' ',
    DASH = '-',
    COMMA_WHITESPACE = ', ',
    DOT = '.',
    FORWARD_SLASH = '/',
    DOLLAR_SIGN = '$',
    PERCENTAGE_SIGN = '%',
    ELLIPSIS = '...',
    NA = 'N/A',
    NONE = 'None',
    GI = 'gi',
    NA_UPPERCASE = 'NA',
    ZERO = '0',
}
