export enum TableActionsStringEnum {
    SHOW_MORE = 'show-more',
    OPEN_MODAL = 'open-modal',
    VIEW_MODE = 'view-mode',
    TAB_SELECTED = 'tab-selected',
    DELETE_MULTIPLE = 'delete-multiple',
    DEACTIVATE_MULTIPLE = 'multiple-deactivate',
    UPDATE = 'update',
    DELETE = 'delete',
    API = 'api',
    STORE = 'store',
    ACTIVE = 'active',
    ADD = 'add',
    LIST = 'List',
    CARD = 'Card',
    SORT = 'sort',
    TABLE_CONTAINER = 'table-container',
    INACTIVE = 'inactive',
    OWNER_TABLE_COUNT = 'ownerTableCount',
    CLOSED_ARRAY = 'closedArray',
}
