import { TruckAdditionalData } from '@pages/truck/pages/truck-table/models/truck-additional-data.model';
import { TruckFHWA } from '@pages/truck/pages/truck-table/models/truck-fhwa.model';
import { TruckLeasePurchase } from '@pages/truck/pages/truck-table/models/truck-lease-purchase.model';
import { TruckOwner } from '@pages/truck/pages/truck-table/models/truck-owner.model';
import { TruckRegistration } from '@pages/truck/pages/truck-table/models/truck-registration.model';
import { TruckTitle } from '@pages/truck/pages/truck-table/models/truck-title.model';

export interface TruckMapped {
    id: number;
    companyId: number;
    divisinFlag: number;
    companyOwned: number;
    ownerId: number;
    truckNumber: string;
    vin: string;
    year: number;
    categoryId: string | number | null;
    category: string | null;
    make: string;
    model: string;
    licensePlate: string;
    licenseExpData: string;
    colorName: string;
    colorCode: string;
    svgIcons: string;
    svgClass: string;
    length: string | number | null;
    fhwaInsepction: string;
    status: number;
    used: number;
    canBeUsedByCompany: number;
    location: string | null;
    longgitude: string | null;
    latitude: string | null;
    devideId: number | null;
    uniqueId: number | null;
    percentage: number | null;
    doc: any;
    mileage: number | null;
    additionData: TruckAdditionalData;
    registrationData: TruckRegistration[];
    fhwaData: TruckFHWA[];
    titleData: TruckTitle[];
    purchaseData: TruckLeasePurchase[];
    ownerData: TruckOwner;
    note: any;
    tableRegistrationData: TruckRegistration;
    tableFhwaData: TruckFHWA;
    tableTitleData: TruckTitle;
    tableLeaseData: TruckLeasePurchase;
    isSelected: boolean;
    tableVin: { boldText: string; regularText: string };
    truckTypeIcon: string;
}
