export enum eUserModalForm {
    EMAIL = 'email',
    FIRST_NAME = 'firstName',
    LAST_NAME = 'lastName',
    DEPARTMENT = 'departmentId',
    IS_ADMIN = 'isAdmin',
    OFFICE = 'companyOfficeId',
    PHONE = 'phone',
    PHONE_EXTENSION = 'extensionPhone',
    PERSONAL_PHONE = 'personalPhone',
    PERSONAL_EMAIL = 'personalEmail',
    ADDRESS = 'address',
    ADDRESS_UNIT = 'addressUnit',
    NOTE = 'note',
    START_DATE = 'startDate',
    PAYMENT_TYPE = 'paymentType',
    SALARY = 'salary',
    BASE = 'base',
    IS_1099 = 'is1099',
    INCLUDED_IN_PAYROLL = 'includeInPayroll',
    BANK_NAME = 'bankId',
    ROUTING = 'routingNumber',
    ACCOUNT = 'accountNumber',
    COMMISSION = 'commission',
}
