export enum eUserModalForm {
    EMAIL = 'email',
    FIRST_NAME = 'firstName',
    LAST_NAME = 'lastName',
    DEPARTMENT = 'departmentId',
    IS_ADMIN = 'isAdmin',
    OFFICE = 'officeId',
    PHONE = 'phone',
    PHONE_EXTENSION = 'extensionPhone',
    PERSONAL_PHONE = 'personalPhone',
    PERSONAL_EMAIL = 'personalEmail',
    ADDRESS = 'address',
    ADDRESS_UNIT = 'addressUnit',
    NOTE = 'note',
}
