export enum eUserModalForm {
    EMAIL = 'email',
    FIRST_NAME = 'firstName',
    LAST_NAME = 'lastName',
    DEPARTMENT = 'departmentId',
    IS_ADMIN = 'isAdmin',
    OFFICE = 'officeId',
    PHONE = 'phone',
    PHONE_EXTENSION = 'extensionPhone',
    PERSONAL_PHONE = 'personalPhone',
    PERSONAL_EMAIL = 'personalEmail',
    START_DATE = 'startDate',
    SALARY = 'salary',
    IS_1099 = 'is1099',
}
