export enum TaModalTableStringEnum {
    PHONE_TABLE_ITEMS = 'phoneTableItems',
    EMAIL_TABLE_ITEMS = 'emailTableItems',
    REPAIR_BILL_TABLE_ITEMS = 'repairBillTableItems',
    REPAIR_ORDER_TABLE_ITEMS = 'repairOrderTableItems',
    CONTACT_TABLE_ITEMS = 'contactTableItems',
    PM_TABLE_ITEMS = 'pmTableItems',
    OFF_DUTY_LOCATION_TABLE_ITEMS = 'offDutyLocationTableItems',
    FUEL_CARD_TABLE_ITEMS = 'fuelCardTableItems',
    PREVIOUS_ADDRESSES_TABLE_ITEMS = 'previousAddressesTableItems',
    LOAD_MODAL_TABLE_ITEMS = 'loadModalTableItems',
    PRICE = 'price',
    CONTACT_PHONE_TYPE = 'contact-phone-type',
    CONTACT_EMAIL_TYPE = 'contact-email-type',
    CONTACT_DEPARTMENT_TYPE = 'contact-department-type',
    PM_TRUCK_TYPE = 'pm-truck-type',
    PM_TRAILER_TYPE = 'pm-trailer-type',
    PM_TRUCK_TRAILER_REPAIR_TYPE = 'pm-truck-trailer-repair-type',
    ADDRESS = 'address',
    FUEL_CARD_TYPE = 'fuel-card-type',
    EMAIL = 'email',
    VALID = 'VALID',
    TARP = 'tarp',
    SECURE = 'secure',
    DESCRIPTION = 'description',
    HAZARDOUS = 'hazardousMaterialId',
    DEPARTMENT_CONTACT = 'departmentTableItems',
}
