export enum EPlaidLinkStableEvent {
    OPEN = 'OPEN',
    EXIT = 'EXIT',
    HANDOFF = 'HANDOFF',
    SELECT_INSTITUTION = 'SELECT_INSTITUTION',
    ERROR = 'ERROR',
    BANK_INCOME_INSIGHTS_COMPLETED = 'BANK_INCOME_INSIGHTS_COMPLETED',
    IDENTITY_VERIFICATION_PASS_SESSION = 'IDENTITY_VERIFICATION_PASS_SESSION',
    IDENTITY_VERIFICATION_FAIL_SESSION = 'IDENTITY_VERIFICATION_FAIL_SESSION'
}