// enums
import { ConstantStringEnum } from '../../enums/constant-string.enum';

// models
import { MapStates } from '../../models/dashboard-state-models/map-states.model';

export class DashboardStateConstants {
    static usaStates: MapStates = {
        AL: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Alabama',
            value: null,
            percent: null,
        },
        AK: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Alaska',
            value: null,
            percent: null,
        },
        AS: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'American Samoa',
            value: null,
            percent: null,
        },
        AZ: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Arizona',
            value: null,
            percent: null,
        },
        AR: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Arkansas',
            value: null,
            percent: null,
        },
        CA: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'California',
            value: null,
            percent: null,
        },
        CO: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Colorado',
            value: null,
            percent: null,
        },
        CT: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Connecticut',
            value: null,
            percent: null,
        },
        DE: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Delaware',
            value: null,
            percent: null,
        },
        DC: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'District Of Columbia',
            value: null,
            percent: null,
        },
        FM: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Federated States Of Micronesia',
            value: null,
            percent: null,
        },
        FL: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Florida',
            value: null,
            percent: null,
        },
        GA: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Georgia',
            value: null,
            percent: null,
        },
        GU: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Guam',
            value: null,
            percent: null,
        },
        HI: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Hawaii',
            value: null,
            percent: null,
        },
        ID: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Idaho',
            value: null,
            percent: null,
        },
        IL: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Illinois',
            value: null,
            percent: null,
        },
        IN: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Indiana',
            value: null,
            percent: null,
        },
        IA: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Iowa',
            value: null,
            percent: null,
        },
        KS: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Kansas',
            value: null,
            percent: null,
        },
        KY: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Kentucky',
            value: null,
            percent: null,
        },
        LA: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Louisiana',
            value: null,
            percent: null,
        },
        ME: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Maine',
            value: null,
            percent: null,
        },
        MH: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Marshall Islands',
            value: null,
            percent: null,
        },
        MD: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Maryland',
            value: null,
            percent: null,
        },
        MA: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Massachusetts',
            value: null,
            percent: null,
        },
        MI: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Michigan',
            value: null,
            percent: null,
        },
        MN: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Minnesota',
            value: null,
            percent: null,
        },
        MS: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Mississippi',
            value: null,
            percent: null,
        },
        MO: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Missouri',
            value: null,
            percent: null,
        },
        MT: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Montana',
            value: null,
            percent: null,
        },
        NE: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Nebraska',
            value: null,
            percent: null,
        },
        NV: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Nevada',
            value: null,
            percent: null,
        },
        NH: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'New Hampshire',
            value: null,
            percent: null,
        },
        NJ: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'New Jersey',
            value: null,
            percent: null,
        },
        NM: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'New Mexico',
            value: null,
            percent: null,
        },
        NY: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'New York',
            value: null,
            percent: null,
        },
        NC: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'North Carolina',
            value: null,
            percent: null,
        },
        ND: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'North Dakota',
            value: null,
            percent: null,
        },
        MP: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Northern Mariana Islands',
            value: null,
            percent: null,
        },
        OH: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Ohio',
            value: null,
            percent: null,
        },
        OK: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Oklahoma',
            value: null,
            percent: null,
        },
        OR: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Oregon',
            value: null,
            percent: null,
        },
        PW: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Palau',
            value: null,
            percent: null,
        },
        PA: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Pennsylvania',
            value: null,
            percent: null,
        },
        PR: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Puerto Rico',
            value: null,
            percent: null,
        },
        RI: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Rhode Island',
            value: null,
            percent: null,
        },
        SC: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'South Carolina',
            value: null,
            percent: null,
        },
        SD: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'South Dakota',
            value: null,
            percent: null,
        },
        TN: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Tennessee',
            value: null,
            percent: null,
        },
        TX: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Texas',
            value: null,
            percent: null,
        },
        UT: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Utah',
            value: null,
            percent: null,
        },
        VT: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Vermont',
            value: null,
            percent: null,
        },
        VI: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Virgin Islands',
            value: null,
            percent: null,
        },
        VA: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Virginia',
            value: null,
            percent: null,
        },
        WA: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Washington',
            value: null,
            percent: null,
        },
        WV: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'West Virginia',
            value: null,
            percent: null,
        },
        WI: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Wisconsin',
            value: null,
            percent: null,
        },
        WY: {
            color: ConstantStringEnum.MAP_STATE_DEFAULT_COLOR,
            state: 'Wyoming',
            value: null,
            percent: null,
        },
    };
}
