// enums
import { ConstantStringEnum } from '../../enums/constant-string.enum';

// models
import { DashboardTab } from '../../models/dashboard-tab.model';
import { PerformanceDataItem } from '../../models/dashboard-performance-models/performance-data-item.model';

export class DashboardPerformanceConstants {
    static PERFORMANCE_TABS: DashboardTab[] = [
        {
            name: ConstantStringEnum.TODAY,
            checked: false,
        },
        {
            name: ConstantStringEnum.WTD,
            checked: false,
        },
        {
            name: ConstantStringEnum.MTD,
            checked: false,
        },
        {
            name: ConstantStringEnum.QTD,
            checked: false,
        },
        {
            name: ConstantStringEnum.YTD,
            checked: false,
        },
        {
            name: ConstantStringEnum.ALL,
            checked: true,
        },
        {
            name: ConstantStringEnum.CUSTOM,
            checked: false,
            custom: true,
        },
    ];

    static TREND_LIST: string[] = [
        ConstantStringEnum.NET_INCOME,
        ConstantStringEnum.REVENUE_2,
        ConstantStringEnum.LOAD_2,
        ConstantStringEnum.MILES,
        ConstantStringEnum.ROADSIDE_INSP,
        ConstantStringEnum.DRIVER_2,
        ConstantStringEnum.TRUCK_2,
        ConstantStringEnum.TRAILER,
        ConstantStringEnum.OWNER_2,
        ConstantStringEnum.USER_2,
        ConstantStringEnum.REPAIR_SHOP_2,
        ConstantStringEnum.BROKER_2,
        ConstantStringEnum.SHIPPER_2,
    ];

    static TREND_LIST_2: string[] = [
        ConstantStringEnum.EXPENSES,
        ConstantStringEnum.FUEL_GALLON,
        ConstantStringEnum.FUEL_COST,
        ConstantStringEnum.REPAIR_COST,
        ConstantStringEnum.VIOALTION,
        ConstantStringEnum.ACCIDENT,
    ];

    static PERFROMANCE_DATA: PerformanceDataItem[] = [
        {
            title: ConstantStringEnum.NET_INCOME,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [
                2, 8, 3, 3, 7, 0, 0, 8, 7, 5, 7, 1, 1, 3, 4, 6, 1, 1, 5, 5, 9,
                0, 2,
            ],
        },
        {
            title: ConstantStringEnum.REVENUE_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: ConstantStringEnum.LOAD_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: ConstantStringEnum.MILES,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: ConstantStringEnum.FUEL_GALLON,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: ConstantStringEnum.FUEL_COST,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: ConstantStringEnum.REPAIR_COST,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: ConstantStringEnum.ROADSIDE_INSP,
            isSelected: false,
            isHovered: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: ConstantStringEnum.VIOALTION,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: ConstantStringEnum.ACCIDENT,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: ConstantStringEnum.EXPENSES,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [
                23, 8, 3, 11, 7, 0, 44, 45, 46, 5, 7, 13, 18, 33, 42, 6, 10, 19,
                5, 5, 9, 40, 22,
            ],
        },
        {
            title: ConstantStringEnum.DRIVER_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: ConstantStringEnum.TRUCK_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: ConstantStringEnum.TRAILER,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: ConstantStringEnum.OWNER_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: ConstantStringEnum.USER_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: ConstantStringEnum.REPAIR_SHOP_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: ConstantStringEnum.BROKER_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
        {
            title: ConstantStringEnum.SHIPPER_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
            lineChartDataValues: [],
        },
    ];
}
