// enums
import { ConstantStringEnum } from '../../enums/constant-string.enum';

// models
import { DashboardTab } from '../../models/dashboard-tab.model';
import { PerformanceDataItem } from '../../models/dashboard-performance-models/performance-data-item.model';

export class DashboardPerformanceConstants {
    static PERFORMANCE_TABS: DashboardTab[] = [
        {
            name: ConstantStringEnum.TODAY,
            checked: false,
        },
        {
            name: ConstantStringEnum.WTD,
            checked: false,
        },
        {
            name: ConstantStringEnum.MTD,
            checked: true,
        },
        {
            name: ConstantStringEnum.QTD,
            checked: false,
        },
        {
            name: ConstantStringEnum.YTD,
            checked: false,
        },
        {
            name: ConstantStringEnum.ALL,
            checked: false,
        },
        {
            name: ConstantStringEnum.CUSTOM,
            checked: false,
            custom: true,
        },
    ];

    static TREND_LIST: string[] = [
        ConstantStringEnum.NET_INCOME,
        ConstantStringEnum.REVENUE_2,
        ConstantStringEnum.LOAD_2,
        ConstantStringEnum.MILES,
        ConstantStringEnum.ROADSIDE_INSP,
        ConstantStringEnum.DRIVER_2,
        ConstantStringEnum.TRUCK_2,
        ConstantStringEnum.TRAILER,
        ConstantStringEnum.OWNER_2,
        ConstantStringEnum.USER_2,
        ConstantStringEnum.REPAIR_SHOP_2,
        ConstantStringEnum.BROKER_2,
        ConstantStringEnum.SHIPPER_2,
    ];

    static TREND_LIST_2: string[] = [
        ConstantStringEnum.EXPENSES,
        ConstantStringEnum.FUEL_GALLON,
        ConstantStringEnum.FUEL_COST,
        ConstantStringEnum.REPAIR_COST,
        ConstantStringEnum.VIOALTION,
        ConstantStringEnum.ACCIDENT,
    ];

    static PERFROMANCE_DATA: PerformanceDataItem[] = [
        {
            title: ConstantStringEnum.NET_INCOME,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
        },
        {
            title: ConstantStringEnum.REVENUE_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: 444.44,
            lastIntervalTrend: 26.53,
            intervalAverageValue: 1,
        },
        {
            title: ConstantStringEnum.LOAD_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
        },
        {
            title: ConstantStringEnum.MILES,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
        },
        {
            title: ConstantStringEnum.FUEL_GALLON,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
        },
        {
            title: ConstantStringEnum.FUEL_COST,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
        },
        {
            title: ConstantStringEnum.REPAIR_COST,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
        },
        {
            title: ConstantStringEnum.ROADSIDE_INSP,
            isSelected: false,
            isHovered: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
        },
        {
            title: ConstantStringEnum.VIOALTION,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
        },
        {
            title: ConstantStringEnum.ACCIDENT,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
        },
        {
            title: ConstantStringEnum.EXPENSES,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
        },
        {
            title: ConstantStringEnum.DRIVER_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
        },
        {
            title: ConstantStringEnum.TRUCK_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
        },
        {
            title: ConstantStringEnum.TRAILER,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
        },
        {
            title: ConstantStringEnum.OWNER_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
        },
        {
            title: ConstantStringEnum.USER_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
        },
        {
            title: ConstantStringEnum.REPAIR_SHOP_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
        },
        {
            title: ConstantStringEnum.BROKER_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
        },
        {
            title: ConstantStringEnum.SHIPPER_2,
            isHovered: false,
            isSelected: false,
            selectedColor: null,
            selectedHoverColor: null,
            lastIntervalValue: null,
            lastIntervalTrend: null,
            intervalAverageValue: null,
        },
    ];
}
