import { SortOrder } from "appcoretruckassist";

export interface IGetLoadListParam {
    loadType?: number,
    statusType?: number, // statusType -> 1 - pending, 2 - active, 3 - closed
    status?: Array<number>,
    dispatcherIds?: Array<number>,
    dispatcherId?: number,
    dispatchId?: number,
    brokerId?: number,
    shipperId?: number,
    loadIds?: Array<number>,
    loadId?: number,
    dateFrom?: string,
    dateTo?: string,
    revenueFrom?: number,
    revenueTo?: number,
    truckId?: number,
    driverId?: number,
    rateFrom?: number,
    rateTo?: number,
    paidFrom?: number,
    paidTo?: number,
    dueFrom?: number,
    dueTo?: number,
    pickup?: boolean,
    delivery?: boolean,
    longitude?: number,
    latitude?: number,
    distance?: number,
    pageIndex?: number,
    pageSize?: number,
    companyId?: number,
    sort?: string,
    sortOrder?: SortOrder,
    sortBy?: string,
    search?: string,
    search1?: string,
    search2?: string,
    loadStatusType?: string;
}