export enum WebsiteStringEnum {
    LOGIN = 'login',
    RESET_PASSWORD = 'reset password',
    RESET_PASSWORD_REQUESTED = 'reset password requested',
    CREATE_NEW_PASSWORD = 'create new password',
    PASSWORD_UPDATED = 'password updated',
    START_TRIAL = 'start trial',
    START_TRIAL_CONFIRMATION = 'start trial confirmation',
    START_TRIAL_WELCOME = 'start trial welcome',
    RESEND_CONFIRMATION = 'resend confirmation',
    RESEND_CONFIRMATION_REQUESTED = 'resend confirmation requested',
    REGISTER_USER = 'register user',
    REGISTER_USER_WELCOME = 'register user welcome',
    REGISTER_USER_CONFIRMATION = 'register user confirmation',

    EMAIL_ADDRESS = 'email',
    ADDRESS = 'address',
    ADDRESS_UNIT = 'addressUnit',
    PASSWORD = 'password',
    CONFIRM_PASSWORD = 'confirmPassword',
    NEW_PASSWORD = 'newPassword',
    CREATE_PASSWORD_NEW = 'createNewPassword',
    OLD_PASSWORD = 'oldPassword',
    EIN = 'ein',
    COMPANY_NAME_2 = 'companyName',
    PHONE = 'phone',
    STAY_LOGGED_IN = 'stayLoggedIn',

    EMAIL_HASH = 'EmailHash',
    CODE = 'Code',
    FIRST_NAME = 'FirstName',
    LAST_NAME = 'LastName',
    EMAIL = 'Email',
    DEPARTMENT = 'Department',
    COMPANY_NAME = 'CompanyName',
    AVATAR = 'Avatar',

    WEBSITE = '/website',
    WEBSITE_SELECT_COMPANY = '/website/select-company',

    LOGIN_BTN = 'login-btn',
    RESET_PASSWORD_BTN = 'reset-password-btn',
    RESEND_CONFIRMATION_BTN = 'resend-confirmation-btn',

    CONFIRMATION_EMAIL = 'confirmationEmail',

    SIDEBAR = '#sidebar',

    PHONE_ALREADY_EXIST = 'Phone already exists.',
    EIN_ALREADY_EXIST = 'Ein already exists.',
    EMAIL_ALREADY_EXIST = 'Email already exists.',
    THIS_USER_DOESENT_EXIST = "This user doesn't exist.",
    WRONG_PASSWORD_TRY_AGAIN = 'Wrong password, try again.',
    USER_NOT_FOUND = 'User not found.',
    USER_ALREADY_VERIFIED = 'User already verified.',

    COMPANY = 'company',
    USER = 'user',

    LEFT = 'left',
}
