/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LongLat } from './longLat';
import { AddressEntity } from './addressEntity';


export interface AddressResponse { 
    address?: AddressEntity;
    longLat?: LongLat;
}

