/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiApplicantMvrPostRequest { 
    Id?: number;
    IsEmployee?: boolean;
    IsPeriodicallyObtained?: boolean;
    IsInformationCorrect?: boolean;
    DontHaveMvr?: boolean;
    OnlyLicense?: boolean;
    Signature?: string;
    IssueDate?: string;
    Files?: Array<Blob>;
    FilesForDeleteIds?: Array<number>;
    ApplicantId?: number;
}

