/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateOffDutyLocationCommand } from './createOffDutyLocationCommand';
import { OwnerType } from './ownerType';
import { FleetType } from './fleetType';
import { CreateTagCommand } from './createTagCommand';


export interface ApiDriverPostRequest1 { 
    FirstName?: string;
    LastName?: string;
    DateOfBirth?: string;
    Phone?: string;
    Email?: string;
    Ssn?: string;
    Hired?: string;
    Address_City?: string;
    Address_State?: string;
    Address_County?: string;
    Address_Address?: string;
    Address_Street?: string;
    Address_StreetNumber?: string;
    Address_Country?: string;
    Address_ZipCode?: string;
    Address_StateShortName?: string;
    Address_AddressUnit?: string;
    BussinesName?: string;
    Ein?: string;
    IsOwner?: boolean;
    OwnerType?: OwnerType;
    OwnerId?: number;
    DriverType?: number;
    UseCarrieraAch?: boolean;
    PayType?: number;
    SoloDriver?: boolean;
    TeamDriver?: boolean;
    Solo_EmptyMile?: number;
    Solo_LoadedMile?: number;
    Solo_PerStop?: number;
    Team_EmptyMile?: number;
    Team_LoadedMile?: number;
    Team_PerStop?: number;
    FleetType?: FleetType;
    BankId?: number;
    Account?: string;
    Routing?: string;
    PerMileSolo?: number;
    PerMileTeam?: number;
    CommissionSolo?: number;
    CommissionTeam?: number;
    FlatRateSolo?: number;
    FlatRateTeam?: number;
    IsOpenPayrollShared?: boolean;
    IsPayrollCalculated?: boolean;
    OffDutyLocations?: Array<CreateOffDutyLocationCommand>;
    EmergencyContactName?: string;
    EmergencyContactPhone?: string;
    EmergencyContactRelationship?: string;
    Files?: Array<Blob>;
    Tags?: Array<CreateTagCommand>;
    Note?: string;
    Avatar?: string;
    Twic?: boolean;
    TwicExpDate?: string;
    FuelCardIds?: Array<number>;
    MvrExpiration?: number;
    General_MailNotification?: boolean;
    General_PushNotification?: boolean;
    General_SmsNotification?: boolean;
    Payroll_MailNotification?: boolean;
    Payroll_PushNotification?: boolean;
    Payroll_SmsNotification?: boolean;
}

