/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EditFuelItemCommand } from './editFuelItemCommand';


export interface ApiFuelTransactionPostRequest { 
    Id?: number;
    Invoice?: string;
    TruckId?: number;
    DriverId?: number;
    TrailerId?: number;
    FuelStopStoreId?: number;
    PayrollOwnerId?: number;
    TransactionDate?: string;
    Total?: number;
    FuelItems?: Array<EditFuelItemCommand>;
    Files?: Array<Blob>;
    FilesForDeleteIds?: Array<number>;
}

