/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoadStopCommand } from './loadStopCommand';
import { LoadBillingAdditionalCommand } from './loadBillingAdditionalCommand';
import { LoadPaymentPayCommand } from './loadPaymentPayCommand';
import { LoadType } from './loadType';
import { CreateTagCommand } from './createTagCommand';


export interface ApiLoadSaveasclosedPostRequest { 
    Type?: LoadType;
    LoadNumber?: string;
    LoadTemplateId?: number;
    DispatcherId?: number;
    CompanyId?: number;
    DispatchId?: number;
    DateCreated?: string;
    BrokerId?: number;
    BrokerContactId?: number;
    ReferenceNumber?: string;
    GeneralCommodity?: number;
    Weight?: number;
    LoadRequirements_Id?: number;
    LoadRequirements_TruckTypeId?: number;
    LoadRequirements_TrailerTypeId?: number;
    LoadRequirements_DoorType?: number;
    LoadRequirements_Suspension?: number;
    LoadRequirements_TrailerLengthId?: number;
    LoadRequirements_Year?: number;
    LoadRequirements_Liftgate?: boolean;
    LoadRequirements_DriverMessage?: string;
    Note?: string;
    BaseRate?: number;
    AdjustedRate?: number;
    DriverRate?: number;
    CoDriverRate?: number;
    AdvancePay?: number;
    EmptyMiles?: number;
    TotalMiles?: number;
    TotalHours?: number;
    TotalMinutes?: number;
    AdditionalBillingRates?: Array<LoadBillingAdditionalCommand>;
    Stops?: Array<LoadStopCommand>;
    Pays?: Array<LoadPaymentPayCommand>;
    Files?: Array<Blob>;
    Tags?: Array<CreateTagCommand>;
}

