/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicantEmergencyContact } from './applicantEmergencyContact';
import { ApplicantEducationReview } from './applicantEducationReview';
import { Applicant } from './applicant';


export interface ApplicantEducation { 
    id?: number;
    highestGrade?: number;
    collegeGrade?: number;
    specialTraining?: boolean;
    specialTrainingDescription?: string | null;
    otherTraining?: boolean;
    otherTrainingDescription?: string | null;
    knowledgeOfSafetyRegulations?: boolean;
    driverBefore?: boolean;
    from?: string | null;
    to?: string | null;
    unableForJob?: boolean;
    unableForJobDescription?: string | null;
    educationReview?: ApplicantEducationReview;
    emergencyContacts?: Array<ApplicantEmergencyContact> | null;
    reviewed?: boolean | null;
    approved?: boolean | null;
    applicantId?: number;
    applicant?: Applicant;
    createdAt?: string;
    updatedAt?: string;
}

