/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Applicant } from './applicant';
import { ApplicantCdlInformationReview } from './applicantCdlInformationReview';
import { ApplicantCdl } from './applicantCdl';


export interface ApplicantCdlInformation { 
    id?: number;
    cdlDenied?: boolean;
    cdlDeniedExplanation?: string | null;
    licences?: Array<ApplicantCdl> | null;
    cdlInformationReview?: ApplicantCdlInformationReview;
    reviewed?: boolean | null;
    approved?: boolean | null;
    applicantId?: number;
    applicant?: Applicant;
    createdAt?: string;
    updatedAt?: string;
}

