/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicantCdlCard } from './applicantCdlCard';


export interface ApplicantCdlCardReview { 
    id?: number;
    isIssueDateValid?: boolean;
    isExpireDateValid?: boolean;
    dateMessage?: string | null;
    cdlCardId?: number;
    cdlCard?: ApplicantCdlCard;
    createdAt?: string;
    updatedAt?: string;
}

