/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicantSphAccidentHistory } from './applicantSphAccidentHistory';
import { AddressEntity } from './addressEntity';


export interface ApplicantSphAccidentHistoryItem { 
    id?: number;
    location?: AddressEntity;
    date?: string;
    fatalities?: number | null;
    injuries?: number | null;
    hazmatSpill?: boolean;
    description?: string | null;
    sphAccidentHistoryId?: number;
    sphAccidentHistory?: ApplicantSphAccidentHistory;
    createdAt?: string;
    updatedAt?: string;
}

