/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicantDrugAndAlcoholReview } from './applicantDrugAndAlcoholReview';
import { Applicant } from './applicant';
import { AddressEntity } from './addressEntity';


export interface ApplicantDrugAndAlcohol { 
    id?: number;
    positiveTest?: boolean;
    motorCarrier?: string | null;
    phone?: string | null;
    address: AddressEntity;
    sapName?: string | null;
    sapPhone?: string | null;
    sapAddress: AddressEntity;
    certifyInformation?: boolean;
    drugAndAlcoholReview?: ApplicantDrugAndAlcoholReview;
    reviewed?: boolean | null;
    approved?: boolean | null;
    applicantId?: number;
    applicant?: Applicant;
    createdAt?: string;
    updatedAt?: string;
}

