/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ApplicationStatus = 'Incomplete' | 'Ready' | 'BadReview' | 'GoodReview';

export const ApplicationStatus = {
    Incomplete: 'Incomplete' as ApplicationStatus,
    Ready: 'Ready' as ApplicationStatus,
    BadReview: 'BadReview' as ApplicationStatus,
    GoodReview: 'GoodReview' as ApplicationStatus
};

