/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Company } from './company';


export interface BankCard { 
    id?: number;
    companyId?: number;
    company?: Company;
    nickname?: string | null;
    card?: string | null;
    cvc?: string | null;
    expireDate?: string;
    createdAt?: string;
    updatedAt?: string;
}

