/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Accident } from './accident';
import { RoadsideInspection } from './roadsideInspection';


export interface Citation { 
    id?: number;
    roadsideInspectionId?: number | null;
    roadsideInspection?: RoadsideInspection;
    accidentId?: number | null;
    accident?: Accident;
    citationNo?: string | null;
    cost?: number | null;
    description?: string | null;
    citationDate?: string | null;
    paid?: boolean | null;
    note?: string | null;
    createdAt?: string;
    updatedAt?: string;
}

