/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Company } from './company';
import { ApiCategory } from './apiCategory';
import { CompanyAccountLabel } from './companyAccountLabel';


export interface CompanyAccount { 
    id?: number;
    companyId?: number;
    company?: Company;
    name?: string | null;
    url?: string | null;
    username?: string | null;
    password?: string | null;
    contractId?: number | null;
    api?: number;
    apiCategory?: ApiCategory;
    connected?: boolean;
    note?: string | null;
    companyAccountLabelId?: number | null;
    companyAccountLabel?: CompanyAccountLabel;
    createdAt?: string;
    updatedAt?: string;
}

