/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Company } from './company';
import { Department } from './department';
import { PerMileEntity } from './perMileEntity';


export interface CompanyPayroll { 
    id?: number;
    companyId?: number;
    company?: Company;
    departmentId?: number;
    department?: Department;
    payPeriod?: number;
    endingIn?: number;
    defaultBase?: number | null;
    defaultCommission?: number | null;
    solo: PerMileEntity;
    team: PerMileEntity;
    soloPerLoad?: number | null;
    teamPerLoad?: number | null;
    perMileSolo?: number | null;
    perMileTeam?: number | null;
    loadedAndEmptySameRate?: boolean | null;
    defaultSoloDriverCommission?: number | null;
    defaultTeamDriverCommission?: number | null;
    defaultOwnerCommission?: number | null;
    createdAt?: string;
    updatedAt?: string;
}

