/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Company } from './company';
import { CompanyAccount } from './companyAccount';
import { LabelColor } from './labelColor';


export interface CompanyAccountLabel { 
    id?: number;
    companyId?: number;
    company?: Company;
    name?: string | null;
    colorId?: number;
    color?: LabelColor;
    companyAccounts?: Array<CompanyAccount> | null;
    createdAt?: string;
    updatedAt?: string;
}

