/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateOffDutyLocationCommand } from './createOffDutyLocationCommand';
import { OwnerType } from './ownerType';
import { FleetType } from './fleetType';
import { PerMileEntity } from './perMileEntity';
import { NotificationEntity } from './notificationEntity';
import { AddressEntity } from './addressEntity';


export interface CreateDriverCommand { 
    firstName?: string | null;
    lastName?: string | null;
    phone?: string | null;
    email?: string | null;
    address?: AddressEntity;
    dateOfBirth?: string;
    ssn?: string | null;
    mvrExpiration?: number;
    bankId?: number | null;
    account?: string | null;
    routing?: string | null;
    payType?: number | null;
    useTruckAssistAch?: boolean;
    solo: PerMileEntity;
    team: PerMileEntity;
    fleetType?: FleetType;
    soloDriver?: boolean | null;
    teamDriver?: boolean | null;
    perMileSolo?: number | null;
    perMileTeam?: number | null;
    commissionSolo?: number | null;
    commissionTeam?: number | null;
    flatRate?: number | null;
    isOwner?: boolean;
    ownerId?: number | null;
    ownerType?: OwnerType;
    ein?: string | null;
    bussinesName?: string | null;
    offDutyLocations?: Array<CreateOffDutyLocationCommand> | null;
    emergencyContactName?: string | null;
    emergencyContactPhone?: string | null;
    emergencyContactRelationship?: string | null;
    note?: string | null;
    avatar?: string | null;
    twic?: boolean;
    twicExpDate?: string | null;
    fuelCard?: string | null;
    general?: NotificationEntity;
    payroll?: NotificationEntity;
}

