/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmergencyContactReviewCommand } from './emergencyContactReviewCommand';


export interface CreateEducationReviewCommand { 
    id?: number | null;
    isSpecialTrainingDescriptionValid?: boolean;
    specialTrainingDescriptionMessage?: string | null;
    isOtherTrainingDescriptionValid?: boolean;
    otherTrainingDescriptionMessage?: string | null;
    isFromValid?: boolean;
    isToValid?: boolean;
    datesMessage?: string | null;
    isUnableToPreformJobDescriptionValid?: boolean | null;
    unableToPreformJobDescriptionMessage?: string | null;
    emergencyContactReviews?: Array<EmergencyContactReviewCommand> | null;
    applicantId?: number;
}

