/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PayrollDeductionType } from './payrollDeductionType';
import { PayrollDeductionRecurringType } from './payrollDeductionRecurringType';


export interface CreatePayrollDeductionCommand { 
    type?: PayrollDeductionType;
    driverId?: number | null;
    truckId?: number | null;
    trailerId?: number | null;
    date?: string;
    description?: string | null;
    amount?: number;
    recurring?: boolean;
    recurringType?: PayrollDeductionRecurringType;
    limited?: boolean;
    limitedNumber?: number | null;
    limitedLevy?: number | null;
}

