/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateDrugAndAlcoholReviewCommand { 
    isCarrierValid?: boolean;
    carrierMessage?: string | null;
    isAddressValid?: boolean;
    addressMessage?: string | null;
    isSapValid?: boolean;
    sapMessage?: string | null;
    isSapAddressValid?: boolean;
    sapAddressMessage?: string | null;
    drugAndAlcoholId?: number;
    applicantId?: number;
}

