/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PayrollCreditType } from './payrollCreditType';


export interface CreatePayrollCreditCommand { 
    type?: PayrollCreditType;
    driverId?: number | null;
    ownerId?: number | null;
    date?: string;
    description?: string | null;
    amount?: number;
}

