/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateOffDutyLocationCommand } from './createOffDutyLocationCommand';
import { OwnerType } from './ownerType';
import { PerMileEntity } from './perMileEntity';
import { AddressEntity } from './addressEntity';


export interface CreateDriverCommand { 
    firstName?: string | null;
    lastName?: string | null;
    phone?: string | null;
    email?: string | null;
    ssn?: string | null;
    note?: string | null;
    avatar?: string | null;
    dateOfBirth?: string;
    offDutyLocations?: Array<CreateOffDutyLocationCommand> | null;
    isOwner?: boolean;
    ownerId?: number | null;
    ownerType?: OwnerType;
    ein?: string | null;
    bussinesName?: string | null;
    address?: AddressEntity;
    bankId?: number | null;
    account?: string | null;
    routing?: string | null;
    payroll?: boolean;
    payType?: number | null;
    mailNotification?: boolean | null;
    phoneCallNotification?: boolean | null;
    smsNotification?: boolean | null;
    solo: PerMileEntity;
    team: PerMileEntity;
    commissionSolo?: number | null;
    commissionTeam?: number | null;
    twic?: boolean;
    twicExpDate?: string | null;
    fuelCard?: string | null;
    emergencyContactName?: string | null;
    emergencyContactPhone?: string | null;
    emergencyContactRelationship?: string | null;
}

