/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoadShortResponse } from './loadShortResponse';


export interface DispatchAssignedLoadListResponse { 
    pending?: Array<LoadShortResponse> | null;
    closed?: Array<LoadShortResponse> | null;
    active?: Array<LoadShortResponse> | null;
}

