/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TruckMinimalMobileResponse } from './truckMinimalMobileResponse';
import { TrailerMinimalMobileResponse } from './trailerMinimalMobileResponse';


export interface DispatchShortMobileResponse { 
    id?: number;
    dispatchBoardId?: number;
    dispatcherId?: number | null;
    truck?: TruckMinimalMobileResponse;
    trailer?: TrailerMinimalMobileResponse;
}

