/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Dispatch } from './dispatch';
import { DispatchHosFlag } from './dispatchHosFlag';


export interface DispatchHos { 
    id?: number;
    dispatchId?: number;
    dispatch?: Dispatch;
    start?: number;
    end?: number;
    flag?: DispatchHosFlag;
    createdAt?: string;
    updatedAt?: string;
}

