/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DispatchStatusFilterResponse } from './dispatchStatusFilterResponse';
import { TrailerTypeFilterResponse } from './trailerTypeFilterResponse';
import { DispatchParkingFilterResponse } from './dispatchParkingFilterResponse';
import { TruckTypeFilterResponse } from './truckTypeFilterResponse';


export interface DispatchBoardFiltersResponse { 
    truckTypes?: Array<TruckTypeFilterResponse> | null;
    trailerTypes?: Array<TrailerTypeFilterResponse> | null;
    statuses?: Array<DispatchStatusFilterResponse> | null;
    parkings?: Array<DispatchParkingFilterResponse> | null;
}

