/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumValue } from './enumValue';
import { DriverMinimalResponse } from './driverMinimalResponse';


export interface DriverDetailsDispatchResponse { 
    coDriver?: DriverMinimalResponse;
    truckId?: number | null;
    truckNumber?: string | null;
    truckType?: EnumValue;
    trailerId?: number | null;
    trailerNumber?: string | null;
    trailerType?: EnumValue;
    teamName?: string | null;
}

