/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Company } from './company';
import { Owner } from './owner';
import { Bank } from './bank';
import { FleetType } from './fleetType';
import { MilesStop } from './milesStop';
import { Dispatch } from './dispatch';
import { Cdl } from './cdl';
import { PerMileEntity } from './perMileEntity';
import { OffDutyLocation } from './offDutyLocation';
import { CompanyUser } from './companyUser';
import { EmploymentHistory } from './employmentHistory';
import { Test } from './test';
import { DispatchHistory } from './dispatchHistory';
import { Medical } from './medical';
import { NotificationEntity } from './notificationEntity';
import { AddressEntity } from './addressEntity';


export interface Driver { 
    id?: number;
    companyId?: number;
    company?: Company;
    companyUserId?: number;
    companyUser?: CompanyUser;
    ownerId?: number | null;
    owner?: Owner;
    firstName?: string | null;
    lastName?: string | null;
    phone?: string | null;
    email?: string | null;
    ssn?: string | null;
    status?: number;
    note?: string | null;
    address: AddressEntity;
    mvrExpiration?: number;
    dateOfBirth?: string;
    dateTerminated?: string | null;
    bankId?: number | null;
    bank?: Bank;
    account?: string | null;
    routing?: string | null;
    payType?: number | null;
    useTruckAssistAch?: boolean;
    solo: PerMileEntity;
    team: PerMileEntity;
    fleetType?: FleetType;
    soloDriver?: boolean | null;
    teamDriver?: boolean | null;
    commissionSolo?: number | null;
    commissionTeam?: number | null;
    soloFlatRate?: number | null;
    teamFlatRate?: number | null;
    latitude?: number | null;
    longitude?: number | null;
    avatar?: string | null;
    twic?: boolean;
    twicExpDate?: string | null;
    fuelCard?: string | null;
    emergencyContactName?: string | null;
    emergencyContactPhone?: string | null;
    emergencyContactRelationship?: string | null;
    general: NotificationEntity;
    payroll: NotificationEntity;
    createdAt?: string;
    updatedAt?: string;
    offDutyLocations?: Array<OffDutyLocation> | null;
    employmentHistories?: Array<EmploymentHistory> | null;
    hired?: string | null;
    medicals?: Array<Medical> | null;
    tests?: Array<Test> | null;
    cdls?: Array<Cdl> | null;
    dispatches?: Array<Dispatch> | null;
    coDispatches?: Array<Dispatch> | null;
    dispatchHistories?: Array<DispatchHistory> | null;
    milesStops?: Array<MilesStop> | null;
}

