/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileResponse } from './fileResponse';
import { BankResponse } from './bankResponse';
import { EnumValue } from './enumValue';
import { CdlResponse } from './cdlResponse';
import { OwnerResponse } from './ownerResponse';
import { PerMileEntity } from './perMileEntity';
import { NotificationEntity } from './notificationEntity';
import { AddressEntity } from './addressEntity';


export interface DriverShortResponse { 
    id?: number;
    owner?: OwnerResponse;
    fullName?: string | null;
    phone?: string | null;
    email?: string | null;
    ssn?: string | null;
    status?: number;
    note?: string | null;
    avatarFile?: FileResponse;
    address?: AddressEntity;
    dateOfBirth?: string | null;
    colorFlag?: EnumValue;
    bank?: BankResponse;
    account?: string | null;
    routing?: string | null;
    useTruckAssistAch?: boolean;
    payType?: EnumValue;
    solo?: PerMileEntity;
    team?: PerMileEntity;
    perMileSolo?: number | null;
    perMileTeam?: number | null;
    commissionSolo?: number | null;
    commissionTeam?: number | null;
    soloFlatRate?: number | null;
    teamFlatRate?: number | null;
    twic?: boolean;
    twicExpirationDays?: number | null;
    fuelCard?: string | null;
    emergencyContactName?: string | null;
    emergencyContactPhone?: string | null;
    emergencyContactRelationship?: string | null;
    general?: NotificationEntity;
    payroll?: NotificationEntity;
    cdls?: Array<CdlResponse> | null;
    cdlNumber?: string | null;
    licenseStateShortName?: string | null;
    hired?: string | null;
    mvrExpirationDays?: number | null;
    mvrExpirationHours?: number | null;
    cdlExpirationHours?: number | null;
    medicalExpirationHours?: number | null;
    cdlExpirationDays?: number | null;
    medicalExpirationDays?: number | null;
    mvrPercentage?: number | null;
    cdlPercentage?: number | null;
    medicalPercentage?: number | null;
    fileCount?: number | null;
}

