/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileResponse } from './fileResponse';
import { BankResponse } from './bankResponse';
import { DispatchShortResponse } from './dispatchShortResponse';
import { EmploymentHistoryResponse } from './employmentHistoryResponse';
import { EnumValue } from './enumValue';
import { OwnerResponse } from './ownerResponse';
import { OffDutyLocationResponse } from './offDutyLocationResponse';
import { PerMileEntity } from './perMileEntity';
import { NotificationEntity } from './notificationEntity';
import { AddressEntity } from './addressEntity';


export interface DriverResponse { 
    id?: number;
    owner?: OwnerResponse;
    firstName?: string | null;
    lastName?: string | null;
    phone?: string | null;
    email?: string | null;
    ssn?: string | null;
    status?: number;
    note?: string | null;
    mvrExpiration?: number;
    address?: AddressEntity;
    dateOfBirth?: string;
    dateTerminated?: string | null;
    bank?: BankResponse;
    account?: string | null;
    routing?: string | null;
    useTruckAssistAch?: boolean;
    payType?: EnumValue;
    solo?: PerMileEntity;
    team?: PerMileEntity;
    fleetType?: EnumValue;
    soloDriver?: boolean | null;
    teamDriver?: boolean | null;
    commissionSolo?: number | null;
    commissionTeam?: number | null;
    soloFlatRate?: number | null;
    teamFlatRate?: number | null;
    hired?: string | null;
    avatar?: string | null;
    twic?: boolean;
    twicExpDate?: string | null;
    fuelCard?: string | null;
    emergencyContactName?: string | null;
    emergencyContactPhone?: string | null;
    emergencyContactRelationship?: string | null;
    general?: NotificationEntity;
    payroll?: NotificationEntity;
    employmentHistories?: Array<EmploymentHistoryResponse> | null;
    offDutyLocations?: Array<OffDutyLocationResponse> | null;
    mvrExpirationDays?: number | null;
    cdlExpirationDays?: number | null;
    medicalExpirationDays?: number | null;
    mvrPercentage?: number | null;
    cdlPercentage?: number | null;
    medicalPercentage?: number | null;
    dispatches?: Array<DispatchShortResponse> | null;
    files?: Array<FileResponse> | null;
    assignedTo?: DispatchShortResponse;
    createdAt?: string;
    updatedAt?: string;
}

