/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CdlEndorsement } from './cdlEndorsement';


export interface Endorsement { 
    id?: number;
    code?: string | null;
    description?: string | null;
    cdlEndorsements?: Array<CdlEndorsement> | null;
    createdAt?: string;
    updatedAt?: string;
}

