/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FuelStopFranchise } from './fuelStopFranchise';
import { Company } from './company';
import { FuelTransaction } from './fuelTransaction';
import { FuelStopExtension } from './fuelStopExtension';
import { AddressEntity } from './addressEntity';


export interface FuelStopStore { 
    id?: number;
    companyId?: number | null;
    company?: Company;
    fuelStopFranchiseId?: number | null;
    fuelStopFranchise?: FuelStopFranchise;
    businessName?: string | null;
    store?: string | null;
    efsCode?: string | null;
    comdataCode?: string | null;
    phone?: string | null;
    fax?: string | null;
    address?: AddressEntity;
    pricePerGallon?: number | null;
    lowestPricePerGallon?: number | null;
    highestPricePerGallon?: number | null;
    chainId?: number | null;
    latitude?: number | null;
    longitude?: number | null;
    fuelTransactions?: Array<FuelTransaction> | null;
    fuelStopExtensions?: Array<FuelStopExtension> | null;
    createdAt?: string;
    updatedAt?: string;
}

