/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FuelTransactionResponse } from './fuelTransactionResponse';
import { FuelStopExtensionResponse } from './fuelStopExtensionResponse';
import { AddressEntity } from './addressEntity';
import { FuelStopFranchiseMinimalResponse } from './fuelStopFranchiseMinimalResponse';


export interface FuelStopResponse { 
    id?: number;
    fuelStopFranchise?: FuelStopFranchiseMinimalResponse;
    businessName?: string | null;
    store?: string | null;
    phone?: string | null;
    fax?: string | null;
    address?: AddressEntity;
    pricePerGallon?: number | null;
    lowestPricePerGallon?: number | null;
    highestPricePerGallon?: number | null;
    longitude?: number | null;
    latitude?: number | null;
    fuelTransactions?: Array<FuelTransactionResponse> | null;
    fuelStopExtensions?: Array<FuelStopExtensionResponse> | null;
    createdAt?: string;
    updatedAt?: string;
}

