/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoadStopType } from './loadStopType';
import { AddressEntity } from './addressEntity';


export interface LiveTrackingLoadStopResponse { 
    totalLegMiles?: number | null;
    legMiles?: number | null;
    latitude?: number | null;
    longitude?: number | null;
    stopType?: LoadStopType;
    address?: AddressEntity;
    businessName?: string | null;
    stopOrder?: number;
}

