/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoadStopType } from './loadStopType';
//import { LoadStopItemCommand } from './loadStopItemCommand';
import { TimeType } from './timeType';


export interface LoadStopCommand { 
    id?: number | null;
    stopType?: LoadStopType;
    stopOrder?: number;
    shipperId?: number;
    shipperContactId?: number | null;
    dateFrom?: string;
    dateTo?: string | null;
    timeType?: TimeType;
    timeFrom?: string | null;
    timeTo?: string | null;
    arrive?: string | null;
    depart?: string | null;
    legMiles?: number | null;
    legHours?: number | null;
    legMinutes?: number | null;
    totalLegMiles?: number | null;
    totalLegHours?: number | null;
    totalLegMinutes?: number | null;
    items?: Array<any> | null;
}