/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommentResponse } from './commentResponse';
import { LoadDispatcherMobileResponse } from './loadDispatcherMobileResponse';
import { LoadStatusResponse } from './loadStatusResponse';
import { LoadStopMobileResponse } from './loadStopMobileResponse';
import { DispatchShortResponse } from './dispatchShortResponse';
import { EnumValue } from './enumValue';
import { BrokerShortMobileResponse } from './brokerShortMobileResponse';
import { LoadRequirementsResponse } from './loadRequirementsResponse';
import { LoadProgressResponse } from './loadProgressResponse';
import { LoadStopShortResponse } from './loadStopShortResponse';
import { MilesMobileResponse } from './milesMobileResponse';


export interface LoadMobileFullDetailsResponse { 
    id?: number;
    loadNumber?: string | null;
    referenceNumber?: string | null;
    payType?: EnumValue;
    totalRate?: number | null;
    isInActivePayroll?: boolean;
    weight?: number | null;
    closingPayrollDate?: string | null;
    loadDeliveryTime?: string | null;
    assignedDate?: string | null;
    pickup?: LoadStopShortResponse;
    delivery?: LoadStopShortResponse;
    pickupCount?: number;
    deliveryCount?: number;
    miles?: MilesMobileResponse;
    completedPercentage?: number;
    pendingPercentage?: number | null;
    closedPercentage?: number | null;
    loadProgress?: LoadProgressResponse;
    statusType?: EnumValue;
    status?: LoadStatusResponse;
    lastStatusPassed?: { [key: string]: number; } | null;
    dispatcher?: LoadDispatcherMobileResponse;
    dispatch?: DispatchShortResponse;
    loadRequirements?: LoadRequirementsResponse;
    driverAssist?: string | null;
    extraStopsCount?: number;
    generalCommodity?: EnumValue;
    broker?: BrokerShortMobileResponse;
    stopsCount?: number;
    stops?: Array<LoadStopMobileResponse> | null;
    commentsCount?: number;
    comments?: Array<CommentResponse> | null;
    est?: { [key: string]: number; } | null;
    duration?: { [key: string]: number; } | null;
    totalWait?: { [key: string]: number; } | null;
    totalDriving?: { [key: string]: number; } | null;
    createdAt?: string;
    updatedAt?: string;
}

