/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoadStopLoadListResponse } from './loadStopLoadListResponse';


export interface LoadListLoadStopResponse { 
    loadStops?: Array<LoadStopLoadListResponse> | null;
    totalMiles?: number | null;
    firstPickup?: { [key: string]: number; } | null;
    completedPercentage?: number | null;
}

