/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumValue } from './enumValue';
import { LoadDriverInfo } from './loadDriverInfo';
import { BrokerLoadStopResponse } from './brokerLoadStopResponse';
import { CompanyUserShortResponse } from './companyUserShortResponse';


export interface LoadBrokerDetailsResponse { 
    id?: number;
    loadNumber?: string | null;
    referenceNumber?: string | null;
    dispatcher?: CompanyUserShortResponse;
    driver?: LoadDriverInfo;
    pickup?: BrokerLoadStopResponse;
    pickupCount?: number;
    delivery?: BrokerLoadStopResponse;
    deliveryCount?: number;
    status?: EnumValue;
    lastStatusPassed?: { [key: string]: number; } | null;
    totalRate?: number | null;
    totalMiles?: number | null;
    createdAt?: string;
    updatedAt?: string;
}

