/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type LoadSortBy = 'LoadNumber' | 'Dispatcher' | 'BrokerBusinessName' | 'BrokerContactName' | 'BrokerContactPhone' | 'Weight' | 'Status' | 'TruckType' | 'TrailerType' | 'TrailerLength' | 'Year' | 'DriverMessage' | 'InvoicedDate' | 'PaidDate' | 'AddedDate' | 'EditedDate' | 'Suspension' | 'LTLComboNumber' | 'AdditionalBillingRatesTotal';

export const LoadSortBy = {
    LoadNumber: 'LoadNumber' as LoadSortBy,
    Dispatcher: 'Dispatcher' as LoadSortBy,
    BrokerBusinessName: 'BrokerBusinessName' as LoadSortBy,
    BrokerContactName: 'BrokerContactName' as LoadSortBy,
    BrokerContactPhone: 'BrokerContactPhone' as LoadSortBy,
    Weight: 'Weight' as LoadSortBy,
    Status: 'Status' as LoadSortBy,
    TruckType: 'TruckType' as LoadSortBy,
    TrailerType: 'TrailerType' as LoadSortBy,
    TrailerLength: 'TrailerLength' as LoadSortBy,
    Year: 'Year' as LoadSortBy,
    DriverMessage: 'DriverMessage' as LoadSortBy,
    InvoicedDate: 'InvoicedDate' as LoadSortBy,
    PaidDate: 'PaidDate' as LoadSortBy,
    AddedDate: 'AddedDate' as LoadSortBy,
    EditedDate: 'EditedDate' as LoadSortBy,
    Suspension: 'Suspension' as LoadSortBy,
    LtlComboNumber: 'LTLComboNumber' as LoadSortBy,
    AdditionalBillingRatesTotal: 'AdditionalBillingRatesTotal' as LoadSortBy
};

