/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommentResponse } from './commentResponse';
import { EnumValue } from './enumValue';
import { LoadRequirementsResponse } from './loadRequirementsResponse';
import { BillingInfo } from './billingInfo';
import { CompanyUserShortResponse } from './companyUserShortResponse';
import { LoadDetails } from './loadDetails';
import { MilesInfo } from './milesInfo';
import { BrokerContactResponse } from './brokerContactResponse';
import { LoadStatusResponse } from './loadStatusResponse';
import { LoadStopInfo } from './loadStopInfo';
import { LoadBrokerInfo } from './loadBrokerInfo';
import { LoadDriverInfo } from './loadDriverInfo';
import { LoadBillingAdditionalResponse } from './loadBillingAdditionalResponse';


export interface LoadListDto { 
    id?: number;
    loadNumber?: string | null;
    ltlComboNumber?: string | null;
    statusType?: EnumValue;
    loadType?: EnumValue;
    lastStatusPassed?: { [key: string]: number; } | null;
    status?: LoadStatusResponse;
    dispatcher?: CompanyUserShortResponse;
    companyName?: string | null;
    broker?: LoadBrokerInfo;
    brokers?: Array<LoadBrokerInfo> | null;
    brokerContact?: BrokerContactResponse;
    loadDetails?: LoadDetails;
    truckId?: number | null;
    trailerId?: number | null;
    pickup?: LoadStopInfo;
    delivery?: LoadStopInfo;
    note?: string | null;
    baseRate?: number;
    totalRate?: number;
    totalAdjustedRate?: number | null;
    additionalBillingRatesTotal?: number | null;
    additionalBillingRates?: Array<LoadBillingAdditionalResponse> | null;
    advancePay?: number | null;
    driver?: LoadDriverInfo;
    totalDue?: number;
    miles?: MilesInfo;
    loadCommentsCount?: number;
    comments?: Array<CommentResponse> | null;
    createdAt?: string;
    updatedAt?: string;
    fileCount?: number | null;
    loadRequirements?: LoadRequirementsResponse;
    billing?: BillingInfo;
    invoicedDate?: string | null;
    paidDate?: string | null;
}

