/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Load } from './load';
import { TrailerLength } from './trailerLength';
import { TruckType } from './truckType';
import { LoadTemplate } from './loadTemplate';
import { TrailerType } from './trailerType';


export interface LoadRequirements { 
    id?: number;
    loadId?: number | null;
    load?: Load;
    loadTemplateId?: number | null;
    loadTemplate?: LoadTemplate;
    truckTypeId?: number | null;
    truckType?: TruckType;
    trailerTypeId?: number | null;
    trailerType?: TrailerType;
    doorType?: number | null;
    suspension?: number | null;
    trailerLengthId?: number | null;
    trailerLength?: TrailerLength;
    year?: number | null;
    liftgate?: boolean | null;
    driverMessage?: string | null;
    createdAt?: string;
    updatedAt?: string;
}

