/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoadStopItemMobileResponse { 
    description?: string | null;
    quantity?: number | null;
    temperature?: number | null;
    weight?: number | null;
    length?: number | null;
    height?: number | null;
    bolNumber?: string | null;
    appointmentNumber?: string | null;
    pickupNumber?: string | null;
    poNumber?: string | null;
    code?: string | null;
}

