/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumValue } from './enumValue';
import { ShipperShortMobileResponse } from './shipperShortMobileResponse';


export interface LoadStopMobileResponse { 
    id?: number;
    stopType?: EnumValue;
    stopOrder?: number;
    stopLoadOrder?: number;
    shipper?: ShipperShortMobileResponse;
    dateFrom?: string;
    dateTo?: string | null;
    arrive?: string | null;
    depart?: string | null;
    wait?: { [key: string]: number; } | null;
    driving?: { [key: string]: number; } | null;
    timeType?: EnumValue;
    milesType?: EnumValue;
    legMiles?: number | null;
    legHours?: number | null;
    legMinutes?: number | null;
}

