/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoadStopItemResponse } from './loadStopItemResponse';
import { EnumValue } from './enumValue';
import { ShipperShortResponse } from './shipperShortResponse';


export interface LoadStopResponse { 
    stopType?: EnumValue;
    stopOrder?: number;
    shipper?: ShipperShortResponse;
    dateFrom?: string;
    dateTo?: string | null;
    timeType?: EnumValue;
    timeFrom?: string | null;
    timeTo?: string | null;
    items?: Array<LoadStopItemResponse> | null;
    legMiles?: number | null;
    totalLegMiles?: number | null;
}

