/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileResponse } from './fileResponse';
import { EnumValue } from './enumValue';
import { CompanyUserShortResponse } from './companyUserShortResponse';
import { LinkResponse } from './linkResponse';


export interface MessageResponse { 
    id?: number;
    messageType?: EnumValue;
    sender?: CompanyUserShortResponse;
    conversationId?: number;
    content?: string | null;
    parentMessageId?: number | null;
    parentMessageContent?: string | null;
    createdAt?: string;
    updatedAt?: string;
    isEdited?: boolean;
    isDeleted?: boolean;
    files?: Array<FileResponse> | null;
    filesCount?: number;
    media?: Array<FileResponse> | null;
    mediaCount?: number;
    links?: Array<LinkResponse> | null;
    linksCount?: number;
}

