/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MilesByState } from './milesByState';
import { FuelTransaction } from './fuelTransaction';
import { LoadStop } from './loadStop';
import { RepairShop } from './repairShop';
import { MilesByUnit } from './milesByUnit';
import { Driver } from './driver';
import { MileStopType } from './mileStopType';
import { Parking } from './parking';
import { AddressEntity } from './addressEntity';
import { Trailer } from './trailer';


export interface MilesStop { 
    id?: number;
    milesByUnitId?: number;
    milesByUnit?: MilesByUnit;
    order?: number;
    type?: MileStopType;
    location: AddressEntity;
    longitude?: number;
    latitude?: number;
    isLoaded?: boolean;
    legMiles?: number;
    emptyMiles?: number;
    loadedMiles?: number;
    totalMiles?: number;
    travelHours?: number;
    travelMinutes?: number;
    dateTimeFrom?: string;
    dateTimeTo?: string | null;
    trailerId?: number | null;
    trailer?: Trailer;
    driverId?: number | null;
    driver?: Driver;
    loadStopId?: number | null;
    loadStop?: LoadStop;
    repairShopId?: number | null;
    repairShop?: RepairShop;
    parkingId?: number | null;
    parking?: Parking;
    fuelTransactionId?: number | null;
    fuelTransaction?: FuelTransaction;
    milesByStates?: Array<MilesByState> | null;
    createdAt?: string;
    updatedAt?: string;
}

