/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumValue } from './enumValue';
import { AddressEntity } from './addressEntity';


export interface MilesStopPayrollResponse { 
    id?: number;
    order?: number;
    type?: EnumValue;
    location?: AddressEntity;
    legMiles?: number;
    emptyMiles?: number;
    loadedMiles?: number;
    totalMiles?: number;
    travelHours?: number;
    travelMinutes?: number;
    dateTimeFrom?: string;
    dateTimeTo?: string | null;
    duration?: { [key: string]: number; } | null;
    subtotalAmount?: number;
    createdAt?: string;
    updatedAt?: string;
}

