/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumValue } from './enumValue';
import { DriverShortResponse } from './driverShortResponse';
import { PayrollDeductionResponse } from './payrollDeductionResponse';
import { PayrollPaymentResponse } from './payrollPaymentResponse';
import { LoadShortResponse } from './loadShortResponse';
import { PayrollCreditResponse } from './payrollCreditResponse';


export interface PayrollDriverCommissionResponse { 
    id?: number;
    driver?: DriverShortResponse;
    payrollNumber?: string | null;
    period?: string;
    closedDate?: string | null;
    paidDate?: string | null;
    status?: EnumValue;
    mileageAmount?: number;
    salaryAmount?: number;
    creditAmount?: number;
    deductionAmount?: number;
    totalAmount?: number;
    loadsCount?: number;
    additionalDays?: number | null;
    previousLoad?: LoadShortResponse;
    lastLoad?: LoadShortResponse;
    stops?: Array<LoadShortResponse> | null;
    credits?: Array<PayrollCreditResponse> | null;
    deductions?: Array<PayrollDeductionResponse> | null;
    payments?: Array<PayrollPaymentResponse> | null;
    createdAt?: string;
    updatedAt?: string;
}

