/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PayrollDeductionMinimalResponse } from './payrollDeductionMinimalResponse';
import { PayrollLoadMinimalResponse } from './payrollLoadMinimalResponse';
import { PayrollCommissionTotalSum } from './payrollCommissionTotalSum';
import { PayrollCreditMinimalResponse } from './payrollCreditMinimalResponse';
import { OwnerResponse } from './ownerResponse';
import { PayrollMapLocation } from './payrollMapLocation';
import { PayrollDeadlineShortResponse } from './payrollDeadlineShortResponse';
import { TruckShortResponse } from './truckShortResponse';
import { PayrollFuelMinimalResponse } from './payrollFuelMinimalResponse';


export interface PayrollOwnerResponse { 
    id?: number;
    previousLoadId?: number | null;
    owner?: OwnerResponse;
    truck?: TruckShortResponse;
    payrollNumber?: string | null;
    periodStart?: string;
    periodEnd?: string;
    payrollDeadLine?: PayrollDeadlineShortResponse;
    total?: number | null;
    commission?: number | null;
    salary?: number | null;
    includedDeductions?: Array<PayrollDeductionMinimalResponse> | null;
    excludedDeductions?: Array<PayrollDeductionMinimalResponse> | null;
    totalDeduction?: number;
    includedCredits?: Array<PayrollCreditMinimalResponse> | null;
    excludedCredits?: Array<PayrollCreditMinimalResponse> | null;
    totalCredits?: number;
    includedLoads?: Array<PayrollLoadMinimalResponse> | null;
    excludedLoads?: Array<PayrollLoadMinimalResponse> | null;
    totalFuels?: number;
    includedFuels?: Array<PayrollFuelMinimalResponse> | null;
    excludedFuels?: Array<PayrollFuelMinimalResponse> | null;
    mapLocations?: Array<PayrollMapLocation> | null;
    sums?: PayrollCommissionTotalSum;
}

