/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type PayTypeEnum = 'WireTransfer' | 'Cash' | 'Check' | 'MoneyCode' | 'Quick' | 'Zelle' | 'Venmo' | 'Cashapp' | 'PayPal';

export const PayTypeEnum = {
    WireTransfer: 'WireTransfer' as PayTypeEnum,
    Cash: 'Cash' as PayTypeEnum,
    Check: 'Check' as PayTypeEnum,
    MoneyCode: 'MoneyCode' as PayTypeEnum,
    Quick: 'Quick' as PayTypeEnum,
    Zelle: 'Zelle' as PayTypeEnum,
    Venmo: 'Venmo' as PayTypeEnum,
    Cashapp: 'Cashapp' as PayTypeEnum,
    PayPal: 'PayPal' as PayTypeEnum
};

