/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NetIncomeGraphPerformanceResponse } from './netIncomeGraphPerformanceResponse';
import { ViolationGraphPerformanceResponse } from './violationGraphPerformanceResponse';
import { RevenueGraphPerformanceResponse } from './revenueGraphPerformanceResponse';
import { FuelGallonGraphPerformanceResponse } from './fuelGallonGraphPerformanceResponse';
import { FuelCostGraphPerformanceResponse } from './fuelCostGraphPerformanceResponse';
import { MilesGraphPerformanceResponse } from './milesGraphPerformanceResponse';
import { AccidentGraphPerformanceResponse } from './accidentGraphPerformanceResponse';
import { PricePerGallonGraphPerformanceResponse } from './pricePerGallonGraphPerformanceResponse';
import { ShipperGraphPerformanceResponse } from './shipperGraphPerformanceResponse';
import { LoadRatePerMileGraphPerformanceResponse } from './loadRatePerMileGraphPerformanceResponse';
import { UserGraphPerformanceResponse } from './userGraphPerformanceResponse';
import { TrailerGraphPerformanceResponse } from './trailerGraphPerformanceResponse';
import { BrokerGraphPerformanceResponse } from './brokerGraphPerformanceResponse';
import { DriverGraphPerformanceResponse } from './driverGraphPerformanceResponse';
import { LoadGraphPerformanceResponse } from './loadGraphPerformanceResponse';
import { RepairCostGraphPerformanceResponse } from './repairCostGraphPerformanceResponse';
import { ExpencesGraphPerformanceResponse } from './expencesGraphPerformanceResponse';
import { RoadsideGraphPerformanceResponse } from './roadsideGraphPerformanceResponse';
import { TruckGraphPerformanceResponse } from './truckGraphPerformanceResponse';
import { RepairShopGraphPerformanceResponse } from './repairShopGraphPerformanceResponse';


export interface PerformanceGraphResponse { 
    userGraphPerformance?: UserGraphPerformanceResponse;
    accidentGraphPerformance?: AccidentGraphPerformanceResponse;
    brokerGraphPerformance?: BrokerGraphPerformanceResponse;
    driverGraphPerformance?: DriverGraphPerformanceResponse;
    expencesGraphPerformance?: ExpencesGraphPerformanceResponse;
    fuelCostGraphPerformance?: FuelCostGraphPerformanceResponse;
    fuelGallonGraphPerformance?: FuelGallonGraphPerformanceResponse;
    loadGraphPerformance?: LoadGraphPerformanceResponse;
    milesGraphPerformance?: MilesGraphPerformanceResponse;
    netIncomeGraphPerformance?: NetIncomeGraphPerformanceResponse;
    repairCostGraphPerformance?: RepairCostGraphPerformanceResponse;
    repairShopGraphPerformance?: RepairShopGraphPerformanceResponse;
    revenueGraphPerformance?: RevenueGraphPerformanceResponse;
    roadsideGraphPerformance?: RoadsideGraphPerformanceResponse;
    shipperGraphPerformance?: ShipperGraphPerformanceResponse;
    trailerGraphPerformance?: TrailerGraphPerformanceResponse;
    truckGraphPerformance?: TruckGraphPerformanceResponse;
    violationGraphPerformance?: ViolationGraphPerformanceResponse;
    loadRatePerMileGraphPerformance?: LoadRatePerMileGraphPerformanceResponse;
    pricePerGallonGraphPerformance?: PricePerGallonGraphPerformanceResponse;
}

