/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BankResponse } from './bankResponse';
import { ApplicantPreviousAddressResponse } from './applicantPreviousAddressResponse';
import { AddressEntity } from './addressEntity';
import { ApplicantPersonalInfoReviewResponse } from './applicantPersonalInfoReviewResponse';


export interface PersonalInfoFeedbackResponse { 
    id?: number;
    applicantId?: number;
    firstName?: string | null;
    lastName?: string | null;
    fullName?: string | null;
    phone?: string | null;
    email?: string | null;
    doB?: string;
    isAgreement?: boolean;
    address?: AddressEntity;
    ssn?: string | null;
    bank?: BankResponse;
    bankName?: string | null;
    accountNumber?: string | null;
    routingNumber?: string | null;
    legalWork?: boolean;
    anotherName?: boolean;
    anotherNameDescription?: string | null;
    inMilitary?: boolean;
    felony?: boolean;
    misdemeanor?: boolean;
    drunkDriving?: boolean;
    reviewed?: boolean | null;
    approved?: boolean | null;
    previousAddresses?: Array<ApplicantPreviousAddressResponse> | null;
    personalInfoReview?: ApplicantPersonalInfoReviewResponse;
}

