/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Company } from './company';
import { PMTrailerUnit } from './pMTrailerUnit';
import { RepairItem } from './repairItem';
import { PMStatus } from './pMStatus';


export interface PMTrailer { 
    id?: number;
    title?: string | null;
    months?: number;
    status?: PMStatus;
    logoName?: string | null;
    createdAt?: string;
    updatedAt?: string;
    items?: Array<RepairItem> | null;
    pmTrailerUnitId?: number | null;
    pmTrailerUnit?: PMTrailerUnit;
    companyId?: number | null;
    company?: Company;
    updateFromDefaultPM?: boolean;
}

