/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumValue } from './enumValue';


export interface PMTrailerResponse { 
    trailerId?: number | null;
    id?: number;
    title?: string | null;
    status?: EnumValue;
    months?: number;
    passedMonths?: number | null;
    logoName?: string | null;
}

