/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { State } from './state';
import { Truck } from './truck';
import { Trailer } from './trailer';


export interface Registration { 
    id?: number;
    truckId?: number | null;
    truck?: Truck;
    trailerId?: number | null;
    trailer?: Trailer;
    stateId?: number;
    state?: State;
    issueDate?: string;
    expDate?: string | null;
    licensePlate?: string | null;
    note?: string | null;
    createdAt?: string;
    updatedAt?: string;
}

