/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ServiceType = 'Truck' | 'Trailer' | 'Mobile' | 'Shop' | 'Towing' | 'Parts' | 'Tire' | 'Dealer';

export const ServiceType = {
    Truck: 'Truck' as ServiceType,
    Trailer: 'Trailer' as ServiceType,
    Mobile: 'Mobile' as ServiceType,
    Shop: 'Shop' as ServiceType,
    Towing: 'Towing' as ServiceType,
    Parts: 'Parts' as ServiceType,
    Tire: 'Tire' as ServiceType,
    Dealer: 'Dealer' as ServiceType
};

