/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Department } from './department';
import { LoadStop } from './loadStop';
import { Shipper } from './shipper';


export interface ShipperContact { 
    id?: number;
    fullName?: string | null;
    departmentId?: number;
    phone?: string | null;
    phoneExt?: string | null;
    email?: string | null;
    shipperId?: number;
    shipper?: Shipper;
    department?: Department;
    loadStops?: Array<LoadStop> | null;
    createdAt?: string;
    updatedAt?: string;
}

