/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileResponse } from './fileResponse';
import { RatingReviewResponse } from './ratingReviewResponse';
import { EnumValue } from './enumValue';
import { ShipperContactResponse } from './shipperContactResponse';
import { AddressEntity } from './addressEntity';


export interface ShipperResponse { 
    id?: number;
    businessName?: string | null;
    phone?: string | null;
    phoneExt?: string | null;
    email?: string | null;
    address?: AddressEntity;
    locationType?: EnumValue;
    longitude?: number | null;
    latitude?: number | null;
    receivingAppointment?: boolean;
    receivingFrom?: string | null;
    receivingTo?: string | null;
    shippingAppointment?: boolean | null;
    shippingFrom?: string | null;
    shippingTo?: string | null;
    receivingOpenTwentyFourHours?: boolean;
    shippingOpenTwentyFourHours?: boolean;
    note?: string | null;
    shippingHoursSameReceiving?: boolean;
    shipperContacts?: Array<ShipperContactResponse> | null;
    ratingReviews?: Array<RatingReviewResponse> | null;
    status?: number;
    downCount?: number;
    upCount?: number;
    commentCount?: number;
    currentCompanyUserRating?: number | null;
    rating?: number;
    pickups?: number;
    deliveries?: number;
    totalPickupDelivery?: number;
    avgPickupTimeInMin?: number | null;
    avgDeliveryTimeInMin?: number | null;
    files?: Array<FileResponse> | null;
    fileCount?: number | null;
    cover?: FileResponse;
    createdAt?: string;
    updatedAt?: string;
    lastUsedAt?: string | null;
}

