/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type StateFilter = 'Broker' | 'Shipper' | 'RepairShop';

export const StateFilter = {
    Broker: 'Broker' as StateFilter,
    Shipper: 'Shipper' as StateFilter,
    RepairShop: 'RepairShop' as StateFilter
};

