/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DispatchHosCommand } from './dispatchHosCommand';
import { AddressEntity } from './addressEntity';


export interface SwitchDispatchCommand { 
    id?: number;
    truckId?: number | null;
    location?: AddressEntity;
    trailerId?: number | null;
    driverId?: number | null;
    coDriverId?: number | null;
    hoursOfService?: Array<DispatchHosCommand> | null;
}

