/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileResponse } from './fileResponse';
import { StateResponse } from './stateResponse';


export interface TitleResponse { 
    id?: number;
    number?: string | null;
    note?: string | null;
    state?: StateResponse;
    purchaseDate?: string;
    issueDate?: string;
    files?: Array<FileResponse> | null;
}

