/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TopRepairShopResponsePagination } from './topRepairShopResponsePagination';
import { RepairShopIntervalResponse } from './repairShopIntervalResponse';


export interface TopRepairShopListResponse { 
    pagination?: TopRepairShopResponsePagination;
    topRepairShops?: Array<RepairShopIntervalResponse> | null;
    allOther?: Array<RepairShopIntervalResponse> | null;
    totalCost?: number | null;
    totalVisit?: number | null;
    intervalLabels?: Array<string> | null;
}

