/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TruckIntervalResponse } from './truckIntervalResponse';


export interface TopTruckResponse { 
    id?: number;
    number?: string | null;
    mileage?: number | null;
    revenue?: number | null;
    mileagePercentage?: number | null;
    revenuePercentage?: number | null;
    intervals?: Array<TruckIntervalResponse> | null;
}

