/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TrailerSortBy = 'Unit' | 'Type' | 'Vin' | 'Make' | 'Model' | 'Year' | 'Color' | 'Length' | 'Owner' | 'EmptyWeight' | 'Volume' | 'Axle' | 'Suspension' | 'TireSize' | 'ReeferUnit' | 'DoorType' | 'InsPolicy' | 'Mileage' | 'PurchasePrice' | 'PurchaseDate' | 'LicencePlateNo' | 'LicenceState' | 'LicenceExpiration' | 'FhwaTerm' | 'FhwaInspectionIssued' | 'FhwaInspectionExpiration' | 'TitleNumber' | 'TitleState' | 'TitlePurchase' | 'TitleIssued' | 'AssignedDriver' | 'AssignedTruck' | 'DateAdded' | 'DateUpdated' | 'DateDeactivated';

export const TrailerSortBy = {
    Unit: 'Unit' as TrailerSortBy,
    Type: 'Type' as TrailerSortBy,
    Vin: 'Vin' as TrailerSortBy,
    Make: 'Make' as TrailerSortBy,
    Model: 'Model' as TrailerSortBy,
    Year: 'Year' as TrailerSortBy,
    Color: 'Color' as TrailerSortBy,
    Length: 'Length' as TrailerSortBy,
    Owner: 'Owner' as TrailerSortBy,
    EmptyWeight: 'EmptyWeight' as TrailerSortBy,
    Volume: 'Volume' as TrailerSortBy,
    Axle: 'Axle' as TrailerSortBy,
    Suspension: 'Suspension' as TrailerSortBy,
    TireSize: 'TireSize' as TrailerSortBy,
    ReeferUnit: 'ReeferUnit' as TrailerSortBy,
    DoorType: 'DoorType' as TrailerSortBy,
    InsPolicy: 'InsPolicy' as TrailerSortBy,
    Mileage: 'Mileage' as TrailerSortBy,
    PurchasePrice: 'PurchasePrice' as TrailerSortBy,
    PurchaseDate: 'PurchaseDate' as TrailerSortBy,
    LicencePlateNo: 'LicencePlateNo' as TrailerSortBy,
    LicenceState: 'LicenceState' as TrailerSortBy,
    LicenceExpiration: 'LicenceExpiration' as TrailerSortBy,
    FhwaTerm: 'FhwaTerm' as TrailerSortBy,
    FhwaInspectionIssued: 'FhwaInspectionIssued' as TrailerSortBy,
    FhwaInspectionExpiration: 'FhwaInspectionExpiration' as TrailerSortBy,
    TitleNumber: 'TitleNumber' as TrailerSortBy,
    TitleState: 'TitleState' as TrailerSortBy,
    TitlePurchase: 'TitlePurchase' as TrailerSortBy,
    TitleIssued: 'TitleIssued' as TrailerSortBy,
    AssignedDriver: 'AssignedDriver' as TrailerSortBy,
    AssignedTruck: 'AssignedTruck' as TrailerSortBy,
    DateAdded: 'DateAdded' as TrailerSortBy,
    DateUpdated: 'DateUpdated' as TrailerSortBy,
    DateDeactivated: 'DateDeactivated' as TrailerSortBy
};

