/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DispatchStatus } from './dispatchStatus';
import { AddressEntity } from './addressEntity';


export interface UpdateDispatchCommand { 
    id?: number;
    status?: DispatchStatus;
    order?: number;
    truckId?: number | null;
    trailerId?: number | null;
    driverId?: number | null;
    coDriverId?: number | null;
    location?: AddressEntity;
    hourOfService?: number | null;
    note?: string | null;
    loadIds?: Array<number> | null;
}

