/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateContactEmailCommand } from './updateContactEmailCommand';
import { UpdateContactPhoneCommand } from './updateContactPhoneCommand';
import { AddressEntity } from './addressEntity';


export interface UpdateCompanyContactCommand { 
    id?: number;
    name?: string | null;
    address?: AddressEntity;
    note?: string | null;
    shared?: boolean;
    avatar?: string | null;
    companyContactLabelId?: number | null;
    contactPhones?: Array<UpdateContactPhoneCommand> | null;
    contactEmails?: Array<UpdateContactEmailCommand> | null;
}

