/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressEntity } from './addressEntity';


export interface UpdatePersonalInfoCommand { 
    applicantId?: number;
    firstName?: string | null;
    lastName?: string | null;
    phone?: string | null;
    doB?: string;
    isAgreed?: boolean;
    address?: AddressEntity;
    ssn?: string | null;
    bankId?: number | null;
    accountNumber?: string | null;
    routingNumber?: string | null;
    legalWork?: boolean;
    anotherName?: boolean;
    anotherNameDescription?: string | null;
    inMilitary?: boolean;
    felony?: boolean;
    misdemeanor?: boolean;
    drunkDriving?: boolean;
    previousAddresses?: Array<AddressEntity> | null;
}

