/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TruckMakeResponse } from './truckMakeResponse';
import { TrailerMakeResponse } from './trailerMakeResponse';
import { TruckEngineTypeResponse } from './truckEngineTypeResponse';


export interface VinDecodeResponse { 
    model?: string | null;
    year?: number | null;
    truckMake?: TruckMakeResponse;
    trailerMake?: TrailerMakeResponse;
    engineType?: TruckEngineTypeResponse;
}

