/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ViolationCategory = 'UnsafeDriving' | 'HOSCompliance' | 'VehicleMaint' | 'DrugsAlcohol' | 'HMCompliance' | 'DriverFitness';

export const ViolationCategory = {
    UnsafeDriving: 'UnsafeDriving' as ViolationCategory,
    HosCompliance: 'HOSCompliance' as ViolationCategory,
    VehicleMaint: 'VehicleMaint' as ViolationCategory,
    DrugsAlcohol: 'DrugsAlcohol' as ViolationCategory,
    HmCompliance: 'HMCompliance' as ViolationCategory,
    DriverFitness: 'DriverFitness' as ViolationCategory
};

