/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ViolationCommand { 
    id?: number | null;
    code?: string | null;
    category?: string | null;
    unit?: string | null;
    sw?: string | null;
    oos?: boolean | null;
    sms?: boolean | null;
    description?: string | null;
    extraDescription?: string | null;
    reason?: string | null;
    violationCategoryId?: number | null;
}

