/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ViolationCategory } from './violationCategory';
import { RoadsideInspection } from './roadsideInspection';


export interface Violation { 
    id?: number;
    roadsideInspectionId?: number;
    roadsideInspection?: RoadsideInspection;
    code?: string | null;
    category?: string | null;
    unit?: string | null;
    sw?: string | null;
    oos?: boolean | null;
    sms?: boolean | null;
    description?: string | null;
    extraDescription?: string | null;
    violationCategoryId?: number | null;
    violationCategory?: ViolationCategory;
    reason?: string | null;
    createdAt?: string;
    updatedAt?: string;
}

