/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WorkExperienceItemReviewResponse { 
    id?: number;
    isEmployerValid?: boolean | null;
    employerMessage?: string | null;
    isJobDescriptionValid?: boolean;
    isFromValid?: boolean;
    isToValid?: boolean;
    jobDescriptionMessage?: string | null;
    isPhoneValid?: boolean;
    isFaxValid?: boolean;
    isEmailValid?: boolean;
    contactMessage?: string | null;
    isAddressValid?: boolean;
    addressMessage?: string | null;
    isCfrPartValid?: boolean;
    isFmcsaValid?: boolean;
    cfrFmcsaMessage?: string | null;
    isReasonForLeavingValid?: boolean | null;
    reasonForLeavingMessage?: string | null;
    isAccountForPeriodBetweenValid?: boolean | null;
    accountForPeriodBetweenMessage?: string | null;
    workExperienceId?: number;
}

