/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WorkExperienceReviewResponse { 
    id?: number;
    isEmployerValid?: boolean;
    employerMessage?: string | null;
    isJobValid?: boolean;
    jobMessage?: string | null;
    isContactValid?: boolean;
    contactMessage?: string | null;
    isAddressValid?: boolean;
    addressMessage?: string | null;
    isCFRPartValid?: boolean;
    cfrPartMessage?: string | null;
    isReasonForLeavingValid?: boolean;
    reasonForLeavingMessage?: string | null;
    isAccountForPeriodBetweenValid?: boolean;
    accountForPeriodBetweenMessage?: string | null;
    workExperienceId?: number;
}

