export enum DispatchTableStringEnum {
    TRUCK = 'truck',
    TRAILER = 'trailer',
    LOCATION = 'location',
    DRIVER = 'driver',

    COMMON = 'common',
    COLORS = 'colors',

    OPEN = 'open',
    SMALL = 'small',
    TRUCK_MODAL = 'truck-modal',
    TRAILER_MODAL = 'trailer-modal',
    DRIVER_MODAL = 'driver-modal',

    TRUCK_ID = 'truckId',
    TRAILER_ID = 'trailerId',
    DRIVER_ID = 'driverId',
    CO_DRIVER_ID = 'coDriverId',

    EMPTY_STRING = '',

    CIRCLE_ROUTE = 'ic_circle.svg',
    OWNER_STATUS_ROUTE = 'ic_owner-status.svg',

    PARKING = 'parking',

    STATUS_HISTORY_MODAL = 'status-history-modal',

    BOARD = 'Board',
    BOARD_2 = 'board',
    DISPATCH_USER_SELECT = 'dispatchUserSelect',
    TEAM_BOARD = 'Team Board',
    ALL_BOARDS = 'All Boards',
    ACTIVE = 'active',
    DISPATCH = 'Dispatch',
    TOGGLE_LOCKED = 'toggle-locked',
    OPEN_DISPATCH_LOAD_MODAL = 'open-dispatch-load-modal',
    DROPDOWN = 'dropdown',
    LOAD_DISPATCHER = 'load-dispatcher',
    DISPATCHER = 'dispatcher',
    OFF = 'Off',
    OFF_2 = 'off',
    TEXTAREA = 'textarea',
    COPY = 'copy',
    VALUE = 'value',
    NOTE = 'NOTE',
    TRUCK_1 = 'TRUCK',
    TRAILER_1 = 'TRAILER',
    DRIVER_1 = 'DRIVER',
    LAST_LOCATION = 'LAST LOCATION',
    PARKING_1 = 'PARKING',
    INSPECTION = 'INSPECTION',
    PROGRESS = 'PROGRESS',
    STATUS = 'STATUS',
    DISPATCHER_1 = 'DISPATCHER',
    PICKUP = 'PICKUP',
}
