export enum DispatchTableStringEnum {
    TRUCK = 'truck',
    TRAILER = 'trailer',
    LOCATION = 'location',
    DRIVER = 'driver',

    COMMON = 'common',
    COLORS = 'colors',

    OPEN = 'open',
    SMALL = 'small',
    TRUCK_MODAL = 'truck-modal',
    TRAILER_MODAL = 'trailer-modal',
    DRIVER_MODAL = 'driver-modal',

    TRUCK_ID = 'truckId',
    TRAILER_ID = 'trailerId',
    DRIVER_ID = 'driverId',
    CO_DRIVER_ID = 'coDriverId',

    EMPTY_STRING = '',

    CIRCLE_ROUTE = 'ic_circle.svg',
    OWNER_STATUS_ROUTE = 'ic_owner-status.svg',

    PARKING = 'parking',

    STATUS_HISTORY_MODAL = 'status-history-modal',

    BOARD = 'Board',
    BOARD_2 = 'board',
    DISPATCH_USER_SELECT = 'dispatchUserSelect',
    TEAM_BOARD = 'Team Board',
    ALL_BOARDS = 'All Boards',
    ACTIVE = 'active',
    ACTIVE_2 = 'Active',
    DISPATCH = 'Dispatch',
    TOGGLE_LOCKED = 'toggle-locked',
    OPEN_DISPATCH_LOAD_MODAL = 'open-dispatch-load-modal',
    DROPDOWN = 'dropdown',
    LOAD_DISPATCHER = 'load-dispatcher',
    DISPATCHER = 'dispatcher',
    DISPATCHER_2 = 'Dispatcher',
    OFF = 'Off',
    OFF_2 = 'off',
    TEXTAREA = 'textarea',
    COPY = 'copy',
    VALUE = 'value',
    NOTE = 'NOTE',
    NOTE_2 = 'Note',
    NOTE_3 = 'note',
    TRUCK_1 = 'TRUCK',
    TRAILER_1 = 'TRAILER',
    DRIVER_1 = 'DRIVER',
    LAST_LOCATION = 'LAST LOCATION',
    PARKING_1 = 'PARKING',
    INSPECTION = 'INSPECTION',
    PROGRESS = 'PROGRESS',
    PROGRESS_2 = 'Progress',
    PROGRESS_3 = 'progress',
    STATUS = 'STATUS',
    STATUS_2 = 'status',
    DISPATCHER_1 = 'DISPATCHER',
    PICKUP = 'PICKUP',
    ALL_ASSIGNED = 'All Assigned',
    DISPATCH_TABLE_CONFIG = 'dispatch-table-config',
    DISPATCH_TABLE_COLUMN_WIDTHS = 'dispatch-table-column-widths',
    PRE_TRIP = 'PreTrip',
    CITY = 'city',

    // Resize
    CURSOR = 'cursor',
    COL_RESIZE = 'col-resize',
    DOCUMENT = 'document',
    MOUSE_MOVE = 'mousemove',
    MOUSE_UP = 'mouseup',
    WIDTH = 'width',
    NAME = 'Name',
    PICKUP_DELIVERY = 'Pickup & Delivery',
    PICKUP_DELIVERY_2 = 'Pickup&Delivery',
    PICKUP_DELIVERY_3 = 'pickup_delivery',
    FIRST_NAME = 'firstName',
    TRUCK_NUMBER = 'truckNumber',
    TRAILER_NUMBER = 'trailerNumber',
    SLOT_NUMBER = 'slotNumber',

    // Progress bar
    NO_GPS_DEVICE = 'NO GPS DEVICE',
    DEADHEAD = 'DeadHead',
}
