export function getFuelTransactionColumnDefinition() { 
  return [
    {
      ngTemplate: 'checkbox',
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'text',
      title: 'Unit #',
      field: 'truckNumber',
      name: 'Unit #',
      sortName: 'truckNumber',
      hidden: false,
      width: 120,
      minWidth: 120,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Driver',
      field: 'driverFullName',
      name: 'Driver',
      sortName: 'driverFullName',
      hidden: false,
      width: 129,
      minWidth: 129,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Fuel Card #',
      field: 'cardNumber',
      name: 'Fuel Card #',
      sortName: 'cardNumber',
      hidden: false,
      width: 87,
      minWidth: 87,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Date',
      field: 'transactionDate',
      name: 'Date',
      sortName: 'transactionDate',
      hidden: false,
      width: 86,
      minWidth: 86,
      filter: '',
      isNumeric: true,
      isDate: true,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Time',
      field: 'transactionTime',
      name: 'Time',
      sortName: 'transactionTime',
      hidden: false,
      width: 79,
      minWidth: 79,
      filter: '',
      isNumeric: false,
      index: 5,
      sortable: false,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Fuel Stop',
      field: 'name',
      name: 'Fuel Stop',
      sortName: 'name',
      hidden: false,
      width: 146,
      minWidth: 146,
      filter: '',
      isNumeric: false,
      index: 6,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Location',
      field: 'location',
      name: 'Location',
      sortName: 'location',
      hidden: false,
      width: 215,
      minWidth: 215,
      filter: '',
      isNumeric: false,
      index: 7,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'description',
      title: 'Item',
      field: 'fuelTableItem',
      name: 'Item',
      sortName: '',
      hidden: false,
      width: 143,
      minWidth: 143,
      filter: '',
      isNumeric: false,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      showQTY: true
    },
    {
      ngTemplate: 'text',
      title: 'Fuel gal.',
      field: 'qty',
      name: 'Fuel gal.',
      sortName: 'qty',
      hidden: false,
      width: 86,
      minWidth: 86,
      filter: '',
      isNumeric: false,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      showQTY: true
    },
    {
      ngTemplate: 'ppg',
      title: 'PPG',
      field: '',
      name: 'PPG',
      sortName: '',
      hidden: false,
      width: 86,
      minWidth: 86,
      filter: '',
      isNumeric: false,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      showQTY: true
    },
    {
      ngTemplate: 'total',
      title: 'Total',
      field: 'total',
      name: 'Total',
      sortName: 'total',
      hidden: false,
      width: 90,
      minWidth: 90,
      filter: '',
      isNumeric: false,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      showFuelDropDown: true,
      class: 'overflow-unset'
    },
    {
      ngTemplate: 'actions',
      title: 'Actions',
      field: 'action',
      name: '',
      hidden: false,
      width: 40,
      minWidth: 40,
      filter: '',
      isNumeric: false,
      index: 10,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
      isAction: true
    },
  ];
}

export function getFuelStopColumnDefinition() { 
  return [
    {
      ngTemplate: 'checkbox',
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'text',
      title: 'Name',
      field: 'tableName',
      name: 'Name',
      sortName: '',
      hidden: false,
      width: 145,
      minWidth: 145,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Store #',
      field: 'tableStore',
      name: 'Store #',
      sortName: '',
      hidden: false,
      width: 96,
      minWidth: 96,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Address',
      field: 'tableAddress',
      name: 'Address',
      sortName: '',
      hidden: false,
      width: 215,
      minWidth: 215,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Phone',
      field: 'tablePhone',
      name: 'Phone',
      sortName: '',
      hidden: false,
      width: 127,
      minWidth: 127,
      filter: '',
      isNumeric: true,
      isDate: true,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'PPG',
      field: 'tablePPG',
      name: 'PPG',
      sortName: '',
      hidden: false,
      width: 109,
      minWidth: 109,
      filter: '',
      isNumeric: false,
      index: 5,
      sortable: false,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Last $',
      field: 'tableLast',
      name: 'Last $',
      sortName: '',
      hidden: false,
      width: 84,
      minWidth: 84,
      filter: '',
      isNumeric: false,
      index: 5,
      sortable: false,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Used',
      field: 'tableUsed',
      name: 'Used',
      sortName: '',
      hidden: false,
      width: 91,
      minWidth: 91,
      filter: '',
      isNumeric: false,
      index: 6,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Total Cost',
      field: 'tableTotalCost',
      name: 'Total Cost',
      sortName: '',
      hidden: false,
      width: 92,
      minWidth: 92,
      filter: '',
      isNumeric: false,
      index: 7,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'favorite',
      title: 'Favorite',
      field: 'favorite',
      name: '',
      hidden: false,
      width: 40,
      minWidth: 40,
      headIconStyle: {
        width: 18,
        height: 18,
        imgPath: '../../../assets/svg/truckassist-table/favorite-selected-row.svg',
      },
      filter: '',
      isNumeric: false,
      index: 17,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: false,
      isAction: true
    },
    {
      ngTemplate: 'actions',
      title: 'Actions',
      field: 'action',
      name: '',
      hidden: false,
      width: 40,
      minWidth: 40,
      filter: '',
      isNumeric: false,
      index: 10,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
      isAction: true
    },
  ];
}
