export function getAccountingFuelColumnDefinition() {
  return [
    {
      ngTemplate: 'checkbox',
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'text',
      title: 'Unit #',
      field: 'truckNumber',
      name: 'Unit #',
      sortName: 'truckNumber',
      hidden: false,
      width: 70,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Driver',
      field: 'driverFullName',
      name: 'Driver',
      sortName: 'driverFullName',
      hidden: false,
      width: 150,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Fuel Card #',
      field: 'cardNumber',
      name: 'Fuel Card #',
      sortName: 'cardNumber',
      hidden: false,
      width: 150,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Date',
      field: 'transactionDate',
      name: 'Date',
      sortName: 'transactionDate',
      hidden: false,
      width: 90,
      filter: '',
      isNumeric: true,
      isDate: true,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Time',
      field: 'transactionTime',
      name: 'Time',
      sortName: 'transactionTime',
      hidden: false,
      width: 90,
      filter: '',
      isNumeric: false,
      index: 5,
      sortable: false,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Fuel Stop',
      field: 'name',
      name: 'Fuel Stop',
      sortName: 'name',
      hidden: false,
      width: 200,
      filter: '',
      isNumeric: false,
      index: 6,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Location',
      field: 'location',
      name: 'Location',
      sortName: 'location',
      hidden: false,
      width: 200,
      filter: '',
      isNumeric: false,
      index: 7,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'item-drop',
      title: 'Item',
      field: 'items',
      name: 'Item',
      sortName: '',
      hidden: false,
      width: 128,
      filter: '',
      isNumeric: false,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      showQTY: true
    },
    {
      ngTemplate: 'text',
      title: 'Fuel gal.',
      field: 'qty',
      name: 'Fuel gal.',
      sortName: 'qty',
      hidden: false,
      width: 90,
      filter: '',
      isNumeric: false,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      showQTY: true
    },
    {
      ngTemplate: 'ppg',
      title: 'PPG',
      field: '',
      name: 'PPG',
      sortName: '',
      hidden: false,
      width: 50,
      filter: '',
      isNumeric: false,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      showQTY: true
    },
    {
      ngTemplate: 'total',
      title: 'Total',
      field: 'total',
      name: 'Total',
      sortName: 'total',
      hidden: false,
      width: 90,
      filter: '',
      isNumeric: false,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      showFuelDropDown: true,
      class: 'overflow-unset'
    },
    {
      ngTemplate: 'attachments',
      title: '',
      field: 'additionalData.files',
      name: '',
      moveRight: true,
      headIconStyle: {
        width: 19,
        height: 19,
        imgPath:
          'assets/svg/truckassist-table/attachment/attachemnt-regular-svgIcon.svg',
      },
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 16,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'actions',
      title: '',
      field: 'action',
      name: '',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 10,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
  ];
}
