// APPLICANT TABLE COLUMNS DEFINITION
export function getApplicantColumnsDefinition() {
  return [
    {
      ngTemplate: 'checkbox',
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      width: 28,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'nameLink',
      title: 'Name',
      field: 'fullName',
      name: 'Name',
      hidden: false,
      width: 170,
      pdfWidth: 10,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: true,
      linkField: {
        routerLinkStart: '',
        routerLinkEnd: '',
      },
    },
    {
      ngTemplate: 'text',
      title: 'Dob',
      field: 'dob',
      name: 'Dob',
      hidden: false,
      width: 119,
      filter: '',
      isNumeric: true,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Phone',
      field: 'phone',
      name: 'Phone',
      hidden: false,
      width: 108,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Email',
      field: 'email',
      name: 'Email',
      hidden: false,
      width: 153,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'applicantDoneCheckbox',
      title: 'App.',
      field: 'app',
      name: 'App.',
      setCenter: true,
      hidden: false,
      width: 55,
      filter: '',
      isNumeric: true,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'applicantDoneCheckbox',
      title: 'MVR',
      field: 'mvr',
      name: 'MVR',
      hidden: false,
      setCenter: true,
      width: 55,
      filter: '',
      isNumeric: true,
      isDate: true,
      index: 6,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'applicantDoneCheckbox',
      title: 'PSP',
      field: 'psp',
      name: 'PSP',
      isComputed: false,
      hidden: false,
      setCenter: true,
      width: 55,
      filter: '',
      isNumeric: true,
      isDate: true,
      index: 7,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'applicantDoneCheckbox',
      title: 'SPH',
      field: 'sph',
      name: 'SPH',
      hidden: false,
      setCenter: true,
      width: 55,
      filter: '',
      isNumeric: true,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'applicantDoneCheckbox',
      title: 'SSN',
      field: 'ssnApplicant',
      setCenter: true,
      name: 'SSN',
      hidden: false,
      width: 55,
      filter: '',
      isNumeric: true,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'progress',
      title: 'Medical',
      field: 'medical',
      name: 'Medical',
      hidden: false,
      width: 145,
      filter: '',
      isNumeric: true,
      index: 10,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: {
        start: 'cdl[0].startDate',
        end: 'cdl[0].endDate',
      },
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'progress',
      title: 'CDL',
      field: 'cdl',
      name: 'CDL',
      hidden: false,
      width: 139,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: {
        start: 'cdl[0].startDate',
        end: 'cdl[0].endDate',
      },
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'applicantReview',
      title: 'Rev',
      field: 'rev',
      name: 'Rev',
      setCenter: true,
      hidden: false,
      width: 45,
      filter: '',
      isNumeric: false,
      index: 12,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'attachments',
      title: '',
      field: 'additionalData.files',
      name: '',
      hidden: false,
      width: 18,
      moveRight: true,
      headIconStyle: {
        width: 19,
        height: 19,
        imgPath:
          'assets/svg/truckassist-table/attachment/attachemnt-regular-svgIcon.svg',
      },
      filter: '',
      isNumeric: false,
      index: 16,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'note',
      title: '',
      field: 'additionalData.note',
      name: '',
      hidden: false,
      width: 40,
      headIconStyle: {
        width: 16,
        height: 18,
        imgPath: '',
      },
      filter: '',
      isNumeric: false,
      index: 17,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: false,
    },
    {
      ngTemplate: 'actions',
      title: '',
      field: 'action',
      name: '',
      headIconStyle: {
        width: 22,
        height: 6,
        imgPath: '',
      },
      hidden: false,
      width: 42,
      filter: '',
      isNumeric: false,
      index: 18,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
  ] as any[];
}
