// APPLICANT TABLE COLUMNS DEFINITION
export function getApplicantColumnsDefinition() { 
  return [
    {
      ngTemplate: 'checkbox',
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      width: 28,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'nameLink',
      title: 'Name',
      field: 'fullName',
      name: 'Name',
      hidden: false,
      width: 129,
      minWidth: 129,
      pdfWidth: 10,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: true,
      link: {
        routerLinkStart: '/applicant/',
        routerLinkEnd: '/broker-details',
      },
    },
    {
      ngTemplate: 'text',
      title: 'Invited',
      field: 'invited',
      name: 'Invited',
      hidden: false,
      width: 86,
      minWidth: 86,
      filter: '',
      isNumeric: true,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Accepted',
      field: 'accepted',
      name: 'Accepted',
      hidden: false,
      width: 86,
      minWidth: 86,
      filter: '',
      isNumeric: true,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Phone',
      field: 'phone',
      name: 'Phone',
      hidden: false,
      width: 127,
      minWidth: 127,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Dob',
      field: 'dob',
      name: 'Dob',
      hidden: false,
      width: 86,
      minWidth: 86,
      filter: '',
      isNumeric: true,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Email',
      field: 'email',
      name: 'Email',
      hidden: false,
      width: 151,
      minWidth: 151,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: '',
      title: 'App.',
      field: 'applicantProgress',
      name: 'App.',
      hidden: false,
      width: 312,
      minWidth: 312,
      filter: '',
      isNumeric: true,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'progress',
      title: 'Medical Exp.',
      field: 'medical',
      name: 'Medical Exp.',
      hidden: false,
      width: 101,
      minWidth: 101,
      filter: '',
      isNumeric: true,
      index: 10,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'progress',
      title: 'CDL Exp.',
      field: 'cdl',
      name: 'CDL Exp.',
      hidden: false,
      width: 101,
      minWidth: 101,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: '',
      title: 'Review',
      field: 'rev',
      name: 'Review',
      hidden: false,
      width: 123,
      minWidth: 123,
      filter: '',
      isNumeric: false,
      index: 12,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'hire',
      title: 'Hire',
      field: 'hire',
      name: '',
      hidden: false,
      width: 40,
      minWidth: 40,
      headIconStyle: {
        width: 18,
        height: 18,
        imgPath: '../../../assets/svg/truckassist-table/hire-applicant-selected-row.svg',
      },
      filter: '',
      isNumeric: false,
      index: 17,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: false,
      isAction: true
    },
    {
      ngTemplate: 'favorite',
      title: 'Favorite',
      field: 'favorite',
      name: '',
      hidden: false,
      width: 40,
      minWidth: 40,
      headIconStyle: {
        width: 18,
        height: 18,
        imgPath: '../../../assets/svg/truckassist-table/favorite-selected-row.svg',
      },
      filter: '',
      isNumeric: false,
      index: 17,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: false,
      isAction: true
    },
    {
      ngTemplate: 'note',
      title: 'Note',
      field: 'note',
      name: '',
      hidden: false,
      width: 40,
      minWidth: 40,
      headIconStyle: {
        width: 16,
        height: 18,
        imgPath: '',
      },
      filter: '',
      isNumeric: false,
      index: 17,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: false,
      isAction: true
    },
    {
      ngTemplate: 'actions',
      title: 'Actions',
      field: 'action',
      name: '',
      headIconStyle: {
        width: 22,
        height: 6,
        imgPath: '',
      },
      hidden: false,
      width: 42,
      minWidth: 42,
      filter: '',
      isNumeric: false,
      index: 18,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
      isAction: true
    },
  ] as any[];
}
