export function getToolsContactsColumnDefinition() {
  return [
    {
      ngTemplate: 'checkbox',
      title: '',
      field: 'select',
      name: 'Select',
      isComputed: true,
      hidden: false,
      width: 32,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'text',
      title: 'Name',
      field: 'name',
      name: 'Name',
      sortName: 'name',
      isComputed: false,
      hidden: false,
      width: 264,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'text',
      title: 'Phone',
      field: 'textPhone',
      name: 'Phone',
      sortName: 'phone',
      isComputed: false,
      hidden: false,
      width: 264,
      filter: '',
      isNumeric: true,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Email',
      field: 'textEmail',
      name: 'Email',
      sortName: 'email',
      isComputed: false,
      hidden: false,
      width: 264,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      imageHover: null,
    },
    {
      ngTemplate: 'text',
      title: 'Address',
      field: 'textAddress',
      name: 'Address',
      sortName: 'address',
      isComputed: false,
      hidden: false,
      width: 264,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'label',
      title: 'Label',
      field: 'labelName',
      name: 'Label',
      sortName: 'labelName',
      isComputed: false,
      hidden: false,
      width: 264,
      filter: '',
      isNumeric: true,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: false,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      imageHover: null,
      showLabel: true,
    },
    {
      ngTemplate: 'note',
      title: '',
      field: 'doc.note',
      name: '',
      moveRight: true,
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 6,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: false,
    },
    {
      ngTemplate: 'actions',
      title: '',
      field: 'action',
      name: '',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: true,
      index: 7,
      sortable: true,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: true,
    },
  ];
}

