// Customer Broker COLUMN DEFINITION
export function getBrokerColumnDefinition() {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: 'Select',
            hidden: false,
            width: 32,
            filter: '',
            isPined: true,
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'nameLink',
            title: 'Business Name',
            field: 'businessName',
            name: 'Business Name',
            sortName: 'businessName',
            hidden: false,
            isPined: true,
            width: 200,
            minWidth: 150,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            link: {
                routerLinkStart: '/customer/',
                routerLinkEnd: '/broker-details',
            },
        },
        {
            ngTemplate: 'text',
            title: 'DBA Name',
            field: 'dbaName',
            name: 'DBA Name',
            sortName: 'dbaName',
            hidden: true,
            isPined: false,
            width: 200,
            minWidth: 150,
            filter: '',
            isNumeric: false,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'EIN',
            field: 'ein',
            name: 'EIN',
            sortName: 'ein',
            isPined: false,
            hidden: true,
            width: 110,
            minWidth: 90,
            filter: '',
            isNumeric: false,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'MC/FF',
            field: 'mcNumber',
            name: 'MC/FF',
            sortName: 'MC/FF',
            isPined: false,
            hidden: true,
            width: 70,
            minWidth: 56,
            filter: '',
            isNumeric: false,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Phone',
            field: 'phone',
            name: 'Phone',
            sortName: 'phone',
            hidden: false,
            isPined: false,
            width: 130,
            minWidth: 112,
            filter: '',
            isNumeric: true,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Email',
            field: 'email',
            name: 'Email',
            isPined: false,
            sortName: 'email',
            hidden: false,
            width: 220,
            minWidth: 150,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Physical',
            field: 'tableAddressPhysical',
            name: 'Physical',
            sortName: 'address',
            groupName:'Address ',
            hidden: true,
            isPined: false,
            width: 270,
            minWidth: 150,
            filter: '',
            isNumeric: false,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Billing',
            field: 'tableAddressBilling',
            name: 'Billing',
            sortName: 'address',
            groupName:'Address ',
            hidden: true,
            isPined: false,
            width: 270,
            minWidth: 150,
            filter: '',
            isNumeric: false,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            // ngTemplate: 'progress',
            ngTemplate: 'text',
            title: 'Avail Credit',
            field: 'tablePaymentDetailAvailCredit',
            name: 'Avail Credit.',
            sortName: 'licenseExpDate',
            groupName:'Payment Detail ',
            hidden: false,
            isPined: false,
            width: 120,
            minWidth: 110,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: '',
                end: 'doc.inspectionData[0].startDate',
            },
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Credit Limit',
            field: 'tablePaymentDetailCreditLimit',
            name: 'Credit Limit',
            groupName:'Payment Detail ',
            hidden: true,
            isPined: false,
            width: 100,
            minWidth: 82,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Term',
            field: 'tablePaymentDetailTerm',
            name: 'Term',
            groupName:'Payment Detail ',
            hidden: true,
            isPined: false,
            width: 80,
            minWidth: 64,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'DTP',
            field: 'tablePaymentDetailDTP',
            name: 'DTP',
            groupName:'Payment Detail ',
            hidden: true,
            isPined: false,
            width: 80,
            minWidth: 64,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'inv-ageing',
            title: 'Invoice Ageing',
            field: 'tablePaymentDetailInvAgeing',
            name: 'Invoice Ageing',
            sortName: 'invAgeing',
            groupName:'Payment Detail ',
            hidden: false,
            isPined: false,
            width: 270,
            minWidth: 140,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Loads',
            field: 'tableLoads',
            name: 'Loads',
            sortName: 'load',
            isPined: false,
            hidden: false,
            width: 70,
            minWidth: 54,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Miles',
            field: 'tableMiles',
            name: 'Miles',
            isPined: false,
            hidden: true,
            width: 80,
            minWidth: 67,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'PPM',
            field: 'tablePPM',
            name: 'PPM',
            isPined: false,
            hidden: true,
            width: 60,
            minWidth: 50,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Revenue',
            field: 'tableRevenue',
            name: 'Revenue',
            isPined: false,
            hidden: false,
            width: 100,
            minWidth: 86,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'rating',
            title: 'Rating',
            field: 'tableRaiting',
            name: 'Rating',
            hidden: false,
            isPined: false,
            width: 128,
            minWidth: 128,
            filter: '',
            isNumeric: false,
            index: 7,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            svg: true,
            showPin: false,
            class: 'overflow-unset',
        },
        {
            ngTemplate: 'contact',
            title: 'Contact',
            field: 'tableContact',
            name: 'Contact',
            hidden: false,
            isPined: false,
            width: 40,
            minWidth: 40,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Added',
            field: 'tableAdded',
            name: 'Added',
            hidden: true,
            isPined: false,
            width: 80,
            minWidth: 66,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Edited',
            field: 'tableEdited',
            name: 'Edited',
            hidden: true,
            isPined: false,
            width: 80,
            minWidth: 66,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'note',
            title: 'Note',
            field: 'note',
            name: '',
            hidden: false,
            width: 40,
            minWidth: 40,
            filter: '',
            isNumeric: false,
            index: 17,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            hidden: false,
            width: 42,
            minWidth: 42,
            filter: '',
            isNumeric: false,
            index: 18,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}

// Customer Shipper COLUMN DEFINITION
export function getShipperColumnDefinition() {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: 'Select',
            hidden: false,
            isPined: true,
            width: 32,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'nameLink',
            title: 'Name',
            field: 'businessName',
            name: 'Name',
            sortName: 'businessName',
            hidden: false,
            isPined: true,
            width: 197,
            minWidth: 197,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            link: {
                routerLinkStart: '/customer/',
                routerLinkEnd: '/shipper-details',
            },
        },
        {
            ngTemplate: 'text',
            title: 'Phone',
            field: 'phone',
            name: 'Phone',
            sortName: 'phone',
            hidden: false,
            isPined: false,
            width: 127,
            minWidth: 127,
            filter: '',
            isNumeric: true,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Email',
            field: 'email',
            name: 'Email',
            sortName: 'email',
            hidden: false,
            isPined: false,
            width: 151,
            minWidth: 151,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Address',
            field: 'textAddress',
            name: 'Address',
            sortName: 'address',
            hidden: false,
            isPined: false,
            width: 215,
            minWidth: 215,
            filter: '',
            isNumeric: false,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Load',
            field: 'loadCount',
            name: 'Load',
            sortName: 'load',
            hidden: false,
            isPined: false,
            width: 84,
            minWidth: 84,
            filter: '',
            isNumeric: false,
            index: 8,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'rating',
            title: 'Rating',
            field: 'raiting',
            name: 'Rating',
            hidden: false,
            isPined: false,
            headAlign: 'center',
            width: 90,
            minWidth: 90,
            filter: '',
            isNumeric: false,
            index: 7,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            svg: true,
            showPin: false,
            class: 'overflow-unset',
        },
        {
            ngTemplate: 'contact',
            title: 'Contact',
            field: 'textContact',
            name: 'Contact',
            sortName: 'contact',
            hidden: false,
            isPined: false,
            width: 71,
            minWidth: 71,
            filter: '',
            isNumeric: false,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            specialColumn: true,
            grossColumn: true,
        },
        {
            ngTemplate: 'text',
            title: 'Unit',
            field: 'textUnit',
            name: 'Unit',
            sortName: 'unit',
            hidden: true,
            isPined: false,
            width: 91,
            minWidth: 91,
            filter: '',
            isNumeric: false,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            specialColumn: true,
            grossColumn: true,
        },
        {
            ngTemplate: 'text',
            title: 'Date Added',
            field: 'textDateAdded',
            name: 'Date Added',
            sortName: 'dateAdded',
            hidden: true,
            isPined: false,
            width: 86,
            minWidth: 86,
            filter: '',
            isNumeric: false,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            specialColumn: true,
            grossColumn: true,
        },
        {
            ngTemplate: 'text',
            title: 'Avg Pickup',
            field: 'textAvgPickup',
            name: 'Avg Pickup',
            sortName: 'avgPickup',
            hidden: true,
            isPined: false,
            width: 104,
            minWidth: 104,
            filter: '',
            isNumeric: false,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            specialColumn: true,
            grossColumn: true,
        },
        {
            ngTemplate: 'text',
            title: 'Avg Delivery',
            field: 'textAvgDelivery',
            name: 'Avg Delivery',
            sortName: 'avgDelivery',
            hidden: true,
            isPined: false,
            width: 104,
            minWidth: 104,
            filter: '',
            isNumeric: false,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            specialColumn: true,
            grossColumn: true,
        },
        {
            ngTemplate: 'work-hour',
            title: 'Ship. Work H.',
            field: 'textShipWorkHour',
            name: 'Ship. Work H.',
            sortName: 'shipWorkHour',
            hidden: true,
            isPined: false,
            width: 225,
            minWidth: 225,
            filter: '',
            isNumeric: false,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            specialColumn: true,
            grossColumn: true,
        },
        {
            ngTemplate: 'work-hour',
            title: 'Rece. Work H.',
            field: 'textReceWorkHour',
            name: 'Rece. Work H.',
            sortName: 'receWorkHour',
            hidden: true,
            isPined: false,
            width: 225,
            minWidth: 225,
            filter: '',
            isNumeric: false,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            specialColumn: true,
            grossColumn: true,
        },
        {
            ngTemplate: 'note',
            title: 'Note',
            field: 'note',
            name: '',
            hidden: false,
            width: 40,
            minWidth: 40,
            filter: '',
            isNumeric: false,
            index: 17,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            hidden: false,
            width: 42,
            minWidth: 42,
            filter: '',
            isNumeric: false,
            index: 18,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}
