// Customer Broker COLUMN DEFINITION
export function getBrokerColumnDefinition() { 
  return [
    {
      ngTemplate: 'checkbox',
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      width: 32,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'nameLink',
      title: 'Name',
      field: 'businessName',
      name: 'Name',
      sortName: 'businessName',
      hidden: false,
      width: 197,
      minWidth: 197,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      link: {
        routerLinkStart: '/customer/',
        routerLinkEnd: '/broker-details',
      },
    },
    {
      ngTemplate: 'text',
      title: 'Phone',
      field: 'phone',
      name: 'Phone',
      sortName: 'phone',
      hidden: false,
      width: 127,
      minWidth: 127,
      filter: '',
      isNumeric: true,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Email',
      field: 'email',
      name: 'Email',
      sortName: 'email',
      hidden: false,
      width: 151,
      minWidth: 151,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'inv-ageing',
      title: 'Inv. Ageing',
      field: 'textInvAgeing',
      name: 'Inv. Ageing',
      sortName: 'invAgeing',
      hidden: false,
      width: 131,
      minWidth: 131,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'progress',
      title: 'Credit',
      field: 'creditProgres',
      name: 'Credit.',
      sortName: 'licenseExpDate',
      hidden: false,
      width: 114,
      minWidth: 114,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: {
        start: '',
        end: 'doc.inspectionData[0].startDate',
      },
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'text',
      title: 'Load',
      field: 'loadCount',
      name: 'Load',
      sortName: 'load',
      hidden: false,
      width: 84,
      minWidth: 84,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Total',
      field: 'textTotal',
      name: 'Total',
      sortName: 'total',
      hidden: false,
      width: 92,
      minWidth: 92,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: '',
      title: 'Rating',
      field: '',
      name: 'Rating',
      headAlign: 'center',
      hidden: false,
      width: 90,
      minWidth: 90,
      filter: '',
      isNumeric: false,
      index: 7,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      svg: true,
      showPin: false,
      class: 'overflow-unset',
    },
    {
      ngTemplate: 'contact',
      title: 'Contact',
      field: 'textContact',
      name: 'Contact',
      hidden: false,
      width: 71,
      minWidth: 71,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'DBA Name',
      field: 'dbaName',
      name: 'DBA Name',
      sortName: 'dbaName',
      hidden: true,
      width: 146,
      minWidth: 146,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'EIN #',
      field: 'ein',
      name: 'EIN #',
      sortName: 'ein',
      hidden: true,
      width: 105,
      minWidth: 105,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'MC/FF #',
      field: 'mcNumber',
      name: 'MC/FF #',
      sortName: 'MC/FF',
      hidden: true,
      width: 92,
      minWidth: 92,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Address',
      field: 'textAddress',
      name: 'Address',
      sortName: 'address',
      hidden: true,
      width: 215,
      minWidth: 215,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Unit',
      field: 'textUnit',
      name: 'Unit',
      sortName: 'unit',
      hidden: true,
      width: 91,
      minWidth: 91,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Credit Limit',
      field: 'textCreditLimit',
      name: 'Credit Limit',
      sortName: 'creditLimit',
      hidden: true,
      width: 91,
      minWidth: 91,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Pay Term',
      field: 'textPayTerm',
      name: 'Pay Term',
      sortName: 'payTermt',
      hidden: true,
      width: 93,
      minWidth: 93,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'PO City, State & Zip',
      field: 'textPoCityStateZip',
      name: 'PO City, State & Zip',
      hidden: true,
      sortName: 'poCityStateZip',
      width: 215,
      minWidth: 215,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'PO Box #',
      field: 'textPoBox',
      name: 'PO Box #',
      sortName: 'poBox',
      hidden: true,
      width: 86,
      minWidth: 86,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'PO Box Addr.',
      field: 'textPoBoxAddr',
      name: 'PO Box Addr.',
      sortName: 'poBoxAddr',
      hidden: true,
      width: 86,
      minWidth: 86,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Last Used',
      field: 'textLastUsed',
      name: 'Last Used',
      sortName: 'lastUsed',
      hidden: true,
      width: 86,
      minWidth: 86,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Avg. Mile',
      field: 'textAvgMile',
      name: 'Avg. Mile',
      sortName: 'avgMile',
      hidden: true,
      width: 95,
      minWidth: 95,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'note',
      title: 'Note',
      field: 'note',
      name: '',
      hidden: false,
      width: 40,
      minWidth: 40,
      filter: '',
      isNumeric: false,
      index: 17,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: false,
      isAction: true
    },
    {
      ngTemplate: 'actions',
      title: 'Actions',
      field: 'action',
      name: '',
      hidden: false,
      width: 42,
      minWidth: 42,
      filter: '',
      isNumeric: false,
      index: 18,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
      isAction: true
    },
  ];
}

// Customer Shipper COLUMN DEFINITION
export function getShipperColumnDefinition() {
  return [
    {
      ngTemplate: 'checkbox',
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      width: 32,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'nameLink',
      title: 'Name',
      field: 'businessName',
      name: 'Name',
      sortName: 'businessName',
      hidden: false,
      width: 197,
      minWidth: 197,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      link: {
        routerLinkStart: '/customer/',
        routerLinkEnd: '/shipper-details',
      },
    },
    {
      ngTemplate: 'text',
      title: 'Phone',
      field: 'phone',
      name: 'Phone',
      sortName: 'phone',
      hidden: false,
      width: 127,
      minWidth: 127,
      filter: '',
      isNumeric: true,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Email',
      field: 'email',
      name: 'Email',
      sortName: 'email',
      hidden: false,
      width: 151,
      minWidth: 151,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Address',
      field: 'textAddress',
      name: 'Address',
      sortName: 'address',
      hidden: false,
      width: 215,
      minWidth: 215,
      filter: '',
      isNumeric: false,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Load',
      field: 'loadCount',
      name: 'Load',
      sortName: 'load',
      hidden: false,
      width: 84,
      minWidth: 84,
      filter: '',
      isNumeric: false,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: '',
      title: 'Rating',
      field: '',
      name: 'Rating',
      hidden: false,
      headAlign: 'center',
      width: 90,
      minWidth: 90,
      filter: '',
      isNumeric: false,
      index: 7,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      svg: true,
      showPin: false,
      class: 'overflow-unset',
    },
    {
      ngTemplate: 'contact',
      title: 'Contact',
      field: 'textContact',
      name: 'Contact',
      sortName: 'contact',
      hidden: false,
      width: 71,
      minWidth: 71,
      filter: '',
      isNumeric: false,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      specialColumn: true,
      grossColumn: true,
    },
    {
      ngTemplate: 'text',
      title: 'Unit',
      field: 'textUnit',
      name: 'Unit',
      sortName: 'unit',
      hidden: true,
      width: 91,
      minWidth: 91,
      filter: '',
      isNumeric: false,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      specialColumn: true,
      grossColumn: true,
    },
    {
      ngTemplate: 'text',
      title: 'Date Added',
      field: 'textDateAdded',
      name: 'Date Added',
      sortName: 'dateAdded',
      hidden: true,
      width: 86,
      minWidth: 86,
      filter: '',
      isNumeric: false,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      specialColumn: true,
      grossColumn: true,
    },
    {
      ngTemplate: 'text',
      title: 'Avg Pickup',
      field: 'textAvgPickup',
      name: 'Avg Pickup',
      sortName: 'avgPickup',
      hidden: true,
      width: 104,
      minWidth: 104,
      filter: '',
      isNumeric: false,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      specialColumn: true,
      grossColumn: true,
    },
    {
      ngTemplate: 'text',
      title: 'Avg Delivery',
      field: 'textAvgDelivery',
      name: 'Avg Delivery',
      sortName: 'avgDelivery',
      hidden: true,
      width: 104,
      minWidth: 104,
      filter: '',
      isNumeric: false,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      specialColumn: true,
      grossColumn: true,
    },
    {
      ngTemplate: 'work-hour',
      title: 'Ship. Work H.',
      field: 'textShipWorkHour',
      name: 'Ship. Work H.',
      sortName: 'shipWorkHour',
      hidden: true,
      width: 225,
      minWidth: 225,
      filter: '',
      isNumeric: false,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      specialColumn: true,
      grossColumn: true,
    },
    {
      ngTemplate: 'work-hour',
      title: 'Rece. Work H.',
      field: 'textReceWorkHour',
      name: 'Rece. Work H.',
      sortName: 'receWorkHour',
      hidden: true,
      width: 225,
      minWidth: 225,
      filter: '',
      isNumeric: false,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      specialColumn: true,
      grossColumn: true,
    },
    {
      ngTemplate: 'note',
      title: 'Note',
      field: 'note',
      name: '',
      hidden: false,
      width: 40,
      minWidth: 40,
      filter: '',
      isNumeric: false,
      index: 17,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: false,
      isAction: true
    },
    {
      ngTemplate: 'actions',
      title: 'Actions',
      field: 'action',
      name: '',
      hidden: false,
      width: 42,
      minWidth: 42,
      filter: '',
      isNumeric: false,
      index: 18,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
      isAction: true
    },
  ];
}
