// DRIVER TABLE COLUMNS DEFINITION
export function getDriverColumnsDefinition() {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: 'Select',
            hidden: false,
            width: 28,
            isPined: true,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'avatar',
            title: 'Name',
            field: 'fullName',
            name: 'Name',
            sortName: 'fullName',
            hidden: false,
            isPined: true,
            width: 200,
            minWidth: 100,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: {
                src: 'additionalData.avatar.src',
            },
            link: {
                routerLinkStart: '/driver/',
                routerLinkEnd: '/details',
            },
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: true,
            export: true,
            resizable: true,
            class: 'overflow-unset',
        },
        {
            ngTemplate: 'text',
            title: 'SSN',
            field: 'ssn',
            name: 'SSN',
            hidden: false,
            isPined: false,
            width: 110,
            minWidth: 80,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Phone',
            field: 'phone',
            name: 'Phone',
            sortName: 'phone',
            isPined: false,
            hidden: false,
            width: 130,
            minWidth: 112,
            filter: '',
            isNumeric: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Email',
            field: 'email',
            name: 'Email',
            sortName: 'email',
            hidden: true,
            isPined: false,
            width: 220,
            minWidth: 150,
            filter: '',
            isNumeric: false,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Address',
            field: 'tableAddress',
            name: 'Address',
            sortName: 'address',
            hidden: true,
            isPined: false,
            width: 270,
            minWidth: 150,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'DOB',
            field: 'tableDOB',
            name: 'DOB',
            sortName: 'dob',
            hidden: true,
            isPined: false,
            width: 80,
            minWidth: 66,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 6,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Assigned Unit Truck',
            field: 'tableAssignedUnitTruck',
            name: 'Assigned Unit Truck',
            hidden: true,
            isPined: false,
            width: 80,
            minWidth: 64,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 6,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Truck Type',
            field: 'tableAssignedUnitTruckType',
            name: 'Truck Type',
            hidden: true,
            isPined: false,
            width: 50,
            minWidth: 50,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 6,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Trailer',
            field: 'tableAssignedUnitTrailer',
            name: 'Trailer',
            hidden: true,
            isPined: false,
            width: 100,
            minWidth: 80,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 6,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Trailer Type',
            field: 'tableAssignedUnitTrailerType',
            name: 'Trailer Type',
            hidden: true,
            isPined: false,
            width: 50,
            minWidth: 50,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 6,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Payroll Detail Type',
            field: 'tablePayrollDetailType',
            name: 'Payroll Detail Type',
            hidden: false,
            isPined: false,
            width: 100,
            minWidth: 62,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 6,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Bank Detail Bank Name',
            field: 'tableBankDetailBankName',
            name: 'Bank Detail Bank Name',
            hidden: true,
            isPined: false,
            sortName: 'bankName',
            width: 150,
            minWidth: 100,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 6,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Routing',
            field: 'tableBankDetailRouting',
            name: 'Routing',
            sortName: 'routingNumber',
            hidden: true,
            isPined: false,
            width: 70,
            minWidth: 40,
            filter: '',
            isNumeric: true,
            index: 15,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Owner Details Type',
            field: 'tableOwnerDetailsType',
            name: 'Owner Details Type',
            hidden: true,
            isPined: false,
            width: 104,
            minWidth: 68,
            filter: '',
            isNumeric: true,
            index: 15,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Busines Name',
            field: 'tableOwnerDetailsBusinesName',
            name: 'Busines Name',
            hidden: true,
            isPined: false,
            width: 200,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            index: 15,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Ein',
            field: 'tableOwnerDetailsEin',
            name: 'Ein',
            hidden: true,
            isPined: false,
            width: 110,
            minWidth: 80,
            filter: '',
            isNumeric: true,
            index: 15,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Off Duty Location',
            field: 'tableOffDutyLocation',
            name: '',
            hidden: true,
            isPined: false,
            width: 40,
            minWidth: 40,
            filter: '',
            isNumeric: true,
            index: 15,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Emerg Contact',
            field: 'tableEmergContact',
            name: 'Emerg Contact',
            hidden: true,
            isPined: false,
            width: 130,
            minWidth: 112,
            filter: '',
            isNumeric: true,
            index: 15,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Twic Exp',
            field: 'tableTwicExp',
            name: 'Twic Exp',
            hidden: true,
            isPined: false,
            width: 122,
            minWidth: 87,
            filter: '',
            isNumeric: true,
            index: 15,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Fuel Card Detail Number',
            field: 'tableFuelCardDetailNumber',
            name: 'Fuel Card Detail Number',
            hidden: true,
            isPined: false,
            width: 170,
            minWidth: 100,
            filter: '',
            isNumeric: true,
            index: 15,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Fuel Card Type',
            field: 'tableFuelCardDetailType',
            name: 'Fuel Card Type',
            hidden: true,
            isPined: false,
            width: 84,
            minWidth: 74,
            filter: '',
            isNumeric: true,
            index: 15,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Account',
            field: 'tableFuelCardDetailAccount',
            name: 'Account',
            hidden: true,
            isPined: false,
            width: 150,
            minWidth: 60,
            filter: '',
            isNumeric: true,
            index: 15,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Cdl Detail Number',
            field: 'tableCdlDetailNumber',
            name: 'Cdl Detail Number',
            hidden: false,
            isPined: false,
            width: 130,
            minWidth: 62,
            filter: '',
            isNumeric: true,
            index: 15,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'textState',
            title: 'State',
            field: 'tableCdlDetailState',
            name: 'State',
            hidden: true,
            isPined: false,
            width: 60,
            minWidth: 60,
            filter: '',
            isNumeric: false,
            index: 9,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: {
                urlStart: '../assets/img/svgs/states/',
                field: 'licenseData[0].state.key',
                urlEnd: '.svg',
            },
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Endorsment',
            field: 'tableCdlDetailEndorsment',
            name: 'Endorsment',
            hidden: true,
            isPined: false,
            width: 110,
            minWidth: 110,
            filter: '',
            isNumeric: true,
            index: 15,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Restriction',
            field: 'tableCdlDetailRestriction',
            name: 'Restriction',
            hidden: true,
            isPined: false,
            width: 110,
            minWidth: 110,
            filter: '',
            isNumeric: true,
            index: 15,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progress',
            title: 'CDL Expiration',
            field: 'tableCdlDetailExpiration',
            name: 'CDL Expiration',
            sortName: 'cdlExp',
            isPined: false,
            hidden: false,
            width: 130,
            minWidth: 87,
            filter: '',
            isNumeric: true,
            index: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Test Details Type',
            field: 'tableTestDetailsType',
            name: 'Test Details Type',
            hidden: true,
            isPined: false,
            width: 60,
            minWidth: 60,
            filter: '',
            isNumeric: true,
            index: 15,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Reason',
            field: 'tableTestDetailsReason',
            name: 'Reason',
            hidden: true,
            isPined: false,
            width: 160,
            minWidth: 72,
            filter: '',
            isNumeric: true,
            index: 15,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Issued',
            field: 'tableTestDetailsIssued',
            name: 'Issued',
            hidden: true,
            isPined: false,
            width: 80,
            minWidth: 66,
            filter: '',
            isNumeric: true,
            index: 15,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Result',
            field: 'tableTestDetailsResult',
            name: 'Result',
            hidden: true,
            isPined: false,
            width: 80,
            minWidth: 66,
            filter: '',
            isNumeric: true,
            index: 15,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progress',
            title: 'Medical Ex.',
            field: 'tableMedicalData',
            name: 'Medical Exp',
            sortName: 'medExp',
            hidden: false,
            isPined: false,
            width: 130,
            minWidth: 87,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'medicalData[0].startDate',
                end: 'medicalData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progress',
            title: 'Mvr Details Expiration',
            field: 'tableMvrDetailsExpiration',
            name: 'Mvr Details Expiration',
            sortName: 'mvrIssue',
            hidden: false,
            isPined: false,
            width: 130,
            minWidth: 87,
            filter: '',
            isNumeric: true,
            index: 12,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: '',
                end: 'mvrData[0].startDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Notification General',
            field: 'tabelNotificationGeneral',
            name: 'Notification General',
            isPined: false,
            hidden: true,
            width: 120,
            minWidth: 100,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 7,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Payroll',
            field: 'tabelNotificationPayroll',
            name: 'Payroll',
            isPined: false,
            hidden: true,
            width: 120,
            minWidth: 100,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 7,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Hired',
            field: 'tabelHired',
            name: 'Hired',
            isPined: false,
            hidden: true,
            width: 120,
            minWidth: 100,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 7,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Terminated',
            field: 'tableTerminated',
            name: 'Terminated',
            isPined: false,
            hidden: true,
            width: 100,
            minWidth: 66,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Added',
            field: 'tableAdded',
            name: 'Added',
            isPined: false,
            hidden: true,
            width: 80,
            minWidth: 66,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Edited',
            field: 'tableEdited',
            name: 'Edited',
            isPined: false,
            hidden: true,
            width: 80,
            minWidth: 66,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'attachments',
            title: 'Attachments',
            field: 'tableAttachments',
            moveRight: true,
            name: '',
            hidden: false,
            width: 20,
            minWidth: 20,
            headIconStyle: {
                width: 19,
                height: 19,
                imgPath:
                    'assets/svg/truckassist-table/attachment/attachemnt-regular-svgIcon.svg',
            },
            filter: '',
            isNumeric: false,
            index: 16,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'note',
            title: 'Note',
            field: 'note',
            name: '',
            hidden: false,
            width: 40,
            minWidth: 40,
            headIconStyle: {
                width: 16,
                height: 18,
                imgPath: '',
            },
            filter: '',
            isNumeric: false,
            index: 17,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            headIconStyle: {
                width: 22,
                height: 6,
                imgPath: '',
            },
            hidden: false,
            width: 42,
            minWidth: 42,
            filter: '',
            isNumeric: false,
            index: 18,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ] as any[];
}
