// DRIVER TABLE COLUMNS DEFINITION
export function getDriverColumnsDefinition() { 
  return [
    {
      ngTemplate: 'checkbox',
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      width: 28,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'avatar',
      title: 'Name',
      field: 'fullName',
      name: 'Name',
      sortName: 'fullName',
      hidden: false,
      width: 179,
      minWidth: 151,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: {
        src: 'additionalData.avatar.src',
      },
      link: {
        routerLinkStart: '/driver/',
        routerLinkEnd: '/details',
      },
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: true,
      class: 'overflow-unset',
    },
    {
      ngTemplate: 'text',
      title: 'Phone',
      field: 'phone',
      name: 'Phone',
      sortName: 'phone',
      hidden: false,
      width: 117,
      minWidth: 127,
      filter: '',
      isNumeric: true,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Email',
      field: 'email',
      name: 'Email',
      sortName: 'email',
      hidden: true,
      width: 100,
      minWidth: 151,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Address',
      field: 'textAddress',
      name: 'Address',
      sortName: 'address',
      hidden: true,
      width: 100,
      minWidth: 215,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'SSN',
      field: 'ssn',
      name: 'SSN',
      hidden: false,
      width: 107,
      minWidth: 110,
      filter: '',
      isNumeric: true,
      index: 5,
      sortable: false,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font', 
    },
    {
      ngTemplate: 'text',
      title: 'DOB',
      field: 'textDOB',
      name: 'DOB',
      sortName: 'dob',
      hidden: false,
      width: 100,
      minWidth: 86,
      filter: '',
      isNumeric: true,
      isDate: true,
      index: 6,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Hired',
      field: 'textHired',
      name: 'Hired',
      sortName: 'hired',
      isComputed: false,
      hidden: false,
      width: 100,
      minWidth: 86,
      filter: '',
      isNumeric: true,
      isDate: true,
      index: 7,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'CDL #',
      field: 'textCDL',
      name: 'CDL #',
      sortName: 'cdlNumber',
      hidden: false,
      width: 148,
      minWidth: 99,
      filter: '',
      isNumeric: true,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'textState',
      title: 'ST',
      field: 'textState',
      name: 'ST',
      hidden: false,
      width: 80,
      minWidth: 70,
      filter: '',
      isNumeric: false,
      index: 9,
      sortable: false,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: {
        urlStart: '../assets/img/svgs/states/',
        field: 'licenseData[0].state.key',
        urlEnd: '.svg',
      },
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Bank',
      field: 'textBank',
      name: 'Bank',
      sortName: 'bankName',
      hidden: true,
      width: 100,
      minWidth: 132,
      filter: '',
      isNumeric: false,
      index: 13,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Account',
      field: 'textAccount',
      name: 'Account',
      sortName: 'accountNumber',
      hidden: true,
      width: 100,
      minWidth: 85,
      filter: '',
      isNumeric: true,
      index: 14,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Routing',
      field: 'textRouting',
      name: 'Routing',
      sortName: 'routingNumber',
      hidden: true,
      width: 100,
      minWidth: 99,
      filter: '',
      isNumeric: true,
      index: 15,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'progress',
      title: 'CDL Exp.',
      field: 'tableCDLData',
      name: 'CDL Exp.',
      sortName: 'cdlExp',
      hidden: false,
      width: 160,
      minWidth: 101,
      filter: '',
      isNumeric: true,
      index: 10,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: {
        start: 'licenseData[0].startDate',
        end: 'licenseData[0].endDate',
      },
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'progress',
      title: 'Medical Exp.',
      field: 'tableMedicalData',
      name: 'Medical Exp.',
      sortName: 'medExp',
      hidden: false,
      width: 160,
      minWidth: 101,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: {
        start: 'medicalData[0].startDate',
        end: 'medicalData[0].endDate',
      },
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'progress',
      title: 'MVR Exp.',
      field: 'tableMvrData',
      name: 'MVR Exp.',
      sortName: 'mvrIssue',
      hidden: false,
      width: 160,
      minWidth: 101,
      filter: '',
      isNumeric: true,
      index: 12,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: {
        start: '',
        end: 'mvrData[0].startDate',
      },
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Unit',
      field: 'textUnit',
      name: 'Unit',
      sortName: 'unit',
      hidden: false,
      width: 91,
      minWidth: 91,
      filter: '',
      isNumeric: true,
      index: 14,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Type',
      field: 'textType',
      name: 'Type',
      sortName: 'type',
      hidden: false,
      width: 92,
      minWidth: 92,
      filter: '',
      isNumeric: true,
      index: 14,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Ein #',
      field: 'textEin',
      name: 'Ein #',
      sortName: 'ein',
      hidden: false,
      width: 105,
      minWidth: 105,
      filter: '',
      isNumeric: true,
      index: 14,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Business',
      field: 'textBusiness',
      name: 'Business',
      sortName: 'business',
      hidden: false,
      width: 146,
      minWidth: 146,
      filter: '',
      isNumeric: true,
      index: 14,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Pay Type',
      field: 'textPayType',
      name: 'Pay Type',
      sortName: 'payType',
      hidden: false,
      width: 93,
      minWidth: 93,
      filter: '',
      isNumeric: true,
      index: 14,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'compact-text',
      title: 'Team',
      field: 'textTeam',
      name: 'Team',
      sortName: 'team',
      hidden: false,
      width: 161,
      minWidth: 161,
      filter: '',
      isNumeric: true,
      index: 14,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'compact-text',
      title: 'Solo',
      field: 'textSolo',
      name: 'Solo',
      sortName: 'solo',
      hidden: false,
      width: 161,
      minWidth: 161,
      filter: '',
      isNumeric: true,
      index: 14,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'progress',
      title: 'TWIC Exp. Date',
      field: 'tableTWICExpDate',
      name: 'TWIC Exp. Date',
      sortName: 'tWICExpDate',
      hidden: false,
      width: 101,
      minWidth: 101,
      filter: '',
      isNumeric: true,
      index: 12,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Fuel Card #',
      field: 'textFuelCard',
      name: 'Fuel Card #',
      sortName: 'fuelCard',
      hidden: false,
      width: 87,
      minWidth: 87,
      filter: '',
      isNumeric: true,
      index: 14,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'compact-text',
      title: 'Emergency Contact',
      field: 'textEmergencyContact',
      name: 'Emergency Contact',
      sortName: 'emergencyContact',
      hidden: false,
      width: 306,
      minWidth: 306,
      filter: '',
      isNumeric: true,
      index: 14,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'attachments',
      title: 'Attachments',
      field: 'additionalData.files',
      moveRight: true,
      name: '',
      hidden: false,
      width: 20,
      minWidth: 20,
      headIconStyle: {
        width: 19,
        height: 19,
        imgPath:
          'assets/svg/truckassist-table/attachment/attachemnt-regular-svgIcon.svg',
      },
      filter: '',
      isNumeric: false,
      index: 16,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
      isAction: true
    },
    {
      ngTemplate: 'note',
      title: 'Note',
      field: 'note',
      name: '',
      hidden: false,
      width: 40,
      minWidth: 40,
      headIconStyle: {
        width: 16,
        height: 18,
        imgPath: '',
      },
      filter: '',
      isNumeric: false,
      index: 17,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: false,
      isAction: true
    },
    {
      ngTemplate: 'actions',
      title: 'Actions',
      field: 'action',
      name: '',
      headIconStyle: {
        width: 22,
        height: 6,
        imgPath: '',
      },
      hidden: false,
      width: 42,
      minWidth: 42,
      filter: '',
      isNumeric: false,
      index: 18,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
      isAction: true
    },
  ] as any[];
}
