// LOAD COLUMN DEFINITION
export function getLoadColumnDefinition() {
  return [
    {
      ngTemplate: 'checkbox',
      title: '',
      field: 'select',
      name: '',
      hidden: false,
      width: 32,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'nameLink',
      title: 'Inv.',
      field: 'loadNumber',
      name: 'Invoice',
      hidden: false,
      width: 80,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: {
        routerLinkStart: '/loads/edit/',
        routerLinkEnd: '/detail',
      },
    },
    {
      ngTemplate: 'text',
      title: 'Broker',
      field: 'brokerName',
      name: 'Broker',
      hidden: false,
      width: 183,
      filter: '',
      isNumeric: true,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Shipper',
      field: 'pickupName',
      name: 'Shipper',
      hidden: true,
      width: 100,
      filter: '',
      isNumeric: true,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Receiver',
      field: 'deliveryName',
      name: 'Receiver',
      hidden: true,
      width: 120,
      filter: '',
      isNumeric: true,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Base Rate',
      field: 'baseRate',
      name: 'Base Rate',
      hidden: true,
      width: 100,
      filter: '',
      isNumeric: true,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Adjusted',
      field: 'adjusted',
      name: 'Adjusted',
      hidden: true,
      width: 100,
      filter: '',
      isNumeric: true,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Advance',
      field: 'advanced',
      name: 'Advance',
      hidden: true,
      width: 100,
      filter: '',
      isNumeric: true,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Additional',
      field: 'additional',
      name: 'Additional',
      hidden: true,
      width: 100,
      filter: '',
      isNumeric: true,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Revised',
      field: 'revised',
      name: 'Revised',
      hidden: true,
      width: 100,
      filter: '',
      isNumeric: true,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Dispatcher',
      field: 'dispatcherName',
      name: 'Dispatcher',
      hidden: true,
      width: 150,
      filter: '',
      isNumeric: true,
      index: 6,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Trailer',
      field: 'trailerNumber',
      name: 'Trailer',
      hidden: true,
      width: 75,
      filter: '',
      isNumeric: true,
      index: 7,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Driver',
      field: 'driverName',
      name: 'Driver',
      hidden: true,
      width: 183,
      filter: '',
      isNumeric: true,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Truck',
      field: 'truckNumber',
      name: 'Truck',
      hidden: false,
      width: 75,
      filter: '',
      isNumeric: false,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Ref #',
      field: 'brokerLoadNumber',
      name: 'Ref #',
      hidden: false,
      width: 81,
      filter: '',
      isNumeric: false,
      index: 10,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Date',
      field: 'pickupDateTime',
      name: 'Date',
      hidden: false,
      width: 84,
      filter: '',
      isNumeric: false,
      isDate: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
      addClassToTitle: 'addGreenToTitle',
    },
    {
      ngTemplate: 'pickup',
      title: 'Pick-Up',
      field: 'pickupCity',
      name: 'Pick-Up',
      hidden: false,
      width: 216,
      filter: '',
      isNumeric: false,
      index: 12,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: true,
      resizable: true,
      devFrom: true,
    },
    {
      ngTemplate: 'delivery',
      title: 'Delivery',
      field: 'deliveryCity',
      name: 'Delivery',
      hidden: false,
      width: 187,
      filter: '',
      isNumeric: false,
      index: 13,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: true,
      resizable: true,
      devTo: true,
    },
    {
      ngTemplate: 'text',
      title: 'Date',
      field: 'deliveryDateTime',
      name: 'Date',
      hidden: false,
      width: 76,
      filter: '',
      isNumeric: false,
      isDate: true,
      index: 14,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
      addClassToTitle: 'addRedToTitle',
    },
    {
      ngTemplate: 'text',
      title: 'Total',
      field: 'total',
      name: 'Total',
      hidden: false,
      width: 92,
      filter: '',
      isNumeric: false,
      index: 15,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Miles',
      field: 'mileage',
      name: 'Miles',
      hidden: false,
      width: 85,
      filter: '',
      isNumeric: false,
      index: 17,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Stops',
      field: 'stops',
      name: 'Stops',
      hidden: true,
      width: 80,
      filter: '',
      isNumeric: true,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'note',
      title: 'Note',
      field: 'note',
      name: '',
      moveRight: true,
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 18,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: true,
      export: true,
      resizable: false,
      isAction: true
    },
    {
      ngTemplate: 'actions',
      title: 'Actions',
      field: 'action',
      name: '',
      headIconStyle: {
        width: 22,
        height: 6,
        imgPath: '',
      },
      hidden: false,
      width: 42,
      filter: '',
      isNumeric: false,
      index: 18,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
      isAction: true
    },
  ];
}
