// LOAD COLUMN DEFINITION
export function getLoadTemplateColumnDefinition() {
   return [
      {
         ngTemplate: 'checkbox',
         title: '',
         field: 'select',
         name: '',
         hidden: false,
         width: 32,
         filter: '',
         isNumeric: false,
         index: 0,
         sortable: false,
         isActionColumn: true,
         isSelectColumn: true,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: false,
         resizable: false,
      },
      {
         ngTemplate: '',
         title: 'Name',
         field: 'textName',
         name: 'Name',
         hidden: false,
         width: 162,
         minWidth: 162,
         filter: '',
         isNumeric: false,
         index: 1,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
         link: {
            routerLinkStart: '/load/',
            routerLinkEnd: '/details',
         },
      },
      {
         ngTemplate: 'text',
         title: 'Added',
         field: 'textAdded',
         name: 'Added',
         hidden: false,
         width: 86,
         minWidth: 86,
         filter: '',
         isNumeric: true,
         index: 2,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Total',
         field: 'textTotal',
         name: 'Total',
         hidden: false,
         width: 92,
         minWidth: 92,
         filter: '',
         isNumeric: true,
         index: 3,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Broker',
         field: 'textBroker',
         name: 'Broker',
         hidden: false,
         width: 192,
         minWidth: 192,
         filter: '',
         isNumeric: true,
         index: 3,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: '',
         title: 'Driver',
         field: 'textDriver',
         name: 'Driver',
         hidden: false,
         width: 144,
         minWidth: 144,
         filter: '',
         isNumeric: true,
         index: 3,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: '',
         title: 'Truck type',
         field: 'textTruckType',
         name: 'Truck type',
         hidden: false,
         width: 82,
         minWidth: 82,
         filter: '',
         isNumeric: true,
         index: 5,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: '',
         title: 'Trailer type',
         field: 'textTrailerType',
         name: 'Trailer type',
         hidden: false,
         width: 91,
         minWidth: 91,
         filter: '',
         isNumeric: true,
         index: 5,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: '',
         title: 'Pickup',
         field: 'textPickup',
         name: 'Pickup',
         hidden: false,
         width: 120,
         minWidth: 120,
         filter: '',
         isNumeric: true,
         index: 5,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: '',
         title: 'Deliv.',
         field: 'textDeliv',
         name: 'Deliv.',
         hidden: false,
         width: 120,
         minWidth: 120,
         filter: '',
         isNumeric: true,
         index: 6,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Miles',
         field: 'textMiles',
         name: 'Miles',
         hidden: false,
         width: 100,
         minWidth: 100,
         filter: '',
         isNumeric: true,
         index: 7,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Commodity',
         field: 'textCommodity',
         name: 'Commodity',
         hidden: true,
         width: 122,
         minWidth: 122,
         filter: '',
         isNumeric: true,
         index: 8,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Weight',
         field: 'textWeight',
         name: 'Weight',
         hidden: true,
         width: 86,
         minWidth: 86,
         filter: '',
         isNumeric: false,
         index: 9,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
         class: 'custom-font',
      },
      {
         ngTemplate: 'text',
         title: 'Truck #',
         field: 'textTruck',
         name: 'Truck #',
         hidden: true,
         width: 70,
         minWidth: 70,
         filter: '',
         isNumeric: false,
         index: 9,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
         class: 'custom-font',
      },
      {
         ngTemplate: 'text',
         title: 'Trailer #',
         field: 'textTrailer',
         name: 'Trailer #',
         hidden: true,
         width: 80,
         minWidth: 80,
         filter: '',
         isNumeric: false,
         index: 9,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
         class: 'custom-font',
      },
      {
         ngTemplate: 'attachments',
         title: 'Attachments',
         field: 'additionalData.files',
         moveRight: true,
         name: '',
         hidden: false,
         width: 20,
         minWidth: 20,
         headIconStyle: {
            width: 19,
            height: 19,
            imgPath:
               'assets/svg/truckassist-table/attachment/attachemnt-regular-svgIcon.svg',
         },
         filter: '',
         isNumeric: false,
         index: 16,
         sortable: false,
         isActionColumn: true,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: false,
         resizable: false,
         isAction: true,
      },
      {
         ngTemplate: 'note',
         title: 'Note',
         field: 'note',
         name: '',
         hidden: false,
         width: 40,
         minWidth: 40,
         headIconStyle: {
            width: 16,
            height: 18,
            imgPath: '',
         },
         filter: '',
         isNumeric: false,
         index: 17,
         sortable: false,
         isActionColumn: true,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: false,
         isAction: true,
      },
      {
         ngTemplate: 'actions',
         title: 'Actions',
         field: 'action',
         name: '',
         headIconStyle: {
            width: 22,
            height: 6,
            imgPath: '',
         },
         hidden: false,
         width: 42,
         minWidth: 42,
         filter: '',
         isNumeric: false,
         index: 18,
         sortable: false,
         isActionColumn: true,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: false,
         resizable: false,
         isAction: true,
      },
   ];
}

export function getLoadActiveAndPendingColumnDefinition() {
   return [
      {
         ngTemplate: 'checkbox',
         title: '',
         field: 'select',
         name: '',
         hidden: false,
         width: 32,
         filter: '',
         isNumeric: false,
         index: 0,
         sortable: false,
         isActionColumn: true,
         isSelectColumn: true,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: false,
         resizable: false,
      },
      {
         ngTemplate: 'invoice',
         title: 'Inv.',
         field: 'loadInvoice',
         name: 'Inv.',
         hidden: false,
         width: 82,
         minWidth: 82,
         filter: '',
         isNumeric: false,
         index: 1,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
         link: {
            routerLinkStart: '/load/',
            routerLinkEnd: '/details',
         },
      },
      {
         ngTemplate: 'dispatcher-avatar',
         title: 'Dispatcher',
         field: 'loadDispatcher',
         name: 'Dispatcher',
         hidden: false,
         width: 130,
         minWidth: 130,
         filter: '',
         isNumeric: true,
         index: 2,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'load-total',
         title: 'Total',
         field: 'loadTotal',
         name: 'Total',
         hidden: false,
         width: 92,
         minWidth: 92,
         filter: '',
         isNumeric: true,
         index: 3,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'customer-name',
         title: 'Broker',
         field: 'loadBroker',
         name: 'Broker',
         hidden: false,
         width: 192,
         minWidth: 192,
         filter: '',
         isNumeric: true,
         index: 3,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Ref #',
         field: 'referenceNumber',
         name: 'Ref #',
         hidden: false,
         width: 86,
         minWidth: 86,
         filter: '',
         isNumeric: true,
         index: 3,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'status',
         title: 'Status',
         field: 'loadStatus',
         name: 'Status',
         setCenter: true,
         hidden: false,
         width: 98,
         minWidth: 98,
         filter: '',
         isNumeric: true,
         index: 4,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text-color',
         title: 'Truck #',
         field: 'loadTruckNumber',
         name: 'Truck #',
         hidden: false,
         width: 70,
         minWidth: 70,
         filter: '',
         isNumeric: true,
         index: 5,
         margin: -10,
         padding: 10,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text-color',
         title: 'Trailer #',
         field: 'loadTrailerNumber',
         name: 'Trailer #',
         hidden: false,
         width: 80,
         minWidth: 80,
         margin: -8,
         padding: 8,
         filter: '',
         isNumeric: true,
         index: 5,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'pickup-delivery',
         title: 'Pickup',
         field: 'loadPickup',
         name: 'Pickup',
         pickupDeliveryType: 'pickup',
         hidden: false,
         width: 120,
         minWidth: 120,
         filter: '',
         isNumeric: true,
         index: 5,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'pickup-delivery',
         title: 'Deliv.',
         field: 'loadDelivery',
         name: 'Deliv.',
         pickupDeliveryType: 'delivery',
         hidden: false,
         width: 120,
         minWidth: 120,
         filter: '',
         isNumeric: true,
         index: 6,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Miles',
         field: 'textMiles',
         name: 'Miles',
         hidden: false,
         width: 100,
         minWidth: 100,
         filter: '',
         isNumeric: true,
         index: 7,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Commodity',
         field: 'textCommodity',
         name: 'Commodity',
         hidden: true,
         width: 122,
         minWidth: 122,
         filter: '',
         isNumeric: true,
         index: 8,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Weight',
         field: 'textWeight',
         name: 'Weight',
         hidden: true,
         width: 86,
         minWidth: 86,
         filter: '',
         isNumeric: false,
         index: 9,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
         class: 'custom-font',
      },
      {
         ngTemplate: 'text',
         title: 'Base',
         field: 'textBase',
         name: 'Base',
         hidden: true,
         width: 92,
         minWidth: 92,
         filter: '',
         isNumeric: false,
         index: 10,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Additional',
         field: 'textAdditional',
         name: 'Additional',
         hidden: true,
         width: 92,
         minWidth: 92,
         filter: '',
         isNumeric: false,
         isDate: true,
         index: 11,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
         class: 'custom-font',
         addClassToTitle: 'addGreenToTitle',
      },
      {
         ngTemplate: 'text',
         title: 'Advance',
         field: 'textAdvance',
         name: 'Advance',
         hidden: true,
         width: 92,
         minWidth: 92,
         filter: '',
         isNumeric: false,
         index: 12,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
         devFrom: true,
      },
      {
         ngTemplate: 'text',
         title: 'Outstanding',
         field: 'textOutstanding',
         name: 'Outstanding',
         hidden: true,
         width: 92,
         minWidth: 92,
         filter: '',
         isNumeric: false,
         index: 13,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
         devTo: true,
      },
      {
         ngTemplate: 'text',
         title: 'Pay Terms',
         field: 'textPayTerms',
         name: 'Pay Terms',
         hidden: true,
         width: 93,
         minWidth: 93,
         filter: '',
         isNumeric: false,
         isDate: true,
         index: 14,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
         class: 'custom-font',
         addClassToTitle: 'addRedToTitle',
      },
      {
         ngTemplate: 'text',
         title: 'Driver',
         field: 'textDriver',
         name: 'Driver',
         hidden: true,
         width: 111,
         minWidth: 111,
         filter: '',
         isNumeric: false,
         index: 15,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Receiver',
         field: 'textReceiver',
         name: 'Receiver',
         hidden: true,
         width: 150,
         minWidth: 150,
         filter: '',
         isNumeric: false,
         index: 17,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Shipper',
         field: 'textShipper',
         name: 'Shipper',
         hidden: true,
         width: 150,
         minWidth: 150,
         filter: '',
         isNumeric: true,
         index: 5,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'attachments',
         title: 'Attachments',
         field: 'additionalData.files',
         moveRight: true,
         name: '',
         hidden: false,
         width: 20,
         minWidth: 20,
         headIconStyle: {
            width: 19,
            height: 19,
            imgPath:
               'assets/svg/truckassist-table/attachment/attachemnt-regular-svgIcon.svg',
         },
         filter: '',
         isNumeric: false,
         index: 16,
         sortable: false,
         isActionColumn: true,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: false,
         resizable: false,
         isAction: true,
      },
      {
         ngTemplate: 'comment',
         title: 'Comment',
         field: 'loadComment',
         name: '',
         hidden: false,
         width: 40,
         minWidth: 40,
         headIconStyle: {
            width: 16,
            height: 18,
            imgPath: '',
         },
         filter: '',
         isNumeric: false,
         index: 17,
         sortable: false,
         isActionColumn: true,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: false,
         isAction: true,
      },
      {
         ngTemplate: 'note',
         title: 'Note',
         field: 'note',
         name: '',
         hidden: false,
         width: 40,
         minWidth: 40,
         headIconStyle: {
            width: 16,
            height: 18,
            imgPath: '',
         },
         filter: '',
         isNumeric: false,
         index: 17,
         sortable: false,
         isActionColumn: true,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: false,
         isAction: true,
      },
      {
         ngTemplate: 'actions',
         title: 'Actions',
         field: 'action',
         name: '',
         headIconStyle: {
            width: 22,
            height: 6,
            imgPath: '',
         },
         hidden: false,
         width: 42,
         minWidth: 42,
         filter: '',
         isNumeric: false,
         index: 18,
         sortable: false,
         isActionColumn: true,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: false,
         resizable: false,
         isAction: true,
      },
   ];
}

export function getLoadClosedColumnDefinition() {
   return [
      {
         ngTemplate: 'checkbox',
         title: '',
         field: 'select',
         name: '',
         hidden: false,
         width: 32,
         filter: '',
         isNumeric: false,
         index: 0,
         sortable: false,
         isActionColumn: true,
         isSelectColumn: true,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: false,
         resizable: false,
      },
      {
         ngTemplate: '',
         title: 'Inv.',
         field: 'loadNumber',
         name: 'Invoice',
         hidden: false,
         width: 82,
         minWidth: 82,
         filter: '',
         isNumeric: false,
         index: 1,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
         link: {
            routerLinkStart: '/load',
            routerLinkEnd: '/details',
         },
      },
      {
         ngTemplate: '',
         title: 'Dispatcher',
         field: 'textDispatcher',
         name: 'Dispatcher',
         hidden: false,
         width: 130,
         minWidth: 130,
         filter: '',
         isNumeric: true,
         index: 2,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Total',
         field: 'textTotal',
         name: 'Total',
         hidden: false,
         width: 92,
         minWidth: 92,
         filter: '',
         isNumeric: true,
         index: 3,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Broker',
         field: 'textBroker',
         name: 'Broker',
         hidden: false,
         width: 192,
         minWidth: 192,
         filter: '',
         isNumeric: true,
         index: 3,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Ref',
         field: 'baseRate',
         name: 'Ref',
         hidden: false,
         width: 86,
         minWidth: 86,
         filter: '',
         isNumeric: true,
         index: 3,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: '',
         title: 'Status',
         field: 'textStatus',
         name: 'Status',
         hidden: false,
         width: 98,
         minWidth: 98,
         filter: '',
         isNumeric: true,
         index: 4,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: '',
         title: 'Truck #',
         field: 'textTruck',
         name: 'Truck #',
         hidden: false,
         width: 70,
         minWidth: 70,
         filter: '',
         isNumeric: true,
         index: 5,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: '',
         title: 'Trailer #',
         field: 'textTrailer',
         name: 'Trailer #',
         hidden: false,
         width: 80,
         minWidth: 80,
         filter: '',
         isNumeric: true,
         index: 5,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: '',
         title: 'Pickup',
         field: 'textPickup',
         name: 'Pickup',
         hidden: false,
         width: 120,
         minWidth: 120,
         filter: '',
         isNumeric: true,
         index: 5,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: '',
         title: 'Deliv.',
         field: 'textDeliv',
         name: 'Deliv.',
         hidden: false,
         width: 120,
         minWidth: 120,
         filter: '',
         isNumeric: true,
         index: 6,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Miles',
         field: 'textMiles',
         name: 'Miles',
         hidden: false,
         width: 100,
         minWidth: 100,
         filter: '',
         isNumeric: true,
         index: 7,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Commodity',
         field: 'textCommodity',
         name: 'Commodity',
         hidden: true,
         width: 122,
         minWidth: 122,
         filter: '',
         isNumeric: true,
         index: 8,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Weight',
         field: 'textWeight',
         name: 'Weight',
         hidden: true,
         width: 86,
         minWidth: 86,
         filter: '',
         isNumeric: false,
         index: 9,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
         class: 'custom-font',
      },
      {
         ngTemplate: 'text',
         title: 'Base',
         field: 'textBase',
         name: 'Base',
         hidden: true,
         width: 92,
         minWidth: 92,
         filter: '',
         isNumeric: false,
         index: 10,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Additional',
         field: 'textAdditional',
         name: 'Additional',
         hidden: true,
         width: 92,
         minWidth: 92,
         filter: '',
         isNumeric: false,
         isDate: true,
         index: 11,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
         class: 'custom-font',
         addClassToTitle: 'addGreenToTitle',
      },
      {
         ngTemplate: 'text',
         title: 'Advance',
         field: 'textAdvance',
         name: 'Advance',
         hidden: true,
         width: 92,
         minWidth: 92,
         filter: '',
         isNumeric: false,
         index: 12,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
         devFrom: true,
      },
      {
         ngTemplate: 'text',
         title: 'Outstanding',
         field: 'textOutstanding',
         name: 'Outstanding',
         hidden: true,
         width: 92,
         minWidth: 92,
         filter: '',
         isNumeric: false,
         index: 13,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
         devTo: true,
      },
      {
         ngTemplate: 'text',
         title: 'Pay Terms',
         field: 'textPayTerms',
         name: 'Pay Terms',
         hidden: true,
         width: 93,
         minWidth: 93,
         filter: '',
         isNumeric: false,
         isDate: true,
         index: 14,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
         class: 'custom-font',
         addClassToTitle: 'addRedToTitle',
      },
      {
         ngTemplate: 'text',
         title: 'Driver',
         field: 'textDriver',
         name: 'Driver',
         hidden: true,
         width: 111,
         minWidth: 111,
         filter: '',
         isNumeric: false,
         index: 15,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Receiver',
         field: 'textReceiver',
         name: 'Receiver',
         hidden: true,
         width: 150,
         minWidth: 150,
         filter: '',
         isNumeric: false,
         index: 17,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Shipper',
         field: 'textShipper',
         name: 'Shipper',
         hidden: true,
         width: 150,
         minWidth: 150,
         filter: '',
         isNumeric: true,
         index: 5,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Invoiced Date',
         field: 'textInvoicedDate',
         name: 'Invoiced Date',
         hidden: true,
         width: 137,
         minWidth: 137,
         filter: '',
         isNumeric: true,
         index: 5,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Paid Date',
         field: 'textPaidDate',
         name: 'Paid Date',
         hidden: true,
         width: 116,
         minWidth: 116,
         filter: '',
         isNumeric: true,
         index: 5,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Short Pay',
         field: 'textShortPay',
         name: 'Short Pay',
         hidden: true,
         width: 129,
         minWidth: 129,
         filter: '',
         isNumeric: true,
         index: 5,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Age',
         field: 'textAge',
         name: 'Age',
         hidden: true,
         width: 80,
         minWidth: 80,
         filter: '',
         isNumeric: true,
         index: 5,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'attachments',
         title: 'Attachments',
         field: 'additionalData.files',
         moveRight: true,
         name: '',
         hidden: false,
         width: 20,
         minWidth: 20,
         headIconStyle: {
            width: 19,
            height: 19,
            imgPath:
               'assets/svg/truckassist-table/attachment/attachemnt-regular-svgIcon.svg',
         },
         filter: '',
         isNumeric: false,
         index: 16,
         sortable: false,
         isActionColumn: true,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: false,
         resizable: false,
         isAction: true,
      },
      {
         ngTemplate: 'comment',
         title: 'Comment',
         field: 'comment',
         name: '',
         hidden: false,
         width: 40,
         minWidth: 40,
         headIconStyle: {
            width: 16,
            height: 18,
            imgPath: '',
         },
         filter: '',
         isNumeric: false,
         index: 17,
         sortable: false,
         isActionColumn: true,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: false,
         isAction: true,
      },
      {
         ngTemplate: 'note',
         title: 'Note',
         field: 'note',
         name: '',
         hidden: false,
         width: 40,
         minWidth: 40,
         headIconStyle: {
            width: 16,
            height: 18,
            imgPath: '',
         },
         filter: '',
         isNumeric: false,
         index: 17,
         sortable: false,
         isActionColumn: true,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: false,
         isAction: true,
      },
      {
         ngTemplate: 'actions',
         title: 'Actions',
         field: 'action',
         name: '',
         headIconStyle: {
            width: 22,
            height: 6,
            imgPath: '',
         },
         hidden: false,
         width: 42,
         minWidth: 42,
         filter: '',
         isNumeric: false,
         index: 18,
         sortable: false,
         isActionColumn: true,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: false,
         resizable: false,
         isAction: true,
      },
   ];
}
