export function getOwnerColumnDefinition() {
  return [
    {
      ngTemplate: 'checkbox',
      title: '',
      field: 'select',
      name: 'Select',
      isComputed: true,
      hidden: false,
      width: 32,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'nameLink',
      title: 'Name',
      field: 'businessName',
      name: 'Name',
      isComputed: true,
      hidden: false,
      width: 200,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      avatar: false /* {
        src: 'doc.additionalData.avatar.src',
        routerLinkStart: '/drivers/edit/',
        routerLinkEnd: '/basic',
      } */,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Type',
      field: 'category',
      name: 'Type',
      isComputed: true,
      hidden: false,
      width: 116,
      filter: '',
      isNumeric: true,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'TRK',
      field: 'activeTruckCount',
      name: 'TRK',
      isComputed: true,
      hidden: false,
      width: 84,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'TLR',
      field: 'activeTrailerCount',
      name: 'TLR',
      isComputed: true,
      hidden: false,
      width: 94,
      filter: '',
      isNumeric: false,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'EIN-SSN',
      field: 'taxNumber',
      name: 'EIN-SSN',
      isComputed: true,
      hidden: false,
      width: 130,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Phone',
      field: 'textPhone',
      name: 'Phone',
      isComputed: true,
      hidden: false,
      width: 151,
      filter: '',
      isNumeric: true,
      index: 6,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Email',
      field: 'textEmail',
      name: 'Email',
      isComputed: false,
      hidden: false,
      width: 235,
      filter: '',
      isNumeric: true,
      index: 7,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Address',
      field: 'textAddress',
      name: 'Address',
      isComputed: false,
      hidden: false,
      width: 345,
      filter: '',
      isNumeric: true,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'attachments',
      title: 'Attachments',
      field: 'additionalData.files',
      name: '',
      moveRight: true,
      headIconStyle: {
        width: 19,
        height: 19,
        imgPath:
          'assets/svg/truckassist-table/attachment/attachemnt-regular-svgIcon.svg',
      },
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 16,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
      isAction: true
    },
    {
      ngTemplate: 'note',
      title: 'Note',
      field: 'doc.additionalData.note',
      name: '',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 9,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: false,
      isAction: true
    },
    {
      ngTemplate: 'actions',
      title: 'Actions',
      field: 'action',
      name: '',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: true,
      index: 10,
      sortable: true,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      isAction: true
    },
  ];
}
