// APPLICANT TABLE COLUMNS DEFINITION
export function getPayrollDriverMilesDefinition() { 
    return [ 
        {
          ngTemplate: 'avatar',
          title: 'Name',
          field: 'fullName',
          name: 'Name',
          sortName: 'fullName',
          hidden: false,
          isPined: true,
          width: 250,
          minWidth: 250,
          filter: '',
          isNumeric: false,
          index: 1,
          sortable: true,
          isActionColumn: false,
          isSelectColumn: false,
          avatar: {
            src: 'additionalData.avatar.src',
          },
          link: {
            routerLinkStart: '/driver/',
            routerLinkEnd: '/details',
          },
          progress: null,
          hoverTemplate: null,
          filterable: true,
          disabled: true,
          export: true,
          resizable: true,
          class: 'overflow-unset',
        },
        {
          ngTemplate: 'text',
          title: 'Payroll',
          field: 'payroll',
          name: 'Payroll',
          sortName: 'payroll',
          isPined: false,
          hidden: false,
          width: 167,
          minWidth: 177,
          filter: '',
          isNumeric: true,
          index: 2,
          sortable: true,
          isActionColumn: false,
          isSelectColumn: false,
          avatar: null,
          progress: null,
          hoverTemplate: null,
          filterable: true,
          disabled: false,
          export: true,
          resizable: true,
          class: 'custom-font',
        },
        {
          ngTemplate: 'text',
          title: 'Period',
          field: 'period',
          name: 'Period',
          sortName: 'period',
          hidden: false,
          isPined: false,
          width: 120,
          minWidth: 151,
          filter: '',
          isNumeric: false,
          index: 3,
          sortable: true,
          isActionColumn: false,
          isSelectColumn: false,
          avatar: null,
          progress: null,
          hoverTemplate: null,
          filterable: true,
          disabled: false,
          export: true,
          resizable: true,
        },
        {
          ngTemplate: 'text',
          title: 'Total',
          field: 'total',
          name: 'Total',
          sortName: 'total',
          hidden: false,
          isPined: false,
          width: 100,
          minWidth: 215,
          filter: '',
          isNumeric: false,
          index: 4,
          sortable: true,
          isActionColumn: false,
          isSelectColumn: false,
          avatar: null,
          progress: null,
          hoverTemplate: null,
          filterable: true,
          disabled: false,
          export: true,
          resizable: true,
        },
        {
          ngTemplate: 'text',
          title: 'Empty',
          field: 'empty',
          name: 'Empty',
          hidden: false,
          isPined: false,
          width: 107,
          minWidth: 110,
          filter: '',
          isNumeric: true,
          index: 5,
          sortable: false,
          isActionColumn: false,
          isSelectColumn: false,
          avatar: null,
          progress: null,
          hoverTemplate: null,
          filterable: true,
          disabled: false,
          export: true,
          resizable: true,
          class: 'custom-font', 
        },
        {
          ngTemplate: 'text',
          title: 'Loaded',
          field: 'loaded',
          name: 'Loaded',
          sortName: 'loaded',
          hidden: false,
          isPined: false,
          width: 100,
          minWidth: 86,
          filter: '',
          isNumeric: true,
          isDate: true,
          index: 6,
          sortable: true,
          isActionColumn: false,
          isSelectColumn: false,
          avatar: null,
          progress: null,
          hoverTemplate: null,
          filterable: true,
          disabled: false,
          export: true,
          resizable: true,
          class: 'custom-font',
        },
        {
          ngTemplate: 'text',
          title: 'MI Pay',
          field: 'MI Pay',
          name: 'MI Pay',
          sortName: 'MI Pay',
          isPined: false,
          isComputed: false,
          hidden: false,
          width: 100,
          minWidth: 86,
          filter: '',
          isNumeric: true,
          isDate: true,
          index: 7,
          sortable: true,
          isActionColumn: false,
          isSelectColumn: false,
          avatar: null,
          progress: null,
          hoverTemplate: null,
          filterable: true,
          disabled: false,
          export: true,
          resizable: true,
          class: 'custom-font',
        },
        {
          ngTemplate: 'text',
          title: 'Salary',
          field: 'salary',
          name: 'Salary',
          sortName: 'salary',
          isPined: false,
          hidden: false,
          width: 148,
          minWidth: 99,
          filter: '',
          isNumeric: true,
          index: 8,
          sortable: true,
          isActionColumn: false,
          isSelectColumn: false,
          avatar: null,
          progress: null,
          hoverTemplate: null,
          filterable: true,
          disabled: false,
          export: true,
          resizable: true,
        },
        {
          ngTemplate: 'text',
          title: 'Total',
          field: 'total',
          name: 'Total',
          sortName: 'total',
          hidden: false,
          isPined: false,
          width: 100,
          minWidth: 132,
          filter: '',
          isNumeric: false,
          index: 13,
          sortable: true,
          isActionColumn: false,
          isSelectColumn: false,
          avatar: null,
          progress: null,
          hoverTemplate: null,
          filterable: true,
          disabled: false,
          export: true,
          resizable: true,
        },
        {
          ngTemplate: 'text',
          title: 'Status',
          field: 'status',
          name: 'Status',
          sortName: 'status',
          hidden: false,
          isPined: false,
          width: 100,
          minWidth: 85,
          filter: '',
          isNumeric: true,
          index: 14,
          sortable: true,
          isActionColumn: false,
          isSelectColumn: false,
          avatar: null,
          progress: null,
          hoverTemplate: null,
          filterable: true,
          disabled: false,
          export: true,
          resizable: true
        }
      ] as any[];
  }
  