// PM TRUCK COLUMN DEFINITION
export function getTruckPMColumnDefinition() {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: 'Select',
            hidden: false,
            isPined: true,
            width: 40,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'nameLink',
            title: 'UNIT',
            field: 'textUnit',
            name: 'UNIT',
            sortName: 'truckNumber',
            hidden: false,
            isPined: true,
            width: 80,
            pdfWidth: 10,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: true,
            export: true,
            resizable: true,
            linkField: {
                doesNotHaveRout: true,
                routerLinkStart: '/trucks/edit/',
                routerLinkEnd: '/detail',
            },
            link: {
                routerLinkStart: '/trucks/edit/',
                routerLinkEnd: '/detail',
            },
        },
        {
            ngTemplate: 'svg',
            title: 'Type',
            field: 'truckTypeIcon',
            isPined: false,
            headAlign: 'center',
            name: 'Type',
            sortName: 'type',
            hidden: false,
            width: 58,
            minWidth: 66,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 6,
            sortable: true,
            tooltipColor: 'tableTruckColor',
            tooltipTitle: 'tableTruckName',
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: false,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            svgUrl: 'assets/svg/common/trucks/',
            classField: 'truckTypeClass',
            svgDimensions: {
                width: 42,
                height: 18,
            },
            class: 'type-icon',
        },
        {
            ngTemplate: 'text',
            title: 'ODO mi',
            field: 'textOdometear',
            name: 'ODOMETEAR',
            sortName: 'odometear',
            hidden: false,
            isPined: false,
            width: 78,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'SERVICED',
            field: 'lastService',
            name: 'LAST SERVICE',
            sortName: 'lastService',
            hidden: false,
            isPined: false,
            width: 95,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'REPAIR SHOP',
            field: 'repairShop',
            name: 'REPAIR SHOP',
            sortName: 'repairShop',
            hidden: false,
            isPined: false,
            width: 238,
            filter: '',
            isNumeric: true,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'OIL & FILTER',
            field: 'oilFilter',
            name: 'OIL & FILTER',
            sortName: 'oilFilter',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'AIR FILTER',
            field: 'airFilter',
            name: 'AIR FILTER',
            sortName: 'airFilter',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'TRANS.FLUID',
            field: 'transFluid',
            name: 'TRANS.FLUID',
            sortName: 'transFluid',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'BELTS',
            field: 'belts',
            name: 'BELTS',
            sortName: 'belts',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'ENG.TUNE-UP',
            field: 'engTuneUp',
            name: 'ENG.TUNE-UP',
            sortName: 'engTuneUp',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'ALIGNMENT',
            field: 'alignment',
            name: 'ALIGNMENT',
            sortName: 'alignment',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'INV',
            field: 'textInv',
            name: 'INV',
            sortName: 'inv',
            hidden: true,
            isPined: false,
            width: 115,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'LAST SHOP',
            field: 'textLastShop',
            name: 'LAST SHOP',
            sortName: 'lastShop',
            hidden: true,
            isPined: false,
            width: 115,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'LAST SERVICE',
            field: 'lastService',
            name: 'LAST SERVICE',
            sortName: 'lastService',
            hidden: true,
            isPined: false,
            width: 115,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            hidden: false,
            width: 40,
            filter: '',
            isNumeric: false,
            index: 18,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}

// PM TRAILER COLUMN DEFINITION
export function getTrailerPMColumnDefinition() {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: 'Select',
            hidden: false,
            isPined: true,
            width: 40,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'nameLink',
            title: 'UNIT',
            field: 'textUnit',
            name: 'UNIT',
            sortName: 'trailerNumber',
            hidden: false,
            isPined: true,
            width: 90,
            pdfWidth: 10,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: true,
            export: true,
            resizable: true,
            linkField: {
                doesNotHaveRout: true,
                routerLinkStart: '/trucks/edit/',
                routerLinkEnd: '/detail',
            },
        },
        
        {
            ngTemplate: 'svg',
            title: 'Type',
            field: 'tableTrailerTypeIcon',
            isPined: false,
            headAlign: 'center',
            name: 'Type',
            sortName: 'type',
            hidden: false,
            width: 58,
            minWidth: 66,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 6,
            sortable: true,
            tooltipColor: 'tableTrailerColor',
            tooltipTitle: 'tableTrailerName',
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: false,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            svgUrl: 'assets/svg/common/trailers/',
            classField: 'trailerTypeClass',
            svgDimensions: {
                width: 42,
                height: 18,
            },
            class: 'type-icon',
        },
        {
            ngTemplate: 'text',
            title: 'ODO mi',
            field: 'textOdometer',
            name: 'ODOMETEAR',
            sortName: 'odometear',
            hidden: false,
            isPined: false,
            width: 78,
            filter: '',
            isNumeric: true,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'SERVICED',
            field: 'lastService',
            name: 'LAST SERV.',
            sortName: 'lastService',
            hidden: false,
            isPined: false,
            width: 88,
            filter: '',
            isNumeric: true,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'REPAIR SHOP',
            field: 'repairShop',
            name: 'REPAIR SHOP',
            sortName: 'repairShop',
            hidden: false,
            isPined: false,
            width: 238,
            filter: '',
            isNumeric: true,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'color',
            title: 'Color',
            field: 'color',
            name: '',
            sortName: 'colorName',
            headAlign: 'center',
            headIconStyle: {
                width: 18,
                height: 18,
                imgPath: 'assets/svg/truckassist-table/color-type.svg',
            },
            hidden: true,
            width: 54,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            isPined: false,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            colorTemplate: {
                value: 'doc.additionalData.color.value',
            },
            opacityIgnore: true,
            class: 'overflow-unset',
        },
        {
            ngTemplate: 'progress',
            title: 'GENERAL',
            field: 'general',
            name: 'GENERAL',
            sortName: 'general',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progress',
            title: 'ALIGNMENT',
            field: 'alignment',
            name: 'ALIGNMENT',
            sortName: 'alignment',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progress',
            title: 'REEFER UNIT',
            field: 'reeferUnit',
            name: 'REEFER UNIT',
            sortName: 'reeferUnit',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progress',
            title: 'PTO PUMP',
            field: 'ptoPump',
            name: 'PTO PUMP',
            sortName: 'ptoPump',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'RU MAKE',
            field: 'ruMake',
            name: 'RU MAKE',
            sortName: 'ruMake',
            hidden: true,
            isPined: false,
            width: 115,
            filter: '',
            isNumeric: true,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progress',
            title: 'PREVENTIVE MAINTENANCE',
            field: 'reventiveMaintenance',
            name: 'PREVENTIVE MAINTENANCE',
            sortName: 'reventiveMaintenance',
            hidden: true,
            width: 260,
            minWidth: 101,
            isPined: false,
            filter: '',
            isNumeric: true,
            index: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            hidden: false,
            width: 40,
            filter: '',
            isNumeric: false,
            index: 18,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}
