// PM TRUCK COLUMN DEFINITION
export function getTruckPMColumnDefinition() {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: 'Select',
            hidden: false,
            isPined: true,
            width: 40,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'nameLink',
            title: 'UNIT',
            field: 'textUnit',
            name: 'UNIT',
            sortName: 'truckNumber',
            hidden: false,
            isPined: true,
            width: 66,
            pdfWidth: 10,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: true,
            export: true,
            resizable: true,
            linkField: {
                routerLinkStart: '/trucks/edit/',
                routerLinkEnd: '/detail',
            },
        },
        {
            ngTemplate: 'text',
            title: 'ODOMETEAR',
            field: 'textOdometear',
            name: 'ODOMETEAR',
            hidden: false,
            isPined: false,
            width: 115,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'progress',
            title: 'OIL & FILTER',
            field: 'oilFilter',
            name: 'OIL & FILTER',
            hidden: false,
            isPined: false,
            width: 160,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progress',
            title: 'AIR FILTER',
            field: 'airFilter',
            name: 'AIR FILTER',
            hidden: false,
            isPined: false,
            width: 160,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progress',
            title: 'TRANS.FLUID',
            field: 'transFluid',
            name: 'TRANS.FLUID',
            hidden: false,
            isPined: false,
            width: 160,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progress',
            title: 'BELTS',
            field: 'belts',
            name: 'BELTS',
            hidden: false,
            isPined: false,
            width: 160,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progress',
            title: 'ENG.TUNE-UP',
            field: 'engTuneUp',
            name: 'ENG.TUNE-UP',
            hidden: false,
            isPined: false,
            width: 160,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progress',
            title: 'ALIGNMENT',
            field: 'alignment',
            name: 'ALIGNMENT',
            hidden: false,
            isPined: false,
            width: 160,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'INV',
            field: 'textInv',
            name: 'INV',
            hidden: true,
            isPined: false,
            width: 115,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'LAST SHOP',
            field: 'textLastShop',
            name: 'LAST SHOP',
            hidden: true,
            isPined: false,
            width: 115,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'LAST SERVICE',
            field: 'lastService',
            name: 'LAST SERVICE',
            hidden: true,
            isPined: false,
            width: 115,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            hidden: false,
            width: 40,
            filter: '',
            isNumeric: false,
            index: 18,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}

// PM TRAILER COLUMN DEFINITION
export function getTrailerPMColumnDefinition() {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: 'Select',
            hidden: false,
            isPined: true,
            width: 40,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'nameLink',
            title: 'UNIT',
            field: 'textUnit',
            name: 'UNIT',
            sortName: 'trailerNumber',
            hidden: false,
            isPined: true,
            width: 66,
            pdfWidth: 10,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: true,
            export: true,
            resizable: true,
            linkField: {
                routerLinkStart: '/trucks/edit/',
                routerLinkEnd: '/detail',
            },
        },
        {
            ngTemplate: 'text',
            title: 'ODOMETEAR',
            field: 'textOdometer',
            name: 'ODOMETEAR',
            hidden: false,
            isPined: false,
            width: 115,
            filter: '',
            isNumeric: true,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'LAST SERV.',
            field: 'lastServe',
            name: 'LAST SERV.',
            hidden: false,
            isPined: false,
            width: 115,
            filter: '',
            isNumeric: true,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'REPAIR SHOP',
            field: 'repairShop',
            name: 'REPAIR SHOP',
            hidden: false,
            isPined: false,
            width: 115,
            filter: '',
            isNumeric: true,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'color',
            title: 'Color',
            field: 'color',
            name: '',
            sortName: 'colorName',
            headAlign: 'center',
            headIconStyle: {
                width: 18,
                height: 18,
                imgPath: 'assets/svg/truckassist-table/color-type.svg',
            },
            hidden: false,
            width: 54,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            isPined: false,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            colorTemplate: {
                value: 'doc.additionalData.color.value',
            },
            opacityIgnore: true,
            class: 'overflow-unset',
        },
        /* ngTemplate: 'svg', */
        {
            ngTemplate: 'text',
            title: 'TYPE',
            field: 'svgIcon',
            headAlign: 'center',
            name: 'TYPE',
            sortName: 'type',
            hidden: false,
            isPined: false,
            width: 83,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 6,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: false,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            imageHover: {
                url: 'assets/svg/truckassist-table/truck/',
                file: 'doc.additionalData.type.file',
                class: 'doc.additionalData.type.class',
            },
            class: 'type-icon',
        },
        {
            ngTemplate: 'progress',
            title: 'REEFER UNIT',
            field: 'reeferUnit',
            name: 'REEFER UNIT',
            hidden: false,
            isPined: false,
            width: 160,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'RU MAKE',
            field: 'ruMake',
            name: 'RU MAKE',
            hidden: false,
            isPined: false,
            width: 115,
            filter: '',
            isNumeric: true,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progress',
            title: 'PREVENTIVE MAINTENANCE',
            field: 'reventiveMaintenance',
            name: 'PREVENTIVE MAINTENANCE',
            hidden: false,
            width: 260,
            minWidth: 101,
            isPined: false,
            filter: '',
            isNumeric: true,
            index: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            hidden: false,
            width: 40,
            filter: '',
            isNumeric: false,
            index: 18,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}
