// ACCIDENTS COLUMN DEFINITION
export function getAccidentColumns() {
  return [
    {
      ngTemplate: 'checkbox',
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      width: 32,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'text',
      title: 'Truck',
      field: 'truckNumber',
      name: 'Truck',
      sortName: 'truckNumber',
      hidden: false,
      width: 74,
      filter: '',
      isNumeric: false,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Trailer',
      field: 'trailerNumber',
      name: 'Trailer',
      sortName: 'trailerNumber',
      hidden: false,
      width: 94,
      filter: '',
      isNumeric: false,
      index: 6,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'avatar',
      title: 'Driver',
      field: 'driverFullName',
      name: 'Driver',
      sortName: 'driverFullName',
      hidden: false,
      width: 212,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: {
        src: 'additionalData.avatar.src',
      },
      link: {
        routerLinkStart: '/drivers/edit/',
        routerLinkEnd: '/basic',
      },
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: true,
      class: 'overflow-unset',
    },
    {
      ngTemplate: 'text',
      title: 'Report #',
      field: 'report',
      name: 'Report #',
      sortName: 'report',
      hidden: false,
      width: 160,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Date',
      field: 'eventDate',
      name: 'Date',
      sortName: 'eventDate',
      hidden: false,
      width: 69,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Time',
      field: 'time',
      name: 'Time',
      sortName: 'time',
      hidden: false,
      width: 79,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },

    {
      ngTemplate: 'text',
      title: 'Location',
      field: 'address',
      name: 'Location',
      sortName: 'address',
      hidden: false,
      width: 252,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },

    {
      ngTemplate: 'text',
      title: 'Fat.',
      field: 'fatality',
      name: 'Fat.',
      sortName: 'fatality',
      hidden: false,
      width: 59,
      filter: '',
      isNumeric: false,
      index: 7,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Inj.',
      field: 'injuries',
      name: 'Inj.',
      sortName: 'injuries',
      hidden: false,
      width: 51,
      filter: '',
      isNumeric: false,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Tow',
      field: 'towing',
      name: 'Tow',
      sortName: 'towing',
      hidden: false,
      width: 58,
      filter: '',
      isNumeric: false,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'HM',
      field: 'hm',
      name: 'HM',
      sortName: 'hm',
      hidden: false,
      width: 53,
      filter: '',
      isNumeric: false,
      index: 10,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'INS. Claim #',
      field: 'insuranceClaim',
      name: 'INS. Claim #',
      sortName: 'insuranceClaim',
      hidden: false,
      width: 127,
      filter: '',
      isNumeric: false,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'attachments',
      title: '',
      field: 'additionalData.files',
      name: 'Files',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 16,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'note',
      title: '',
      field: 'doc.additionalData.note',
      name: 'Note',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 9,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: false,
    },
    {
      ngTemplate: 'actions',
      title: '',
      field: 'action',
      name: 'Action',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: true,
      index: 10,
      sortable: true,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
  ];
}

/* VIOLATION COLUMN DEFINITION */
export function getViolationsColums() {
  return [
    {
      ngTemplate: 'checkbox',
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      width: 32,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'nameLink',
      title: 'Report #',
      field: 'report',
      name: 'Report #',
      hidden: false,
      width: 147,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: {
        routerLinkStart: '/safety/violation/edit/',
        routerLinkEnd: '/details',
      },
    },
    {
      ngTemplate: 'avatar',
      title: 'Driver',
      field: 'driverFullName',
      name: 'Driver',
      hidden: false,
      width: 160,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      avatar: {
        src: 'additionalData.avatar.src',
      },
      link: {
        routerLinkStart: '/drivers/edit/',
        routerLinkEnd: '/basic',
      },
      export: true,
      resizable: true,
      class: 'overflow-unset',
    },
    {
      ngTemplate: 'text',
      title: 'Date',
      field: 'eventDate',
      name: 'Date',
      hidden: false,
      width: 75,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Time',
      field: 'eventTime',
      name: 'Time',
      hidden: false,
      width: 76,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Truck',
      field: 'truckNumber',
      name: 'Truck',
      hidden: false,
      width: 77,
      filter: '',
      isNumeric: false,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Trailer',
      field: 'trailerNumber',
      name: 'Trailer',
      hidden: false,
      width: 78,
      filter: '',
      isNumeric: false,
      index: 6,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: '',
      title: 'OOS',
      field: 'oos',
      name: 'OOS',
      headAlignText: 'center',
      hidden: false,
      width: 92,
      filter: '',
      isNumeric: false,
      index: 7,
      sortable: false,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      outOfService: true,
    },
    {
      ngTemplate: '',
      title: 'State',
      field: 'doc.address.state',
      name: 'State',
      headAlignText: 'center',
      hidden: false,
      width: 71,
      filter: '',
      isNumeric: false,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: {
        urlStart: '../assets/img/svgs/states/',
        field: 'doc.address.stateShortName',
        urlEnd: '.svg',
      },
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'LVL',
      field: 'lvl',
      name: 'LVL',
      headAlignText: 'center',
      hidden: false,
      width: 55,
      filter: '',
      isNumeric: false,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: '',
      title: '',
      field: 'vl1',
      name: 'vl1',
      headAlignText: 'center',
      hidden: false,
      width: 58,
      filter: '',
      isNumeric: false,
      index: 10,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: true,
      resizable: true,
      violation: true,
    },
    {
      ngTemplate: '',
      title: '',
      field: 'vl2',
      name: 'vl2',
      headAlignText: 'center',
      hidden: false,
      width: 58,
      filter: '',
      isNumeric: false,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      violation: true,
    },
    {
      ngTemplate: '',
      title: '',
      field: 'vl3',
      name: 'vl3',
      headAlignText: 'center',
      hidden: false,
      width: 58,
      filter: '',
      isNumeric: false,
      index: 12,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      violation: true,
    },
    {
      ngTemplate: '',
      title: '',
      field: 'vl4',
      name: 'vl4',
      headAlignText: 'center',
      hidden: false,
      width: 58,
      filter: '',
      isNumeric: false,
      index: 13,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      violation: true,
    },
    {
      ngTemplate: '',
      title: '',
      field: 'vl5',
      name: 'vl5',
      headAlignText: 'center',
      hidden: false,
      width: 58,
      filter: '',
      isNumeric: false,
      index: 14,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      violation: true,
    },
    {
      ngTemplate: '',
      title: '',
      field: 'vl6',
      name: 'vl6',
      headAlignText: 'center',
      hidden: false,
      width: 58,
      filter: '',
      isNumeric: false,
      index: 15,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      violation: true,
    },
    {
      ngTemplate: '',
      title: 'Citation',
      field: 'citation',
      name: 'Citation',
      headAlignText: 'center',
      hidden: false,
      width: 90,
      filter: '',
      isNumeric: false,
      index: 17,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      citation: true,
    },
    {
      ngTemplate: 'attachments',
      title: '',
      field: 'additionalData.files',
      name: '',
      moveRight: true,
      headIconStyle: {
        width: 19,
        height: 19,
        imgPath:
          'assets/svg/truckassist-table/attachment/attachemnt-regular-svgIcon.svg',
      },
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 16,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'note',
      title: '',
      field: 'doc.additionalData.note',
      name: '',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 17,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: false,
    },
    {
      ngTemplate: 'actions',
      title: '',
      field: 'action',
      name: '',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 18,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
  ];
}