// ACCIDENTS COLUMN DEFINITION
export function getAccidentColumns() { 
  return [
    {
      ngTemplate: 'checkbox',
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      width: 32,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'text',
      title: 'Truck',
      field: 'truckNumber',
      name: 'Truck',
      sortName: 'truckNumber',
      hidden: false,
      width: 74,
      filter: '',
      isNumeric: false,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Trailer',
      field: 'trailerNumber',
      name: 'Trailer',
      sortName: 'trailerNumber',
      hidden: false,
      width: 94,
      filter: '',
      isNumeric: false,
      index: 6,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'avatar',
      title: 'Driver',
      field: 'driverFullName',
      name: 'Driver',
      sortName: 'driverFullName',
      hidden: false,
      width: 212,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: {
        src: 'additionalData.avatar.src',
      },
      link: {
        routerLinkStart: '/drivers/edit/',
        routerLinkEnd: '/basic',
      },
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: true,
      class: 'overflow-unset',
    },
    {
      ngTemplate: 'text',
      title: 'Report #',
      field: 'report',
      name: 'Report #',
      sortName: 'report',
      hidden: false,
      width: 160,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Date',
      field: 'eventDate',
      name: 'Date',
      sortName: 'eventDate',
      hidden: false,
      width: 69,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Time',
      field: 'time',
      name: 'Time',
      sortName: 'time',
      hidden: false,
      width: 79,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },

    {
      ngTemplate: 'text',
      title: 'Location',
      field: 'address',
      name: 'Location',
      sortName: 'address',
      hidden: false,
      width: 252,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },

    {
      ngTemplate: 'text',
      title: 'Fat.',
      field: 'fatality',
      name: 'Fat.',
      sortName: 'fatality',
      hidden: false,
      width: 59,
      filter: '',
      isNumeric: false,
      index: 7,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Inj.',
      field: 'injuries',
      name: 'Inj.',
      sortName: 'injuries',
      hidden: false,
      width: 51,
      filter: '',
      isNumeric: false,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Tow',
      field: 'towing',
      name: 'Tow',
      sortName: 'towing',
      hidden: false,
      width: 58,
      filter: '',
      isNumeric: false,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'HM',
      field: 'hm',
      name: 'HM',
      sortName: 'hm',
      hidden: false,
      width: 53,
      filter: '',
      isNumeric: false,
      index: 10,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'INS. Claim #',
      field: 'insuranceClaim',
      name: 'INS. Claim #',
      sortName: 'insuranceClaim',
      hidden: false,
      width: 127,
      filter: '',
      isNumeric: false,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'attachments',
      title: 'Attachments',
      field: 'additionalData.files',
      name: '',
      hidden: false,
      moveRight: true,
      headIconStyle: {
        width: 19,
        height: 19,
        imgPath:
          'assets/svg/truckassist-table/attachment/attachemnt-regular-svgIcon.svg',
      },
      width: 40,
      filter: '',
      isNumeric: false,
      index: 16,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
      isAction: true
    },
    {
      ngTemplate: 'note',
      title: 'Note',
      field: 'doc.additionalData.note',
      name: '',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 9,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: false,
      isAction: true
    },
    {
      ngTemplate: 'actions',
      title: 'Actions',
      field: 'action',
      name: '',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: true,
      index: 10,
      sortable: true,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      isAction: true
    },
  ];
}

/* VIOLATION COLUMN DEFINITION */
export function getViolationsColums() {
  return [
    {
      ngTemplate: 'checkbox',
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      width: 32,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: '',
      title: 'Report',
      field: 'tableReport',
      name: 'Report',
      hidden: false,
      width: 126,
      minWidth: 126,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: {
        routerLinkStart: '/safety/violation/edit/',
        routerLinkEnd: '/details',
      },
    },
    {
      ngTemplate: 'text',
      title: 'Driver',
      field: 'tableDriverName',
      name: 'Driver',
      hidden: false,
      width: 129,
      minWidth: 129,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      avatar: {
        src: 'additionalData.avatar.src',
      },
      link: {
        routerLinkStart: '/drivers/edit/',
        routerLinkEnd: '/basic',
      },
      export: true,
      resizable: true,
      class: 'overflow-unset',
    },
    {
      ngTemplate: 'text',
      title: 'Truck',
      field: 'truckNumber',
      name: 'Truck',
      hidden: false,
      width: 78,
      minWidth: 78,
      filter: '',
      isNumeric: false,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Trailer',
      field: 'trailerNumber',
      name: 'Trailer',
      hidden: false,
      width: 78,
      minWidth: 78,
      filter: '',
      isNumeric: false,
      index: 6,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Date',
      field: 'tableDate',
      name: 'Date',
      hidden: false,
      width: 86,
      minWidth: 86,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Start',
      field: 'tabelStartTime',
      name: 'Start',
      hidden: false,
      width: 86,
      minWidth: 86,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'End',
      field: 'tabelEndTime',
      name: 'End',
      hidden: false,
      width: 86,
      minWidth: 86,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: '',
      title: 'LVL',
      field: 'lvl',
      name: 'LVL',
      hidden: false,
      width: 76,
      minWidth: 76,
      filter: '',
      isNumeric: false,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: '',
      title: 'ST',
      field: 'stateText',
      name: 'ST',
      hidden: false,
      width: 70,
      minWidth: 70,
      filter: '',
      isNumeric: false,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: '',
      title: 'Novi head template treba',
      field: 'tableSwTw',
      name: 'Novi head template treba',
      hidden: false,
      width: 190,
      minWidth: 190,
      filter: '',
      isNumeric: false,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: '',
      title: 'Novi head template treba',
      field: 'tableOss',
      name: 'Novi head template treba',
      hidden: false,
      width: 150,
      minWidth: 150,
      filter: '',
      isNumeric: false,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'attachments',
      title: 'Attachments',
      field: 'additionalData.files',
      name: '',
      moveRight: true,
      headIconStyle: {
        width: 19,
        height: 19,
        imgPath:
          'assets/svg/truckassist-table/attachment/attachemnt-regular-svgIcon.svg',
      },
      hidden: false,
      width: 40,
      minWidth: 40,
      filter: '',
      isNumeric: false,
      index: 16,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
      isAction: true
    },
    {
      ngTemplate: 'note',
      title: 'Note',
      field: 'additionalData.note',
      name: '',
      hidden: false,
      width: 40,
      minWidth: 40,
      filter: '',
      isNumeric: false,
      index: 17,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: false,
      isAction: true
    },
    {
      ngTemplate: 'actions',
      title: 'Actions',
      field: 'action',
      name: '',
      hidden: false,
      width: 40,
      minWidth: 40,
      filter: '',
      isNumeric: false,
      index: 18,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
      isAction: true
    },
  ];
}