export function getToolsAccountsColumnDefinition() {  
  return [
    {
      ngTemplate: 'checkbox',
      title: '',
      field: 'select',
      name: 'Select',
      isComputed: true,
      hidden: false,
      width: 32,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'text',
      title: 'Name',
      field: 'name',
      name: 'Name',
      sortName: 'name',
      isComputed: false,
      hidden: false,
      width: 143,
      minWidth: 143,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'url',
      title: 'Url',
      field: 'url',
      name: 'Url',
      sortName: 'url',
      isComputed: false,
      hidden: false,
      width: 153,
      minWidth: 153,
      filter: '',
      isNumeric: true,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      navigateTo: true,
    },
    {
      ngTemplate: 'text',
      title: 'Username',
      field: 'username',
      name: 'Username',
      sortName: 'username',
      hidden: false,
      width: 139,
      minWidth: 139,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      imageHover: null,
    },
    {
      ngTemplate: 'password',
      title: 'Password',
      field: '',
      name: 'Password',
      isComputed: false,
      hidden: false,
      width: 143,
      minWidth: 143,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: false,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      password: true,
    },
    {
      ngTemplate: 'label',
      title: 'Label',
      field: 'labelId',
      name: 'Label',
      sortName: 'labelName',
      isComputed: false,
      hidden: false,
      width: 132,
      minWidth: 132,
      filter: '',
      isNumeric: true,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: false,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      imageHover: null,
      showLabel: true,
    },
    {
      ngTemplate: 'note',
      title: 'Note',
      field: 'doc.note',
      name: '',
      moveRight: true,
      hidden: false,
      width: 40,
      minWidth: 40,
      filter: '',
      isNumeric: false,
      index: 7,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: false,
      isAction: true
    },
    {
      ngTemplate: 'actions',
      title: 'Actions',
      field: 'action',
      name: '',
      hidden: false,
      width: 42,
      minWidth: 42,
      filter: '',
      isNumeric: true,
      index: 8,
      sortable: true,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: true,
      isAction: true
    },
  ];
}
