export function getTrailerColumnDefinition() {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: 'Select',
            hidden: false,
            isPined: true,
            width: 32,
            pdfWidth: 32,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'nameLink',
            title: 'Unit',
            field: 'trailerNumber',
            name: 'Unit',
            isPined: true,
            hidden: false,
            sortName: 'trailerNumber',
            width: 100,
            minWidth: 80,
            pdfWidth: 10,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: true,
            export: true,
            resizable: true,
            link: {
                routerLinkStart: '/trailer/',
                routerLinkEnd: '/details',
            },
        },
        {
            ngTemplate: 'svg',
            title: 'Type',
            field: 'tableTrailerTypeIcon',
            name: 'Type',
            headAlign: 'center',
            sortName: 'type',
            isPined: false,
            hidden: false,
            width: 50,
            minWidth: 50,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 6,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: false,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            svgUrl: 'assets/svg/truckassist-table/trailer/',
            classField: 'tableTrailerTypeClass',
            svgDimensions: {
                width: 42,
                height: 18,
            },
            class: 'type-icon',
        },
        {
            ngTemplate: 'text',
            title: 'VIN',
            field: 'vin',
            name: 'VIN',
            sortName: 'vin',
            hidden: false,
            isPined: false,
            width: 180,
            minWidth: 76,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 7,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Make',
            field: 'tableMake',
            name: 'Make',
            isPined: false,
            sortName: 'make',
            hidden: false,
            width: 120,
            minWidth: 50,
            pdfWidth: 15,
            filter: '',
            isNumeric: false,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            imageHover: {
                url: '../assets/img/svgs/trailer/makers/',
                file: 'doc.additionalData.make.file',
            },
            class: 'make-icon',
        },
        {
            ngTemplate: 'text',
            title: 'Model',
            field: 'tableModel',
            name: 'Model',
            sortName: 'model',
            hidden: false,
            isPined: false,
            width: 140,
            minWidth: 55,
            pdfWidth: 15,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Year',
            field: 'year',
            name: 'Year',
            sortName: 'year',
            isPined: false,
            hidden: false,
            width: 60,
            minWidth: 40,
            pdfWidth: 10,
            filter: '',
            isNumeric: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'color',
            title: 'Color',
            field: 'tableColor',
            isPined: false,
            name: '',
            headAlign: 'center',
            headIconStyle: {
                width: 18,
                height: 18,
                imgPath: 'assets/svg/truckassist-table/color-type.svg',
            },
            sortName: 'color',
            hidden: false,
            width: 34,
            minWidth: 34,
            pdfWidth: 10,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            colorTemplate: {
                value: 'doc.additionalData.color.value',
            },
            opacityIgnore: true,
            class: 'overflow-unset',
        },
        {
            ngTemplate: 'text',
            title: 'Length',
            field: 'tabelLength',
            name: 'Length',
            sortName: 'length',
            hidden: false,
            isPined: false,
            width: 60,
            minWidth: 33,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Assigned To Driver',
            field: 'tableDriver',
            name: 'Assigned To Driver',
            groupName:'Assigned To',
            hidden: false,
            isPined: false,
            width: 200,
            minWidth: 100,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Assigned To Truck',
            field: 'tableTruck',
            name: 'Assigned To Truck',
            groupName:'Assigned To',
            hidden: false,
            isPined: false,
            width: 80,
            minWidth: 64,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Assigned To Truck Type',
            field: 'tableTruckType',
            name: 'Assigned To TruckType',
            groupName:'Assigned To',
            hidden: true,
            isPined: false,
            width: 50,
            minWidth: 50,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
         {
            ngTemplate: 'text',
            title: 'Owner',
            field: 'tableOwner',
            name: 'Owner',
            hidden: true,
            isPined: false,
            width: 200,
            minWidth: 150,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Weight Empty',
            field: 'tableWeightEmpty',
            name: 'Weight Empty',
            groupName:'Weight',
            hidden: true,
            isPined: false,
            width: 100,
            minWidth: 78,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Weight Volume',
            field: 'tableWeightVolume',
            name: 'Weight Volume',
            groupName:'Weight',
            hidden: true,
            isPined: false,
            width: 100,
            minWidth: 78,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Axle',
            field: 'tableAxle',
            name: 'Axle',
            hidden: true,
            isPined: false,
            width: 40,
            minWidth: 40,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Suspension',
            field: 'tableSuspension',
            name: 'Suspension',
            hidden: true,
            isPined: false,
            width: 100,
            minWidth: 80,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Tire Size',
            field: 'tableTireSize',
            name: 'Tire Size',
            hidden: true,
            isPined: false,
            width: 82,
            minWidth: 60,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Reefer Unit',
            field: 'tableReeferUnit',
            name: 'Reefer Unit',
            hidden: true,
            isPined: false,
            width: 100,
            minWidth: 92,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Door Type',
            field: 'tableDoorType',
            name: 'Door Type',
            hidden: true,
            isPined: false,
            width: 88,
            minWidth: 52,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Ins Policy',
            field: 'tableInsPolicy',
            name: 'Ins Policy',
            hidden: true,
            isPined: false,
            width: 130,
            minWidth: 82,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Mileage',
            field: 'tableMileage',
            name: 'Mileage',
            hidden: true,
            isPined: false,
            width: 80,
            minWidth: 67,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Licence Plate Detail Number',
            field: 'tableLicencePlateDetailNumber',
            name: 'Licence Plate Detail Number',
            groupName:'Licence Plate Detail',
            hidden: false,
            isPined: false,
            width: 100,
            minWidth: 76,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Licence Plate Detail ST',
            field: 'tableLicencePlateDetailST',
            name: 'Licence Plate Detail ST',
            groupName:'Licence Plate Detail',
            hidden: true,
            isPined: false,
            width: 60,
            minWidth: 24,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Licence Plate Detail Expiration',
            field: 'tableLicencePlateDetailExpiration',
            name: 'Licence Plate Detail Expiration',
            groupName:'Licence Plate Detail',
            hidden: false,
            isPined: false,
            width: 130,
            minWidth: 87,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'FHWA Inspection Term',
            field: 'tableFHWAInspectionTerm',
            name: 'FHWA Inspection Term',
            groupName:'FHWA Inspection',
            hidden: true,
            isPined: false,
            width: 108,
            minWidth: 87,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'FHWA Inspection Expiration',
            field: 'tableFHWAInspectionExpiration',
            name: 'FHWA Inspection Expiration',
            groupName:'FHWA Inspection',
            hidden: false,
            isPined: false,
            width: 130,
            minWidth: 87,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Title Number',
            field: 'tableTitleNumber',
            name: 'Title Number',
            groupName:'Title',
            hidden: true,
            isPined: false,
            width: 120,
            minWidth: 65,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Title ST',
            field: 'tableTitleST',
            name: 'Title ST',
            groupName:'Title',
            hidden: true,
            isPined: false,
            width: 60,
            minWidth: 24,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Title Purchase',
            field: 'tableTitlePurchase',
            name: 'Title Purchase',
            groupName:'Title',
            hidden: true,
            isPined: false,
            width: 80,
            minWidth: 66,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Title Issued',
            field: 'tableTitleIssued',
            name: 'Title Issued',
            groupName:'Title',
            hidden: true,
            isPined: false,
            width: 80,
            minWidth: 66,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Purchase Date',
            field: 'tablePurchaseDate',
            name: 'Purchase Date',
            groupName:'Purchase',
            hidden: true,
            isPined: false,
            width: 80,
            minWidth: 66,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Purchase Price',
            field: 'tablePurchasePrice',
            name: 'Purchase Price',
            groupName:'Purchase',
            hidden: true,
            isPined: false,
            width: 100,
            minWidth: 82,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Terminated',
            field: 'tableTerminated',
            name: 'Terminated',
            hidden: true,
            isPined: false,
            width: 100,
            minWidth: 66,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Added',
            field: 'tableAdded',
            name: 'Added',
            hidden: true,
            isPined: false,
            width: 80,
            minWidth: 66,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Edited',
            field: 'tableEdited',
            name: 'Edited',
            hidden: true,
            isPined: false,
            width: 80,
            minWidth: 66,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'attachments',
            title: 'Attachments',
            field: 'tableAttachments',
            moveRight: true,
            name: '',
            headIconStyle: {
                width: 19,
                height: 19,
                imgPath:
                    'assets/svg/truckassist-table/attachment/attachemnt-regular-svgIcon.svg',
            },
            hidden: false,
            minWidth: 20,
            width: 20,
            filter: '',
            isNumeric: false,
            index: 16,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'note',
            title: 'Note',
            field: 'note',
            name: '',
            hidden: false,
            minWidth: 40,
            width: 40,
            pdfWidth: 15,
            filter: '',
            isNumeric: false,
            index: 12,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            hidden: false,
            minWidth: 42,
            width: 42,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 13,
            sortable: true,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}
