export function getTrailerColumnDefinition() {
  return [
    {
      ngTemplate: 'checkbox',
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      isPined: true,
      width: 32,
      pdfWidth: 32,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: false,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'nameLink',
      title: 'Unit#',
      field: 'trailerNumber',
      name: 'Unit#',
      isPined: true,
      hidden: false,
      sortName: 'trailerNumber',
      minWidth: 120,
      width: 120,
      pdfWidth: 10,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: true,
      link: {
        routerLinkStart: '/trailer/',
        routerLinkEnd: '/details',
      },
    },
    {
      ngTemplate: 'text',
      title: 'Year',
      field: 'year',
      name: 'Year',
      sortName: 'year',
      isPined: false,
      hidden: false,
      minWidth: 83,
      width: 83,
      pdfWidth: 10,
      filter: '',
      isNumeric: true,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Make',
      field: 'textMake',
      name: 'Make',
      isPined: false,
      sortName: 'make',
      hidden: false,
      minWidth: 100,
      width: 130,
      pdfWidth: 15,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      imageHover: {
        url: '../assets/img/svgs/trailer/makers/',
        file: 'doc.additionalData.make.file',
      },
      class: 'make-icon',
    },
    {
      ngTemplate: 'text',
      title: 'Model',
      field: 'textModel',
      name: 'Model',
      sortName: 'model',
      hidden: false,
      isPined: false,
      minWidth: 100,
      width: 116,
      pdfWidth: 15,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Owner',
      field: 'ownerName',
      name: 'Owner',
      sortName: 'owner',
      isPined: false,
      hidden: false,
      minWidth: 129,
      width: 150,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 10,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'color',
      title: 'Color',
      field: 'textColor',
      isPined: false,
      name: '',
      headAlign: 'center',
      headIconStyle: {
        width: 18,
        height: 18,
        imgPath: 'assets/svg/truckassist-table/color-type.svg',
      },
      sortName: 'color',
      hidden: false,
      minWidth: 71,
      width: 83,
      pdfWidth: 10,
      filter: '',
      isNumeric: true,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      colorTemplate: {
        value: 'doc.additionalData.color.value',
      },
      opacityIgnore: true,
      class: 'overflow-unset',
    },
    {
      ngTemplate: 'svg',
      title: 'Type',
      field: 'trailerTypeIcon',
      name: 'Type',
      headAlign: 'center',
      sortName: 'type',
      isPined: false,
      hidden: false,
      minWidth: 81,
      width: 97,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 6,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: false,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      svgUrl: 'assets/svg/truckassist-table/trailer/',
      classField: 'trailerTypeClass',
      svgDimensions: {
        width: 42,
        height: 18,
      },
      class: 'type-icon',
    },
    {
      ngTemplate: 'text',
      title: 'VIN',
      field: 'vin',
      name: 'VIN',
      sortName: 'vin',
      hidden: false,
      isPined: false,
      minWidth: 92,
      width: 200,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 7,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Length',
      field: 'textLength',
      name: 'Length',
      sortName: 'length',
      hidden: false,
      isPined: false,
      minWidth: 82,
      width: 85,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'text',
      title: 'Lic. Plate',
      field: 'textLicPlate',
      name: 'Lic. Plate',
      sortName: 'licensePlate',
      hidden: false,
      isPined: false,
      minWidth: 116,
      width: 130,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
      class: 'custom-font',
    },
    {
      ngTemplate: 'progress',
      title: 'FHWA Insp. Exp.',
      field: 'textInspectionData',
      name: 'FHWA Insp. Exp.',
      sortName: 'licenseExp',
      hidden: false,
      isPined: false,
      minWidth: 101,
      width: 166,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: {
        start: '',
        end: 'doc.inspectionData[0].startDate',
      },
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'text',
      title: 'Axies',
      field: 'textAxies',
      name: 'Axies',
      sortName: 'axies',
      isPined: false,
      hidden: true,
      minWidth: 84,
      width: 84,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Tire Size',
      field: 'textTireSize',
      name: 'Tire Size',
      sortName: 'tireSize',
      isPined: false,
      hidden: true,
      minWidth: 97,
      width: 97,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Reefer Unit',
      field: 'textReeferUnit',
      name: 'Reefer Unit',
      sortName: 'reeferUnit',
      isPined: false,
      hidden: true,
      minWidth: 108,
      width: 108,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Ins. Policy',
      field: 'textInsPolicy',
      name: 'Ins. Policy',
      sortName: 'insPolicy',
      isPined: false,
      hidden: true,
      minWidth: 105,
      width: 105,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Empty Weight',
      field: 'textEmptyWeight',
      name: 'Empty Weight',
      sortName: 'emptyWeight',
      isPined: false,
      hidden: true,
      minWidth: 103,
      width: 103,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Mileage',
      field: 'textMileage',
      name: 'Mileage',
      sortName: 'mileage',
      isPined: false,
      hidden: true,
      minWidth: 100,
      width: 100,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
      class: 'custom-font',
    },
    {
      ngTemplate: 'attachments',
      title: 'Attachments',
      field: 'additionalData.files',
      moveRight: true,
      name: '',
      headIconStyle: {
        width: 19,
        height: 19,
        imgPath:
          'assets/svg/truckassist-table/attachment/attachemnt-regular-svgIcon.svg',
      },
      hidden: false,
      minWidth: 20,
      width: 20,
      filter: '',
      isNumeric: false,
      index: 16,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
      isAction: true,
    },
    {
      ngTemplate: 'note',
      title: 'Note',
      field: 'note',
      name: '',
      hidden: false,
      minWidth: 40,
      width: 40,
      pdfWidth: 15,
      filter: '',
      isNumeric: false,
      index: 12,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: false,
      isAction: true,
    },
    {
      ngTemplate: 'actions',
      title: 'Actions',
      field: 'action',
      name: '',
      hidden: false,
      minWidth: 42,
      width: 42,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 13,
      sortable: true,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
      isAction: true,
    },
  ];
}
