export function getTruckColumnDefinition() {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: 'Select',
            isPined: true,
            hidden: false,
            width: 32,
            pdfWidth: 32,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'nameLink',
            title: 'Unit',
            field: 'truckNumber',
            name: 'Unit',
            sortName: 'truckNumber',
            isPined: true,
            hidden: false,
            width: 80,
            minWidth: 33,
            pdfWidth: 10,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: true,
            export: true,
            resizable: true,
            link: {
                routerLinkStart: '/truck/',
                routerLinkEnd: '/details',
            },
        },
        {
            ngTemplate: 'svg',
            title: 'Type',
            field: 'truckTypeIcon',
            isPined: false,
            headAlign: 'center',
            name: 'Type',
            sortName: 'type',
            hidden: false,
            width: 140,
            minWidth: 44,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 6,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: false,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            svgUrl: 'assets/svg/truckassist-table/truck/',
            classField: 'truckTypeClass',
            svgDimensions: {
                width: 42,
                height: 18,
            },
            class: 'type-icon',
        },
        {
            ngTemplate: 'text',
            title: 'VIN',
            field: 'vin',
            name: 'VIN',
            sortName: 'vin',
            isPined: false,
            hidden: false,
            width: 180,
            minWidth: 76,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 7,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Make',
            field: 'textMake',
            name: 'Make',
            sortName: 'make',
            isPined: false,
            hidden: false,
            width: 120,
            minWidth: 80,
            pdfWidth: 15,
            filter: '',
            isNumeric: false,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            imageHover: {
                url: '../assets/img/svgs/truck/makers/',
                file: 'doc.additionalData.make.file',
            },
            class: 'make-icon',
        },
        {
            ngTemplate: 'text',
            title: 'Model',
            field: 'textModel',
            isPined: false,
            name: 'Model',
            sortName: 'model',
            hidden: false,
            width: 160,
            minWidth: 100,
            pdfWidth: 15,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Year',
            field: 'textYear',
            name: 'Year',
            sortName: 'year',
            isPined: false,
            hidden: false,
            width: 40,
            minWidth: 23,
            pdfWidth: 10,
            filter: '',
            isNumeric: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'color',
            title: 'Color',
            field: 'tableColor',
            isPined: false,
            name: '',
            sortName: 'colorName',
            headAlign: 'center',
            headIconStyle: {
                width: 18,
                height: 18,
                imgPath: 'assets/svg/truckassist-table/color-type.svg',
            },
            hidden: false,
            width: 40,
            minWidth: 40,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            colorTemplate: {
                value: 'doc.additionalData.color.value',
            },
            opacityIgnore: true,
            class: 'overflow-unset',
        },
        // {
        //     ngTemplate: 'textState',
        //     title: '%',
        //     field: 'textCommission',
        //     name: 'COM',
        //     sortName: 'commission',
        //     isPined: false,
        //     hidden: true,
        //     width: 88,
        //     minWidth: 88,
        //     pdfWidth: 15,
        //     filter: '',
        //     isNumeric: true,
        //     index: 11,
        //     sortable: true,
        //     isActionColumn: false,
        //     isSelectColumn: false,
        //     avatar: null,
        //     progress: null,
        //     hoverTemplate: null,
        //     filterable: true,
        //     disabled: false,
        //     export: true,
        //     resizable: true,
        //     linkField: null,
        //     empty: ['companyOwned', 'divisionFlag'],
        //     isProgress: true,
        // },
        {
            ngTemplate: 'text',
            title: 'Driver',
            field: 'tableDriver',
            isPined: false,
            name: 'Driver',
            sortName: 'driver',
            hidden: true,
            width: 160,
            minWidth: 130,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Trailer',
            field: 'tableTrailer',
            isPined: false,
            name: 'Trailer',
            sortName: 'trailer',
            hidden: true,
            width: 100,
            minWidth: 80,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Trailer Type',
            field: 'tableTrailerType',
            isPined: false,
            name: 'Trailer Type',
            sortName: 'trailerType',
            hidden: true,
            width: 100,
            minWidth: 80,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'OwnerDetailesType',
            field: 'tabelOwnerDetailesType',
            isPined: false,
            name: 'OwnerDetailesType',
            sortName: 'ownerType',
            hidden: true,
            width: 110,
            minWidth: 68,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'OwnerDetailesName',
            field: 'tabelOwnerDetailesName',
            isPined: false,
            name: 'OwnerDetailesName',
            sortName: 'ownerName',
            hidden: true,
            width: 200,
            minWidth: 150,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'OwnerDetailesEIN/SSN',
            field: 'tabelOwnerDetailesEinSsn',
            isPined: false,
            name: 'OwnerDetailesEIN/SSN',
            sortName: 'ownerEIN/SSN',
            hidden: true,
            width: 110,
            minWidth: 80,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Gross Weight',
            field: 'textGrossWeight',
            name: 'Gross Weight',
            isPined: false,
            hidden: true,
            width: 156,
            minWidth: 84,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Engine Model',
            field: 'tabelEngineModel',
            name: 'Engine Model',
            isPined: false,
            hidden: true,
            width: 180,
            minWidth: 140,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Oil Type',
            field: 'tabelOilType',
            name: 'Oil Type',
            isPined: false,
            hidden: true,
            width: 180,
            minWidth: 140,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Transmission Model',
            field: 'tabelTransmissionModel',
            name: 'Transmission Model',
            isPined: false,
            hidden: true,
            width: 156,
            minWidth: 84,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Transmission Shifter',
            field: 'tabelTransmissionShifter',
            name: 'Transmission Shifter',
            isPined: false,
            hidden: true,
            width: 84,
            minWidth: 70,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Transmission Ratio',
            field: 'tabelTransmissionRatio',
            name: 'Transmission Ratio',
            isPined: false,
            hidden: true,
            width: 46,
            minWidth: 46,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Tank',
            field: 'tabelTank',
            name: 'Tank',
            isPined: false,
            hidden: true,
            width: 50,
            minWidth: 50,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Axle',
            field: 'tabelAxle',
            name: 'Axle',
            isPined: false,
            hidden: true,
            width: 40,
            minWidth: 40,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Brakes',
            field: 'tabelBrakes',
            name: 'Brakes',
            isPined: false,
            hidden: true,
            width: 60,
            minWidth: 42,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Tire Size',
            field: 'tableTireSize',
            name: 'Tire Size',
            isPined: false,
            hidden: true,
            width: 82,
            minWidth: 82,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Wheels Material Front',
            field: 'tableWheelsMaterialFront',
            name: 'Wheels Material Front',
            isPined: false,
            hidden: true,
            width: 80,
            minWidth: 80,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Wheels Material Rear',
            field: 'tableWheelsMaterialRear',
            name: 'Wheels Material Rear',
            isPined: false,
            hidden: true,
            width: 80,
            minWidth: 80,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'AP Unit',
            field: 'tableAPUnit',
            name: 'AP Unit',
            isPined: false,
            hidden: true,
            width: 68,
            minWidth: 68,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Toll Device Transponder',
            field: 'tableTollDeviceTransponder',
            name: 'Toll Device Transponder',
            isPined: false,
            hidden: true,
            width: 150,
            minWidth: 80,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Toll Device No',
            field: 'tableTollDeviceNo',
            name: 'Toll Device No',
            isPined: false,
            hidden: true,
            width: 150,
            minWidth: 80,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Ins Policy',
            field: 'tableInsPolicy',
            name: 'Ins Policy',
            isPined: false,
            hidden: true,
            width: 126,
            minWidth: 82,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Mileage',
            field: 'tableMileage',
            name: 'Mileage',
            isPined: false,
            hidden: true,
            width: 90,
            minWidth: 82,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Licence Plate Detail Number',
            field: 'tableLicencePlateDetailNumber',
            name: 'Licence Plate Detail Number',
            sortName: 'licensePlate',
            isPined: false,
            hidden: true,
            width: 100,
            minWidth: 76,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: '',
            title: 'Licence Plate Detail ST',
            field: 'tableLicencePlateDetailST',
            name: 'Licence Plate Detail ST',
            isPined: false,
            hidden: true,
            width: 28,
            minWidth: 28,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: '',
            title: 'Licence Plate Detail Expiration',
            field: 'tableLicencePlateDetailExpiration',
            name: 'Licence Plate Detail Expiration',
            isPined: false,
            hidden: true,
            width: 130,
            minWidth: 87,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Fhwa Inspection Term',
            field: 'tableFhwaInspectionTerm',
            name: 'Fhwa Inspection Term',
            isPined: false,
            hidden: true,
            width: 108,
            minWidth: 87,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: '',
            title: 'Fhwa Inspection Expiration',
            field: 'tableFhwaInspectionExpiration',
            name: 'Fhwa Inspection Expiration',
            isPined: false,
            hidden: true,
            width: 130,
            minWidth: 87,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Title Number',
            field: 'tableTitleNumber',
            name: 'Title Number',
            isPined: false,
            hidden: true,
            width: 120,
            minWidth: 65,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Title ST',
            field: 'tableTitleST',
            name: 'Title ST',
            isPined: false,
            hidden: true,
            width: 28,
            minWidth: 28,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Title Issued',
            field: 'tableTitleIssued',
            name: 'Title Issued',
            isPined: false,
            hidden: true,
            width: 80,
            minWidth: 66,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Purchase Date',
            field: 'tablePurchaseDate',
            name: 'Purchase Date',
            isPined: false,
            hidden: true,
            width: 80,
            minWidth: 66,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Purchase Price',
            field: 'tablePurchasePrice',
            name: 'Purchase Price',
            isPined: false,
            hidden: true,
            width: 100,
            minWidth: 82,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Terminated',
            field: 'tableTerminated',
            name: 'Terminated',
            isPined: false,
            hidden: true,
            width: 100,
            minWidth: 66,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Added',
            field: 'tableAdded',
            name: 'Added',
            isPined: false,
            hidden: true,
            width: 80,
            minWidth: 66,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Edited',
            field: 'tableEdited',
            name: 'Edited',
            isPined: false,
            hidden: true,
            width: 80,
            minWidth: 66,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'note',
            title: 'Note',
            field: 'note',
            name: '',
            hidden: false,
            width: 40,
            minWidth: 40,
            pdfWidth: 15,
            filter: '',
            isNumeric: false,
            index: 12,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            hidden: false,
            width: 42,
            minWidth: 42,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 13,
            sortable: true,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}
