export function getTruckColumnDefinition() {
  return [
    {
      ngTemplate: 'checkbox',
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      width: 32,
      pdfWidth: 32,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: false,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'nameLink',
      title: 'Unit#',
      field: 'truckNumber',
      name: 'Unit#',
      sortName: 'truckNumber',
      hidden: false,
      width: 66,
      pdfWidth: 10,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: true,
      linkField: {
        routerLinkStart: '/trucks/edit/',
        routerLinkEnd: '/detail',
      },
    },
    {
      ngTemplate: 'text',
      title: 'Year',
      field: 'textYear',
      name: 'Year',
      sortName: 'year',
      hidden: false,
      width: 65,
      pdfWidth: 10,
      filter: '',
      isNumeric: true,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'text',
      title: 'Make',
      field: 'textMake',
      name: 'Make',
      sortName: 'make',
      hidden: false,
      width: 146,
      pdfWidth: 15,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      imageHover: {
        url: '../assets/img/svgs/truck/makers/',
        file: 'doc.additionalData.make.file',
      },
      class: 'make-icon',
    },
    {
      ngTemplate: 'text',
      title: 'Model',
      field: 'textModel',
      name: 'Model',
      sortName: 'model',
      hidden: false,
      width: 137,
      pdfWidth: 15,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'color',
      title: 'Color',
      field: 'color',
      name: '',
      sortName: 'colorName',
      headAlign: 'center',
      headIconStyle: {
        width: 18,
        height: 18,
        imgPath: 'assets/svg/truckassist-table/head-color.svg',
      },
      hidden: false,
      width: 54,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      colorTemplate: {
        value: 'doc.additionalData.color.value',
      },
      opacityIgnore: true,
      class: 'overflow-unset',
    },
    {
      ngTemplate: 'svg',
      title: 'Type',
      field: 'svgIcon',
      headAlign: 'center',
      name: 'Type',
      sortName: 'type',
      hidden: false,
      width: 83,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 6,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: false,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      imageHover: {
        url: 'assets/svg/truckassist-table/truck/',
        file: 'doc.additionalData.type.file',
        class: 'doc.additionalData.type.class',
      },
      class: 'type-icon',
    },
    {
      ngTemplate: 'text',
      title: 'VIN',
      field: 'vin',
      name: 'VIN',
      sortName: 'vin',
      hidden: false,
      width: 195,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 7,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Lic. Plate',
      field: 'truckLicensePlate',
      name: 'Lic. Plate',
      sortName: 'licensePlate',
      hidden: false,
      width: 119,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
      class: 'custom-font',
    },
    {
      ngTemplate: 'progress',
      title: 'Annual insp.',
      field: 'truckInspectionProgres',
      name: 'Annual insp.',
      sortName: 'licenseExpDate',
      hidden: false,
      width: 147,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: {
        start: '',
        end: 'doc.inspectionData[0].startDate',
      },
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'text',
      title: 'Owner',
      field: 'ownerName',
      name: 'Owner',
      sortName: 'ownerName',
      hidden: false,
      width: 240,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'text',
      title: 'Insurance Policy',
      field: 'truckInsurancePolicyNumber',
      name: 'Insurance Policy',
      hidden: true,
      width: 0,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'text',
      title: 'Axies',
      field: 'truckAxises',
      name: 'Axies',
      hidden: true,
      width: 0,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'text',
      title: 'Empty Weight',
      field: 'truckEmptyWeight',
      name: 'Empty Weight',
      hidden: true,
      width: 0,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'text',
      title: 'Engine Type',
      field: 'truckEngine',
      name: 'Engine Type',
      hidden: true,
      width: 0,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'text',
      title: 'Tire Size',
      field: 'truckTireSize',
      name: 'Tire Size',
      hidden: true,
      width: 0,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'text',
      title: 'Mileage',
      field: 'truckMileage',
      name: 'Mileage',
      hidden: true,
      width: 0,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'text',
      title: 'IPAS / EZPASS',
      field: 'truckIpasEzpass',
      name: 'IPAS / EZPASS',
      hidden: true,
      width: 0,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'text',
      title: '%',
      field: 'commission',
      name: 'Commission',
      sortName: 'commission',
      hidden: false,
      width: 57,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
      empty: ['companyOwned', 'divisionFlag'],
      isProgress: true,
    },
    {
      ngTemplate: 'attachments',
      title: '',
      field: 'additionalData.files',
      name: '',
      headIconStyle: {
        width: 19,
        height: 19,
        imgPath:
          'assets/svg/truckassist-table/attachment/attachemnt-regular-svgIcon.svg',
      },
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 16,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'note',
      title: '',
      field: 'doc.additionalData.note',
      name: '',
      hidden: false,
      width: 40,
      pdfWidth: 15,
      filter: '',
      isNumeric: false,
      index: 12,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: false,
    },
    {
      ngTemplate: 'actions',
      title: '',
      field: 'action',
      name: '',
      hidden: false,
      width: 40,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 13,
      sortable: true,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
  ];
}
