export function getTruckColumnDefinition() {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: 'Select',
            isPined: true,
            hidden: false,
            width: 32,
            pdfWidth: 32,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'nameLink',
            title: 'Unit#',
            field: 'truckNumber',
            name: 'Unit#',
            sortName: 'truckNumber',
            isPined: true,
            hidden: false,
            width: 66,
            minWidth: 120,
            pdfWidth: 10,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: true,
            export: true,
            resizable: true,
            link: {
                routerLinkStart: '/truck/',
                routerLinkEnd: '/details',
            },
        },
        {
            ngTemplate: 'text',
            title: 'Year',
            field: 'textYear',
            name: 'Year',
            sortName: 'year',
            isPined: false,
            hidden: false,
            width: 65,
            minWidth: 83,
            pdfWidth: 10,
            filter: '',
            isNumeric: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Make',
            field: 'textMake',
            name: 'Make',
            sortName: 'make',
            isPined: false,
            hidden: false,
            width: 146,
            minWidth: 100,
            pdfWidth: 15,
            filter: '',
            isNumeric: false,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            imageHover: {
                url: '../assets/img/svgs/truck/makers/',
                file: 'doc.additionalData.make.file',
            },
            class: 'make-icon',
        },
        {
            ngTemplate: 'text',
            title: 'Model',
            field: 'textModel',
            isPined: false,
            name: 'Model',
            sortName: 'model',
            hidden: false,
            width: 137,
            minWidth: 100,
            pdfWidth: 15,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'textState',
            title: '%',
            field: 'textCommission',
            name: 'COM',
            sortName: 'commission',
            isPined: false,
            hidden: false,
            width: 88,
            minWidth: 88,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
            empty: ['companyOwned', 'divisionFlag'],
            isProgress: true,
        },
        {
            ngTemplate: 'text',
            title: 'Owner',
            field: 'ownerName',
            isPined: false,
            name: 'Owner',
            sortName: 'ownerName',
            hidden: false,
            width: 240,
            minWidth: 129,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'color',
            title: 'Color',
            field: 'color',
            isPined: false,
            name: '',
            sortName: 'colorName',
            headAlign: 'center',
            headIconStyle: {
                width: 18,
                height: 18,
                imgPath: 'assets/svg/truckassist-table/color-type.svg',
            },
            hidden: false,
            width: 54,
            minWidth: 71,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            colorTemplate: {
                value: 'doc.additionalData.color.value',
            },
            opacityIgnore: true,
            class: 'overflow-unset',
        },
        {
            ngTemplate: 'svg',
            title: 'Type',
            field: 'truckTypeIcon',
            isPined: false,
            headAlign: 'center',
            name: 'Type',
            sortName: 'type',
            hidden: false,
            width: 83,
            minWidth: 83,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 6,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: false,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            svgUrl: 'assets/svg/truckassist-table/truck/',
            classField: 'truckTypeClass',
            svgDimensions: {
                width: 42,
                height: 18,
            },
            class: 'type-icon',
        },
        {
            ngTemplate: 'text',
            title: 'VIN',
            field: 'vin',
            name: 'VIN',
            sortName: 'vin',
            isPined: false,
            hidden: false,
            width: 195,
            minWidth: 92,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 7,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Lic. Plate',
            field: 'truckLicensePlate',
            name: 'Lic. Plate',
            sortName: 'licensePlate',
            isPined: false,
            hidden: false,
            width: 119,
            minWidth: 116,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
            class: 'custom-font',
        },
        {
            ngTemplate: 'progress',
            title: 'Annual insp.',
            field: 'truckInspectionProgres',
            name: 'Annual insp.',
            sortName: 'licenseExpDate',
            isPined: false,
            hidden: false,
            width: 147,
            minWidth: 101,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: '',
                end: 'doc.inspectionData[0].startDate',
            },
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Insurance Policy',
            field: 'truckInsurancePolicyNumber',
            name: 'Insurance Policy',
            isPined: false,
            hidden: true,
            width: 0,
            minWidth: 105,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Axies',
            field: 'truckAxises',
            name: 'Axies',
            isPined: false,
            hidden: true,
            width: 0,
            minWidth: 84,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Empty Weight',
            field: 'truckEmptyWeight',
            name: 'Empty Weight',
            isPined: false,
            hidden: true,
            width: 0,
            minWidth: 103,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Engine Type',
            field: 'truckEngine',
            name: 'Engine Type',
            isPined: false,
            hidden: true,
            width: 0,
            minWidth: 126,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Tire Size',
            field: 'truckTireSize',
            name: 'Tire Size',
            isPined: false,
            hidden: true,
            width: 0,
            minWidth: 97,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Mileage',
            field: 'truckMileage',
            name: 'Mileage',
            isPined: false,
            hidden: true,
            width: 0,
            minWidth: 100,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'IPAS / EZPASS',
            field: 'truckIpasEzpass',
            name: 'IPAS / EZPASS',
            isPined: false,
            hidden: true,
            width: 0,
            minWidth: 118,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Gross Weight',
            field: 'textGrossWeight',
            name: 'Gross Weight',
            isPined: false,
            hidden: true,
            width: 169,
            minWidth: 169,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Purchase Price',
            field: 'textPurchasePrice',
            name: 'Purchase Price',
            isPined: false,
            hidden: true,
            width: 100,
            minWidth: 100,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Purchase Date',
            field: 'textPurchaseDate',
            name: 'Purchase Date',
            isPined: false,
            hidden: true,
            width: 100,
            minWidth: 100,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'attachments',
            title: 'Attachments',
            field: 'additionalData.files',
            moveRight: true,
            name: '',
            headIconStyle: {
                width: 19,
                height: 19,
                imgPath:
                    'assets/svg/truckassist-table/attachment/attachemnt-regular-svgIcon.svg',
            },
            hidden: false,
            width: 20,
            minWidth: 20,
            filter: '',
            isNumeric: false,
            index: 16,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'note',
            title: 'Note',
            field: 'note',
            name: '',
            hidden: false,
            width: 40,
            minWidth: 40,
            pdfWidth: 15,
            filter: '',
            isNumeric: false,
            index: 12,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            hidden: false,
            width: 42,
            minWidth: 42,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 13,
            sortable: true,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}
