export function getUsersColumnDefinition() {
  return [
    {
      ngTemplate: 'user-checkbox',
      title: '',
      field: 'active',
      name: '',
      hidden: false,
      width: 28,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
      showUserCheckbox: true,
    },
    {
      ngTemplate: 'user-avatar',
      title: 'Name',
      field: 'userFullName',
      name: 'Name',
      hidden: false,
      width: 260,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: {
        src: 'doc.avatar.src',
      },
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: true,
      class: 'overflow-unset',
    },
    {
      ngTemplate: 'text',
      title: 'Dept.',
      field: 'textDept',
      name: 'Dept.',
      hidden: false,
      width: 120,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Office',
      field: 'textOffice',
      name: 'Office',
      hidden: false,
      width: 120,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Phone',
      field: 'textPhone',
      name: 'Phone',
      hidden: false,
      width: 120,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Ext.',
      field: 'textExt',
      name: 'Ext.',
      hidden: false,
      width: 120,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'text',
      title: 'Email',
      field: 'email',
      name: 'Email',
      hidden: false,
      width: 250,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'user-status',
      title: 'Status',
      field: 'userStatus',
      name: 'Status',
      headAlign: 'center',
      hidden: false,
      width: 100,
      filter: '',
      isNumeric: false,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      addFontToTableText: true,
    },
    {
      ngTemplate: 'semi-bold-text',
      title: 'Comm.',
      field: 'textComm',
      name: 'Comm.',
      fontWeight: '600',
      hidden: false,
      width: 100,
      filter: '',
      isNumeric: false,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      addFontToTableText: true,
    },
    {
      ngTemplate: 'semi-bold-text',
      title: 'Salary.',
      field: 'textSalary',
      name: 'Salary.',
      hidden: false,
      width: 100,
      filter: '',
      isNumeric: false,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      addFontToTableText: true,
    },
    {
      ngTemplate: 'note',
      title: '',
      field: 'doc.additionalData.note',
      name: '',
      hidden: false,
      moveRight: true,
      width: 40,
      pdfWidth: 15,
      filter: '',
      isNumeric: false,
      index: 12,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: false,
    },
    {
      ngTemplate: 'actions',
      title: '',
      field: 'action',
      name: '',
      hidden: false,
      width: 40,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 13,
      sortable: true,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
  ];
}
