export function getUsersColumnDefinition() {
   return [
      {
         ngTemplate: 'user-checkbox',
         title: 'Checkbox',
         field: 'active',
         name: '',
         hidden: false,
         width: 28,
         minWidth: 28,
         filter: '',
         isNumeric: false,
         index: 0,
         sortable: false,
         isActionColumn: true,
         isSelectColumn: true,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: false,
         resizable: false,
         showUserCheckbox: true,
      },
      {
         ngTemplate: 'user-avatar',
         title: 'Name',
         field: 'userAvatar',
         name: 'Name',
         hidden: false,
         width: 160,
         minWidth: 160,
         filter: '',
         isNumeric: false,
         index: 1,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         avatar: {
            src: 'doc.avatar.src',
         },
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: true,
         export: true,
         resizable: true,
         class: 'overflow-unset',
      },
      {
         ngTemplate: 'text',
         title: 'Department',
         field: 'userTableDept',
         name: 'Department',
         hidden: false,
         width: 120,
         minWidth: 120,
         filter: '',
         isNumeric: false,
         index: 2,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
         class: 'custom-font',
      },
      {
         ngTemplate: 'text',
         title: 'Office',
         field: 'userTableOffice',
         name: 'Office',
         hidden: false,
         width: 150,
         minWidth: 150,
         filter: '',
         isNumeric: false,
         index: 2,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
         class: 'custom-font',
      },
      {
         ngTemplate: 'text',
         title: 'Phone',
         field: 'userTablePhone',
         name: 'Phone',
         hidden: false,
         width: 150,
         minWidth: 150,
         filter: '',
         isNumeric: false,
         index: 3,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
         class: 'custom-font',
      },
      {
         ngTemplate: 'text',
         title: 'Ext.',
         field: 'uesrTableExt',
         name: 'Ext.',
         hidden: false,
         width: 80,
         minWidth: 80,
         filter: '',
         isNumeric: false,
         index: 3,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
         class: 'custom-font',
      },
      {
         ngTemplate: 'text',
         title: 'Email',
         field: 'email',
         name: 'Email',
         hidden: false,
         width: 150,
         minWidth: 150,
         filter: '',
         isNumeric: false,
         index: 4,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Hired',
         field: 'userTableHired',
         name: 'Hired',
         hidden: false,
         width: 80,
         minWidth: 80,
         filter: '',
         isNumeric: false,
         index: 4,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'text',
         title: 'Personal PH.',
         field: 'userTablePersonalPH',
         name: 'Personal PH.',
         hidden: false,
         width: 150,
         minWidth: 150,
         filter: '',
         isNumeric: false,
         index: 4,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
      },
      {
         ngTemplate: 'user-status',
         title: 'Status',
         field: 'userTableStatus',
         name: 'Status',
         headAlign: 'center',
         thSetCenter: true,
         setCenter: true,
         hidden: false,
         width: 100,
         minWidth: 100,
         filter: '',
         isNumeric: false,
         index: 5,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
         addFontToTableText: true,
      },
      {
         ngTemplate: 'semi-bold-text',
         title: 'Comm.',
         field: 'userTableCommission',
         name: 'Comm.',
         fontWeight: '600',
         hidden: false,
         width: 100,
         minWidth: 100,
         filter: '',
         isNumeric: false,
         index: 5,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
         addFontToTableText: true,
      },
      {
         ngTemplate: 'semi-bold-text',
         title: 'Salary.',
         field: 'userTableSalary',
         name: 'Salary.',
         hidden: false,
         width: 100,
         minWidth: 100,
         filter: '',
         isNumeric: false,
         index: 5,
         sortable: true,
         isActionColumn: false,
         isSelectColumn: false,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: true,
         addFontToTableText: true,
      },
      {
         ngTemplate: 'note',
         title: 'Note',
         field: 'note',
         name: '',
         hidden: false,
         moveRight: true,
         width: 40,
         minWidth: 40,
         pdfWidth: 15,
         filter: '',
         isNumeric: false,
         index: 12,
         sortable: false,
         isActionColumn: true,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: true,
         disabled: false,
         export: true,
         resizable: false,
         isAction: true,
      },
      {
         ngTemplate: 'actions',
         title: 'Actions',
         field: 'action',
         name: '',
         hidden: false,
         width: 42,
         minWidth: 42,
         pdfWidth: 15,
         filter: '',
         isNumeric: true,
         index: 13,
         sortable: true,
         isActionColumn: true,
         isSelectColumn: false,
         avatar: null,
         progress: null,
         hoverTemplate: null,
         filterable: false,
         disabled: false,
         export: false,
         resizable: false,
         isAction: true,
      },
   ];
}
