// Interface
import { ITableColumn } from '@shared/components/new-table/interfaces';

// Models
import { CompanyUserSortBy } from 'appcoretruckassist/model/companyUserSortBy';

export class UserTableColumnsConfig {
    static getTableColumns(): ITableColumn[] {
        return [
            UserTableColumnsConfig.selectColumn,
            UserTableColumnsConfig.editNameColumn,
            UserTableColumnsConfig.userNameColumn,
            UserTableColumnsConfig.departmentColumn,
            UserTableColumnsConfig.employeeDetailGroup,
            UserTableColumnsConfig.personalDetailGroup,
            UserTableColumnsConfig.statusColumn,
            UserTableColumnsConfig.activityColumn,
            UserTableColumnsConfig.bankDetailGroup,
            UserTableColumnsConfig.payrollDetailGroup,
            UserTableColumnsConfig.datesColumn,
        ];
    }

    static selectColumn: ITableColumn = {
        id: 1,
        key: 'select',
        label: '',
        pinned: 'left',
        width: 32,
        minWidth: 32,
        maxWidth: 200,
        isResizable: true,
        isDisabled: true,
        isChecked: true,
        hasSort: false,
    };

    static editNameColumn: ITableColumn = {
        key: 'edit',
        label: 'Edit',
        labelToolbar: 'Edit',
        width: 234,
        minWidth: 234,
        maxWidth: 234,
        isResizable: true,
        isChecked: true,
        isDisabled: true,
        hasSort: true,
        sortName: CompanyUserSortBy.Name,
    };

    static userNameColumn: ITableColumn = {
        id: 2,
        key: 'name',
        label: 'Name',
        labelToolbar: 'Name',
        pinned: 'left',
        width: 234,
        minWidth: 234,
        maxWidth: 234,
        isResizable: true,
        isChecked: true,
        isDisabled: true,
        hasSort: true,
        sortName: CompanyUserSortBy.Name,
    };

    static departmentColumn: ITableColumn = {
        id: 3,
        key: 'department',
        label: 'Department',
        labelToolbar: 'Department',
        pinned: null,
        width: 138,
        minWidth: 138,
        maxWidth: 138,
        isResizable: true,
        isChecked: true,
        hasSort: true,
        sortName: CompanyUserSortBy.Department,
    };

    static employeeDetailGroup: ITableColumn = {
        key: 'employeeDetailGroup',
        label: 'Employee',
        labelToolbar: 'Employee Detail',
        isChecked: true,
        pinned: null,
        columns: [
            {
                id: 4,
                key: 'employeeOffice',
                label: 'Office',
                labelToolbar: 'Office',
                width: 208,
                minWidth: 208,
                maxWidth: 208,
                isResizable: true,
                isChecked: true,
                hasSort: true,
                sortName: CompanyUserSortBy.EmployeeOffice,
            },
            {
                id: 5,
                key: 'employeePhone',
                label: 'Phone',
                labelToolbar: 'Phone',
                width: 188,
                minWidth: 188,
                maxWidth: 188,
                isResizable: true,
                isChecked: true,
                hasSort: true,
                sortName: CompanyUserSortBy.Phone,
            },
            {
                id: 6,
                key: 'employeeEmail',
                label: 'Email',
                labelToolbar: 'Email',
                width: 228,
                minWidth: 228,
                maxWidth: 228,
                isResizable: true,
                isChecked: true,
                hasSort: true,
                sortName: CompanyUserSortBy.Email,
            },
        ],
    };

    static personalDetailGroup: ITableColumn = {
        key: 'personalDetailGroup',
        label: 'Personal',
        labelToolbar: 'Personal Detail',
        pinned: null,
        isChecked: false,
        columns: [
            {
                id: 7,
                key: 'personalPhone',
                label: 'Phone',
                labelToolbar: 'Phone',
                width: 128,
                minWidth: 128,
                maxWidth: 128,
                isResizable: true,
                isChecked: false,
                hasSort: true,
                sortName: CompanyUserSortBy.PersonalPhone,
            },
            {
                id: 8,
                key: 'personalEmail',
                label: 'Email',
                labelToolbar: 'Email',
                width: 228,
                minWidth: 228,
                maxWidth: 228,
                isResizable: true,
                isChecked: false,
                hasSort: true,
                sortName: CompanyUserSortBy.PersonalEmail,
            },
            {
                id: 9,
                key: 'personalAddress',
                label: 'Address',
                labelToolbar: 'Address',
                width: 320,
                minWidth: 320,
                maxWidth: 320,
                isResizable: true,
                isChecked: false,
                hasSort: true,
                sortName: CompanyUserSortBy.Address,
            },
        ],
    };

    static statusColumn: ITableColumn = {
        key: 'statusColumnGroup',
        label: '',
        labelToolbar: '',
        pinned: null,
        isChecked: true,
        columns: [
            {
                id: 10,
                key: 'status',
                label: 'Status',
                labelToolbar: 'Status',
                width: 98,
                minWidth: 98,
                maxWidth: 98,
                isResizable: true,
                isChecked: true,
                hasSort: true,
                sortName: CompanyUserSortBy.Status,
            },
        ],
    };

    static activityColumn: ITableColumn = {
        key: 'activityColumnGroup',
        label: '',
        labelToolbar: '',
        pinned: null,
        isChecked: true,
        columns: [
            {
                id: 11,
                key: 'activity',
                label: 'Activity',
                labelToolbar: 'Activity',
                width: 118,
                minWidth: 118,
                maxWidth: 118,
                isResizable: true,
                isChecked: true,
                hasSort: true,
                sortName: CompanyUserSortBy.Activity,
            },
        ],
    };

    static bankDetailGroup: ITableColumn = {
        key: 'bankDetailGroup',
        label: 'Bank',
        labelToolbar: 'Bank Detail',
        isChecked: false,
        pinned: null,
        columns: [
            {
                id: 12,
                key: 'bankName',
                label: 'Name',
                labelToolbar: 'Name',
                width: 148,
                minWidth: 148,
                maxWidth: 148,
                isResizable: true,
                isChecked: false,
                hasSort: true,
                sortName: CompanyUserSortBy.BankName,
            },
            {
                id: 13,
                key: 'bankRouting',
                label: 'Routing',
                labelToolbar: 'Routing',
                width: 76,
                minWidth: 76,
                maxWidth: 76,
                isResizable: true,
                isChecked: false,
                hasSort: true,
                sortName: CompanyUserSortBy.BankRouting,
            },
            {
                id: 14,
                key: 'bankAccount',
                label: 'Account',
                labelToolbar: 'Account',
                width: 138,
                minWidth: 138,
                maxWidth: 138,
                isResizable: true,
                isChecked: false,
                hasSort: false,
            },
        ],
    };

    static payrollDetailGroup: ITableColumn = {
        key: 'payrollDetailGroup',
        label: 'Payroll',
        labelToolbar: 'Payroll Detail',
        isChecked: true,
        pinned: null,
        columns: [
            {
                id: 15,
                key: 'payrollType',
                label: 'Pay Type',
                labelToolbar: 'Pay Type',
                width: 108,
                minWidth: 108,
                maxWidth: 108,
                isResizable: true,
                isChecked: true,
                hasSort: true,
                sortName: CompanyUserSortBy.PayType,
            },
            {
                id: 16,
                key: 'payrollForm',
                label: 'Form',
                labelToolbar: 'Form',
                width: 68,
                minWidth: 68,
                maxWidth: 68,
                isResizable: true,
                isChecked: false,
                hasSort: true,
                sortName: CompanyUserSortBy.Form,
            },
            {
                id: 17,
                key: 'payrollComm',
                label: 'Comm',
                labelToolbar: 'Commission',
                width: 68,
                minWidth: 68,
                maxWidth: 68,
                isResizable: true,
                isChecked: true,
                hasSort: true,
                sortName: CompanyUserSortBy.Comm,
            },
            {
                id: 18,
                key: 'payrollSalary',
                label: 'Salary',
                labelToolbar: 'Salary',
                width: 101,
                minWidth: 101,
                maxWidth: 101,
                isResizable: true,
                isChecked: true,
                hasSort: true,
                sortName: CompanyUserSortBy.Salary,
            },
        ],
    };

    static datesColumn: ITableColumn = {
        key: 'datesColumnGroup',
        label: '',
        labelToolbar: '',
        pinned: null,
        isChecked: false,
        columns: [
            {
                id: 19,
                key: 'dateHired',
                label: 'Hired',
                labelToolbar: 'Date Hired',
                width: 88,
                minWidth: 88,
                maxWidth: 88,
                isResizable: true,
                isChecked: false,
                hasSort: true,
                sortName: CompanyUserSortBy.Hired,
            },
            {
                id: 20,
                key: 'dateDeactivated',
                label: 'Deact',
                labelToolbar: 'Date Deactivated',
                width: 88,
                minWidth: 88,
                maxWidth: 88,
                isResizable: true,
                isChecked: false,
                hasSort: true,
                sortName: CompanyUserSortBy.DateDeactivated,
            },
            {
                id: 21,
                key: 'dateAdded',
                label: 'Added',
                labelToolbar: 'Date Added',
                width: 88,
                minWidth: 88,
                maxWidth: 88,
                isResizable: true,
                isChecked: false,
                hasSort: true,
                sortName: CompanyUserSortBy.DateCreated,
            },
            {
                id: 22,
                key: 'dateEdited',
                label: 'Edited',
                labelToolbar: 'Date Edited',
                width: 88,
                minWidth: 88,
                maxWidth: 88,
                isResizable: true,
                isChecked: false,
                hasSort: true,
                sortName: CompanyUserSortBy.DateUpdated,
            },
        ],
    };
}
