export enum ChartValueLabelEnum {
    MILES = 'miles',
    EARNINGS = 'earnings',
    AVERAGE_RATE = 'averageRate',
    HIGHEST_RATE = 'highestRate',
    LOWEST_RARE = 'lowestRate',
    REVENUE = 'revenue',
    COUNT = 'count',
    MILES_PER_GALLON = 'milesPerGallon',
    COST_PER_GALLON = 'costPerGallon',
    FUEL_COST = 'fuelCost',
    COST = 'cost',
    GALLON = 'gallon',
    REPAIR_COST = 'repairCost',
    AVERAGE_PAY_PERIOD_DAYS = 'averagePayPeriod',
    PAY_TERM = 'payTerm',
    AVERAGE_PICKUP_TIME = 'avgPickupTime',
    AVERAGE_DELIVERY_TIME = 'avgDeliveryTime',
    MILEAGE_PERCENTAGE = 'mileagePercentage',
    REVENUE_PERCENTAGE = 'revenuePercentage',
    LOAD_PERCENTAGE = 'loadPercentage',
    COST_PERCENTAGE = 'costPercentage',
    VISIT_PERCENTAGE = 'visitPercentage'
}