export enum ESettingsFormControls {
    SOLO_LOADED_MILE = 'soloLoadedMile',
    SOLO_EMPTY_MILE = 'soloEmptyMile',
    PER_MILE_SOLO = 'perMileSolo',
    TEAM_EMPTY_MILE = 'teamEmptyMile',
    TEAM_LOADED_MILE = 'teamLoadedMile',
    PER_MILE_TEAM = 'perMileTeam',
    TEAM_PER_STOP = 'teamPerStop',
    BANK_CARDS = 'bankCards',
    BANK_ACCOUNTS = 'bankAccounts',
    LOGO = 'logo',
    LOADED_AND_EMPTY_SAME_RATE = 'loadedAndEmptySameRate',
    DEPARTMENT_CONTACTS = 'departmentContacts',
    SAFETY_PAY_PERIOD = 'safetyPayPeriod',
    DRIVER_OWNER_PAY_PERIOD = 'driveOwnerPayPeriod',
    DRIVER_OWNER_ENDING_IN = 'driverOwnerEndingIn',
    SOLO_PER_STOP = 'soloPerStop',
    DRIVER_SOLO_DEFAULT_COMMISSION = 'driverSoloDefaultCommission',
    DRIVER_TEAM_DEFAULT_COMMISSION = 'driverTeamDefaultCommission',
    OWNER_DEFAULT_COMMISSION = 'ownerDefaultCommission',
}