export enum FuelValuesStringEnum {
    TRUCK_ID = 'truckId',
    TRAILER_ID = 'trailerId',
    TOTAL = 'total',
    FUEL_STOP_STORE_ID = 'fuelStopStoreId',
    TRANSACTION_DATE = 'transactionDate',
    TRANSACTION_TIME = 'transactionTime',
    UPDATE = 'update',
    ITEM_ID = 'itemId',
    PRICE = 'price',
    QTY = 'qty',
    SUBTOTAL = 'subtotal',
    COMMON = 'common',
    TRUCKS = 'trucks',
    TRAILERS = 'trailers',
    DRIVER_FULL_NAME = 'driverFullName',
    DRIVER_ID = 'driverId',
    FUEL_ITEMS = 'fuelItems',
    MANUAL = 'Manual',
    INVOICE = 'invoice',
    CREATE = 'create',
    TRUCK = 'truck',
}
