export enum FuelValuesStringEnum {
    TRUCK_ID = 'truckId',
    TRANSACTION_DATE = 'transactionDate',
    UPDATE = 'update',
    ITEM_ID = 'itemId',
    PRICE = 'price',
    QTY = 'qty',
    SUBTOTAL = 'subtotal',
    COMMON = 'common',
    TRUCKS = 'trucks',
    DRIVER_FULL_NAME = 'driverFullName',
    FUEL_ITEMS = 'fuelItems',
    MANUAL = 'Manual',
    INVOICE = 'invoice',
    CREATE = 'create',
}