/* eslint-disable perfectionist/sort-classes */
export class UserStoreConstants {
    static COMPONENT_NAME_KEY = '[User Store]';
    public static ACTION_DISPATCH_LOAD_USER_LIST = `${this.COMPONENT_NAME_KEY} ACTION_DISPATCH_LOAD_USER_LIST`;
    public static ACTION_DISPATCH_LOAD_USER_LIST_SUCCESS = `${this.COMPONENT_NAME_KEY} ACTION_DISPATCH_LOAD_USER_LIST_SUCCESS`;
    public static ACTION_DISPATCH_LOAD_USER_LIST_ERROR = `${this.COMPONENT_NAME_KEY} ACTION_DISPATCH_LOAD_USER_LIST_ERROR`;
    public static ACTION_NEW_PAGE_LIST_SUCCESS = `${this.COMPONENT_NAME_KEY} ACTION_NEW_PAGE_LIST_SUCCESS`;
    public static ACTION_DISPATCH_USER_TYPE_CHANGE = `${this.COMPONENT_NAME_KEY} ACTION_DISPATCH_USER_TYPE_CHANGE`;
    public static ACTION_DISPATCH_VIEW_MODE_CHANGE = `${this.COMPONENT_NAME_KEY} ACTION_DISPATCH_VIEW_MODE_CHANGE`;
    public static ACTION_GET_NEW_PAGE_RESULTS = `${this.COMPONENT_NAME_KEY} ACTION_GET_NEW_PAGE_RESULTS`;
    public static ACTION_SORTING_CHANGE = `${this.COMPONENT_NAME_KEY} ACTION_SORTING_CHANGE`;

    //#region Search
    public static ACTION_SEARCH_FILTER_CHANGED = `${this.COMPONENT_NAME_KEY} ACTION_SEARCH_FILTER_CHANGED`;
    public static ACTION_FILTER_CHANGED = `${this.COMPONENT_NAME_KEY} ACTION_FILTER_CHANGED`;
    //#endregin
    //#region Selection
    public static ACTION_DISPATCH_ON_USER_SELECTION = `${this.COMPONENT_NAME_KEY} ACTION_DISPATCH_ON_USER_SELECTION`;
    public static ACTION_ON_SELECT_ALL = `${this.COMPONENT_NAME_KEY} ACTION_ON_SELECT_ALL`;
    //#endregion

    //#region Delete
    public static ACTION_DISPATCH_DELETE_USERS = `${this.COMPONENT_NAME_KEY} ACTION_DISPATCH_DELETE_USERS`;
    public static ACTION_DISPATCH_DELETE_USERS_SUCCESS = `${this.COMPONENT_NAME_KEY} ACTION_DISPATCH_DELETE_USERS_SUCCESS`;
    public static ACTION_DISPATCH_DELETE_USERS_ERROR = `${this.COMPONENT_NAME_KEY} ACTION_DISPATCH_DELETE_USERS_ERROR`;
    //#endregion

    //#region Status
    public static ACTION_DISPATCH_USER_STATUS_CHANGE = `${this.COMPONENT_NAME_KEY} ACTION_DISPATCH_USER_STATUS_CHANGE`;
    public static ACTION_DISPATCH_USER_STATUS_CHANGE_SUCCESS = `${this.COMPONENT_NAME_KEY} ACTION_DISPATCH_USER_STATUS_CHANGE_SUCCESS`;
    public static ACTION_DISPATCH_USER_STATUS_CHANGE_ERROR = `${this.COMPONENT_NAME_KEY} ACTION_DISPATCH_USER_STATUS_CHANGE_ERROR`;
    //#endregion

    //#region Toolbar actions
    public static ACTION_SET_TOOLBAR_DROPDOWN_MENU_COLUMNS_ACTIVE = `${this.COMPONENT_NAME_KEY} ACTION_SET_TOOLBAR_DROPDOWN_MENU_COLUMNS_ACTIVE`;
    public static ACTION_TOGGLE_COLUMN_VISIBILITY = `${this.COMPONENT_NAME_KEY} ACTION_TOGGLE_COLUMN_VISIBILITY`;

    //#endregion

    //#region  Modal
    public static ACTION_OPEN_USER_MODAL = `${this.COMPONENT_NAME_KEY} ACTION_OPEN_USER_MODAL`;
    //#endregion

    //#region Modal action
    public static ACTION_DISPATCH_UPDATE_USER = `${this.COMPONENT_NAME_KEY} ACTION_DISPATCH_UPDATE_USER`;
}
