export class UserStoreConstants {
    static COMPONENT_NAME_KEY = '[User Store]';
    public static ACTION_DISPATCH_LOAD_USER_LIST = `${this.COMPONENT_NAME_KEY} ACTION_DISPATCH_LOAD_USER_LIST`;
    public static ACTION_DISPATCH_LOAD_USER_LIST_SUCCESS = `${this.COMPONENT_NAME_KEY} ACTION_DISPATCH_LOAD_USER_LIST_SUCCESS`;
    public static ACTION_DISPATCH_LOAD_USER_LIST_ERROR = `${this.COMPONENT_NAME_KEY} ACTION_DISPATCH_LOAD_USER_LIST_ERROR`;
    public static ACTION_NEW_PAGE_LIST_SUCCESS = `${this.COMPONENT_NAME_KEY} ACTION_NEW_PAGE_LIST_SUCCESS`;
    public static ACTION_DISPATCH_USER_TYPE_CHANGE = `${this.COMPONENT_NAME_KEY} ACTION_DISPATCH_USER_TYPE_CHANGE`;
    public static ACTION_DISPATCH_VIEW_MODE_CHANGE = `${this.COMPONENT_NAME_KEY} ACTION_DISPATCH_VIEW_MODE_CHANGE`;
    public static ACTION_GET_NEW_PAGE_RESULTS = `${this.COMPONENT_NAME_KEY} ACTION_GET_NEW_PAGE_RESULTS`;
    //#region Search
    public static ACTION_SEARCH_FILTER_CHANGED = `${this.COMPONENT_NAME_KEY} ACTION_SEARCH_FILTER_CHANGED`;
    //#region
    //#region Selection
    public static ACTION_DISPATCH_ON_USER_SELECTION = `${this.COMPONENT_NAME_KEY} ACTION_DISPATCH_ON_USER_SELECTION`;
    public static ACTION_ON_SELECT_ALL = `${this.COMPONENT_NAME_KEY} ACTION_ON_SELECT_ALL`;
    //#endregion
}
