/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BrokerContactCommand } from './brokerContactCommand';
import { CreditType } from './creditType';


export interface ApiBrokerPostRequest { 
    Id?: number;
    BusinessName?: string;
    DbaName?: string;
    McNumber?: string;
    Ein?: string;
    Email?: string;
    Phone?: string;
    MainAddress_City?: string;
    MainAddress_State?: string;
    MainAddress_County?: string;
    MainAddress_Address?: string;
    MainAddress_Street?: string;
    MainAddress_StreetNumber?: string;
    MainAddress_Country?: string;
    MainAddress_ZipCode?: string;
    MainAddress_StateShortName?: string;
    MainAddress_AddressUnit?: string;
    BillingAddress_City?: string;
    BillingAddress_State?: string;
    BillingAddress_County?: string;
    BillingAddress_Address?: string;
    BillingAddress_Street?: string;
    BillingAddress_StreetNumber?: string;
    BillingAddress_Country?: string;
    BillingAddress_ZipCode?: string;
    BillingAddress_StateShortName?: string;
    BillingAddress_AddressUnit?: string;
    MainPoBox_City?: string;
    MainPoBox_State?: string;
    MainPoBox_ZipCode?: string;
    MainPoBox_PoBox?: string;
    BillingPoBox_City?: string;
    BillingPoBox_State?: string;
    BillingPoBox_ZipCode?: string;
    BillingPoBox_PoBox?: string;
    CreditLimit?: number;
    AvailableCredit?: number;
    CreditType?: CreditType;
    PayTerm?: number;
    Note?: string;
    IsCheckedBillingAddress?: boolean;
    Longitude?: number;
    Latitude?: number;
    BrokerContacts?: Array<BrokerContactCommand>;
    Files?: Array<Blob>;
    FilesForDeleteIds?: Array<number>;
}

