/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateTagCommand } from './createTagCommand';


export interface ApiCompanyDocumentsGetRequest { 
    Files?: Array<Blob>;
    Tags?: Array<CreateTagCommand>;
    FilesForDeleteIds?: Array<number>;
}

