/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PayrollBonusResponse } from './payrollBonusResponse';
import { EnumValue } from './enumValue';
import { MilesStopPayrollResponse } from './milesStopPayrollResponse';
import { DriverShortResponse } from './driverShortResponse';
import { PayrollDeductionResponse } from './payrollDeductionResponse';
import { PayrollPaymentResponse } from './payrollPaymentResponse';
import { PayrollCreditResponse } from './payrollCreditResponse';
import { PayrollDeadlineShortResponse } from './payrollDeadlineShortResponse';


export interface PayrollDriverMileageResponse { 
    id?: number;
    driver?: DriverShortResponse;
    payrollNumber?: string | null;
    period?: string;
    closedDate?: string | null;
    paidDate?: string | null;
    status?: EnumValue;
    mileageAmount?: number;
    mileageEmpty?: number;
    mileageLoaded?: number;
    emptyMilesPay?: number;
    loadedMilesPay?: number;
    milesPay?: number;
    bonusAmount?: number;
    salaryAmount?: number;
    creditAmount?: number;
    deductionAmount?: number;
    totalAmount?: number;
    stopsCount?: number;
    loadsCount?: number;
    additionalDays?: number | null;
    payDeadline?: PayrollDeadlineShortResponse;
    previousMilesStop?: MilesStopPayrollResponse;
    lastMilesStop?: MilesStopPayrollResponse;
    stops?: Array<MilesStopPayrollResponse> | null;
    bonuses?: Array<PayrollBonusResponse> | null;
    credits?: Array<PayrollCreditResponse> | null;
    deductions?: Array<PayrollDeductionResponse> | null;
    payments?: Array<PayrollPaymentResponse> | null;
    createdAt?: string;
    updatedAt?: string;
}

