/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkExperienceItemResponse } from './workExperienceItemResponse';


export interface WorkExperienceFeedbackResponse { 
    id?: number;
    haveWorkExperience?: boolean;
    applicantId?: number;
    workExperienceItems?: Array<WorkExperienceItemResponse> | null;
    reviewed?: boolean | null;
    approved?: boolean | null;
}

