export enum CurrencyValuesEnum {
    REVENUE = 'REVENUE',
    FUEL_COST = 'FUEL COST',
    REPAIR_COST = 'REPAIR COST',
    EXPENSES = 'EXPENSES',
    NET_INCOME = 'NET INCOME',
    PRICE_PER_GALLON = 'PRICE PER GALLON',
}