import { Pipe, PipeTransform } from '@angular/core';

@Pipe({ name: 'tableDoubleHeadText', standalone: true })
export class TableDoubleHeadTextPipe implements PipeTransform {
    transform(tableHeadTitle: string): string {
        return tableHeadTitle === 'PRIMARY '
            ? 'PHONE'
            : tableHeadTitle === 'PRIMARY'
            ? 'EMAIL'
            : tableHeadTitle === 'REPAIR SHOP'
            ? 'MVR'
            : tableHeadTitle === 'TYPE '
            ? 'OWNER'
            : tableHeadTitle === 'NAME '
            ? 'BANK'
            : tableHeadTitle === 'NUMBER '
            ? 'FUEL CARD'
            : tableHeadTitle === 'NUMBER'
            ? 'CDL'
            : tableHeadTitle === 'ISSUED'
            ? 'TEST'
            : tableHeadTitle === 'GENERAL'
            ? 'NOTIFICATION'
            : tableHeadTitle === 'TRUCK'
            ? 'ASSIGNED'
            : tableHeadTitle === 'NAME  '
            ? 'EMERGENCY CONTACT'
            : tableHeadTitle === ' NAME'
            ? 'OWNER'
            : tableHeadTitle === 'Registration Detail '
            ? 'LICENCE'
            : tableHeadTitle === 'FHWA Inspection '
            ? 'FHWA'
            : tableHeadTitle === 'DRIVER'
            ? 'ASSIGNED'
            : tableHeadTitle === 'GROSS'
            ? 'WEIGHT'
            : tableHeadTitle === 'TERM'
            ? 'FHWA'
            : tableHeadTitle === 'NUMBER  '
            ? 'LICENCE'
            : tableHeadTitle === ' NUMBER'
            ? 'TITLE'
            : tableHeadTitle === 'PRICE'
            ? 'PURCHASE'
            : tableHeadTitle === 'TYPE '
            ? 'FUEL'
            : tableHeadTitle === 'TRANSPONDER'
            ? 'TOLL DEVICE'
            : tableHeadTitle === 'FRONT'
            ? 'WHEEL COMP'
            : tableHeadTitle === ' MODEL'
            ? 'TRANSMISSION'
            : tableHeadTitle === 'MODEL '
            ? 'ENGINE'
            : tableHeadTitle === 'NAME   '
            ? 'REPAIR SHOP'
            : tableHeadTitle === 'NUMBER   '
            ? 'UNIT'
            : tableHeadTitle === 'DESCRIPTION'
            ? 'ITEM'
            : tableHeadTitle === 'PHYSICAL'
            ? 'ADDRESS'
            : tableHeadTitle === 'CREDIT LIMIT'
            ? 'BILLING'
            : tableHeadTitle === 'EMPTY'
            ? 'WEIGHT'
            : 'MVR';
    }
}
