/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BrokerContactResponse } from './brokerContactResponse';
import { EnumValue } from './enumValue';
import { PoBoxEntity } from './poBoxEntity';
import { AddressEntity } from './addressEntity';
import { ReviewResponse } from './reviewResponse';


export interface BrokerResponse { 
    id?: number;
    businessName?: string | null;
    dbaName?: string | null;
    mcNumber?: string | null;
    ein?: string | null;
    email?: string | null;
    phone?: string | null;
    mainAddress?: AddressEntity;
    billingAddress?: AddressEntity;
    mainPoBox?: PoBoxEntity;
    billingPoBox?: PoBoxEntity;
    creditType?: EnumValue;
    creditLimit?: number | null;
    availableCredit?: number | null;
    payTerm?: EnumValue;
    ban?: boolean;
    dnu?: boolean;
    note?: string | null;
    brokerContacts?: Array<BrokerContactResponse> | null;
    reviews?: Array<ReviewResponse> | null;
    status?: number;
    downRatingCount?: number;
    upRatingCount?: number;
    currentCompanyUserRating?: number | null;
    createdAt?: string;
}

