/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TestType } from './testType';


export interface CreateTestCommand { 
    driverId?: number;
    testReasonId?: number;
    testType?: TestType;
    testingDate?: string;
    note?: string | null;
}

