/**
 * Truckassist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShipperContactDepartmentResponse } from './shipperContactDepartmentResponse';


export interface ShipperContactResponse { 
    id?: number;
    fullName?: string | null;
    department?: ShipperContactDepartmentResponse;
    phone?: string | null;
    phoneExt?: string | null;
    email?: string | null;
}

