export enum BrokerDetailsStringEnum {
    BROKER_DETAIL = 'Broker Detail',
    GENERAL = 'general',
    LOAD = 'Load',
    LOAD_2 = 'load',
    REVENUE = 'Revenue',
    CONTACT = 'Contact',
    CONTACT_2 = 'contact',
    REVIEW = 'Review',
    REVIEW_2 = 'review',
    DATE = 'Date',
    CLOCK = 'clock',
    SEARCH = 'search',
    BROKER_USER = 'broker-user',
    HALF_CIRCLE = 'half-circle',
    LOCATION = 'location',
    DOLLAR = 'dolar',
    IC_PLUS = 'ic_plus',
    CHANGE_STATUS = 'change-status',
    DELETE_TRUCK_TEXT = 'Are you sure you want to delete truck(s)?',
    DELETE_DRIVER_TEXT = 'Are you sure you want to delete driver(s)?',
    PICKUP = 'Pickup',
    DELIVERY = 'Delivery',
}
