// models
import { MilesStopSortBy } from 'appcoretruckassist';

// interfaces
import { ITableColumn } from '@shared/components/new-table/interface';

export class MilesTableColumnsConfig {
    static columnsConfig: ITableColumn[] = [
        {
            id: 1,
            key: 'unit',
            label: 'Unit',
            labelToolbar: 'Unit No',
            width: 80,
            minWidth: 80,
            maxWidth: 200,
            isResizable: true,
            isDisabled: true,
            isChecked: true,
            hasSort: true,
            sortName: MilesStopSortBy.UnitNumber,
        },
        {
            id: 2,
            key: 'truckType',
            label: 'Type',
            labelToolbar: 'Type',
            width: 64,
            minWidth: 64,
            maxWidth: 200,
            isResizable: true,
            isChecked: true,
            hasSort: true,
            sortName: MilesStopSortBy.UnitType,
        },
        {
            key: 'stops',
            label: 'Stop',
            labelToolbar: 'Stops',
            columns: [
                {
                    id: 3,
                    key: 'stopsCount',
                    label: 'Count',
                    labelToolbar: 'Count',
                    width: 62,
                    minWidth: 62,
                    maxWidth: 200,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: MilesStopSortBy.Count,
                },
                {
                    id: 4,
                    key: 'stopsPickup',
                    label: 'PICKUP',
                    labelToolbar: 'Pickup',
                    width: 90,
                    minWidth: 90,
                    maxWidth: 200,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: MilesStopSortBy.Pickup,
                },
                {
                    id: 5,
                    key: 'stopsDelivery',
                    label: 'DELIVERY',
                    labelToolbar: 'Delivery',
                    width: 90,
                    minWidth: 90,
                    maxWidth: 200,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: MilesStopSortBy.Delivery,
                },
                {
                    id: 6,
                    key: 'fuelCount',
                    label: 'FUEL',
                    labelToolbar: 'Fuel',
                    width: 90,
                    minWidth: 90,
                    maxWidth: 200,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: MilesStopSortBy.Fuel,
                },
                {
                    id: 7,
                    key: 'parkingCount',
                    label: 'PARKING',
                    labelToolbar: 'Parking',
                    width: 90,
                    minWidth: 90,
                    maxWidth: 200,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: MilesStopSortBy.Parking,
                },
                {
                    id: 8,
                    key: 'deadHeadCount',
                    label: 'D-HEAD',
                    labelToolbar: 'Deadhead',
                    width: 90,
                    minWidth: 90,
                    maxWidth: 200,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: MilesStopSortBy.Deadhead,
                },
                {
                    id: 9,
                    key: 'repairCount',
                    label: 'REPAIR',
                    labelToolbar: 'Repair',
                    width: 90,
                    minWidth: 90,
                    maxWidth: 200,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: MilesStopSortBy.Repair,
                },
                {
                    id: 10,
                    key: 'towingCount',
                    label: 'TOWING',
                    labelToolbar: 'Towing',
                    width: 90,
                    minWidth: 90,
                    maxWidth: 200,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: MilesStopSortBy.Towing,
                },
            ],
        },
        {
            key: 'load',
            label: '',
            columns: [
                {
                    id: 11,
                    key: 'loadCount',
                    label: 'LOAD',
                    labelToolbar: 'Load',
                    width: 62,
                    minWidth: 62,
                    maxWidth: 200,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: MilesStopSortBy.Load,
                },
            ],
        },
        {
            key: 'fuel',
            label: 'Fuel',
            labelToolbar: 'Fuel',
            hasSort: false,
            columns: [
                {
                    id: 12,
                    key: 'fuelGalons',
                    label: 'GAL',
                    labelToolbar: 'Gallon',
                    width: 62,
                    minWidth: 62,
                    maxWidth: 200,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: MilesStopSortBy.FuelGallons,
                },
                {
                    id: 13,
                    key: 'fuelCost',
                    label: 'Cost',
                    labelToolbar: 'Cost',
                    width: 101,
                    minWidth: 101,
                    maxWidth: 200,
                    isResizable: true,
                    isChecked: false,
                    hasSort: true,
                    sortName: MilesStopSortBy.FuelCost,
                },
                {
                    id: 14,
                    key: 'fuelMpg',
                    label: 'MPG',
                    labelToolbar: 'MPG',
                    width: 64,
                    minWidth: 64,
                    maxWidth: 200,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
            ],
        },
        {
            key: 'miles',
            label: 'Miles',
            labelToolbar: 'Miles',
            hasSort: false,
            columns: [
                {
                    id: 15,
                    key: 'milesLoaded',
                    label: 'LOADED',
                    labelToolbar: 'Loaded',
                    width: 78,
                    minWidth: 78,
                    maxWidth: 200,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: MilesStopSortBy.LoadedMiles,
                },
                {
                    id: 16,
                    key: 'milesEmpty',
                    label: 'EMPTY',
                    labelToolbar: 'Empty',
                    width: 78,
                    minWidth: 78,
                    maxWidth: 200,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: MilesStopSortBy.EmptyMiles,
                },
                {
                    id: 17,
                    key: 'milesTotal',
                    label: 'TOTAL',
                    labelToolbar: 'Total',
                    width: 78,
                    minWidth: 78,
                    maxWidth: 200,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: MilesStopSortBy.TotalMiles,
                },
            ],
        },
        {
            key: 'revenueGroup',
            label: '',
            isAlignedRight: true,
            columns: [
                {
                    id: 18,
                    key: 'revenue',
                    label: 'revenue',
                    labelToolbar: 'Revenue',
                    width: 78,
                    minWidth: 78,
                    maxWidth: 200,
                    isResizable: true,
                    isChecked: false,
                    hasSort: true,
                    sortName: MilesStopSortBy.Revenue,
                },
            ],
        },
    ];
}
