// models
import { MilesStopSortBy } from 'appcoretruckassist';

// interfaces
import { ITableColumn } from '@shared/components/new-table/interfaces';

export class MilesTableColumnsConfig {
    static getTableColumns(): ITableColumn[] {
        return [
            MilesTableColumnsConfig.unitColumn,
            MilesTableColumnsConfig.truckTypeColumn,
            MilesTableColumnsConfig.stopsGroupColumn,
            MilesTableColumnsConfig.loadGroupColumn,
            MilesTableColumnsConfig.fuelGroupColumn,
            MilesTableColumnsConfig.milesGroupColumn,
            MilesTableColumnsConfig.revenueGroupColumn,
            MilesTableColumnsConfig.dateDeactivatedColumn,
        ];
    }

    static unitColumn: ITableColumn = {
        id: 1,
        key: 'unit',
        label: 'Unit',
        labelToolbar: 'Unit No',
        pinned: 'left',
        width: 88,
        minWidth: 88,
        maxWidth: 200,
        isResizable: true,
        isDisabled: true,
        isChecked: true,
        hasSort: true,
        sortName: MilesStopSortBy.UnitNumber,
    };

    static truckTypeColumn: ITableColumn = {
        id: 2,
        key: 'truckType',
        label: 'Type',
        labelToolbar: 'Type',
        pinned: null,
        width: 64,
        minWidth: 64,
        maxWidth: 200,
        isResizable: true,
        isChecked: true,
        hasSort: true,
        sortName: MilesStopSortBy.UnitType,
    };

    static stopsGroupColumn: ITableColumn = {
        key: 'stops',
        label: 'Stop',
        labelToolbar: 'Stops',
        pinned: null,
        isChecked: true,
        columns: [
            {
                id: 3,
                key: 'stopsCount',
                label: 'Count',
                labelToolbar: 'Count',
                width: 72,
                minWidth: 72,
                maxWidth: 200,
                isResizable: true,
                isChecked: true,
                hasSort: true,
                sortName: MilesStopSortBy.Count,
            },
            {
                id: 4,
                key: 'stopsPickup',
                label: 'PICKUP',
                labelToolbar: 'Pickup',
                width: 72,
                minWidth: 72,
                maxWidth: 200,
                isResizable: true,
                isChecked: true,
                hasSort: true,
                sortName: MilesStopSortBy.Pickup,
            },
            {
                id: 5,
                key: 'stopsDelivery',
                label: 'DELIVERY',
                labelToolbar: 'Delivery',
                width: 72,
                minWidth: 72,
                maxWidth: 200,
                isResizable: true,
                isChecked: true,
                hasSort: true,
                sortName: MilesStopSortBy.Delivery,
            },
            {
                id: 6,
                key: 'deadHeadCount',
                label: 'D-HEAD',
                labelToolbar: 'Deadhead',
                width: 72,
                minWidth: 72,
                maxWidth: 200,
                isResizable: true,
                isChecked: true,
                hasSort: true,
                sortName: MilesStopSortBy.Deadhead,
            },
            {
                id: 7,
                key: 'parkingCount',
                label: 'PARKING',
                labelToolbar: 'Parking',
                width: 72,
                minWidth: 72,
                maxWidth: 200,
                isResizable: true,
                isChecked: true,
                hasSort: true,
                sortName: MilesStopSortBy.Parking,
            },
            {
                id: 8,
                key: 'fuelCount',
                label: 'FUEL',
                labelToolbar: 'Fuel',
                width: 72,
                minWidth: 72,
                maxWidth: 200,
                isResizable: true,
                isChecked: true,
                hasSort: true,
                sortName: MilesStopSortBy.Fuel,
            },
            {
                id: 9,
                key: 'repairCount',
                label: 'REPAIR',
                labelToolbar: 'Repair',
                width: 72,
                minWidth: 72,
                maxWidth: 200,
                isResizable: true,
                isChecked: true,
                hasSort: true,
                sortName: MilesStopSortBy.Repair,
            },
            {
                id: 10,
                key: 'towingCount',
                label: 'TOWING',
                labelToolbar: 'Towing',
                width: 72,
                minWidth: 72,
                maxWidth: 200,
                isResizable: true,
                isChecked: true,
                hasSort: true,
                sortName: MilesStopSortBy.Towing,
            },
            {
                id: 11,
                key: 'splitCount',
                label: 'SPLIT',
                labelToolbar: 'Split',
                width: 72,
                minWidth: 72,
                maxWidth: 200,
                isResizable: true,
                isChecked: true,
                hasSort: true,
            },
        ],
    };

    static loadGroupColumn: ITableColumn = {
        key: 'load',
        label: 'Load',
        labelToolbar: 'Load',
        pinned: null,
        isChecked: true,
        columns: [
            {
                id: 12,
                key: 'loadCount',
                label: 'COUNT',
                labelToolbar: 'Count',
                width: 72,
                minWidth: 72,
                maxWidth: 200,
                isResizable: true,
                isChecked: true,
                hasSort: true,
                sortName: MilesStopSortBy.Load,
            },
            {
                id: 13,
                key: 'loadExtraStops',
                label: 'X-STOP',
                labelToolbar: 'Extra Stop',
                width: 72,
                minWidth: 72,
                maxWidth: 200,
                isResizable: true,
                isChecked: false,
                hasSort: true,
            },
            {
                id: 14,
                key: 'loadRatePerMile',
                label: 'RPM',
                labelToolbar: 'Rate per Mile',
                width: 80,
                minWidth: 80,
                maxWidth: 200,
                isResizable: true,
                isChecked: true,
                hasSort: true,
            },
        ],
    };

    static fuelGroupColumn: ITableColumn = {
        key: 'fuel',
        label: 'Fuel',
        labelToolbar: 'Fuel',
        pinned: null,
        isChecked: true,
        columns: [
            {
                id: 15,
                key: 'fuelGalons',
                label: 'GAL',
                labelToolbar: 'Gallon',
                width: 72,
                minWidth: 72,
                maxWidth: 200,
                isResizable: true,
                isChecked: true,
                hasSort: true,
                sortName: MilesStopSortBy.FuelGallons,
            },
            {
                id: 16,
                key: 'fuelCost',
                label: 'Cost',
                labelToolbar: 'Cost',
                width: 101,
                minWidth: 101,
                maxWidth: 200,
                isResizable: true,
                isChecked: false,
                hasSort: true,
                sortName: MilesStopSortBy.FuelCost,
            },
            {
                id: 17,
                key: 'fuelMpg',
                label: 'MPG',
                labelToolbar: 'Mile per Gallon',
                width: 64,
                minWidth: 64,
                maxWidth: 200,
                isResizable: true,
                isChecked: true,
                hasSort: true,
            },
        ],
    };

    static milesGroupColumn: ITableColumn = {
        key: 'miles',
        label: 'Miles',
        labelToolbar: 'Miles',
        pinned: null,
        isChecked: true,
        columns: [
            {
                id: 18,
                key: 'milesLoaded',
                label: 'LOADED',
                labelToolbar: 'Loaded',
                width: 78,
                minWidth: 78,
                maxWidth: 200,
                isResizable: true,
                isChecked: true,
                hasSort: true,
                sortName: MilesStopSortBy.LoadedMiles,
            },
            {
                id: 19,
                key: 'milesEmpty',
                label: 'EMPTY',
                labelToolbar: 'Empty',
                width: 78,
                minWidth: 78,
                maxWidth: 200,
                isResizable: true,
                isChecked: true,
                hasSort: true,
                sortName: MilesStopSortBy.EmptyMiles,
            },
            {
                id: 20,
                key: 'milesTotal',
                label: 'TOTAL',
                labelToolbar: 'Total',
                width: 78,
                minWidth: 78,
                maxWidth: 200,
                isResizable: true,
                isChecked: true,
                hasSort: true,
                sortName: MilesStopSortBy.TotalMiles,
            },
            {
                id: 21,
                key: 'milesPerLoad',
                label: 'MPL',
                labelToolbar: 'Mile per Load',
                width: 78,
                minWidth: 78,
                maxWidth: 200,
                isResizable: true,
                isChecked: false,
                hasSort: true,
            },
        ],
    };

    static revenueGroupColumn: ITableColumn = {
        key: 'revenueGroup',
        label: '',
        pinned: null,
        isAlignedRight: true,
        isChecked: true,
        columns: [
            {
                id: 22,
                key: 'revenue',
                label: 'revenue',
                labelToolbar: 'Revenue',
                width: 101,
                minWidth: 101,
                maxWidth: 200,
                isResizable: true,
                isChecked: true,
                hasSort: true,
                sortName: MilesStopSortBy.Revenue,
            },
        ],
    };

    static dateDeactivatedColumn: ITableColumn = {
        id: 23,
        key: 'dateDeactivated',
        label: 'DEACT',
        labelToolbar: 'Date Deactivated',
        width: 88,
        minWidth: 72,
        maxWidth: 88,
        isResizable: true,
        isChecked: false,
        hasSort: true,
        sortName: MilesStopSortBy.Deactivated,
    };
}
