export enum LoadModalStringEnum {
    MODAL_SIZE = 'modal-container-M',
    MODAL_CONTAINER_LOAD = 'modal-container-load',
    LOAD_TEMPLATE = 'load-template',
    LOAD = 'load',

    PICKUP = 'pickup',
    DELIVERY = 'delivery',
    EXTRA_STOP = 'extra-stop',

    PICKUP_2 = 'Pickup',
    DELIVERY_2 = 'Delivery',

    DRIVER_MESSAGE = 'driverMessage',
    NOTE = 'note',
    PICKUP_TIME_TO = 'pickupTimeTo',
    DELIVERY_TIME_TO = 'deliveryTimeTo',
    DATE_FROM = 'dateFrom',
    DATE_TO = 'dateTo',
    TIME_FROM = 'timeFrom',
    TIME_TO = 'timeTo',
    TEMPLATE_NAME = 'templateName',
    DISPATCH_ID = 'dispatchId',
    HAZARDOUS = 'hazardous',
    STOP_TYPE = 'stopType',
    STOP_ORDER = 'stopOrder',
    DRIVER_RATE = 'driverRate',
    ADJUSTED_RATE = 'adjustedRate',
    PICKUP_LEG_MILES = 'pickuplegMiles',
    BROKER_CONTACT_ID = 'brokerContactId',
    PICKUP_SHIPPER_CONTACT_ID = 'pickupShipperContactId',
    DELIVERY_SHIPPER_CONTACT_ID = 'deliveryShipperContactId',
    SHIPPER_CONTACT_ID = 'shipperContactId',
    ADDITIONAL_BILLINGS = 'additionalBillings',
    BILLING_DROPDOWN = 'billingDropdown',
    BILLING = 'billing',
    BILLING_VALUE = 'billingValue',
    PAYMENT = 'payment',
    PAYMENT_TYPE = 'pay-type',
    ADVANCE_PAY = 'advancePay',
    BASE_RATE = 'baseRate',
    LEG_MILES = 'legMiles',
    LEG_HOURS = 'legHours',
    LEG_MINUTES = 'legMinutes',
    DELIVERY_STOP_ORDER = 'deliveryStopOrder',
    LOAD_MILES = 'loadMiles',
    PICKUP_LEG_HOURS = 'pickuplegHours',
    PICKUP_LEG_MINUTES = 'pickuplegMinutes',
    PICKUP_LEG_COST = 'pickuplegCost',
    LEG_COST = 'legCost',
    DELIVERY_LEG_MILES = 'deliverylegMiles',
    DELIVERY_LEG_HOURS = 'deliverylegHours',
    DELIVERY_LEG_MINUTES = 'deliverylegMinutes',
    DELIVERY_LEG_COST = 'deliverylegCost',
    TOTAL_MILES = 'totalMiles',
    MAP = 'map',
    DISPATCHER_ID = 'dispatcherId',

    CANCEL = 'Cancel',
    CONFIRM = 'Confirm',
    DELETE = 'Delete',

    ADD = 'add',
    UPDATE = 'update',
    FILES = 'files',
    DELETE_2 = 'delete',
    TAG = 'tag',
    TAGS = 'tags',

    SAVE = 'save',
    SAVE_AND_ADD_NEW = 'save and add new',
    CONVERT_TO_TEMPLATE = 'convert-to-template',

    TRUCK = 'Truck',
    TRAILER = 'Trailer',
    DRIVER = 'Driver',
    DRIVER_PAY = 'Driver Pay',
    FLAT_RATE = 'Flat Rate',
    ADJUSTED = 'Adjusted',
    ADJUSTED_2 = 'adjusted',

    USER = 'user',
    DISPATCHER = 'dispatcher',
    COMPANY = 'company',
    GENERAL_COMMODITY = 'general-commodity',
    DISPATCHES = 'dispatches',
    BROKER = 'broker',
    BROKER_CONTACT = 'broker-contact',
    SHIPPER_PICKUP = 'shipper-pickup',
    SHIPPER_CONTACT_PICKUP = 'shipper-contact-pickup',
    SHIPPER_DELIVERY = 'shipper-delivery',
    SHIPPER_CONTACT_DELIVERY = 'shipper-contact-delivery',
    SHIPPER_EXTRA_STOPS = 'shipper-extra-stops',
    SHIPPER_CONTACT_EXTRA_STOPS = 'shipper-contact-extra-stops',
    EXTRA_STOP_SHIPPER = 'extra-stop-shipper',
    EXTRA_STOP_SHIPPER_CONTACT = 'extra-stop-shipper-contact',
    EXTRA_sTOPS_2 = 'extraStops',

    CONTACT = 'Contact',
    PHONE = 'Phone',
    SHIPPER = 'Shipper',
    CITY_STATE_ZIP = 'City, State, Zip',
    LOADS = 'Loads',

    TRUCK_REQ = 'truck-req',
    TRAILER_REQ = 'trailer-req',
    DOOR_TYPE = 'door-type',
    SUSPENSION = 'suspension',
    LENGTH = 'length',
    YEAR = 'year',

    LAYOVER = 'Layover',
    LUMPER = 'Lumper',
    FUEL_SURCHARGE = 'Fuel Surcharge',
    ESCORT = 'Escort',
    DETENTION = 'Detention',

    FTL_LTL = 'ftl-ltl',
    STOP_TAB = 'stop-tab',
    STOP_TIME_PICKUP = 'stop-time-pickup',
    STOP_TIME_DELIVERY = 'stop-time-delivery',
    EXTRA_STOPS_TIME = 'extra-stops-time',
    FIRST_PICKUP = 'first-pickup',
    FIRST_DELIVERY = 'first-delivery',
    EXTRA_STOPS = 'extra-stops',
    WORK_HOURS_2 = 'work hours',

    NUMBER_3 = '3',
    NUMBER_4 = '4',
    NUMBER_9 = '9',

    DROPDOWN_WIDTH_1 = 'w-col-608',
    DROPDOWN_WIDTH_2 = 'w-col-330',

    COLOR_1 = '26A690',
    COLOR_2 = 'EF5350',
    COLOR_3 = '3074D3',
    COLOR_4 = '#919191',
    COLOR_5 = '#26A690',
    COLOR_6 = '#EF5350',

    BROKER_OPEN_SVG = 'ic_load-broker-dnu-ban.svg',
    BROKER_CLOSED_SVG = 'ic_load-broker-closed-business.svg',
    HAZARDOUS_SVG = 'ic_hazardous.svg',

    WORK_HOURS = 'WORK HOURS',
    APPOINTMENT = 'APPOINTMENT',

    EMPTY_SPACE_STRING = ' ',
    EMPTY_STRING = '',

    LOAD_DISPATCHES_TTD = 'load-dispatches-ttd',
    NO_URL = 'no-url',
    COMMON = 'common',
    TRUCKS = 'trucks',
    TRAILERS = 'trailers',
    OPEN = 'open',
    LOAD_MODAL = 'load-modal',
    NEW = 'new',
    SMALL = 'small',
    UNLIMITED = 'Unlimited',
    LOAD_BROKER = 'load-broker',
    LOAD_BROKER_CONTACT = 'load-broker-contact',
    ADD_NEW = 'ADD NEW',
    EDIT_CONTACT = 'edit-contact',
    LOAD_SHIPPER = 'load-shipper',
    LOAD_SHIPPER_CONTACT = 'load-shipper-contact',
    OPEN_CLOSE = 'openClose',
    NAME = 'name',
    INPUT_DROPDOWN = 'Input Dropdown',
    TEXT = 'text',
    UPPERCASE = 'uppercase',
    CAPITALIZE = 'capitalize',
    CREATE = 'create',
}
