export function getPersonalInfoReviewFeedbackData() {
  return [
    {
      id: '',
      code: 'FLD',
      codeDescription: 'firstName lastName birthday',
      description: '',
      approved: null,
      type: 'STEP1',
    },
    {
      id: '',
      code: 'PE',
      codeDescription: 'personalPhone email',
      description: '',
      approved: null,
      type: 'STEP1',
    },
    {
      id: '',
      code: 'AU',
      codeDescription: 'address addressUnit',
      description: '',
      approved: null,
      type: 'STEP1',
    },
    {
      id: '',
      code: 'SB',
      codeDescription: 'ssn bankData',
      description: '',
      approved: null,
      type: 'STEP1',
    },
    {
      id: '',
      code: 'AR',
      codeDescription: 'accountNumber routingNumber',
      description: '',
      approved: null,
      type: 'STEP1',
    },
    {
      id: '',
      code: 'FIRST-QUESTION',
      codeDescription: 'legalWork',
      description: '',
      approved: null,
      type: 'STEP1',
    },
    {
      id: '',
      code: 'SECOND-QUESTION',
      codeDescription: 'anotherName',
      description: '',
      approved: null,
      type: 'STEP1',
    },
    {
      id: '',
      code: 'THIRD-QUESTION',
      codeDescription: 'inMilitary',
      description: '',
      approved: null,
      type: 'STEP1',
    },
    {
      id: '',
      code: 'FOURTH-QUESTION',
      codeDescription: 'felony',
      description: '',
      approved: null,
      type: 'STEP1',
    },
    {
      id: '',
      code: 'FIFTH-QUESTION',
      codeDescription: 'misdemeanor',
      description: '',
      approved: null,
      type: 'STEP1',
    },
    {
      id: '',
      code: 'SIXTH-QUESTION',
      codeDescription: 'drunkDriving',
      description: '',
      approved: null,
      type: 'STEP1',
    },
    {
      id: '',
      code: 'PREVIOUS-ADDRESSES-ONE',
      codeDescription: 'ONE',
      description: '',
      approved: null,
      type: 'STEP1',
    },
    {
      id: '',
      code: 'PREVIOUS-ADDRESSES-SECOND',
      codeDescription: 'SECOND',
      description: '',
      approved: null,
      type: 'STEP1',
    },
    {
      id: '',
      code: 'PREVIOUS-ADDRESSES-THIRD',
      codeDescription: 'THIRD',
      description: '',
      approved: null,
      type: 'STEP1',
    },
    {
      id: '',
      code: 'PREVIOUS-ADDRESSES-FOURTH',
      codeDescription: 'FOURTH',
      description: '',
      approved: null,
      type: 'STEP1',
    },
    {
      id: '',
      code: 'PREVIOUS-ADDRESSES-FIFTH',
      codeDescription: 'FIFTH',
      description: '',
      approved: null,
      type: 'STEP1',
    },
  ];
}
