export enum PayrollStringEnum {
    ADD_CREDIT = 'Add credit',
    EDIT_CREDIT = 'Edit credit',
    DRIVER = 'Driver',
    TRUCK = 'Truck',
    DRIVER_ID = 'driverId',
    TRUCK_ID = 'truckId',
    DATE = 'date',
    DESCRIPTION = 'description',
    AMOUNT = 'amount',
    EDIT = 'edit',
    CREATE = 'create',
    RECURRING = 'recurring',
    LIMITED = 'limited',
    LIMITED_NUMBER = 'limitedNumber',
    LIMITED_AMOUNT = 'limitedAmount',
    RECURRING_TYPE = 'reccuringType',
    SELECTED_DRIVER_ID = 'selected-driver-id',
    SELECTED_TRUCK_ID = 'selected-truck-id',
    SELECTED_TYPE_ID = 'selected-type-id',
    MODAL_DEDUCTION = 'MODAL_DEDUCTION',
    MODAL_CREDIT = 'MODAL_CREDIT',
    MODAL_BONUS = 'MODAL_BONUS',
    REPORT = 'report'
}
