export * from './account.service';
import { AccountService } from './account.service';
export * from './bank.service';
import { BankService } from './bank.service';
export * from './broker.service';
import { BrokerService } from './broker.service';
export * from './cdl.service';
import { CdlService } from './cdl.service';
export * from './comment.service';
import { CommentService } from './comment.service';
export * from './company.service';
import { CompanyService } from './company.service';
export * from './companyAccount.service';
import { CompanyAccountService } from './companyAccount.service';
export * from './companyAccountLabel.service';
import { CompanyAccountLabelService } from './companyAccountLabel.service';
export * from './companyContact.service';
import { CompanyContactService } from './companyContact.service';
export * from './companyContactLabel.service';
import { CompanyContactLabelService } from './companyContactLabel.service';
export * from './companyOffice.service';
import { CompanyOfficeService } from './companyOffice.service';
export * from './companyUser.service';
import { CompanyUserService } from './companyUser.service';
export * from './dispatch.service';
import { DispatchService } from './dispatch.service';
export * from './driver.service';
import { DriverService } from './driver.service';
export * from './employmentHistory.service';
import { EmploymentHistoryService } from './employmentHistory.service';
export * from './geolocation.service';
import { GeolocationService } from './geolocation.service';
export * from './inspection.service';
import { InspectionService } from './inspection.service';
export * from './load.service';
import { LoadService } from './load.service';
export * from './medical.service';
import { MedicalService } from './medical.service';
export * from './mvr.service';
import { MvrService } from './mvr.service';
export * from './owner.service';
import { OwnerService } from './owner.service';
export * from './ownerHistory.service';
import { OwnerHistoryService } from './ownerHistory.service';
export * from './parking.service';
import { ParkingService } from './parking.service';
export * from './ratingReview.service';
import { RatingReviewService } from './ratingReview.service';
export * from './registration.service';
import { RegistrationService } from './registration.service';
export * from './repair.service';
import { RepairService } from './repair.service';
export * from './repairShop.service';
import { RepairShopService } from './repairShop.service';
export * from './routing.service';
import { RoutingService } from './routing.service';
export * from './shipper.service';
import { ShipperService } from './shipper.service';
export * from './terminal.service';
import { TerminalService } from './terminal.service';
export * from './test.service';
import { TestService } from './test.service';
export * from './title.service';
import { TitleService } from './title.service';
export * from './todo.service';
import { TodoService } from './todo.service';
export * from './trailer.service';
import { TrailerService } from './trailer.service';
export * from './truck.service';
import { TruckService } from './truck.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './vinDecode.service';
import { VinDecodeService } from './vinDecode.service';
export const APIS = [AccountService, BankService, BrokerService, CdlService, CommentService, CompanyService, CompanyAccountService, CompanyAccountLabelService, CompanyContactService, CompanyContactLabelService, CompanyOfficeService, CompanyUserService, DispatchService, DriverService, EmploymentHistoryService, GeolocationService, InspectionService, LoadService, MedicalService, MvrService, OwnerService, OwnerHistoryService, ParkingService, RatingReviewService, RegistrationService, RepairService, RepairShopService, RoutingService, ShipperService, TerminalService, TestService, TitleService, TodoService, TrailerService, TruckService, UserService, VinDecodeService];
