export enum TaModalActionEnums {
    SAVE_AND_ADD_NEW = 'save and add new',
    SAVE = 'save',
    CLOSE = 'close',
    CLOSE_BUSINESS = 'Close Business',
    DELETE = 'delete',
    CONVERT_TO_TEMPLATE = 'convert-to-template',
    CONVERT_TO_LOAD = 'convert-to-load',
    MOVE_TO_THIS_PERIOD = 'move_to_this_period',
    UPDATE = 'update',
    DEACTIVATE = 'deactivate',
    FINISH_ORDER = 'finish-order',
    MOVE_TO_DNU = 'move-to-dnu',
    MOVE_TO_BFB = 'move-to-bfb',
}
