export class AccountStoreConstants {
    static COMPONENT_NAME_KEY = '[Account Store]';
    public static ACTION_DISPATCH_DELETE_ACCOUNTS = `${this.COMPONENT_NAME_KEY} ACTION_DISPATCH_DELETE_ACCOUNTS`;
    public static ACTION_DISPATCH_ON_ACCOUNT_SELECTION = `${this.COMPONENT_NAME_KEY} ACTION_DISPATCH_ON_ACCOUNT_SELECTION`;
    public static ACTION_DISPATCH_VIEW_MODE_CHANGE = `${this.COMPONENT_NAME_KEY} ACTION_DISPATCH_VIEW_MODE_CHANGE`;
    public static ACTION_GET_NEW_PAGE_RESULTS = `${this.COMPONENT_NAME_KEY} ACTION_GET_NEW_PAGE_RESULTS`;
    public static ACTION_OPEN_ACCOUNT_MODAL = `${this.COMPONENT_NAME_KEY} ACTION_OPEN_ACCOUNT_MODAL`;
    public static ACTION_SET_TOOLBAR_DROPDWN_MENU_COLUMNS_ACTIVE = `${this.COMPONENT_NAME_KEY} ACTION_SET_TOOLBAR_DROPDOWN_MENU_COLUMNS_ACTIVE`;
    static LOAD_ACCOUNTS = `${AccountStoreConstants.COMPONENT_NAME_KEY} Load Accounts`;
    static LOAD_ACCOUNTS_FAILURE = `${AccountStoreConstants.COMPONENT_NAME_KEY} Load Accounts Failure`;
    static LOAD_ACCOUNTS_SUCCESS = `${AccountStoreConstants.COMPONENT_NAME_KEY} Load Accounts Success`;
    public static ACTION_SORTING_CHANGE = `${this.COMPONENT_NAME_KEY} ACTION_SORTING_CHANGE`;
    public static ACTION_NEW_PAGE_LIST_SUCCESS = `${this.COMPONENT_NAME_KEY} ACTION_NEW_PAGE_LIST_SUCCESS`;

    //#region Search
    public static ACTION_SEARCH_FILTER_CHANGED = `${this.COMPONENT_NAME_KEY} ACTION_SEARCH_FILTER_CHANGED`;
    public static ACTION_FILTER_CHANGED = `${this.COMPONENT_NAME_KEY} ACTION_FILTER_CHANGED`;
    //#endregin

    //#region Selection
    public static ACTION_ON_SELECT_ALL = `${this.COMPONENT_NAME_KEY} ACTION_ON_SELECT_ALL`;
    //#endregion

    //#region Toolbar actions
    public static ACTION_SET_TOOLBAR_DROPDOWN_MENU_COLUMNS_ACTIVE = `${this.COMPONENT_NAME_KEY} ACTION_SET_TOOLBAR_DROPDOWN_MENU_COLUMNS_ACTIVE`;
    public static ACTION_TOGGLE_COLUMN_VISIBILITY = `${this.COMPONENT_NAME_KEY} ACTION_TOGGLE_COLUMN_VISIBILITY`;
    //#endregion
}
