import { TableBodyColumnsAvatar } from './table-body-columns-avatar.model';
import { TableBodyColumnsColorTemplate } from './table-body-columns-color-template.model';
import { TableBodyColumnsHeadIconStyle } from './table-body-columns-head-icon-style.model';
import { TableBodyColumnsImageHover } from './table-body-columns-image-hover.model';
import { TableBodyColumnsLink } from './table-body-columns-link.model';
import { TableBodyColumnsProgress } from './table-body-columns-progress.model';
import { TableBodyColumnsSvgDimensions } from './table-body-columns-svg-dimensions.model';

export interface TableBodyColumns {
    ngTemplate?: string;
    title?: string;
    field?: string;
    name?: string;
    hidden?: boolean;
    isNumeric?: boolean;
    sortable?: boolean;
    isActionColumn?: boolean;
    isSelectColumn?: boolean;
    filterable?: boolean;
    disabled?: boolean;
    export?: boolean;
    resizable?: boolean;
    filter?: string;
    width?: number;
    index?: number;
    fontWeight?: string;
    minWidth?: number;
    hoverTemplate?: any;
    thSetCenter?: boolean;
    sortName?: string;
    isPined?: boolean;
    groupName?: string;
    headAlign?: string;
    setCenter?: boolean;
    addFontToTableText?: boolean;
    moveRight?: boolean;
    isAction?: boolean;
    isDate?: boolean;
    class?: string;
    showQTY?: boolean;
    showFuelDropDown?: boolean;
    isComputed?: boolean;
    isRound?: boolean;
    showLabel?: boolean;
    link?: TableBodyColumnsLink | null;
    pdfWidth?: number;
    svg?: boolean;
    showPin?: boolean;
    password?: boolean;
    headIconStyle?: TableBodyColumnsHeadIconStyle | null;
    svgUrl?: string;
    classField?: string;
    fieldPercentage?: string;
    svgDimensions?: TableBodyColumnsSvgDimensions | null;
    objectIn?: boolean;
    specialColumn?: boolean;
    navigateTo?: boolean;
    opacityIgnore?: boolean;
    imageHover?: TableBodyColumnsImageHover | null;
    linkField?: TableBodyColumnsLink | boolean;
    colorTemplate?: TableBodyColumnsColorTemplate | boolean;
    avatar?: TableBodyColumnsAvatar | boolean;
    progress?: TableBodyColumnsProgress | null;
}
