// svg routes
import { AccountingFuelColumnSvgRoutes } from "@shared/utils/svg-routes";

export function getFuelTransactionColumnDefinition() {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: 'Select',
            hidden: false,
            width: 40,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'invoice',
            title: 'Invoice No',
            field: 'loadInvoice',
            name: 'Invoice No',
            sortName: 'invoice',
            hidden: false,
            width: 120,
            minWidth: 120,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            link: {
                routerLinkStart: '/dashboard'
            }
        },
        {
            ngTemplate: 'text',
            title: 'Date & Time',
            field: 'tableTransactionDate',
            name: 'Date',
            sortName: 'transactionDate',
            hidden: false,
            width: 140,
            minWidth: 140,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Truck',
            field: 'tableTruckNumber',
            name: 'Truck',
            sortName: 'truckNumber',
            hidden: false,
            width: 120,
            minWidth: 120,
            filter: '',
            isNumeric: false,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'avatar',
            title: 'Driver',
            field: 'tableDriverName',
            name: 'Driver',
            sortName: 'Driver',
            hidden: false,
            isPined: false,
            width: 234,
            minWidth: 234,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: {
                src: 'additionalData.avatar.src',
            },
            link: {
                routerLinkStart: '/list/driver/',
                routerLinkEnd: '/details',
            },
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: true,
            export: true,
            resizable: true,
            class: 'overflow-unset',
        },
        {
            ngTemplate: 'text',
            title: 'NUMBER',
            field: 'tableFuelCardNumber',
            name: 'Card Number',
            tableHeadTitle: 'Card Number',
            sortName: 'cardNumber',
            hidden: false,
            width: 120,
            minWidth: 120,
            filter: '',
            isNumeric: false,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'NAME',
            field: 'tableFuelStopName',
            name: 'Fuel Stop Name',
            sortName: 'name',
            hidden: false,
            width: 146,
            minWidth: 146,
            filter: '',
            isNumeric: false,
            index: 6,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Location',
            field: 'tableLocation',
            name: 'Location',
            sortName: 'location',
            hidden: false,
            width: 215,
            minWidth: 215,
            filter: '',
            isNumeric: false,
            index: 7,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'description',
            title: 'DESCRIPTION',
            field: 'descriptionItems',
            name: 'Description',
            sortName: 'description',
            isPined: false,
            hidden: false,
            width: 300,
            minWidth: 300,
            filter: '',
            isNumeric: false,
            index: 8,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: true,
            export: true,
            resizable: true,
            objectIn: true,
        },
        {
            ngTemplate: 'text',
            title: 'Gal',
            field: 'tableQTY',
            name: 'Gal',
            sortName: 'qty',
            hidden: false,
            width: 86,
            minWidth: 86,
            filter: '',
            isNumeric: false,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'ppg',
            title: 'PPG',
            field: 'tablePPG',
            name: 'PPG',
            sortName: 'ppg',
            groupName: 'Item Detail ',
            hidden: false,
            width: 86,
            minWidth: 86,
            filter: '',
            isNumeric: false,
            index: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'total',
            title: 'Cost',
            field: 'tableTotal',
            name: 'Cost',
            sortName: 'total',
            groupName: 'Item Detail ',
            hidden: false,
            width: 100,
            minWidth: 100,
            filter: '',
            isNumeric: false,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'attachments',
            title: 'Attachments',
            field: 'tableAttachments',
            moveRight: true,
            name: '',
            hidden: false,
            width: 46,
            minWidth: 46,
            filter: '',
            isNumeric: false,
            index: 12,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            hidden: false,
            width: 26,
            minWidth: 26,
            headIconStyle: {
                width: 22,
                height: 6,
                imgPath: '',
            },
            filter: '',
            isNumeric: false,
            index: 13,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}

export function getFuelStopColumnDefinition() {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: 'Select',
            hidden: false,
            width: 40,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isPined: true
        },
        {
            ngTemplate: 'text',
            title: 'Name',
            field: 'tableName',
            name: 'Name',
            sortName: 'name',
            hidden: false,
            width: 145,
            minWidth: 145,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            isPined: true
        },
        {
            ngTemplate: 'text',
            title: 'Phone',
            field: 'phone',
            name: 'Phone',
            sortName: 'phone',
            hidden: false,
            width: 127,
            minWidth: 127,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Fax',
            field: 'fax',
            name: 'Fax',
            sortName: 'fax',
            hidden: false,
            width: 120,
            minWidth: 120,
            filter: '',
            isNumeric: false,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Address',
            field: 'tableAddress',
            name: 'Address',
            sortName: 'address',
            hidden: false,
            width: 400,
            minWidth: 400,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Used',
            field: 'tableUsed',
            name: 'Used',
            sortName: 'used',
            hidden: false,
            width: 91,
            minWidth: 91,
            filter: '',
            isNumeric: false,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Price Range',
            field: 'tablePriceRange',
            name: 'PriceRange',
            sortName: 'cost',
            hidden: false,
            width: 120,
            minWidth: 120,
            filter: '',
            isNumeric: false,
            index: 6,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progress-range',
            title: 'Last',
            field: 'tableLast',
            name: 'Last',
            sortName: 'last',
            hidden: false,
            width: 90,
            minWidth: 90,
            filter: '',
            isNumeric: false,
            index: 7,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true
        },
        {
            ngTemplate: 'text',
            title: 'Last Visit',
            field: 'tableLastVisit',
            name: 'Last Visit',
            sortName: 'last',
            hidden: false,
            width: 115,
            minWidth: 115,
            filter: '',
            isNumeric: false,
            index: 8,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'total',
            title: 'Expense',
            field: 'tableExpense',
            name: 'Expense',
            sortName: 'cost',
            hidden: false,
            width: 92,
            minWidth: 92,
            filter: '',
            isNumeric: false,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true
        },
        {
            ngTemplate: 'favorite',
            title: 'Favorite',
            field: 'isFavorite',
            name: '',
            hidden: false,
            width: 25,
            minWidth: 25,
            filter: '',
            isNumeric: false,
            index: 10,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'note',
            title: 'Note',
            field: 'note',
            name: '',
            hidden: false,
            width: 35,
            minWidth: 35,
            filter: '',
            isNumeric: false,
            index: 11,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: AccountingFuelColumnSvgRoutes.ICON_NOTE,
            },
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            hidden: false,
            width: 30,
            minWidth: 30,
            filter: '',
            isNumeric: false,
            index: 12,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}
