export function getToolsContactsColumnDefinition() {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: 'Select',
            isComputed: true,
            hidden: false,
            isPined: true,
            width: 32,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'avatar',
            title: 'Name',
            field: 'name',
            name: 'Name',
            sortName: 'name',
            isPined: true,
            isComputed: false,
            hidden: false,
            width: 129,
            minWidth: 129,
            filter: '',
            isNumeric: false,
            isRound: true,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: true,
            export: true,
            resizable: true,
            link: {
                doesNotHaveRout: true,
                routerLinkStart: '/list/contact/',
                routerLinkEnd: '/details',
            },
        },
        {
            ngTemplate: 'text',
            title: 'Company',
            field: 'company',
            name: 'Company',
            sortName: 'company',
            isPined: false,
            isComputed: false,
            hidden: false,
            width: 238,
            minWidth: 238,
            filter: '',
            isNumeric: false,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Primary ',
            field: 'phone',
            name: 'PHONE',
            sortName: 'phone',
            groupName: 'Phone',
            isPined: false,
            isComputed: false,
            hidden: false,
            width: 210,
            minWidth: 210,
            filter: '',
            isNumeric: true,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Second',
            field: 'phoneSecond',
            name: 'Second',
            sortName: 'phone',
            groupName: 'Phone',
            isPined: false,
            isComputed: false,
            hidden: true,
            width: 210,
            minWidth: 210,
            filter: '',
            isNumeric: true,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Third',
            field: 'phoneThird',
            groupName: 'Phone',
            name: 'Third',
            sortName: 'phone',
            isPined: false,
            isComputed: false,
            hidden: true,
            width: 210,
            minWidth: 210,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Primary',
            field: 'email',
            name: 'EMAIL',
            isPined: false,
            sortName: 'email',
            groupName: 'Email',
            isComputed: false,
            hidden: false,
            width: 250,
            minWidth: 250,
            filter: '',
            isNumeric: false,
            index: 6,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            imageHover: null,
        },
        {
            ngTemplate: 'text',
            title: 'Second ',
            field: 'emailSecond',
            name: 'Second',
            isPined: false,
            sortName: 'email',
            groupName: 'Email',
            isComputed: false,
            hidden: true,
            width: 250,
            minWidth: 250,
            filter: '',
            isNumeric: false,
            index: 7,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            imageHover: null,
        },
        {
            ngTemplate: 'text',
            title: 'Address',
            field: 'textAddress',
            name: 'Address',
            isPined: false,
            sortName: 'address',
            isComputed: false,
            hidden: false,
            width: 320,
            minWidth: 320,
            filter: '',
            isNumeric: false,
            index: 8,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'label',
            title: 'Label',
            field: 'lable',
            name: 'Label',
            sortName: 'labelName',
            isComputed: false,
            hidden: false,
            isPined: false,
            width: 180,
            minWidth: 180,
            filter: '',
            isNumeric: true,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: false,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            imageHover: null,
            showLabel: true,
        },
        {
            ngTemplate: 'shared',
            title: 'Shared',
            field: 'textShared',
            name: 'Shared',
            isComputed: false,
            hidden: false,
            isPined: false,
            width: 108,
            minWidth: 108,
            filter: '',
            isNumeric: true,
            index: 10,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: false,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            imageHover: null,
            showLabel: true,
        },
        {
            ngTemplate: 'text',
            title: 'Added',
            field: 'added',
            name: 'Date Added',
            sortName: 'added',
            isPined: false,
            isComputed: false,
            hidden: true,
            width: 88,
            minWidth: 88,
            filter: '',
            isNumeric: false,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Edited',
            field: 'edited',
            name: 'Date Edited',
            sortName: 'edited',
            isPined: false,
            isComputed: false,
            hidden: true,
            width: 88,
            minWidth: 88,
            filter: '',
            isNumeric: false,
            index: 12,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'note',
            title: 'Note',
            field: 'note',
            name: '',
            moveRight: true,
            hidden: false,
            width: 26,
            minWidth: 26,
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: 'assets/svg/truckassist-table/note/Note.svg',
            },
            filter: '',
            isNumeric: false,
            index: 13,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: true,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            hidden: false,
            width: 26,
            minWidth: 26,
            headIconStyle: {
                width: 22,
                height: 6,
                imgPath: '',
            },
            filter: '',
            isNumeric: true,
            index: 14,
            sortable: true,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: true,
            isAction: true,
        },
    ];
}
