// Customer Broker COLUMN DEFINITION
export function getBrokerColumnDefinition() {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: 'Select',
            hidden: false,
            width: 32,
            filter: '',
            isPined: true,
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'customer-name',
            title: 'Name',
            field: 'businessName',
            name: 'Business Name',
            sortName: 'businessname',
            hidden: false,
            isPined: true,
            width: 220,
            minWidth: 220,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            link: {
                routerLinkStart: '/list/customer/',
                routerLinkEnd: '/broker-details',
            },
        },
        {
            ngTemplate: 'text',
            title: 'DBA Name',
            field: 'dbaName',
            name: 'DBA Name',
            sortName: 'dbaname',
            hidden: true,
            isPined: false,
            width: 238,
            minWidth: 238,
            filter: '',
            isNumeric: false,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'EIN',
            field: 'ein',
            name: 'EIN',
            sortName: 'ein',
            isPined: false,
            hidden: true,
            width: 118,
            minWidth: 118,
            filter: '',
            isNumeric: false,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'MC/FF',
            field: 'mcNumber',
            name: 'MC/FF',
            sortName: 'mc',
            isPined: false,
            hidden: true,
            width: 72,
            minWidth: 72,
            filter: '',
            isNumeric: false,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Phone',
            field: 'phone',
            name: 'Phone',
            sortName: 'phone',
            hidden: false,
            isPined: false,
            width: 128,
            minWidth: 128,
            filter: '',
            isNumeric: true,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Email',
            field: 'email',
            name: 'Email',
            isPined: false,
            sortName: 'email',
            hidden: false,
            width: 228,
            minWidth: 228,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Physical',
            field: 'tableAddressPhysical',
            name: 'Physical',
            sortName: 'address',
            groupName: 'Address ',
            hidden: false,
            isPined: false,
            width: 320,
            minWidth: 320,
            filter: '',
            isNumeric: false,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Billing',
            field: 'tableAddressBilling',
            name: 'Billing',
            sortName: 'billingAddress',
            groupName: 'Address ',
            hidden: true,
            isPined: false,
            width: 320,
            minWidth: 320,
            filter: '',
            isNumeric: false,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Credit Limit',
            field: 'tablePaymentDetailCreditLimit',
            name: 'Credit Limit',
            groupName: 'Billing ',
            sortName: 'tablePaymentDetailCreditLimit',
            hidden: true,
            isPined: false,
            width: 101,
            minWidth: 101,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Term',
            field: 'tablePaymentDetailTerm',
            name: 'Pay Term',
            groupName: 'Billing ',
            sortName: 'term',
            hidden: true,
            isPined: false,
            width: 62,
            minWidth: 62,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        // {
        //     ngTemplate: 'text',
        //     title: 'DTP',
        //     field: 'tablePaymentDetailDTP',
        //     name: 'DTP',
        //     groupName: 'Billing ',
        //     sortName: 'dtp',
        //     hidden: true,
        //     isPined: false,
        //     width: 80,
        //     minWidth: 64,
        //     pdfWidth: 15,
        //     filter: '',
        //     isNumeric: true,
        //     index: 11,
        //     sortable: true,
        //     isActionColumn: false,
        //     isSelectColumn: false,
        //     avatar: null,
        //     hoverTemplate: null,
        //     filterable: true,
        //     disabled: false,
        //     export: true,
        //     resizable: true,
        //     linkField: null,
        // },
        {
            ngTemplate: 'progress',
            //ngTemplate: 'text',
            title: 'Avail Credit',
            field: 'tablePaymentDetailAvailCredit',
            name: 'Available Credit',
            sortName: 'licenseExpDate',
            groupName: 'Billing ',
            hidden: true,
            isPined: false,
            width: 150,
            minWidth: 150,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: '',
                end: 'doc.inspectionData[0].startDate',
            },
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'inv-ageing',
            title: 'Invoice Ageing',
            field: 'tablePaymentDetailInvAgeing',
            name: 'Invoice Ageing',
            sortName: 'invAgeing',
            groupName: 'Billing ',
            hidden: true,
            isPined: false,
            width: 280,
            minWidth: 280,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Loads',
            field: 'tableLoads',
            name: 'Loads',
            sortName: 'load',
            isPined: false,
            hidden: false,
            width: 62,
            minWidth: 62,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Miles',
            field: 'tableMiles',
            name: 'Miles',
            sortName: 'miles',
            isPined: false,
            hidden: true,
            width: 78,
            minWidth: 78,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'PPM',
            field: 'tablePPM',
            name: 'PPM',
            sortName: 'ppm',
            isPined: false,
            hidden: true,
            width: 80,
            minWidth: 80,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Revenue',
            field: 'tableRevenue',
            name: 'Revenue',
            sortName: 'revenue',
            isPined: false,
            hidden: false,
            width: 101,
            minWidth: 101,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'rating',
            title: 'Rating & Review',
            field: 'tableRaiting',
            name: 'Rating & Review',
            sortName: 'rating',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: false,
            index: 7,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            svg: true,
            showPin: false,
            class: 'overflow-unset',
        },
        {
            ngTemplate: 'contact',
            title: 'Contact',
            field: 'tableContact',
            name: 'Contact',
            sortName: 'contact',
            hidden: false,
            isPined: false,
            width: 56,
            minWidth: 56,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath:
                    'assets/svg/truckassist-table/customer/contact-column-avatar-select-row.svg',
            },
        },
        {
            ngTemplate: 'text',
            title: 'Added',
            field: 'tableAdded',
            name: 'Added',
            sortName: 'added',
            hidden: true,
            isPined: false,
            width: 88,
            minWidth: 88,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Edited',
            field: 'tableEdited',
            name: 'Edited',
            sortName: 'edited',
            hidden: true,
            isPined: false,
            width: 88,
            minWidth: 88,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'note',
            title: 'Note',
            field: 'note',
            name: '',
            hidden: false,
            width: 40,
            minWidth: 40,
            filter: '',
            isNumeric: false,
            index: 17,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            hidden: false,
            width: 42,
            minWidth: 42,
            filter: '',
            isNumeric: false,
            index: 18,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}

// Customer Shipper COLUMN DEFINITION
export function getShipperColumnDefinition() {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: 'Select',
            hidden: false,
            isPined: true,
            width: 32,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'customer-name',
            title: 'Business Name',
            field: 'businessName',
            name: 'Business Name',
            sortName: 'name',
            hidden: false,
            isPined: true,
            width: 200,
            minWidth: 150,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            link: {
                routerLinkStart: '/list/customer/',
                routerLinkEnd: '/shipper-details',
            },
        },
        {
            ngTemplate: 'text',
            title: 'Phone',
            field: 'phone',
            name: 'Phone',
            sortName: 'phone',
            hidden: false,
            isPined: false,
            width: 130,
            minWidth: 112,
            filter: '',
            isNumeric: true,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Email',
            field: 'email',
            name: 'Email',
            sortName: 'email',
            hidden: false,
            isPined: false,
            width: 220,
            minWidth: 150,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Address',
            field: 'tableAddress',
            name: 'Address',
            sortName: 'address',
            hidden: false,
            isPined: false,
            width: 270,
            minWidth: 150,
            filter: '',
            isNumeric: false,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Loads',
            field: 'tableLoads',
            name: 'Loads',
            sortName: 'load',
            hidden: false,
            isPined: false,
            width: 70,
            minWidth: 54,
            filter: '',
            isNumeric: false,
            index: 8,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Pickup',
            field: 'tableAverageWatingTimePickup',
            name: 'Pickup',
            sortName: 'pickups',
            groupName: 'Average Wating Time ',
            hidden: true,
            isPined: false,
            width: 80,
            minWidth: 64,
            filter: '',
            isNumeric: false,
            index: 8,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Delivery',
            field: 'tableAverageWatingTimeDelivery',
            name: 'Delivery',
            sortName: 'deliveries',
            groupName: 'Average Wating Time ',
            hidden: true,
            isPined: false,
            width: 80,
            minWidth: 64,
            filter: '',
            isNumeric: false,
            index: 8,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'work-hour',
            title: 'Shipping',
            field: 'tableAvailableHoursShipping',
            name: 'Shipping',
            sortName: 'shipWorkHour',
            groupName: 'Available Hours ',
            hidden: true,
            isPined: false,
            width: 170,
            minWidth: 162,
            filter: '',
            isNumeric: false,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            specialColumn: true,
            grossColumn: true,
        },
        {
            ngTemplate: 'work-hour',
            title: 'Receiving',
            field: 'tableAvailableHoursReceiving',
            name: 'Receiving',
            sortName: 'receWorkHour',
            groupName: 'Available Hours ',
            hidden: true,
            isPined: false,
            width: 170,
            minWidth: 162,
            filter: '',
            isNumeric: false,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            specialColumn: true,
            grossColumn: true,
        },
        {
            ngTemplate: 'rating',
            title: 'Rating',
            field: 'tableRaiting',
            name: 'Rating',
            sortName: 'rating',
            hidden: false,
            isPined: false,
            headAlign: 'center',
            width: 128,
            minWidth: 128,
            filter: '',
            isNumeric: false,
            index: 7,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            svg: true,
            showPin: false,
            class: 'overflow-unset',
        },
        {
            ngTemplate: 'contact',
            title: 'Contact',
            field: 'tableContact',
            name: 'Contact',
            sortName: 'contact',
            hidden: false,
            isPined: false,
            width: 40,
            minWidth: 40,
            filter: '',
            isNumeric: false,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            specialColumn: true,
            grossColumn: true,
        },
        {
            ngTemplate: 'text',
            title: 'Added',
            field: 'tableAdded',
            name: 'Added',
            sortName: 'added',
            hidden: true,
            isPined: false,
            width: 80,
            minWidth: 66,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Edited',
            field: 'tableEdited',
            name: 'Edited',
            sortName: 'edited',
            hidden: true,
            isPined: false,
            width: 80,
            minWidth: 66,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'note',
            title: 'Note',
            field: 'note',
            name: '',
            hidden: false,
            width: 40,
            minWidth: 40,
            filter: '',
            isNumeric: false,
            index: 17,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            hidden: false,
            width: 42,
            minWidth: 42,
            filter: '',
            isNumeric: false,
            index: 18,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}
