export function getDispatchColumnDefinition() {
    return [
        {
            ngTemplate: 'text',
            title: 'Truck',
            field: 'truckNumber',
            groupName: 'Truck ',
            name: 'Unit No. ',
            sortName: 'truck',
            hidden: false,
            isPined: true,
            resizable: true,
            width: 320,
            minWidth: 160,
        },
        {
            ngTemplate: 'text',
            title: 'Year Truck',
            field: 'truckNumber',
            groupName: 'Truck ',
            name: 'Year ',
            hidden: true,
        },
        {
            ngTemplate: 'text',
            title: 'Trailer',
            field: 'trailerNumber',
            groupName: 'Trailer',
            name: 'Unit No. ',
            sortName: 'trailer',
            hidden: false,
            isPined: true,

            width: 320,
            minWidth: 160,
        },
        {
            ngTemplate: 'text',
            title: 'Year Trailer',
            field: 'year',
            groupName: 'Trailer',
            name: 'Year',
            hidden: true,
        },

        {
            ngTemplate: 'text',
            title: 'Name',
            field: 'firstName',
            groupName: 'Driver ',
            name: 'Name ',
            sortName: 'driver',
            hidden: false,
            isPined: true,

            width: 400,
            minWidth: 240,
        },
        {
            ngTemplate: 'text',
            title: 'Hours of Service driver',
            field: 'hos',
            groupName: 'Driver ',
            name: 'Hours of Service ',
            sortName: 'driver',
            hidden: false,
        },
        {
            ngTemplate: 'text',
            title: 'Endorsements Driver',
            field: 'end',
            groupName: 'Driver ',
            name: 'Endorsements ',
            sortName: 'driver',
            hidden: true,
        },

        {
            ngTemplate: 'text',
            title: 'Name Co-Driver',
            field: 'firstNameCo',
            groupName: 'Co-Driver ',
            name: 'Name ',
            sortName: 'driver',
            hidden: false,
            isPined: true,
        },
        {
            ngTemplate: 'text',
            title: 'Hours of Service Co-Driver',
            field: 'hosCo',
            groupName: 'Co-Driver ',
            name: 'Hours of Service ',
            sortName: 'driver',
            hidden: true,
        },
        {
            ngTemplate: 'text',
            title: 'Endorsements Co-Driver',
            field: 'endCo',
            groupName: 'Co-Driver ',
            name: 'Endorsements ',
            sortName: 'driver',
            hidden: true,
        },

        {
            ngTemplate: 'text',
            title: 'Pre trip',
            field: 'PreTrip',
            name: 'Pre-Trip Insp. ',
            hidden: false,
            width: 34,
            minWidth: 34,
        },
        {
            ngTemplate: 'text',
            title: 'Last Location',
            field: 'city',
            name: 'Last Location ',
            sortName: 'location',
            hidden: false,
            isPined: true,

            width: 300,
            minWidth: 140,
        },
        {
            ngTemplate: 'text',
            title: 'Status',
            field: 'status',
            name: 'Status ',
            hidden: false,
            isPined: true,

            width: 200,
            minWidth: 120,
        },
        {
            ngTemplate: 'text',
            title: 'Pickup & Delivery',
            field: 'Pickup&Delivery',
            name: 'Pickup & Delivery ',
            hidden: false,
            isPined: true,

            width: 420,
            minWidth: 300,
        },
        {
            ngTemplate: 'text',
            title: 'Progress',
            field: 'Progress',
            name: 'Progress ',
            hidden: false,

            width: 326,
            minWidth: 196,
        },
        {
            ngTemplate: 'text',
            title: 'Parking',
            field: 'slotNumber',

            name: 'Parking ',
            sortName: 'parkingSlot',
            hidden: false,

            width: 200,
            minWidth: 90,
        },
        {
            ngTemplate: 'text',
            title: 'Dispatcher',
            field: 'Dispatcher',

            name: 'Dispatcher',

            hidden: false,
            width: 34,
            minWidth: 34,
        },
        {
            ngTemplate: 'text',
            title: 'Note',
            field: 'Note',

            name: 'Note',
            hidden: false,
            width: 326,
            minWidth: 194,
        },
    ];
}
