// helpers
import { DriverColumnsHelper } from '@shared/utils/helpers/settings-helpers/driver-columns.helper';

// models
import { DriverResponse } from 'appcoretruckassist';

export function getDriverColumnsDefinition(tableData: DriverResponse[]) {
    const payrollColumns =
        DriverColumnsHelper.getDriverPayrollColumns(tableData);

    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: 'Select',
            hidden: false,
            width: 28,
            isPined: true,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'avatar',
            title: 'Name',
            field: 'fullName',
            name: 'Name',
            sortName: 'name',
            hidden: false,
            isPined: true,
            width: 234,
            minWidth: 234,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: {
                src: 'additionalData.avatar.src',
            },
            link: {
                routerLinkStart: '/list/driver/',
                routerLinkEnd: '/details',
            },
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: true,
            export: true,
            resizable: true,
            class: 'overflow-unset',
        },
        {
            ngTemplate: 'text',
            title: 'DOB',
            field: 'tableDOB',
            name: 'Date of Birth',
            sortName: 'dateOfBirth',
            hidden: true,
            isPined: false,
            width: 88,
            minWidth: 88,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'SSN',
            field: 'ssn',
            name: 'SSN Number',
            sortName: 'ssn',
            hidden: false,
            isPined: false,
            width: 118,
            minWidth: 118,
            filter: '',
            isNumeric: true,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Phone',
            field: 'phone',
            name: 'Phone',
            sortName: 'phone',
            isPined: false,
            hidden: false,
            width: 128,
            minWidth: 128,
            filter: '',
            isNumeric: true,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Email',
            field: 'email',
            name: 'Email',
            sortName: 'email',
            hidden: true,
            isPined: false,
            width: 228,
            minWidth: 228,
            filter: '',
            isNumeric: false,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Address',
            field: 'tableAddress',
            name: 'Address',
            sortName: 'address',
            hidden: true,
            isPined: false,
            width: 320,
            minWidth: 320,
            filter: '',
            isNumeric: false,
            index: 6,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Type ',
            field: 'tableOwnerDetailsType',
            name: 'Type ',
            sortName: 'ownerType',
            groupName: 'Owner Detail ',
            hidden: true,
            isPined: false,
            width: 128,
            minWidth: 128,
            filter: '',
            isNumeric: true,
            index: 7,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Business Name',
            field: 'tableOwnerDetailsBusinesName',
            name: 'Business Name',
            sortName: 'ownerName',
            groupName: 'Owner Detail ',
            hidden: true,
            isPined: false,
            width: 238,
            minWidth: 238,
            filter: '',
            isNumeric: true,
            index: 8,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'EIN',
            field: 'tableOwnerDetailsEin',
            name: 'EIN',
            sortName: 'ownerEin',
            groupName: 'Owner Detail ',
            hidden: true,
            isPined: false,
            width: 118,
            minWidth: 118,
            filter: '',
            isNumeric: true,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Driver Type',
            field: 'tableDriverType',
            name: 'Driver Type',
            groupName: null,
            sortName: '',
            hidden: true,
            isPined: false,
            width: 138,
            minWidth: 138,
            filter: '',
            isNumeric: false,
            isDate: false,
            index: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Pay Type',
            field: 'tablePayrollDetailType',
            name: 'Pay Type',
            groupName: null,
            hidden: false,
            isPined: false,
            sortName: 'payType',
            width: 100,
            minWidth: 100,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        ...payrollColumns,
        {
            ngTemplate: 'text',
            title: 'Name ',
            field: 'tableBankDetailBankName',
            name: 'Name',
            groupName: 'Bank Detail ',
            hidden: true,
            isPined: false,
            sortName: 'bankName',
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 22,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Routing',
            field: 'tableBankDetailRouting',
            name: 'Routing',
            groupName: 'Bank Detail ',
            sortName: 'routingNumber',
            hidden: true,
            isPined: false,
            width: 76,
            minWidth: 76,
            filter: '',
            isNumeric: true,
            index: 23,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'password-account',
            title: 'Account ',
            field: 'tableBankDetailAccount',
            name: 'Account ',
            sortName: '',
            groupName: 'Bank Detail ',
            hidden: true,
            isPined: false,
            width: 138,
            minWidth: 138,
            filter: '',
            isNumeric: true,
            index: 24,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'description-driver',
            title: 'Off Duty Location',
            field: 'tableOffDutyLocation',
            name: 'Off-Duty Location',
            sortName: 'offDutyLocation',
            hidden: true,
            isPined: false,
            width: 236,
            minWidth: 236,
            filter: '',
            isNumeric: true,
            index: 25,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Name  ',
            field: 'tableEmergContactName',
            name: 'Name  ',
            groupName: 'Emerg. Contact ',
            sortName: 'emergencyContactName',
            hidden: true,
            isPined: false,
            width: 186,
            minWidth: 186,
            filter: '',
            isNumeric: false,
            index: 26,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Relation',
            field: 'tableEmergContactRelation',
            name: 'Relation',
            groupName: 'Emerg. Contact ',
            sortName: 'tableEmergContactRelation',
            hidden: true,
            isPined: false,
            width: 186,
            minWidth: 186,
            filter: '',
            isNumeric: false,
            index: 27,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Phone ',
            field: 'tableEmergContactPhone',
            name: 'Phone',
            groupName: 'Emerg. Contact ',
            sortName: 'emergencyContactPhone',
            hidden: true,
            isPined: false,
            width: 128,
            minWidth: 128,
            filter: '',
            isNumeric: true,
            index: 28,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'TWIC Exp',
            field: 'tableTwicExp',
            name: 'TWIC Expiration',
            sortName: 'twicExpDate',
            hidden: true,
            isPined: false,
            width: 88,
            minWidth: 88,
            filter: '',
            isNumeric: true,
            index: 29,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Number ',
            field: 'tableFuelCardDetailNumber',
            name: 'Number ',
            groupName: 'Fuel Card Detail ',
            sortName: 'fuelCard',
            hidden: true,
            isPined: false,
            width: 118,
            minWidth: 118,
            filter: '',
            isNumeric: true,
            index: 30,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Type  ',
            field: 'tableFuelCardDetailType',
            name: 'Type ',
            groupName: 'Fuel Card Detail ',
            sortName: 'fuelCardType',
            hidden: true,
            isPined: false,
            width: 98,
            minWidth: 98,
            filter: '',
            isNumeric: true,
            index: 31,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Account',
            field: 'tableFuelCardDetailAccount',
            name: 'Account',
            sortName: 'accountNumber',
            groupName: 'Fuel Card Detail ',
            hidden: true,
            isPined: false,
            width: 138,
            minWidth: 138,
            filter: '',
            isNumeric: true,
            index: 32,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Number',
            field: 'tableCdlDetailNumber',
            name: 'Number',
            sortName: 'cdlNumber',
            groupName: 'Cdl Detail ',
            hidden: false,
            isPined: false,
            width: 138,
            minWidth: 138,
            filter: '',
            isNumeric: true,
            index: 33,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'textState',
            title: 'State',
            field: 'tableCdlDetailState',
            name: 'State',
            groupName: 'Cdl Detail ',
            sortName: 'cdlState',
            hidden: false,
            isPined: false,
            width: 68,
            minWidth: 68,
            filter: '',
            isNumeric: false,
            index: 34,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: {
                urlStart: '/assets/img/svgs/states/',
                field: 'licenseData[0].state.key',
                urlEnd: '.svg',
            },
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'description-driver',
            title: 'Endorsement',
            field: 'tableCdlDetailEndorsment',
            name: 'Endorsement',
            groupName: 'Cdl Detail ',
            sortName: 'endorsment',
            hidden: true,
            isPined: false,
            width: 154,
            minWidth: 154,
            filter: '',
            isNumeric: true,
            index: 35,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'description-driver',
            title: 'Restriction',
            field: 'tableCdlDetailRestriction',
            name: 'Restriction',
            groupName: 'Cdl Detail ',
            sortName: 'cdlRestriction',
            hidden: true,
            isPined: false,
            width: 154,
            minWidth: 154,
            filter: '',
            isNumeric: true,
            index: 36,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progress',
            title: 'Expiration',
            field: 'tableCdlDetailExpiration',
            name: 'Expiration',
            groupName: 'Cdl Detail ',
            sortName: 'cdlExp',
            isPined: false,
            hidden: false,
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            index: 37,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Issued',
            field: 'tableTestDetailsIssued',
            name: 'Issued Date',
            groupName: 'Test Detail ',
            sortName: 'testIssued',
            hidden: true,
            isPined: false,
            width: 88,
            minWidth: 88,
            filter: '',
            isNumeric: true,
            index: 38,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Type',
            field: 'tableTestDetailsType',
            name: 'Type',
            groupName: 'Test Detail ',
            sortName: 'testType',
            hidden: true,
            isPined: false,
            width: 90,
            minWidth: 90,
            filter: '',
            isNumeric: true,
            index: 39,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Reason',
            field: 'tableTestDetailsReason',
            name: 'Reason',
            groupName: 'Test Detail ',
            sortName: 'testReason',
            hidden: true,
            isPined: false,
            width: 138,
            minWidth: 138,
            filter: '',
            isNumeric: true,
            index: 40,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Results',
            field: 'tableTestDetailsResult',
            name: 'Results',
            groupName: 'Test Detail ',
            sortName: 'testResult',
            hidden: true,
            isPined: false,
            width: 90,
            minWidth: 90,
            filter: '',
            isNumeric: true,
            index: 41,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progress',
            title: 'Medical Exp',
            field: 'tableMedicalData',
            name: 'Medical Expiration',
            sortName: 'medExp',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            index: 42,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Term ',
            field: 'tableMvrDetailsRenewalTerm',
            name: 'Renewal Term',
            sortName: '',
            groupName: 'MVR Detail ',
            hidden: true,
            isPined: false,
            width: 88,
            minWidth: 88,
            filter: '',
            isNumeric: true,
            index: 43,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progress',
            title: 'Expiration ',
            field: 'tableMvrDetailsExpiration',
            name: 'Expiration',
            sortName: 'mvrIssue',
            groupName: 'MVR Detail ',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            index: 44,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'General',
            field: 'tabelNotificationGeneral',
            name: 'General',
            groupName: 'Notification ',
            sortName: 'notificationGeneral',
            isPined: false,
            hidden: true,
            width: 138,
            minWidth: 138,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 45,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Payroll',
            field: 'tabelNotificationPayroll',
            name: 'Payroll',
            groupName: 'Notification ',
            sortName: 'notificationPayroll',
            isPined: false,
            hidden: true,
            width: 138,
            minWidth: 138,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 46,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text-assigned',
            title: 'Truck',
            field: 'tableAssignedUnitTruck',
            name: 'Truck',
            groupName: 'Assigned Unit ',
            sortName: 'assignedUnitTruck',
            hidden: false,
            isPined: false,
            width: 78,
            minWidth: 78,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 47,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'cu m-font',
        },
        {
            ngTemplate: 'text-assigned',
            title: 'Trailer',
            field: 'tableAssignedUnitTrailer',
            name: 'Trailer',
            groupName: 'Assigned Unit ',
            sortName: 'assignedUnitTrailer',
            hidden: false,
            isPined: false,
            width: 78,
            minWidth: 78,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 48,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Hired',
            field: 'tabelHired',
            name: 'Date Hired',
            sortName: 'hiredAt',
            isPined: false,
            hidden: false,
            width: 88,
            minWidth: 88,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 49,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Deact',
            field: 'tableTerminated',
            name: 'Date Deactivated',
            sortName: 'terminatedAt',
            isPined: false,
            hidden: true,
            width: 88,
            minWidth: 88,
            filter: '',
            isNumeric: true,
            index: 50,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Added',
            field: 'tableAdded',
            name: 'Date Added',
            sortName: 'createdAt',
            isPined: false,
            hidden: true,
            width: 88,
            minWidth: 88,
            filter: '',
            isNumeric: true,
            index: 51,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Edited',
            field: 'tableEdited',
            name: 'Date Edited',
            sortName: 'updatedAt',
            isPined: false,
            hidden: true,
            width: 88,
            minWidth: 88,
            filter: '',
            isNumeric: true,
            index: 52,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'attachments',
            title: 'Attachments',
            field: 'tableAttachments',
            moveRight: true,
            name: '',
            hidden: false,
            width: 46,
            minWidth: 46,
            filter: '',
            isNumeric: false,
            index: 53,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'note',
            title: 'Note',
            field: 'note',
            name: '',
            hidden: false,
            width: 26,
            minWidth: 26,
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: 'assets/svg/truckassist-table/note/Note.svg',
            },
            filter: '',
            isNumeric: false,
            index: 54,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            headIconStyle: {
                width: 22,
                height: 6,
                imgPath: '',
            },
            hidden: false,
            width: 26,
            minWidth: 26,
            filter: '',
            isNumeric: false,
            index: 55,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}
