// APPLICANT TABLE COLUMNS DEFINITION
export function getDriverApplicantColumnsDefinition() {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: 'Select',
            hidden: false,
            isPined: true,
            width: 28,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'nameLink',
            title: 'Name',
            field: 'name',
            name: 'Name',
            sortName: 'name',
            hidden: false,
            isPined: true,
            width: 129,
            minWidth: 129,
            pdfWidth: 10,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: true,
            export: true,
            resizable: true,
            link: {
                routerLinkStart: '/applicant/',
                routerLinkEnd: '/applicant/',
            },
        },
        {
            ngTemplate: 'text',
            title: 'DOB',
            field: 'tableDOB',
            name: 'Date of Birth',
            sortName: 'dob',
            hidden: false,
            isPined: false,
            width: 88,
            minWidth: 88,
            filter: '',
            isNumeric: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'SSN',
            field: 'ssn',
            name: 'SSN',
            sortName: 'ssn',
            hidden: true,
            isPined: false,
            width: true,
            minWidth: 118,
            filter: '',
            isNumeric: true,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Phone',
            field: 'phone',
            name: 'Phone',
            sortName: 'phone',
            hidden: false,
            isPined: false,
            width: 128,
            minWidth: 128,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Email',
            field: 'email',
            name: 'Email',
            sortName: 'email',
            hidden: false,
            isPined: false,
            width: 228,
            minWidth: 228,
            filter: '',
            isNumeric: false,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Address',
            field: 'tableAddress',
            name: 'Address',
            sortName: 'address',
            hidden: true,
            isPined: false,
            width: 320,
            minWidth: 320,
            filter: '',
            isNumeric: false,
            index: 6,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'applicant-review',
            title: 'Status',
            field: 'tableRev',
            name: 'Status',
            sortName: '',
            isPined: false,
            hidden: false,
            width: 152,
            minWidth: 152,
            filter: '',
            isNumeric: false,
            index: 7,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'applicant-progress',
            title: 'Application Progress ',
            field: 'tableApplicantProgress',
            name: 'Application Progress',
            sortName: 'applicantProgress',
            hidden: false,
            isPined: false,
            width: 328,
            minWidth: 328,
            filter: '',
            isNumeric: true,
            index: 8,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Number',
            field: 'tableCdlDetailNumber',
            name: 'Number',
            sortName: 'cdlNumber',
            groupName: 'Cdl Detail ',
            hidden: true,
            isPined: false,
            width: 138,
            minWidth: 138,
            filter: '',
            isNumeric: true,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'textState',
            title: 'State',
            field: 'tableCdlDetailState',
            name: 'State',
            groupName: 'Cdl Detail ',
            sortName: 'cdlState',
            hidden: true,
            isPined: false,
            width: 68,
            minWidth: 68,
            filter: '',
            isNumeric: false,
            index: 10,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: {
                urlStart: '/assets/img/svgs/states/',
                field: 'licenseData[0].state.key',
                urlEnd: '.svg',
            },
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Endorsement',
            field: 'tableCdlDetailEndorsment',
            name: 'Endorsement',
            groupName: 'Cdl Detail ',
            sortName: 'endorsment',
            hidden: true,
            isPined: false,
            width: 154,
            minWidth: 154,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Restriction',
            field: 'tableCdlDetailRestriction',
            name: 'Restriction',
            groupName: 'Cdl Detail ',
            sortName: 'cdlRestriction',
            hidden: true,
            isPined: false,
            width: 154,
            minWidth: 154,
            filter: '',
            isNumeric: true,
            index: 12,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progress',
            title: 'Expiration',
            field: 'tableCdlDetailExpiration',
            name: 'Expiration',
            groupName: 'Cdl Detail ',
            sortName: 'cdlExp',
            isPined: false,
            hidden: false,
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            index: 13,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progress',
            title: 'Medical Exp',
            field: 'tableMedicalData',
            name: 'Medical Expiration',
            sortName: 'medExp',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            index: 14,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Invited',
            field: 'tableInvited',
            name: 'Date Invited',
            sortName: 'invited',
            hidden: true,
            isPined: false,
            width: 88,
            minWidth: 88,
            filter: '',
            isNumeric: true,
            index: 15,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Accepted',
            field: 'tableAccepted',
            name: 'Date Accepted',
            sortName: 'accepted',
            hidden: true,
            isPined: false,
            width: 88,
            minWidth: 88,
            filter: '',
            isNumeric: true,
            index: 16,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Archived',
            field: 'tableArchived',
            name: 'Date Archived',
            sortName: 'archived',
            hidden: true,
            isPined: false,
            width: 88,
            minWidth: 88,
            filter: '',
            isNumeric: true,
            index: 17,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Added',
            field: 'tableAdded',
            name: 'Date Added',
            sortName: 'added',
            hidden: false,
            isPined: false,
            width: 88,
            minWidth: 88,
            filter: '',
            isNumeric: true,
            index: 18,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Edited',
            field: 'tableEdited',
            name: 'Date Edited',
            sortName: 'edited',
            hidden: true,
            isPined: false,
            width: 88,
            minWidth: 88,
            filter: '',
            isNumeric: true,
            index: 19,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'hire',
            title: 'Hire',
            field: 'hire',
            name: '',
            hidden: false,
            width: 26,
            minWidth: 26,
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: '',
            },
            filter: '',
            isNumeric: false,
            index: 20,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'favorite',
            title: 'Favorite',
            field: 'isFavorite',
            name: '',
            hidden: false,
            width: 26,
            minWidth: 26,
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: '',
            },
            filter: '',
            isNumeric: false,
            index: 21,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'note',
            title: 'Note',
            field: 'note',
            name: '',
            hidden: false,
            width: 26,
            minWidth: 26,
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: 'assets/svg/truckassist-table/note/Note.svg',
            },
            filter: '',
            isNumeric: false,
            index: 22,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            hidden: false,
            width: 26,
            minWidth: 26,
            headIconStyle: {
                width: 22,
                height: 6,
                imgPath: '',
            },
            filter: '',
            isNumeric: false,
            index: 23,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}
