export function getIntegrationsColumnDefinition() {
    return [
        {
            ngTemplate: '',
            title: 'Card Provider',
            field: 'tableCardProvider',
            name: 'Card Provider',
            isComputed: false,
            isPined: true,
            hidden: false,
            width: 150,
            minWidth: 143,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            password: true,
        },
        {
            ngTemplate: 'text',
            title: 'Type',
            field: 'tableType',
            name: 'Type',
            sortName: 'make',
            isPined: false,
            hidden: false,
            width: 110,
            minWidth: 50,
            pdfWidth: 15,
            filter: '',
            isNumeric: false,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Url',
            field: 'tableUrl',
            name: 'Url',
            sortName: 'make',
            isPined: false,
            hidden: false,
            width: 110,
            minWidth: 50,
            pdfWidth: 15,
            filter: '',
            isNumeric: false,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'User Id',
            field: 'tableUserId',
            name: 'User Id',
            isPined: false,
            hidden: false,
            width: 150,
            pdfWidth: 50,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'text',
            title: 'Carrier Id',
            field: 'tableCarrierId',
            name: 'Carrier Id',
            isPined: false,
            hidden: false,
            width: 150,
            pdfWidth: 50,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'password',
            title: 'Password',
            field: 'tableIntegrationPassword',
            name: 'Password',
            isComputed: false,
            isPined: false,
            hidden: false,
            width: 143,
            minWidth: 143,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            password: true,
        },
        {
            ngTemplate: 'text',
            title: 'Status',
            field: 'tableIntegrationConnectedStatus',
            name: 'Status',
            isPined: false,
            hidden: false,
            width: 150,
            pdfWidth: 50,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'text',
            title: 'Last Connected',
            field: 'tableLastConnected',
            name: 'Last Connected',
            isPined: false,
            hidden: false,
            width: 150,
            pdfWidth: 50,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'text',
            title: 'Disconnected',
            field: 'tabledisconnectedDate',
            name: 'Disconnected',
            isPined: false,
            hidden: false,
            width: 150,
            pdfWidth: 50,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            hidden: false,
            width: 26,
            minWidth: 26,
            headIconStyle: {
                width: 22,
                height: 6,
                imgPath: '',
            },
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 13,
            sortable: true,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}
