// LOAD COLUMN DEFINITION
export function getLoadTemplateColumnDefinition() {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: '',
            hidden: false,
            width: 32,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: '',
            title: 'Name',
            field: 'textName',
            name: 'Name',
            sortName: 'loadname',
            hidden: false,
            width: 162,
            minWidth: 162,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            link: {
                routerLinkStart: '/list/load/',
                routerLinkEnd: '/details',
            },
        },
        {
            ngTemplate: 'text',
            title: 'Added',
            field: 'textAdded',
            name: 'Added',
            sortName: 'loadadded',
            hidden: false,
            width: 86,
            minWidth: 86,
            filter: '',
            isNumeric: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Total',
            field: 'textTotal',
            name: 'Total',
            sortName: 'rate',
            hidden: false,
            width: 92,
            minWidth: 92,
            filter: '',
            isNumeric: true,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Broker',
            field: 'textBroker',
            name: 'Broker',
            sortName: 'broker',
            hidden: false,
            width: 192,
            minWidth: 192,
            filter: '',
            isNumeric: true,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: '',
            title: 'Driver',
            field: 'textDriver',
            name: 'Driver',
            sortName: 'driver',
            hidden: false,
            width: 144,
            minWidth: 144,
            filter: '',
            isNumeric: true,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: '',
            title: 'Truck type',
            field: 'textTruckType',
            name: 'Truck type',
            sortName: 'loadtrucktype',
            hidden: false,
            width: 82,
            minWidth: 82,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: '',
            title: 'Trailer type',
            field: 'textTrailerType',
            name: 'Trailer type',
            sortName: 'loadtrailertype',
            hidden: false,
            width: 91,
            minWidth: 91,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: '',
            title: 'Pickup',
            field: 'textPickup',
            name: 'Pickup',
            sortName: 'pickup',
            hidden: false,
            width: 120,
            minWidth: 120,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: '',
            title: 'Deliv.',
            field: 'textDeliv',
            name: 'Deliv.',
            sortName: 'delivery',
            hidden: false,
            width: 120,
            minWidth: 120,
            filter: '',
            isNumeric: true,
            index: 6,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Miles',
            field: 'textMiles',
            name: 'Miles',
            sortName: 'totalMiles',
            hidden: false,
            width: 100,
            minWidth: 100,
            filter: '',
            isNumeric: true,
            index: 7,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Commodity',
            field: 'textCommodity',
            name: 'Commodity',
            sortName: 'commodity',
            hidden: true,
            width: 122,
            minWidth: 122,
            filter: '',
            isNumeric: true,
            index: 8,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Weight',
            field: 'textWeight',
            name: 'Weight',
            sortName: 'weight',
            hidden: true,
            width: 86,
            minWidth: 86,
            filter: '',
            isNumeric: false,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Truck #',
            field: 'textTruck',
            name: 'Truck #',
            sortName: 'truck',
            hidden: true,
            width: 70,
            minWidth: 70,
            filter: '',
            isNumeric: false,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Trailer #',
            field: 'textTrailer',
            name: 'Trailer #',
            sortName: 'trailer',
            hidden: true,
            width: 80,
            minWidth: 80,
            filter: '',
            isNumeric: false,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'attachments',
            title: 'Attachments',
            field: 'tableAttachments',
            moveRight: true,
            name: '',
            hidden: false,
            width: 44,
            minWidth: 44,
            filter: '',
            isNumeric: false,
            index: 16,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'note',
            title: 'Note',
            field: 'note',
            name: '',
            hidden: false,
            width: 40,
            minWidth: 40,
            headIconStyle: {
                width: 16,
                height: 18,
                imgPath: '',
            },
            filter: '',
            isNumeric: false,
            index: 17,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            headIconStyle: {
                width: 22,
                height: 6,
                imgPath: '',
            },
            hidden: false,
            width: 42,
            minWidth: 42,
            filter: '',
            isNumeric: false,
            index: 18,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}

export function getLoadActiveAndPendingColumnDefinition() {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: '',
            hidden: false,
            width: 32,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'invoice',
            title: 'Inv.',
            field: 'loadInvoice',
            sortName: 'loadinv',
            name: 'Load No.',
            hidden: false,
            width: 82,
            minWidth: 82,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            link: {
                routerLinkStart: '/list/load/',
                routerLinkEnd: '/details',
            },
        },
        {
            ngTemplate: 'dispatcher-avatar',
            title: 'Dispatcher',
            field: 'loadDispatcher',
            name: 'Dispatcher',
            sortName: 'dispatcherfullName',
            hidden: false,
            width: 130,
            minWidth: 130,
            filter: '',
            isNumeric: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'customer-name',
            title: 'Bussiness Name   ',
            field: 'loadBroker',
            name: 'Bussiness Name   ',
            groupName: 'Broker',
            sortName: 'bussinessName',
            hidden: false,
            width: 192,
            minWidth: 192,
            filter: '',
            isNumeric: true,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Contact',
            field: 'contact',
            name: 'Contact',
            groupName: 'Broker',
            sortName: 'contact',
            hidden: false,
            width: 192,
            minWidth: 192,
            filter: '',
            isNumeric: true,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Phone',
            field: 'phone',
            name: 'Phone',
            groupName: 'Broker',
            sortName: 'phone',
            isPined: false,
            hidden: false,
            width: 128,
            minWidth: 128,
            filter: '',
            isNumeric: true,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },

        {
            ngTemplate: 'text',
            title: 'Ref #',
            field: 'referenceNumber',
            name: 'Ref Number',
            sortName: 'referenceNumber',
            hidden: false,
            width: 86,
            minWidth: 86,
            filter: '',
            isNumeric: true,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Weight',
            field: 'textWeight',
            name: 'Weight',
            sortName: 'weight',
            hidden: true,
            width: 86,
            minWidth: 86,
            filter: '',
            isNumeric: false,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Commodity',
            field: 'textCommodity',
            name: 'Commodity',
            sortName: 'commodity',
            hidden: true,
            width: 122,
            minWidth: 122,
            filter: '',
            isNumeric: true,
            index: 8,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'avatar-assign',
            title: 'Driver',
            field: 'tableDriver',
            name: 'Driver',
            groupName: 'Assigned',
            sortName: 'driver',
            hidden: false,

            isPined: false,
            width: 200,
            minWidth: 200,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,

            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
            class: 'overflow-unset',
        },
        {
            ngTemplate: 'text-assigned',
            title: 'Truck',
            field: 'tableAssignedUnitTruck',
            name: 'Truck',
            groupName: 'Assigned',
            sortName: 'truck',
            hidden: false,
            isPined: false,
            width: 80,
            minWidth: 80,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text-assigned',
            title: 'Trailer',
            field: 'tableAssignedUnitTrailer',
            isPined: false,
            name: 'Trailer',
            groupName: 'Assigned',
            sortName: 'trailer',
            hidden: false,
            width: 100,
            minWidth: 100,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'status',
            title: 'Status',
            field: 'loadStatus',
            name: 'Status',
            sortName: 'status',
            setCenter: false,
            hidden: false,
            width: 138,
            minWidth: 138,
            filter: '',
            isNumeric: true,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'svg',
            title: ' Truck ',
            field: 'loadTruckNumber',
            groupName: 'Requirement',
            name: 'Truck Type',
            sortName: 'loadTruckNumber',
            hidden: false,
            width: 70,
            minWidth: 70,
            filter: '',
            isNumeric: true,
            index: 5,
            margin: -10,
            padding: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            tooltipColor: 'tableTruckColor',
            tooltipTitle: 'tableTruckName',

            export: true,
            resizable: true,
            svgUrl: 'assets/svg/common/trucks/',
            classField: 'truckTypeClass',
            svgDimensions: {
                width: 42,
                height: 18,
            },
            class: 'type-icon',
        },
        {
            ngTemplate: 'svg',
            title: 'Trailer',
            field: 'loadTrailerNumber',
            name: 'Trailer Type',
            groupName: 'Requirement',
            sortName: 'loadTrailerNumber',
            hidden: false,
            width: 80,
            minWidth: 80,
            margin: -8,
            padding: 8,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            tooltipColor: 'tableTrailerColor',
            tooltipTitle: 'tableTrailerName',
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
            svgUrl: 'assets/svg/common/trailers/',
            classField: 'tableTrailerTypeClass',
            svgDimensions: {
                width: 42,
                height: 18,
            },
            class: 'type-icon',
        },
        {
            ngTemplate: 'text',
            title: 'ft',
            field: 'tabelLength',
            groupName: 'Requirement',
            isPined: false,
            name: 'Length',
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: 'assets/svg/truckassist-table/length-icon.svg',
            },
            headAlign: 'center',
            sortName: 'color',
            hidden: true,
            width: 34,
            minWidth: 34,
            pdfWidth: 10,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            colorTemplate: {
                value: 'doc.additionalData.color.value',
            },
            opacityIgnore: true,
            class: 'overflow-unset',
        },
        {
            ngTemplate: 'text',
            title: 'Door',
            field: 'tableDoorType',
            name: 'Door Type',
            groupName: 'Requirement',
            sortName: 'doorType',
            hidden: true,
            isPined: false,
            width: 110,
            minWidth: 110,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Suspension',
            field: 'tableSuspension',
            name: 'Suspension',
            groupName: 'Requirement',
            sortName: 'suspension',
            hidden: true,
            isPined: false,
            width: 100,
            minWidth: 100,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Year',
            field: 'year',
            name: 'Year',
            groupName: 'Requirement',
            sortName: 'year',
            isPined: false,
            hidden: false,
            width: 60,
            minWidth: 60,
            pdfWidth: 10,
            filter: '',
            isNumeric: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Liftgate',
            field: 'liftgate',
            name: 'Liftgate',
            groupName: 'Requirement',
            sortName: 'liftgate',
            isPined: false,
            hidden: false,
            width: 78,
            minWidth: 78,
            pdfWidth: 10,
            filter: '',
            isNumeric: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'pickup-delivery',
            title: 'Pickup Delivery',
            field: 'loadPickup',
            name: 'Pickup  Delivery',
            sortName: 'pickup',
            pickupDeliveryType: 'pickup',
            hidden: false,
            width: 306,
            minWidth: 306,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },

        {
            ngTemplate: 'text',
            title: 'Driver Message',
            field: 'textDriver',
            name: 'Driver Message',
            sortName: 'driverMessage',
            hidden: true,
            width: 234,
            minWidth: 234,
            filter: '',
            isNumeric: false,
            index: 15,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: ' Loaded ',
            field: 'loaded',
            name: 'Loaded',
            groupName: 'Miles ',
            sortName: 'loaded',
            hidden: false,
            isPined: false,
            width: 100,
            minWidth: 100,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 6,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: ' Total ',
            field: 'total',
            name: 'Total',
            groupName: 'Miles ',
            sortName: 'total',
            hidden: false,
            isPined: false,
            width: 100,
            minWidth: 100,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Empty',
            field: 'empty',
            groupName: 'Miles ',
            name: 'Empty',
            hidden: false,
            isPined: false,
            width: 107,
            minWidth: 107,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },

        {
            ngTemplate: 'text',
            title: ' Rate ',
            field: 'rate',
            name: 'Rate',
            sortName: 'rate',
            groupName: 'Billing ',
            hidden: true,
            isPined: false,
            width: 320,
            minWidth: 320,
            filter: '',
            isNumeric: false,
            index: 8,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Paid',
            field: 'paid',
            name: 'Paid',
            groupName: 'Billing ',
            sortName: 'paid',
            hidden: true,
            isPined: false,
            width: 101,
            minWidth: 101,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },

        {
            ngTemplate: 'text',
            title: 'Date',
            field: 'tableAdded',
            name: 'Date Created',
            sortName: 'createdAt',
            hidden: true,
            isPined: false,
            width: 88,
            minWidth: 88,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Edited',
            field: 'tableEdited',
            name: 'Date Edited',
            sortName: 'updatedAt',
            hidden: true,
            isPined: false,
            width: 88,
            minWidth: 88,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'attachments',
            title: 'Attachments',
            field: 'tableAttachments',
            moveRight: true,
            name: '',
            hidden: false,
            width: 44,
            minWidth: 44,
            filter: '',
            isNumeric: false,
            index: 16,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'comment',
            title: 'Comment',
            field: 'loadComment',
            name: '',
            hidden: false,
            width: 40,
            minWidth: 40,
            headIconStyle: {
                width: 16,
                height: 18,
                imgPath: '',
            },
            filter: '',
            isNumeric: false,
            index: 17,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'note',
            title: 'Note',
            field: 'note',
            name: '',
            hidden: false,
            width: 40,
            minWidth: 40,
            headIconStyle: {
                width: 16,
                height: 18,
                imgPath: '',
            },
            filter: '',
            isNumeric: false,
            index: 17,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            headIconStyle: {
                width: 22,
                height: 6,
                imgPath: '',
            },
            hidden: false,
            width: 42,
            minWidth: 42,
            filter: '',
            isNumeric: false,
            index: 18,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}

export function getLoadClosedColumnDefinition() {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: '',
            hidden: false,
            width: 32,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: '',
            title: 'Inv.',
            field: 'loadNumber',
            name: 'Invoice',
            sortName: 'loadinv',
            hidden: false,
            width: 82,
            minWidth: 82,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            link: {
                routerLinkStart: '/list/load',
                routerLinkEnd: '/details',
            },
        },
        {
            ngTemplate: '',
            title: 'Dispatcher',
            field: 'textDispatcher',
            name: 'Dispatcher',
            sortName: 'dispatcher',
            hidden: false,
            width: 130,
            minWidth: 130,
            filter: '',
            isNumeric: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Total',
            field: 'textTotal',
            name: 'Total',
            sortName: 'rate',
            hidden: false,
            width: 92,
            minWidth: 92,
            filter: '',
            isNumeric: true,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Broker',
            field: 'textBroker',
            name: 'Broker',
            sortName: 'broker',
            hidden: false,
            width: 192,
            minWidth: 192,
            filter: '',
            isNumeric: true,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Ref',
            field: 'baseRate',
            name: 'Ref',
            sortName: 'referenceNumber',
            hidden: false,
            width: 86,
            minWidth: 86,
            filter: '',
            isNumeric: true,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: '',
            title: 'Status',
            field: 'textStatus',
            name: 'Status',
            sortName: 'status',
            hidden: false,
            width: 98,
            minWidth: 98,
            filter: '',
            isNumeric: true,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: '',
            title: 'Truck #',
            field: 'textTruck',
            name: 'Truck #',
            sortName: 'loadTruckNumber',
            hidden: false,
            width: 70,
            minWidth: 70,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: '',
            title: 'Trailer #',
            field: 'textTrailer',
            name: 'Trailer #',
            sortName: 'loadTrailerNumber',
            hidden: false,
            width: 80,
            minWidth: 80,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: '',
            title: 'Pickup',
            field: 'textPickup',
            name: 'Pickup',
            sortName: 'pickup',
            hidden: false,
            width: 120,
            minWidth: 120,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: '',
            title: 'Deliv.',
            field: 'textDeliv',
            name: 'Deliv.',
            sortName: 'delivery',
            hidden: false,
            width: 120,
            minWidth: 120,
            filter: '',
            isNumeric: true,
            index: 6,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Miles',
            field: 'textMiles',
            name: 'Miles',
            sortName: 'totalMiles',
            hidden: false,
            width: 100,
            minWidth: 100,
            filter: '',
            isNumeric: true,
            index: 7,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Commodity',
            field: 'textCommodity',
            name: 'Commodity',
            sortName: 'commodity',
            hidden: true,
            width: 122,
            minWidth: 122,
            filter: '',
            isNumeric: true,
            index: 8,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Weight',
            field: 'textWeight',
            name: 'Weight',
            sortName: 'weight',
            hidden: true,
            width: 86,
            minWidth: 86,
            filter: '',
            isNumeric: false,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Base',
            field: 'textBase',
            name: 'Base',
            sortName: 'rate',
            hidden: true,
            width: 92,
            minWidth: 92,
            filter: '',
            isNumeric: false,
            index: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Additional',
            field: 'textAdditional',
            name: 'Additional',
            sortName: 'additionalRate',
            hidden: true,
            width: 92,
            minWidth: 92,
            filter: '',
            isNumeric: false,
            isDate: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
            addClassToTitle: 'addGreenToTitle',
        },
        {
            ngTemplate: 'text',
            title: 'Advance',
            field: 'textAdvance',
            name: 'Advance',
            hidden: true,
            width: 92,
            minWidth: 92,
            filter: '',
            isNumeric: false,
            index: 12,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
            devFrom: true,
        },
        {
            ngTemplate: 'text',
            title: 'Pay Terms',
            field: 'textPayTerms',
            name: 'Pay Terms',
            sortName: 'payTerm',
            hidden: true,
            width: 93,
            minWidth: 93,
            filter: '',
            isNumeric: false,
            isDate: true,
            index: 14,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
            addClassToTitle: 'addRedToTitle',
        },
        {
            ngTemplate: 'avatar',
            title: 'Driver',
            field: 'textDriver',
            name: 'Driver',
            sortName: 'driver',
            hidden: true,
            width: 111,
            minWidth: 111,
            filter: '',
            isNumeric: false,
            avatar: {
                src: 'additionalData.avatar.src',
            },
            index: 15,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Invoiced Date',
            field: 'textInvoicedDate',
            name: 'Invoiced Date',
            sortName: 'invoicedDate',
            hidden: true,
            width: 137,
            minWidth: 137,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Paid Date',
            field: 'textPaidDate',
            name: 'Paid Date',
            sortName: 'paidDate',
            hidden: true,
            width: 116,
            minWidth: 116,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Short Pay',
            field: 'textShortPay',
            name: 'Short Pay',
            sortName: 'shortPay',
            hidden: true,
            width: 129,
            minWidth: 129,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Age',
            field: 'textAge',
            name: 'Age',
            sortName: 'age',
            hidden: true,
            width: 80,
            minWidth: 80,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'attachments',
            title: 'Attachments',
            field: 'tableAttachments',
            moveRight: true,
            name: '',
            hidden: false,
            width: 44,
            minWidth: 44,
            filter: '',
            isNumeric: false,
            index: 16,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'comment',
            title: 'Comment',
            field: 'comment',
            name: '',
            hidden: false,
            width: 40,
            minWidth: 40,
            headIconStyle: {
                width: 16,
                height: 18,
                imgPath: '',
            },
            filter: '',
            isNumeric: false,
            index: 17,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'note',
            title: 'Note',
            field: 'note',
            name: '',
            hidden: false,
            width: 40,
            minWidth: 40,
            headIconStyle: {
                width: 16,
                height: 18,
                imgPath: '',
            },
            filter: '',
            isNumeric: false,
            index: 17,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            headIconStyle: {
                width: 22,
                height: 6,
                imgPath: '',
            },
            hidden: false,
            width: 42,
            minWidth: 42,
            filter: '',
            isNumeric: false,
            index: 18,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}
