// appcoretruckassist
import { LoadSortBy } from 'appcoretruckassist';

// models
import { ITableColummn } from '@shared/models';

// LOAD COLUMN DEFINITION
export function getLoadTemplateColumnDefinition() {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: '',
            hidden: false,
            width: 32,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'text',
            title: 'Template Name',
            field: 'loadTemplateName',
            name: 'Template Name',
            sortName: LoadSortBy.LoadNumber,
            hidden: false,
            width: 200,
            minWidth: 200,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: true,
            export: true,
            resizable: true,
            link: {
                routerLinkStart: '/list/load/',
                routerLinkEnd: '/details',
            },
        },
        {
            ngTemplate: 'dispatcher-avatar',
            title: 'Dispatcher',
            field: 'loadDispatcher',
            name: 'Dispatcher',
            sortName: LoadSortBy.Dispatcher,
            hidden: true,
            width: 208,
            minWidth: 208,
            filter: '',
            isNumeric: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'customer-name',
            title: 'Bussiness Name',
            field: 'loadBroker',
            name: 'Bussiness Name',
            groupName: 'Broker Detail',
            sortName: LoadSortBy.BrokerBusinessName,
            hidden: false,
            width: 238,
            minWidth: 238,
            filter: '',
            isNumeric: true,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Contact',
            field: 'contact',
            name: 'Contact',
            groupName: 'Broker Detail',
            sortName: LoadSortBy.BrokerContactName,
            hidden: false,
            width: 192,
            minWidth: 192,
            filter: '',
            isNumeric: true,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Phone',
            field: 'phone',
            name: 'Phone',
            groupName: 'Broker Detail',
            sortName: LoadSortBy.BrokerContactPhone,
            isPined: false,
            hidden: false,
            width: 128,
            minWidth: 128,
            filter: '',
            isNumeric: true,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },

        {
            ngTemplate: 'text',
            title: 'Ref #',
            field: 'referenceNumber',
            name: 'Ref Number',
            sortName: 'referenceNumber',
            hidden: true,
            width: 86,
            minWidth: 86,
            filter: '',
            isNumeric: true,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Commodity',
            field: 'textCommodity',
            name: 'Commodity',
            sortName: 'commodity',
            hidden: false,
            width: 122,
            minWidth: 122,
            filter: '',
            isNumeric: true,
            index: 8,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Weight',
            field: 'textWeight',
            name: 'Weight',
            sortName: LoadSortBy.Weight,
            hidden: true,
            width: 86,
            minWidth: 86,
            filter: '',
            isNumeric: false,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'avatar-assign',
            title: 'Driver',
            field: 'tableDriver',
            name: 'Driver',
            groupName: 'Assigned',
            sortName: 'driver',
            hidden: true,

            isPined: false,
            width: 200,
            minWidth: 200,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,

            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
            class: 'overflow-unset',
        },
        {
            ngTemplate: 'text-assigned',
            title: 'Truck',
            field: 'tableAssignedUnitTruck',
            name: 'Truck',
            groupName: 'Assigned',
            sortName: 'truck',
            hidden: true,
            isPined: false,
            width: 80,
            minWidth: 80,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text-assigned',
            title: 'Trailer',
            field: 'tableAssignedUnitTrailer',
            isPined: false,
            name: 'Trailer',
            groupName: 'Assigned',
            sortName: 'trailer',
            hidden: true,
            width: 100,
            minWidth: 100,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'pickup',
            title: 'Pickup',
            field: 'loadPickup',
            name: 'Pickup',
            sortName: 'pickup',
            pickupDeliveryType: 'pickup',
            hidden: false,
            width: 153,
            minWidth: 153,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: 'assets/svg/common/ic_pickup.svg',
                customClass: 'pickup-icon',
            },
        },
        {
            ngTemplate: 'delivery',
            title: 'Delivery',
            field: 'loadPickup',
            name: 'Delivery',
            sortName: 'pickup',
            pickupDeliveryType: 'pickup',
            hidden: false,
            width: 153,
            minWidth: 153,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: 'assets/svg/common/ic_delivery.svg',
                customClass: 'delivery-icon',
            },
        },

        {
            ngTemplate: 'svg',
            title: ' Truck ',
            field: 'loadTruckNumber',
            groupName: 'Requirement',
            name: 'Truck Type',
            sortName: LoadSortBy.TruckType,
            hidden: true,
            width: 70,
            minWidth: 70,
            filter: '',
            isNumeric: true,
            index: 5,
            margin: -10,
            padding: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            tooltipColor: 'tableTruckColor',
            tooltipTitle: 'tableTruckName',

            export: true,
            resizable: true,
            svgUrl: 'assets/svg/common/trucks/',
            classField: 'truckTypeClass',
            svgDimensions: {
                width: 42,
                height: 18,
            },
            class: 'type-icon',
        },
        {
            ngTemplate: 'svg',
            title: 'Trailer',
            field: 'loadTrailerNumber',
            name: 'Trailer Type',
            groupName: 'Requirement',
            sortName: LoadSortBy.TrailerType,
            hidden: true,
            width: 80,
            minWidth: 80,
            margin: -8,
            padding: 8,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            tooltipColor: 'tableTrailerColor',
            tooltipTitle: 'tableTrailerName',
            progress: null,
            hoverTemplate: false,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
            svgUrl: 'assets/svg/common/trailers/',
            classField: 'tableTrailerTypeClass',
            svgDimensions: {
                width: 42,
                height: 18,
            },
            class: 'type-icon',
        },
        {
            ngTemplate: 'text',
            title: 'ft',
            field: 'tabelLength',
            groupName: 'Requirement',
            isPined: false,
            name: 'Length',
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: 'assets/svg/truckassist-table/length-icon.svg',
            },
            headAlign: 'center',
            sortName: LoadSortBy.TrailerLength,
            hidden: true,
            width: 34,
            minWidth: 34,
            pdfWidth: 10,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            colorTemplate: {
                value: 'doc.additionalData.color.value',
            },
            opacityIgnore: true,
            class: 'overflow-unset',
        },
        {
            ngTemplate: 'text',
            title: 'Door',
            field: 'tableDoorType',
            name: 'Door Type',
            groupName: 'Requirement',
            sortName: 'doorType',
            hidden: true,
            isPined: false,
            width: 110,
            minWidth: 110,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Suspension',
            field: 'tableSuspension',
            name: 'Suspension',
            groupName: 'Requirement',
            sortName: LoadSortBy.Suspension,
            hidden: true,
            isPined: false,
            width: 100,
            minWidth: 100,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Year',
            field: 'year',
            name: 'Year',
            groupName: 'Requirement',
            sortName: LoadSortBy.Year,
            isPined: false,
            hidden: true,
            width: 60,
            minWidth: 60,
            pdfWidth: 10,
            filter: '',
            isNumeric: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Liftgate',
            field: 'liftgate',
            name: 'Liftgate',
            groupName: 'Requirement',
            sortName: 'liftgate',
            isPined: false,
            hidden: true,
            width: 78,
            minWidth: 78,
            pdfWidth: 10,
            filter: '',
            isNumeric: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Driver Message',
            field: 'textDriver',
            name: 'Driver Message',
            sortName: LoadSortBy.DriverMessage,
            hidden: true,
            width: 234,
            minWidth: 234,
            filter: '',
            isNumeric: false,
            index: 15,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: ' Loaded ',
            field: 'loaded',
            name: 'Loaded',
            groupName: 'Miles ',
            sortName: 'loaded',
            hidden: true,
            isPined: false,
            width: 100,
            minWidth: 100,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 6,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Empty',
            field: 'empty',
            groupName: 'Miles ',
            name: 'Empty',
            hidden: true,
            isPined: false,
            width: 107,
            minWidth: 107,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: ' Total ',
            field: 'total',
            name: 'Total',
            groupName: 'Miles ',
            sortName: 'total',
            hidden: false,
            isPined: false,
            width: 100,
            minWidth: 100,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },

        {
            ngTemplate: 'text-paid',
            title: ' Rate ',
            field: 'rate',
            name: 'Rate',
            sortName: 'rate',
            groupName: 'Billing ',
            hidden: false,
            isPined: false,
            width: 101,
            minWidth: 101,
            filter: '',
            isNumeric: false,
            index: 8,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Paid',
            field: 'paid',
            name: 'Paid',
            groupName: 'Billing ',
            sortName: 'paid',
            hidden: true,
            isPined: false,
            width: 101,
            minWidth: 101,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },

        {
            ngTemplate: 'text',
            title: 'Date',
            field: 'tableAdded',
            name: 'Date Created',
            sortName: LoadSortBy.AddedDate,
            hidden: false,
            isPined: false,
            width: 88,
            minWidth: 88,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Edited',
            field: 'tableEdited',
            name: 'Date Edited',
            sortName: LoadSortBy.EditedDate,
            hidden: true,
            isPined: false,
            width: 88,
            minWidth: 88,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'note',
            title: 'Note',
            field: 'note',
            name: '',
            hidden: false,
            width: 26,
            minWidth: 26,
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: 'assets/svg/truckassist-table/note/Note.svg',
            },
            filter: '',
            isNumeric: false,
            index: 17,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            hidden: false,
            width: 26,
            minWidth: 26,
            headIconStyle: {
                width: 22,
                height: 6,
                imgPath: '',
            },
            filter: '',
            isNumeric: false,
            index: 18,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}

export function getLoadActiveAndPendingColumnDefinition() {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: '',
            hidden: false,
            width: 32,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'invoice',
            title: 'Load No.',
            field: 'loadInvoice',
            sortName: LoadSortBy.LoadNumber,
            name: 'Load No.',
            hidden: false,
            width: 100,
            minWidth: 100,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: true,
            export: true,
            resizable: true,
            link: {
                routerLinkStart: '/list/load/',
                routerLinkEnd: '/details',
            },
        },
        {
            ngTemplate: 'dispatcher-avatar',
            title: 'Dispatcher',
            field: 'loadDispatcher',
            name: 'Dispatcher',
            sortName: LoadSortBy.Dispatcher,
            hidden: false,
            width: 208,
            minWidth: 208,
            filter: '',
            isNumeric: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'customer-name',
            title: 'Bussiness Name',
            field: 'loadBroker',
            name: 'Bussiness Name   ',
            groupName: 'Broker Detail',
            sortName: LoadSortBy.BrokerBusinessName,
            hidden: false,
            width: 238,
            minWidth: 238,
            filter: '',
            isNumeric: true,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Contact',
            field: 'contact',
            name: 'Contact',
            groupName: 'Broker Detail',
            sortName: LoadSortBy.BrokerContactName,
            hidden: true,
            width: 192,
            minWidth: 192,
            filter: '',
            isNumeric: true,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Phone',
            field: 'phone',
            name: 'Phone',
            groupName: 'Broker Detail',
            sortName: LoadSortBy.BrokerContactPhone,
            isPined: false,
            hidden: true,
            width: 128,
            minWidth: 128,
            filter: '',
            isNumeric: true,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Ref #',
            field: 'referenceNumber',
            name: 'Ref Number',
            sortName: 'referenceNumber',
            hidden: false,
            width: 86,
            minWidth: 86,
            filter: '',
            isNumeric: true,
            index: 3,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Commodity',
            field: 'textCommodity',
            name: 'Commodity',
            sortName: 'commodity',
            hidden: true,
            width: 122,
            minWidth: 122,
            filter: '',
            isNumeric: true,
            index: 8,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Weight',
            field: 'textWeight',
            name: 'Weight',
            sortName: LoadSortBy.Weight,
            hidden: true,
            width: 86,
            minWidth: 86,
            filter: '',
            isNumeric: false,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'avatar-assign',
            title: 'Driver',
            field: 'tableDriver',
            name: 'Driver',
            groupName: 'Assigned',
            sortName: 'driver',
            hidden: true,
            isPined: false,
            width: 200,
            minWidth: 200,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,

            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
            class: 'overflow-unset',
        },
        {
            ngTemplate: 'text-assigned',
            title: 'Truck',
            field: 'tableAssignedUnitTruck',
            name: 'Truck',
            groupName: 'Assigned',
            sortName: 'truck',
            hidden: false,
            isPined: false,
            width: 80,
            minWidth: 80,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text-assigned',
            title: 'Trailer',
            field: 'tableAssignedUnitTrailer',
            isPined: false,
            name: 'Trailer',
            groupName: 'Assigned',
            sortName: 'trailer',
            hidden: false,
            width: 100,
            minWidth: 100,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'status',
            title: 'Status',
            field: 'loadStatus',
            name: 'Status',
            sortName: LoadSortBy.Status,
            setCenter: false,
            hidden: false,
            width: 138,
            minWidth: 138,
            filter: '',
            isNumeric: true,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'pickup',
            title: 'Pickup',
            field: 'loadPickup',
            name: 'Pickup',
            sortName: 'pickup',
            pickupDeliveryType: 'pickup',
            hidden: false,
            width: 153,
            minWidth: 153,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: 'assets/svg/common/ic_pickup.svg',
                customClass: 'pickup-icon',
            },
        },
        {
            ngTemplate: 'delivery',
            title: 'Delivery',
            field: 'loadPickup',
            name: 'Delivery',
            sortName: 'pickup',
            pickupDeliveryType: 'pickup',
            hidden: false,
            width: 153,
            minWidth: 153,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: 'assets/svg/common/ic_delivery.svg',
                customClass: 'delivery-icon',
            },
        },
        {
            ngTemplate: 'svg',
            title: ' Truck ',
            field: 'loadTruckNumber',
            groupName: 'Requirement',
            name: 'Truck Type',
            sortName: LoadSortBy.TruckType,
            hidden: true,
            width: 70,
            minWidth: 70,
            filter: '',
            isNumeric: true,
            index: 5,
            margin: -10,
            padding: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            tooltipColor: 'tableTruckColor',
            tooltipTitle: 'tableTruckName',

            export: true,
            resizable: true,
            svgUrl: 'assets/svg/common/trucks/',
            classField: 'truckTypeClass',
            svgDimensions: {
                width: 42,
                height: 18,
            },
            class: 'type-icon',
        },
        {
            ngTemplate: 'svg',
            title: 'Trailer',
            field: 'loadTrailerNumber',
            name: 'Trailer Type',
            groupName: 'Requirement',
            sortName: LoadSortBy.TrailerType,
            hidden: true,
            width: 80,
            minWidth: 80,
            margin: -8,
            padding: 8,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            tooltipColor: 'tableTrailerColor',
            tooltipTitle: 'tableTrailerName',
            progress: null,
            hoverTemplate: false,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
            svgUrl: 'assets/svg/common/trailers/',
            classField: 'tableTrailerTypeClass',
            svgDimensions: {
                width: 42,
                height: 18,
            },
            class: 'type-icon',
        },
        {
            ngTemplate: 'text',
            title: 'ft',
            field: 'tabelLength',
            groupName: 'Requirement',
            isPined: false,
            name: 'Length',
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: 'assets/svg/truckassist-table/length-icon.svg',
            },
            headAlign: 'center',
            sortName: LoadSortBy.TrailerLength,
            hidden: true,
            width: 34,
            minWidth: 34,
            pdfWidth: 10,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            colorTemplate: {
                value: 'doc.additionalData.color.value',
            },
            opacityIgnore: true,
            class: 'overflow-unset',
        },
        {
            ngTemplate: 'text',
            title: 'Door',
            field: 'tableDoorType',
            name: 'Door Type',
            groupName: 'Requirement',
            sortName: 'doorType',
            hidden: true,
            isPined: false,
            width: 110,
            minWidth: 110,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Suspension',
            field: 'tableSuspension',
            name: 'Suspension',
            groupName: 'Requirement',
            sortName: LoadSortBy.Suspension,
            hidden: true,
            isPined: false,
            width: 100,
            minWidth: 100,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Year',
            field: 'year',
            name: 'Year',
            groupName: 'Requirement',
            sortName: LoadSortBy.Year,
            isPined: false,
            hidden: true,
            width: 60,
            minWidth: 60,
            pdfWidth: 10,
            filter: '',
            isNumeric: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Liftgate',
            field: 'liftgate',
            name: 'Liftgate',
            groupName: 'Requirement',
            sortName: 'liftgate',
            isPined: false,
            hidden: true,
            width: 78,
            minWidth: 78,
            pdfWidth: 10,
            filter: '',
            isNumeric: true,
            index: 2,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },

        {
            ngTemplate: 'text',
            title: 'Driver Message',
            field: 'textDriver',
            name: 'Driver Message',
            sortName: LoadSortBy.DriverMessage,
            hidden: true,
            width: 234,
            minWidth: 234,
            filter: '',
            isNumeric: false,
            index: 15,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: ' Loaded ',
            field: 'loaded',
            name: 'Loaded',
            groupName: 'Miles ',
            sortName: 'loaded',
            hidden: true,
            isPined: false,
            width: 100,
            minWidth: 100,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 6,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Empty',
            field: 'empty',
            groupName: 'Miles ',
            name: 'Empty',
            hidden: true,
            isPined: false,
            width: 107,
            minWidth: 107,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: ' Total ',
            field: 'total',
            name: 'Total',
            groupName: 'Miles ',
            sortName: 'total',
            hidden: false,
            isPined: false,
            width: 100,
            minWidth: 100,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },

        {
            ngTemplate: 'text-paid',
            title: ' Rate ',
            field: 'rate',
            name: 'Rate',
            sortName: 'rate',
            groupName: 'Billing ',
            hidden: false,
            isPined: false,
            width: 101,
            minWidth: 101,
            filter: '',
            isNumeric: false,
            index: 8,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Paid',
            field: 'paid',
            name: 'Paid ',
            groupName: 'Billing ',
            sortName: 'paid',
            hidden: true,
            isPined: false,
            width: 101,
            minWidth: 101,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 9,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },

        {
            ngTemplate: 'text',
            title: 'Date',
            field: 'tableAdded',
            name: 'Date Created',
            sortName: LoadSortBy.AddedDate,
            hidden: true,
            isPined: false,
            width: 88,
            minWidth: 88,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Edited',
            field: 'tableEdited',
            name: 'Date Edited',
            sortName: LoadSortBy.EditedDate,
            hidden: true,
            isPined: false,
            width: 88,
            minWidth: 88,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'attachments',
            title: 'Attachments',
            field: 'tableAttachments',
            moveRight: true,
            name: '',
            hidden: false,
            width: 46,
            minWidth: 46,
            filter: '',
            isNumeric: false,
            index: 16,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'comment',
            title: 'Comment',
            field: 'loadComment',
            name: '',
            hidden: false,
            width: 32,
            minWidth: 32,
            filter: '',
            isNumeric: false,
            index: 17,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'note',
            title: 'Note',
            field: 'note',
            name: '',
            hidden: false,
            width: 26,
            minWidth: 26,
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: 'assets/svg/truckassist-table/note/Note.svg',
            },
            filter: '',
            isNumeric: false,
            index: 17,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            hidden: false,
            width: 26,
            minWidth: 26,
            headIconStyle: {
                width: 22,
                height: 6,
                imgPath: '',
            },
            filter: '',
            isNumeric: false,
            index: 18,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}

export function getLoadClosedColumnDefinition(): ITableColummn[] {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: '',
            hidden: false,
            width: 32,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'invoice',
            title: 'Invoice No.',
            field: 'loadInvoice',
            sortName: LoadSortBy.LoadNumber,
            name: 'Invoice No.',
            hidden: false,
            width: 120,
            minWidth: 120,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            link: {
                routerLinkStart: '/list/load/',
                routerLinkEnd: '/details',
            },
        },
        {
            ngTemplate: 'dispatcher-avatar',
            title: 'Dispatcher',
            field: 'loadDispatcher',
            name: 'Dispatcher',
            sortName: LoadSortBy.Dispatcher,
            hidden: false,
            width: 208,
            minWidth: 208,
            filter: '',
            isNumeric: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'customer-name',
            title: 'Bussiness Name',
            field: 'loadBroker',
            name: 'Bussiness Name   ',
            groupName: 'Broker Detail',
            sortName: LoadSortBy.BrokerBusinessName,
            hidden: false,
            width: 238,
            minWidth: 238,
            filter: '',
            isNumeric: true,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Contact',
            field: 'contact',
            name: 'Contact',
            groupName: 'Broker Detail',
            sortName: LoadSortBy.BrokerContactName,
            hidden: true,
            width: 192,
            minWidth: 192,
            filter: '',
            isNumeric: true,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Phone',
            field: 'phone',
            name: 'Phone',
            groupName: 'Broker Detail',
            sortName: LoadSortBy.BrokerContactPhone,
            isPined: false,
            hidden: true,
            width: 128,
            minWidth: 128,
            filter: '',
            isNumeric: true,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Ref #',
            field: 'referenceNumber',
            name: 'Ref Number',
            sortName: 'referenceNumber',
            hidden: false,
            width: 86,
            minWidth: 86,
            filter: '',
            isNumeric: true,
            index: 3,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Commodity',
            field: 'textCommodity',
            name: 'Commodity',
            sortName: 'commodity',
            hidden: true,
            width: 122,
            minWidth: 122,
            filter: '',
            isNumeric: true,
            index: 8,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Weight',
            field: 'textWeight',
            name: 'Weight',
            sortName: LoadSortBy.Weight,
            hidden: true,
            width: 86,
            minWidth: 86,
            filter: '',
            isNumeric: false,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'avatar-assign',
            title: 'Driver',
            field: 'tableDriver',
            name: 'Driver',
            groupName: 'Assigned',
            sortName: 'driver',
            hidden: true,
            isPined: false,
            width: 200,
            minWidth: 200,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
            class: 'overflow-unset',
        },
        {
            ngTemplate: 'text-assigned',
            title: 'Truck',
            field: 'tableAssignedUnitTruck',
            name: 'Truck',
            groupName: 'Assigned',
            sortName: 'truck',
            hidden: true,
            isPined: false,
            width: 80,
            minWidth: 80,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text-assigned',
            title: 'Trailer',
            field: 'tableAssignedUnitTrailer',
            isPined: false,
            name: 'Trailer',
            groupName: 'Assigned',
            sortName: 'trailer',
            hidden: true,
            width: 100,
            minWidth: 100,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'status',
            title: 'Status',
            field: 'loadStatus',
            name: 'Status',
            sortName: LoadSortBy.Status,
            setCenter: false,
            hidden: false,
            width: 138,
            minWidth: 138,
            filter: '',
            isNumeric: true,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'pickup',
            title: 'Pickup',
            field: 'loadPickup',
            name: 'Pickup',
            sortName: 'pickup',
            pickupDeliveryType: 'pickup',
            hidden: false,
            width: 153,
            minWidth: 153,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: 'assets/svg/common/ic_pickup.svg',
                customClass: 'pickup-icon',
            },
        },
        {
            ngTemplate: 'delivery',
            title: 'Delivery',
            field: 'loadPickup',
            name: 'Delivery',
            sortName: 'pickup',
            pickupDeliveryType: 'pickup',
            hidden: false,
            width: 153,
            minWidth: 153,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: 'assets/svg/common/ic_delivery.svg',
                customClass: 'delivery-icon',
            },
        },
        {
            ngTemplate: 'svg',
            title: ' Truck ',
            field: 'loadTruckNumber',
            groupName: 'Requirement',
            name: 'Truck Type',
            sortName: LoadSortBy.TruckType,
            hidden: true,
            width: 70,
            minWidth: 70,
            filter: '',
            isNumeric: true,
            index: 5,
            margin: -10,
            padding: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            tooltipColor: 'tableTruckColor',
            tooltipTitle: 'tableTruckName',

            export: true,
            resizable: true,
            svgUrl: 'assets/svg/common/trucks/',
            classField: 'truckTypeClass',
            svgDimensions: {
                width: 42,
                height: 18,
            },
            class: 'type-icon',
        },
        {
            ngTemplate: 'svg',
            title: 'Trailer',
            field: 'loadTrailerNumber',
            name: 'Trailer Type',
            groupName: 'Requirement',
            sortName: LoadSortBy.TrailerType,
            hidden: true,
            width: 80,
            minWidth: 80,
            margin: -8,
            padding: 8,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            tooltipColor: 'tableTrailerColor',
            tooltipTitle: 'tableTrailerName',
            progress: null,
            hoverTemplate: false,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
            svgUrl: 'assets/svg/common/trailers/',
            classField: 'tableTrailerTypeClass',
            svgDimensions: {
                width: 42,
                height: 18,
            },
            class: 'type-icon',
        },
        {
            ngTemplate: 'text',
            title: 'ft',
            field: 'tabelLength',
            groupName: 'Requirement',
            isPined: false,
            name: 'Length',
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: 'assets/svg/truckassist-table/length-icon.svg',
            },
            headAlign: 'center',
            sortName: LoadSortBy.TrailerLength,
            hidden: true,
            width: 34,
            minWidth: 34,
            pdfWidth: 10,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            colorTemplate: {
                value: 'doc.additionalData.color.value',
            },
            opacityIgnore: true,
            class: 'overflow-unset',
        },
        {
            ngTemplate: 'text',
            title: 'Door',
            field: 'tableDoorType',
            name: 'Door Type',
            groupName: 'Requirement',
            sortName: 'doorType',
            hidden: true,
            isPined: false,
            width: 110,
            minWidth: 110,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Suspension',
            field: 'tableSuspension',
            name: 'Suspension',
            groupName: 'Requirement',
            sortName: LoadSortBy.Suspension,
            hidden: true,
            isPined: false,
            width: 100,
            minWidth: 100,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Year',
            field: 'year',
            name: 'Year',
            groupName: 'Requirement',
            sortName: LoadSortBy.Year,
            isPined: false,
            hidden: true,
            width: 60,
            minWidth: 60,
            pdfWidth: 10,
            filter: '',
            isNumeric: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Liftgate',
            field: 'liftgate',
            name: 'Liftgate',
            groupName: 'Requirement',
            sortName: 'liftgate',
            isPined: false,
            hidden: true,
            width: 78,
            minWidth: 78,
            pdfWidth: 10,
            filter: '',
            isNumeric: true,
            index: 2,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Driver Message',
            field: 'textDriver',
            name: 'Driver Message',
            sortName: LoadSortBy.DriverMessage,
            hidden: true,
            width: 234,
            minWidth: 234,
            filter: '',
            isNumeric: false,
            index: 15,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: ' Loaded ',
            field: 'loaded',
            name: 'Loaded',
            groupName: 'Miles ',
            sortName: 'loaded',
            hidden: true,
            isPined: false,
            width: 100,
            minWidth: 100,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 6,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Empty',
            field: 'empty',
            groupName: 'Miles ',
            name: 'Empty',
            hidden: true,
            isPined: false,
            width: 107,
            minWidth: 107,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: ' Total ',
            field: 'total',
            name: 'Total',
            groupName: 'Miles ',
            sortName: 'total',
            hidden: false,
            isPined: false,
            width: 100,
            minWidth: 100,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: ' Term',
            field: 'payTerm',
            name: 'Pay Term',
            groupName: 'Billing ',
            sortName: 'paid',
            hidden: true,
            isPined: false,
            width: 101,
            minWidth: 101,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Age unp.',
            field: 'ageUnpaid',
            name: 'Age - Unpaid',
            groupName: 'Billing ',
            sortName: 'paid',
            hidden: false,
            isPined: false,
            width: 101,
            minWidth: 101,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 9,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Age paid',
            field: 'agePaid',
            name: 'Age - Paid',
            groupName: 'Billing ',
            sortName: 'paid',
            hidden: true,
            isPined: false,
            width: 101,
            minWidth: 101,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 9,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text-paid',
            title: ' Rate',
            field: 'rate',
            name: 'Rate',
            sortName: 'rate',
            groupName: 'Billing ',
            hidden: false,
            isPined: false,
            width: 101,
            minWidth: 101,
            filter: '',
            isNumeric: false,
            index: 8,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Paid',
            field: 'paid',
            name: 'Paid',
            groupName: 'Billing ',
            sortName: 'paid',
            hidden: false,
            isPined: false,
            width: 101,
            minWidth: 101,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 9,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Due',
            field: 'due',
            name: 'Due',
            groupName: 'Billing ',
            headAlign: 'right',
            sortName: 'due',
            hidden: false,
            isPined: false,
            width: 101,
            minWidth: 101,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 9,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Invoiced',
            field: 'tableInvoice',
            name: 'Invoiced Date',
            sortName: LoadSortBy.InvoicedDate,
            hidden: false,
            isPined: false,
            width: 88,
            minWidth: 88,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Date Paid',
            field: 'tablePaid',
            name: 'Paid Date',
            sortName: LoadSortBy.PaidDate,
            hidden: true,
            isPined: false,
            width: 88,
            minWidth: 88,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Date',
            field: 'tableAdded',
            name: 'Date Created',
            sortName: LoadSortBy.AddedDate,
            hidden: true,
            isPined: false,
            width: 88,
            minWidth: 88,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Edited',
            field: 'tableEdited',
            name: 'Date Edited',
            sortName: LoadSortBy.EditedDate,
            hidden: true,
            isPined: false,
            width: 88,
            minWidth: 88,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'attachments',
            title: 'Attachments',
            field: 'tableAttachments',
            moveRight: true,
            name: '',
            hidden: false,
            width: 46,
            minWidth: 46,
            filter: '',
            isNumeric: false,
            index: 16,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'comment',
            title: 'Comment',
            field: 'loadComment',
            name: '',
            hidden: false,
            width: 32,
            minWidth: 32,
            filter: '',
            isNumeric: false,
            index: 17,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'note',
            title: 'Note',
            field: 'note',
            name: '',
            hidden: false,
            width: 26,
            minWidth: 26,
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: 'assets/svg/truckassist-table/note/Note.svg',
            },
            filter: '',
            isNumeric: false,
            index: 17,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            hidden: false,
            width: 26,
            minWidth: 26,
            headIconStyle: {
                width: 22,
                height: 6,
                imgPath: '',
            },
            filter: '',
            isNumeric: false,
            index: 18,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}
