// PM TRUCK COLUMN DEFINITION
export function getTruckPMColumnDefinition() {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: 'Select',
            hidden: false,
            isPined: true,
            width: 40,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'nameLink',
            title: 'UNIT',
            field: 'textUnit',
            name: 'Unit number',
            sortName: 'truckNumber',
            hidden: false,
            isPined: true,
            width: 80,
            pdfWidth: 10,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: true,
            export: true,
            resizable: true,
            linkField: {
                doesNotHaveRout: true,
                routerLinkStart: '/trucks/edit/',
                routerLinkEnd: '/detail',
            },
            link: {
                routerLinkStart: '/trucks/edit/',
                routerLinkEnd: '/detail',
            },
        },
        // {
        //     ngTemplate: 'text',
        //     title: 'MAKE',
        //     field: 'make',
        //     name: 'MAKE',
        //     sortName: 'make',
        //     hidden: true,
        //     isPined: false,
        //     width: 138,
        //     filter: '',
        //     isNumeric: true,
        //     isDate: true,
        //     index: 3,
        //     sortable: true,
        //     isActionColumn: false,
        //     isSelectColumn: false,
        //     progress: null,
        //     hoverTemplate: null,
        //     filterable: true,
        //     disabled: false,
        //     export: true,
        //     resizable: true,
        //     class: 'custom-font',
        // },
        {
            ngTemplate: 'svg',
            title: 'Type',
            field: 'truckTypeIcon',
            isPined: false,
            headAlign: 'center',
            name: 'Type',
            sortName: 'type',
            hidden: false,
            width: 58,
            minWidth: 66,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 2,
            sortable: true,
            tooltipColor: 'tableTruckColor',
            tooltipTitle: 'tableTruckName',
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: false,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            svgUrl: 'assets/svg/common/trucks/',
            classField: 'truckTypeClass',
            svgDimensions: {
                width: 42,
                height: 18,
            },
            class: 'type-icon',
        },
        {
            ngTemplate: 'text',
            title: 'ODO mi',
            field: 'textOdometear',
            name: 'Odometer',
            sortName: 'odometear',
            hidden: false,
            isPined: false,
            width: 78,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'SERVICED',
            field: 'lastService',
            name: 'Last Serviced Date',
            sortName: 'lastService',
            hidden: false,
            isPined: false,
            width: 95,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'REPAIR SHOP',
            field: 'repairShop',
            name: 'Repair Shop',
            sortName: 'repairShop',
            hidden: false,
            isPined: false,
            width: 238,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'OIL & FILTER',
            field: 'oilFilter',
            name: 'Engine Oil & Filter',
            sortName: 'oilFilter',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 6,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'AIR FILTER',
            field: 'airFilter',
            name: 'Air Filter',
            sortName: 'airFilter',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 7,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'TRANS.FLUID',
            field: 'transFluid',
            name: 'Transmission Fluid',
            sortName: 'transFluid',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 8,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'BELTS',
            field: 'belts',
            name: 'Belts',
            sortName: 'belts',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'ENG.TUNE-UP',
            field: 'engTuneUp',
            name: 'Engine Tune-Up',
            sortName: 'engTuneUp',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'ALIGNMENT',
            field: 'alignment',
            name: 'Alignment',
            sortName: 'alignment',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'BATTERY',
            field: 'battery',
            name: 'Battery',
            sortName: 'battery',
            hidden: true,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 12,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'BRAKE CHAMBER',
            field: 'brakeChamber',
            name: 'Brake Chamber',
            sortName: 'brakeChamber',
            hidden: true,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 13,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'OIL PUMP',
            field: 'oilPump',
            name: 'Oil Pump',
            sortName: 'oilPump',
            hidden: true,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 14,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'WATER PUMP',
            field: 'waterPump',
            name: 'Water Pump',
            sortName: 'waterPump',
            hidden: true,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 15,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'FUEL PUMP',
            field: 'fuelPump',
            name: 'Fuel Pump',
            sortName: 'fuelPump',
            hidden: true,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 16,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'AIR COMPRESSOR',
            field: 'airCompressor',
            name: 'Air Compressor',
            sortName: 'airCompressor',
            hidden: true,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 17,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'AC COMPRESSOR',
            field: 'acCompressor',
            name: 'AC Compressor',
            sortName: 'acCompressor',
            hidden: true,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 18,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'TURBO',
            field: 'turbo',
            name: 'Turbo',
            sortName: 'turbo',
            hidden: true,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 19,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'RADIATOR',
            field: 'radiator',
            name: 'Radiator',
            sortName: 'radiator',
            hidden: true,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 20,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        // {
        //     ngTemplate: 'progressMiles',
        //     title: 'CUSTOM TITLE',
        //     field: 'customTitle',
        //     name: 'Custom Title',
        //     sortName: 'customTitle',
        //     hidden: true,
        //     isPined: false,
        //     width: 150,
        //     minWidth: 101,
        //     filter: '',
        //     isNumeric: true,
        //     index: 21,
        //     sortable: true,
        //     isActionColumn: false,
        //     isSelectColumn: false,
        //     avatar: null,
        //     progress: {
        //         start: 'licenseData[0].startDate',
        //         end: 'licenseData[0].endDate',
        //     },
        //     hoverTemplate: null,
        //     filterable: false,
        //     disabled: false,
        //     export: true,
        //     resizable: true,
        // },
        {
            ngTemplate: 'note',
            title: 'Note',
            field: 'additionalData.note',
            name: '',
            hidden: false,
            width: 40,
            minWidth: 40,
            filter: '',
            isNumeric: false,
            index: 22,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            hidden: false,
            width: 40,
            filter: '',
            isNumeric: false,
            index: 23,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}

// PM TRAILER COLUMN DEFINITION
export function getTrailerPMColumnDefinition() {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: 'Select',
            hidden: false,
            isPined: true,
            width: 40,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'nameLink',
            title: 'UNIT',
            field: 'textUnit',
            name: 'Unit Number',
            sortName: 'trailerNumber',
            hidden: false,
            isPined: true,
            width: 90,
            pdfWidth: 10,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: true,
            export: true,
            resizable: true,
            linkField: {
                doesNotHaveRout: true,
                routerLinkStart: '/trucks/edit/',
                routerLinkEnd: '/detail',
            },
        },
        {
            ngTemplate: 'svg',
            title: 'Type',
            field: 'tableTrailerTypeIcon',
            isPined: false,
            headAlign: 'center',
            name: 'Type',
            sortName: 'type',
            hidden: false,
            width: 58,
            minWidth: 66,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 2,
            sortable: true,
            tooltipColor: 'tableTrailerColor',
            tooltipTitle: 'tableTrailerName',
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: false,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            svgUrl: 'assets/svg/common/trailers/',
            classField: 'trailerTypeClass',
            svgDimensions: {
                width: 42,
                height: 18,
            },
            class: 'type-icon',
        },
        {
            ngTemplate: 'text',
            title: 'ODO mi',
            field: 'textOdometer',
            name: 'Odometer',
            sortName: 'odometear',
            hidden: false,
            isPined: false,
            width: 78,
            filter: '',
            isNumeric: true,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'SERVICED',
            field: 'lastService',
            name: 'Last Serviced Date',
            sortName: 'lastService',
            hidden: false,
            isPined: false,
            width: 88,
            filter: '',
            isNumeric: true,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'REPAIR SHOP',
            field: 'repairShop',
            name: 'Repair Shop',
            sortName: 'repairShop',
            hidden: false,
            isPined: false,
            width: 238,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progress',
            title: 'GENERAL',
            field: 'general',
            name: 'General',
            sortName: 'general',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 6,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progress',
            title: 'REEFER UNIT',
            field: 'reeferUnit',
            name: 'Reefer Unit',
            sortName: 'reeferUnit',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 7,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progress',
            title: 'ALIGNMENT',
            field: 'alignment',
            name: 'Alignment',
            sortName: 'alignment',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 8,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progress',
            title: 'PTO PUMP',
            field: 'ptoPump',
            name: 'PTO Pump',
            sortName: 'ptoPump',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 101,
            filter: '',
            isNumeric: true,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: {
                start: 'licenseData[0].startDate',
                end: 'licenseData[0].endDate',
            },
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        // {
        //     ngTemplate: 'progressMiles',
        //     title: 'CUSTOM TITLE',
        //     field: 'customTitle',
        //     name: 'Custom Title',
        //     sortName: 'customTitle',
        //     hidden: true,
        //     isPined: false,
        //     width: 150,
        //     minWidth: 101,
        //     filter: '',
        //     isNumeric: true,
        //     index: 10,
        //     sortable: true,
        //     isActionColumn: false,
        //     isSelectColumn: false,
        //     avatar: null,
        //     progress: {
        //         start: 'licenseData[0].startDate',
        //         end: 'licenseData[0].endDate',
        //     },
        //     hoverTemplate: null,
        //     filterable: false,
        //     disabled: false,
        //     export: true,
        //     resizable: true,
        // },
        {
            ngTemplate: 'note',
            title: 'Note',
            field: 'additionalData.note',
            name: '',
            hidden: false,
            width: 40,
            minWidth: 40,
            filter: '',
            isNumeric: false,
            index: 11,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            hidden: false,
            width: 40,
            filter: '',
            isNumeric: false,
            index: 12,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}
