import { PmTableColumns } from '@pages/pm-truck-trailer/pages/pm-table/models/pm-table-columns.model';

// PM TRUCK COLUMN DEFINITION
export function getTruckPMColumnDefinition(): PmTableColumns[] {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: 'Select',
            hidden: false,
            isPined: true,
            width: 40,
            minWidth: 40,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: true,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'nameLink',
            title: 'UNIT',
            field: 'textUnit',
            name: 'Unit Number',
            sortName: 'truckNumber',
            hidden: false,
            isPined: true,
            width: 80,
            minWidth: 80,
            pdfWidth: 10,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: true,
            disabled: true,
            export: true,
            resizable: true,
            link: {
                doesNotHaveRout: true,
                routerLinkStart: '',
                routerLinkEnd: '',
            },
        },
        {
            ngTemplate: 'svg',
            title: 'Type',
            field: 'truckTypeIcon',
            isPined: false,
            headAlign: 'center',
            name: 'Type',
            sortName: 'type',
            hidden: false,
            width: 58,
            minWidth: 58,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 2,
            sortable: true,
            tooltipColor: 'tableTruckColor',
            tooltipTitle: 'tableTruckName',
            isActionColumn: false,
            isSelectColumn: false,
            hoverTemplate: false,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            svgUrl: 'assets/svg/common/trucks/',
            classField: 'truckTypeClass',
            svgDimensions: {
                width: 42,
                height: 18,
            },
            class: 'type-icon',
        },
        {
            ngTemplate: 'text',
            title: 'Make',
            field: 'textMake',
            name: 'Make',
            sortName: 'make',
            isPined: false,
            hidden: true,
            width: 110,
            minWidth: 110,
            pdfWidth: 15,
            filter: '',
            isNumeric: false,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            imageHover: {
                url: '/assets/img/svgs/truck/makers/',
                file: 'doc.additionalData.make.file',
            },
            class: 'make-icon',
        },
        {
            ngTemplate: 'text',
            title: 'Model',
            field: 'textModel',
            isPined: false,
            name: 'Model',
            sortName: 'model',
            hidden: true,
            width: 140,
            minWidth: 140,
            pdfWidth: 15,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Year',
            field: 'textYear',
            name: 'Year',
            sortName: 'year',
            isPined: false,
            hidden: true,
            width: 60,
            minWidth: 60,
            pdfWidth: 10,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'ODO mi',
            field: 'textOdometer',
            name: 'Odometer',
            sortName: 'textOdometer',
            hidden: false,
            isPined: false,
            width: 78,
            minWidth: 78,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 6,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'SERVICED',
            field: 'lastService',
            name: 'Last Serviced Date',
            sortName: 'lastService',
            hidden: false,
            isPined: false,
            width: 95,
            minWidth: 95,
            filter: '',
            isNumeric: true,
            isDate: true,
            index: 7,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Name',
            field: 'textRepairShop',
            name: 'Name',
            sortName: 'repairShop',
            tableHeadTitle: 'Name',
            groupName: 'Shop Detail',
            hidden: true,
            isPined: false,
            width: 238,
            minWidth: 238,
            filter: '',
            isNumeric: true,
            index: 8,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'ADDRESS',
            field: 'textRepairShopAddress',
            name: 'Address',
            sortName: 'address',
            groupName: 'Shop Detail',
            isPined: false,
            hidden: true,
            width: 320,
            minWidth: 320,
            filter: '',
            isNumeric: true,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'progressMiles',
            title: 'OIL & FILTER',
            field: 'oilFilter',
            name: 'Engine Oil & Filter',
            sortName: 'oilFilter',
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: 'assets/svg/common/repair-pm/oil_filters.svg',
            },
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            index: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'AIR FILTER',
            field: 'airFilter',
            name: 'Air Filter',
            sortName: 'airFilter',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'TRANS. FLUID',
            field: 'transFluid',
            name: 'Transmission Fluid',
            sortName: 'transFluid',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            index: 12,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'BELTS',
            field: 'belts',
            name: 'Belts',
            sortName: 'belts',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            index: 13,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'ENG. TUNE-UP',
            field: 'engTuneUp',
            name: 'Engine Tune-Up',
            sortName: 'engTuneUp',
            hidden: true,
            isPined: false,
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            index: 14,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'ALIGNMENT',
            field: 'alignment',
            name: 'Alignment',
            sortName: 'alignment',
            hidden: true,
            isPined: false,
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            index: 15,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'BATTERY',
            field: 'battery',
            name: 'Battery',
            sortName: 'battery',
            hidden: true,
            isPined: false,
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            index: 16,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'BRAKE CHAMBER',
            field: 'brakeChamber',
            name: 'Brake Chamber',
            sortName: 'brakeChamber',
            hidden: true,
            isPined: false,
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            index: 17,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'OIL PUMP',
            field: 'oilPump',
            name: 'Oil Pump',
            sortName: 'oilPump',
            hidden: true,
            isPined: false,
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            index: 18,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'WATER PUMP',
            field: 'waterPump',
            name: 'Water Pump',
            sortName: 'waterPump',
            hidden: true,
            isPined: false,
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            index: 19,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'FUEL PUMP',
            field: 'fuelPump',
            name: 'Fuel Pump',
            sortName: 'fuelPump',
            hidden: true,
            isPined: false,
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            index: 20,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'AIR COMPRESSOR',
            field: 'airCompressor',
            name: 'Air Compressor',
            sortName: 'airCompressor',
            hidden: true,
            isPined: false,
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            index: 21,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'AC COMPRESSOR',
            field: 'acCompressor',
            name: 'AC Compressor',
            sortName: 'acCompressor',
            hidden: true,
            isPined: false,
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            index: 22,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'TURBO',
            field: 'turbo',
            name: 'Turbo',
            sortName: 'turbo',
            hidden: true,
            isPined: false,
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            index: 23,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'RADIATOR',
            field: 'radiator',
            name: 'Radiator',
            sortName: 'radiator',
            hidden: true,
            isPined: false,
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            index: 24,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progressMiles',
            title: 'CUSTOM TITLE',
            field: 'customTitle',
            name: 'Custom Title',
            sortName: 'customTitle',
            hidden: true,
            isPined: false,
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            index: 24,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'note',
            title: 'Note',
            field: 'note',
            name: '',
            hidden: false,
            width: 26,
            minWidth: 26,
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: 'assets/svg/truckassist-table/note/Note.svg',
            },
            filter: '',
            isNumeric: false,
            index: 25,
            sortable: true,
            isActionColumn: true,
            isSelectColumn: false,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            hidden: false,
            width: 26,
            minWidth: 26,
            headIconStyle: {
                width: 22,
                height: 6,
                imgPath: '',
            },
            filter: '',
            isNumeric: false,
            index: 26,
            sortable: true,
            isActionColumn: true,
            isSelectColumn: false,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}

// PM TRAILER COLUMN DEFINITION
export function getTrailerPMColumnDefinition(): PmTableColumns[] {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: 'Select',
            hidden: false,
            isPined: true,
            width: 40,
            minWidth: 40,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: true,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'nameLink',
            title: 'UNIT',
            field: 'textUnit',
            name: 'Unit Number',
            sortName: 'trailerNumber',
            hidden: false,
            isPined: true,
            width: 90,
            minWidth: 90,
            pdfWidth: 10,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: true,
            disabled: true,
            export: true,
            resizable: true,
            link: {
                doesNotHaveRout: true,
                routerLinkStart: '',
                routerLinkEnd: '',
            },
        },
        {
            ngTemplate: 'svg',
            title: 'Type',
            field: 'tableTrailerTypeIcon',
            isPined: false,
            headAlign: 'center',
            name: 'Type',
            sortName: 'type',
            hidden: false,
            width: 58,
            minWidth: 58,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 2,
            sortable: true,
            tooltipColor: 'tableTrailerColor',
            tooltipTitle: 'tableTrailerName',
            isActionColumn: false,
            isSelectColumn: false,
            hoverTemplate: false,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            svgUrl: 'assets/svg/common/trailers/',
            classField: 'trailerTypeClass',
            svgDimensions: {
                width: 42,
                height: 18,
            },
            class: 'type-icon',
        },

        {
            ngTemplate: 'text',
            title: 'Make',
            field: 'textMake',
            name: 'Make',
            sortName: 'make',
            isPined: false,
            hidden: true,
            width: 110,
            minWidth: 110,
            pdfWidth: 15,
            filter: '',
            isNumeric: false,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            imageHover: {
                url: '/assets/img/svgs/truck/makers/',
                file: 'doc.additionalData.make.file',
            },
            class: 'make-icon',
        },
        {
            ngTemplate: 'text',
            title: 'Model',
            field: 'textModel',
            isPined: false,
            name: 'Model',
            sortName: 'model',
            hidden: true,
            width: 140,
            minWidth: 140,
            pdfWidth: 15,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Year',
            field: 'textYear',
            name: 'Year',
            sortName: 'year',
            isPined: false,
            hidden: true,
            width: 60,
            minWidth: 60,
            pdfWidth: 10,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'ODO mi',
            field: 'textOdometer',
            name: 'Odometer',
            sortName: 'odometear',
            hidden: false,
            isPined: false,
            width: 78,
            minWidth: 78,
            filter: '',
            isNumeric: true,
            index: 6,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'SERVICED',
            field: 'lastService',
            name: 'Last Serviced Date',
            sortName: 'lastService',
            hidden: false,
            isPined: false,
            width: 88,
            minWidth: 88,
            filter: '',
            isNumeric: true,
            index: 7,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Name',
            field: 'textRepairShop',
            name: 'Name',
            sortName: 'repairShop',
            groupName: 'Shop Detail',
            hidden: true,
            isPined: false,
            width: 238,
            minWidth: 238,
            filter: '',
            isNumeric: true,
            index: 8,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'ADDRESS',
            field: 'textRepairShopAddress',
            name: 'Address',
            sortName: 'address',
            groupName: 'Shop Detail',
            isPined: false,
            hidden: true,
            width: 320,
            minWidth: 320,
            filter: '',
            isNumeric: true,
            index: 9,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'progress',
            title: 'GENERAL',
            field: 'general',
            name: 'General',
            sortName: 'general',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            index: 10,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progress',
            title: 'REEFER UNIT',
            field: 'reeferUnit',
            name: 'Reefer Unit',
            sortName: 'reeferUnit',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progress',
            title: 'ALIGNMENT',
            field: 'alignment',
            name: 'Alignment',
            sortName: 'alignment',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            index: 12,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'progress',
            title: 'PTO PUMP',
            field: 'ptoPump',
            name: 'PTO Pump',
            sortName: 'ptoPump',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 150,
            filter: '',
            isNumeric: true,
            index: 13,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            filterable: false,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'note',
            title: 'Note',
            field: 'additionalData.note',
            name: '',
            hidden: false,
            width: 26,
            minWidth: 26,
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: 'assets/svg/truckassist-table/note/Note.svg',
            },
            filter: '',
            isNumeric: false,
            index: 14,
            sortable: true,
            isActionColumn: true,
            isSelectColumn: false,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            hidden: false,
            width: 26,
            minWidth: 26,
            headIconStyle: {
                width: 22,
                height: 6,
                imgPath: '',
            },
            filter: '',
            isNumeric: false,
            index: 15,
            sortable: true,
            isActionColumn: true,
            isSelectColumn: false,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}
