export function getToolsAccountsColumnDefinition() {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: 'Select',
            isComputed: true,
            hidden: false,
            isPined: true,
            width: 32,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'nameLink',
            title: 'Name',
            field: 'name',
            name: 'Name',
            sortName: 'name',
            isComputed: false,
            isPined: true,
            hidden: false,
            width: 200,
            minWidth: 200,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            link: {
                doesNotHaveRout: true,
                routerLinkStart: '/list/account/',
                routerLinkEnd: '/details',
            },
        },
        {
            ngTemplate: 'url',
            title: 'Url',
            field: 'url',
            name: 'Url',
            sortName: 'url',
            isPined: false,
            isComputed: false,
            hidden: false,
            width: 308,
            minWidth: 308,
            filter: '',
            isNumeric: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            navigateTo: true,
        },
        {
            ngTemplate: 'text',
            title: 'Username',
            field: 'username',
            name: 'Username',
            sortName: 'username',
            isPined: false,
            hidden: false,
            width: 208,
            minWidth: 208,
            filter: '',
            isNumeric: false,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            imageHover: null,
        },
        {
            ngTemplate: 'password',
            title: 'Password',
            field: 'accountPassword',
            name: 'Password',
            isComputed: false,
            isPined: false,
            hidden: false,
            width: 208,
            minWidth: 208,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            password: true,
        },
        {
            ngTemplate: 'label',
            title: 'Label',
            field: 'lable',
            name: 'Label',
            sortName: 'label',
            isPined: false,
            isComputed: false,
            hidden: false,
            width: 180,
            minWidth: 180,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: false,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            imageHover: null,
            showLabel: true,
        },
        {
            ngTemplate: 'note',
            title: 'Note',
            field: 'note',
            name: '',
            moveRight: true,
            hidden: false,
            width: 26,
            minWidth: 26,
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: 'assets/svg/truckassist-table/note/Note.svg',
            },
            filter: '',
            isNumeric: false,
            index: 7,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: true,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            hidden: false,
            width: 26,
            minWidth: 26,
            headIconStyle: {
                width: 22,
                height: 6,
                imgPath: '',
            },
            filter: '',
            isNumeric: true,
            index: 8,
            sortable: true,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: true,
            isAction: true,
        },
    ];
}
