export function getTrailerColumnDefinition() {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: 'Select',
            hidden: false,
            isPined: true,
            width: 32,
            pdfWidth: 32,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'nameLink',
            title: 'Unit',
            field: 'trailerNumber',
            name: 'Unit Number',
            isPined: true,
            hidden: false,
            sortName: 'unit',
            width: 100,
            minWidth: 100,
            pdfWidth: 10,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: true,
            export: true,
            resizable: true,
            link: {
                routerLinkStart: '/list/trailer/',
                routerLinkEnd: '/details',
            },
        },
        {
            ngTemplate: 'svg',
            title: 'Type',
            field: 'tableTrailerTypeIcon',
            name: 'Type',
            headAlign: 'center',
            sortName: 'type',
            isPined: false,
            hidden: false,
            width: 50,
            minWidth: 50,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 6,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            tooltipColor: 'tableTrailerColor',
            tooltipTitle: 'tableTrailerName',
            avatar: null,
            progress: null,
            hoverTemplate: false,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            svgUrl: 'assets/svg/common/trailers/',
            classField: 'tableTrailerTypeClass',
            svgDimensions: {
                width: 42,
                height: 18,
            },
            class: 'type-icon',
        },
        {
            ngTemplate: 'vin',
            title: 'VIN',
            field: 'tableVin',
            name: 'VIN',
            sortName: 'vin',
            hidden: false,
            isPined: false,
            width: 180,
            minWidth: 180,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 7,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Make',
            field: 'tableMake',
            name: 'Make',
            isPined: false,
            sortName: 'make',
            hidden: false,
            width: 120,
            minWidth: 120,
            pdfWidth: 15,
            filter: '',
            isNumeric: false,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            imageHover: {
                url: '/assets/img/svgs/trailer/makers/',
                file: 'doc.additionalData.make.file',
            },
            class: 'make-icon',
        },
        {
            ngTemplate: 'text',
            title: 'Model',
            field: 'tableModel',
            name: 'Model',
            sortName: 'model',
            hidden: false,
            isPined: false,
            width: 140,
            minWidth: 140,
            pdfWidth: 15,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Year',
            field: 'year',
            name: 'Year',
            sortName: 'year',
            isPined: false,
            hidden: false,
            width: 60,
            minWidth: 60,
            pdfWidth: 10,
            filter: '',
            isNumeric: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'color',
            title: 'Color',
            field: 'tableColor',
            isPined: false,
            name: '',
            headAlign: 'center',
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: 'assets/svg/truckassist-table/color-type.svg',
            },
            sortName: 'color',
            hidden: false,
            width: 34,
            minWidth: 34,
            pdfWidth: 10,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            colorTemplate: {
                value: 'doc.additionalData.color.value',
            },
            opacityIgnore: true,
            class: 'overflow-unset',
        },
        {
            ngTemplate: 'text',
            title: 'ft',
            field: 'tabelLength',
            isPined: false,
            name: 'Length',
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: 'assets/svg/truckassist-table/length-icon.svg',
            },
            headAlign: 'row-reverse',
            sortName: 'trailerLength',
            hidden: false,
            width: 34,
            minWidth: 34,
            pdfWidth: 10,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            colorTemplate: {
                value: 'doc.additionalData.color.value',
            },
            opacityIgnore: true,
            class: 'overflow-unset',
        },

        {
            ngTemplate: 'text',
            title: 'Driver',
            field: 'tableDriver',
            name: 'Driver',
            groupName: 'Assigned To ',
            sortName: 'driver',
            hidden: false,
            isPined: false,
            width: 200,
            minWidth: 200,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Truck',
            field: 'tableTruck',
            name: 'Truck',
            groupName: 'Assigned To ',
            sortName: 'truck',
            hidden: false,
            isPined: false,
            width: 80,
            minWidth: 80,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Owner',
            field: 'tableOwner',
            name: 'Owner',
            sortName: 'owner',
            hidden: true,
            isPined: false,
            width: 200,
            minWidth: 200,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Empty',
            field: 'tableWeightEmpty',
            name: 'Empty',
            sortName: 'emptyWeight',
            groupName: 'Weight ',
            hidden: true,
            isPined: false,
            width: 100,
            minWidth: 100,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Volume',
            field: 'tableWeightVolume',
            name: 'Volume',
            groupName: 'Weight ',
            sortName: 'volumeWeight',
            hidden: true,
            isPined: false,
            width: 100,
            minWidth: 100,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Axle',
            field: 'tableAxle',
            name: 'Axle',
            sortName: 'axles',
            hidden: true,
            isPined: false,
            width: 64,
            minWidth: 64,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Suspension',
            field: 'tableSuspension',
            name: 'Suspension',
            sortName: 'suspension',
            hidden: true,
            isPined: false,
            width: 100,
            minWidth: 100,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Tire Size',
            field: 'tableTireSize',
            name: 'Tire Size',
            sortName: 'tireSize',
            hidden: true,
            isPined: false,
            width: 82,
            minWidth: 82,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Reefer Unit',
            field: 'tableReeferUnit',
            name: 'Reefer Unit',
            sortName: 'reeferUnit',
            hidden: true,
            isPined: false,
            width: 100,
            minWidth: 100,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Door Type',
            field: 'tableDoorType',
            name: 'Door Type',
            sortName: 'doorType',
            hidden: true,
            isPined: false,
            width: 110,
            minWidth: 110,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Ins Policy',
            field: 'tableInsPolicy',
            name: 'Insurance Policy',
            sortName: 'insurancePolicy',
            hidden: true,
            isPined: false,
            width: 130,
            minWidth: 130,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Mileage',
            field: 'tableMileage',
            name: 'Mileage',
            sortName: 'mileage',
            hidden: true,
            isPined: false,
            width: 80,
            minWidth: 80,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Number  ',
            field: 'tableLicencePlateDetailNumber',
            name: 'Plate Number',
            sortName: 'licensePlate',
            groupName: 'Lic. Plate Detail ',
            hidden: false,
            isPined: false,
            width: 100,
            minWidth: 100,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'textState',
            title: 'State',
            field: 'tableLicencePlateDetailST',
            name: 'State Issued',
            groupName: 'Lic. Plate Detail ',
            sortName: 'st',
            hidden: true,
            isPined: false,
            width: 68,
            minWidth: 68,
            pdfWidth: 15,
            filter: '',
            isNumeric: false,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            filterable: true,
            hoverTemplate: {
                urlStart: '/assets/img/svgs/states/',
                field: 'registrationState.stateShortName',
                urlEnd: '.svg',
            },
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'progress',
            title: 'Expiration',
            field: 'tableLicencePlateDetailExpiration',
            name: 'Expiration',
            groupName: 'Lic. Plate Detail ',
            sortName: 'licenceExpiration',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 150,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Term',
            field: 'tableFHWAInspectionTerm',
            name: 'Term',
            groupName: 'FHWA Inspection ',
            sortName: 'fhwaTerm',
            hidden: true,
            isPined: false,
            width: 108,
            minWidth: 108,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'progress',
            title: 'Expiration',
            field: 'tableFHWAInspectionExpiration',
            name: 'Expiration',
            groupName: 'FHWA Inspection ',
            sortName: 'fhwaInspectionExpDate',
            hidden: false,
            isPined: false,
            width: 150,
            minWidth: 150,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'progress',
            title: 'Issued',
            field: 'tableFHWAInspectionIssueDate',
            name: 'Issue Date',
            groupName: 'FHWA Inspection ',
            sortName: 'issueDate',
            hidden: false,
            isPined: false,
            width: 130,
            minWidth: 130,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: ' Number',
            field: 'tableTitleNumber',
            name: 'Number',
            groupName: 'Title ',
            sortName: 'number',
            hidden: true,
            isPined: false,
            width: 120,
            minWidth: 120,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'textState',
            title: 'State',
            field: 'tableTitle',
            name: 'State Issued',
            groupName: 'Title ',
            sortName: 'st',
            hidden: true,
            isPined: false,
            width: 68,
            minWidth: 68,
            pdfWidth: 15,
            filter: '',
            isNumeric: false,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            filterable: true,
            disabled: false,
            hoverTemplate: {
                urlStart: '/assets/img/svgs/states/',
                field: 'title?.state?.stateShortName',
                urlEnd: '.svg',
            },
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Purchase',
            field: 'tableTitlePurchase',
            name: 'Purchase Date',
            groupName: 'Title ',
            sortName: 'purchaseDate',
            hidden: true,
            isPined: false,
            width: 88,
            minWidth: 88,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Issued',
            field: 'tableTitleIssued',
            name: 'Issue Date',
            groupName: 'Title ',
            sortName: 'issueDate',
            hidden: true,
            isPined: false,
            width: 80,
            minWidth: 80,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Price',
            field: 'tablePurchasePrice',
            name: 'Price',
            groupName: 'Purchase ',
            sortName: 'purchasePrice',
            hidden: true,
            isPined: false,
            width: 100,
            minWidth: 100,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Date',
            field: 'tablePurchaseDate',
            name: 'Date',
            groupName: 'Purchase ',
            sortName: 'purchaseDate',
            hidden: true,
            isPined: false,
            width: 80,
            minWidth: 80,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Deact',
            field: 'tableTerminated',
            name: 'Date Terminated',
            sortName: 'dateTerminated',
            hidden: true,
            isPined: false,
            width: 88,
            minWidth: 88,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Date',
            field: 'tableAdded',
            name: 'Date Added',
            sortName: 'createdAt',
            hidden: true,
            isPined: false,
            width: 88,
            minWidth: 88,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Edited',
            field: 'tableEdited',
            name: 'Date Edited',
            sortName: 'updatedAt',
            hidden: true,
            isPined: false,
            width: 88,
            minWidth: 88,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'attachments',
            title: 'Attachments',
            field: 'tableAttachments',
            moveRight: true,
            name: '',
            hidden: false,
            width: 46,
            minWidth: 46,
            filter: '',
            isNumeric: false,
            index: 16,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'note',
            title: 'Note',
            field: 'note',
            name: '',
            hidden: false,
            width: 26,
            minWidth: 26,
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: 'assets/svg/truckassist-table/note/Note.svg',
            },
            pdfWidth: 15,
            filter: '',
            isNumeric: false,
            index: 12,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            hidden: false,
            width: 26,
            minWidth: 26,
            headIconStyle: {
                width: 22,
                height: 6,
                imgPath: '',
            },
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 13,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}
