export function getTruckColumnDefinition() {
    return [
        {
            ngTemplate: 'checkbox',
            title: '',
            field: 'select',
            name: 'Select',
            isPined: true,
            hidden: false,
            width: 32,
            pdfWidth: 32,
            filter: '',
            isNumeric: false,
            index: 0,
            sortable: false,
            isActionColumn: false,
            isSelectColumn: true,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
        },
        {
            ngTemplate: 'nameLink',
            title: 'Unit',
            field: 'truckNumber',
            name: 'Unit Number',
            sortName: 'unit',
            isPined: true,
            hidden: false,
            width: 80,
            minWidth: 80,
            pdfWidth: 10,
            filter: '',
            isNumeric: false,
            index: 1,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: true,
            export: true,
            resizable: true,
            link: {
                routerLinkStart: '/list/truck/',
                routerLinkEnd: '/details',
            },
        },
        {
            ngTemplate: 'svg',
            title: 'Type',
            field: 'truckTypeIcon',
            isPined: false,
            headAlign: 'center',
            name: 'Type',
            sortName: 'type',
            hidden: false,
            width: 64,
            minWidth: 64,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 6,
            sortable: true,
            tooltipColor: 'tableTruckColor',
            tooltipTitle: 'tableTruckName',
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: false,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            svgUrl: 'assets/svg/common/trucks/',
            classField: 'truckTypeClass',
            svgDimensions: {
                width: 42,
                height: 18,
            },
            class: 'type-icon',
        },
        {
            ngTemplate: 'vin',
            title: 'VIN',
            field: 'tableVin',
            name: 'VIN',
            sortName: 'vin',
            isPined: false,
            hidden: false,
            width: 180,
            minWidth: 180,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 7,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            class: 'custom-font',
        },
        {
            ngTemplate: 'text',
            title: 'Make',
            field: 'textMake',
            name: 'Make',
            sortName: 'make',
            isPined: false,
            hidden: false,
            width: 110,
            minWidth: 110,
            pdfWidth: 15,
            filter: '',
            isNumeric: false,
            index: 3,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            imageHover: {
                url: '/assets/img/svgs/truck/makers/',
                file: 'doc.additionalData.make.file',
            },
            class: 'make-icon',
        },
        {
            ngTemplate: 'text',
            title: 'Model',
            field: 'textModel',
            isPined: false,
            name: 'Model',
            sortName: 'model',
            hidden: false,
            width: 140,
            minWidth: 140,
            pdfWidth: 15,
            filter: '',
            isNumeric: false,
            index: 4,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Year',
            field: 'textYear',
            name: 'Year',
            sortName: 'year',
            isPined: false,
            hidden: false,
            width: 60,
            minWidth: 60,
            pdfWidth: 10,
            filter: '',
            isNumeric: true,
            index: 2,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
        },
        {
            ngTemplate: 'color',
            title: 'Color',
            field: 'tableColor',
            isPined: false,
            name: '',
            sortName: 'color',
            headAlign: 'center',
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: 'assets/svg/truckassist-table/color-type.svg',
            },
            hidden: false,
            width: 34,
            minWidth: 34,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            colorTemplate: {
                value: 'doc.additionalData.color.value',
            },
            opacityIgnore: true,
            class: 'overflow-unset',
        },
        {
            ngTemplate: 'text',
            title: 'ft',
            field: 'tabelLength',
            isPined: false,
            name: 'Length',
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: 'assets/svg/truckassist-table/length-icon.svg',
            },
            headAlign: 'center',
            sortName: 'color',
            hidden: true,
            width: 34,
            minWidth: 34,
            pdfWidth: 10,
            filter: '',
            isNumeric: true,
            index: 5,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            colorTemplate: {
                value: 'doc.additionalData.color.value',
            },
            opacityIgnore: true,
            class: 'overflow-unset',
        },
        {
            ngTemplate: 'text',
            title: 'Assigned To Driver',
            field: 'tableDriver',
            isPined: false,
            name: 'Assigned To Driver',
            groupName: 'Assigned To ',
            sortName: 'driver',
            hidden: false,
            width: 200,
            minWidth: 200,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Assigned To Trailer',
            field: 'tableTrailer',
            isPined: false,
            name: 'Assigned To Trailer',
            groupName: 'Assigned To ',
            sortName: 'trailer',
            hidden: false,
            width: 100,
            minWidth: 100,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Owner Details Name',
            field: 'tabelOwnerDetailsName',
            isPined: false,
            name: 'Name',
            groupName: 'Owner Details',
            sortName: 'owner',
            hidden: true,
            width: 200,
            minWidth: 200,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Owner Details Commision',
            field: 'tabelOwnerDetailsComm',
            isPined: false,
            name: 'Commision',
            groupName: 'Owner Details',
            sortName: 'comm',
            hidden: true,
            width: 60,
            minWidth: 60,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Gross',
            field: 'textWeightGross',
            name: 'Gross',
            sortName: 'grossWeight',
            groupName: 'Weight ',
            isPined: false,
            hidden: true,
            width: 156,
            minWidth: 156,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Empty',
            field: 'textWeightEmpty',
            name: 'Empty',
            sortName: 'emptyWeight',
            groupName: 'Weight ',
            isPined: false,
            hidden: true,
            width: 90,
            minWidth: 90,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Model ',
            field: 'tabelEngineModel',
            name: 'Model ',
            sortName: 'engineType',
            groupName: 'Engine Detail',
            isPined: false,
            hidden: true,
            width: 180,
            minWidth: 180,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Oil Type',
            field: 'tabelEngineOilType',
            name: 'Oil Type',
            groupName: 'Engine Detail',
            sortName: 'engineOilType',
            isPined: false,
            hidden: true,
            width: 180,
            minWidth: 180,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: ' Model',
            field: 'tabelTransmissionModel',
            name: ' Model',
            groupName: 'Transmission ',
            sortName: 'transmissionModel',
            isPined: false,
            hidden: true,
            width: 156,
            minWidth: 156,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Shifter',
            field: 'tabelTransmissionShifter',
            name: 'Shifter',
            groupName: 'Transmission ',
            sortName: 'shifter',
            isPined: false,
            hidden: true,
            width: 84,
            minWidth: 84,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Gear Ratio',
            field: 'tabelTransmissionRatio',
            name: 'Gear Ratio',
            groupName: 'Transmission ',
            sortName: 'ratio',
            isPined: false,
            hidden: true,
            width: 46,
            minWidth: 46,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Type ',
            field: 'tabelFuelDetailsFuelType',
            name: 'Type',
            groupName: 'Fuel Detail',
            sortName: 'fuelType',
            isPined: false,
            hidden: true,
            width: 80,
            minWidth: 80,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Tank Size',
            field: 'tabelFuelDetailsTank',
            name: 'Tank Sizes',
            groupName: 'Fuel Detail',
            sortName: 'fuelTank',
            isPined: false,
            hidden: true,
            width: 50,
            minWidth: 50,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Axle',
            field: 'tabelAxle',
            name: 'Axle',
            sortName: 'axles',
            isPined: false,
            hidden: true,
            width: 40,
            minWidth: 40,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Brakes',
            field: 'tabelBrakes',
            name: 'Brakes',
            sortName: 'brakes',
            isPined: false,
            hidden: true,
            width: 60,
            minWidth: 60,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Tire Size',
            field: 'tableTireSize',
            name: 'Tire Size',
            sortName: 'tireSize',
            isPined: false,
            hidden: true,
            width: 82,
            minWidth: 82,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Front',
            field: 'tableWheelCompositionFront',
            name: 'Front Wheels',
            groupName: 'Wheel Detail ',
            sortName: 'frontWheels',
            isPined: false,
            hidden: true,
            width: 80,
            minWidth: 80,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Rear',
            field: 'tableWheelCompositionRear',
            name: 'Rear Wheels',
            groupName: 'Wheel Detail ',
            sortName: 'rearWheels',
            isPined: false,
            hidden: true,
            width: 80,
            minWidth: 80,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Base',
            field: 'tableWheelBase',
            name: 'Wheel Base',
            groupName: 'Wheel Detail ',
            sortName: 'wheelBase',
            isPined: false,
            hidden: true,
            width: 80,
            minWidth: 80,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'AP Unit',
            field: 'tableAPUnit',
            name: 'AP Unit',
            sortName: 'apUnit',
            isPined: false,
            hidden: true,
            width: 68,
            minWidth: 68,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'features',
            title: 'Features',
            field: 'tableFeatures',
            name: 'Features',
            sortName: 'features',
            isPined: false,
            hidden: true,
            width: 220,
            minWidth: 220,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            svgUrl: 'assets/svg/common/',
            svgDimensions: {
                width: 18,
                height: 18,
            },
            class: 'features-icon',
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Transponder',
            field: 'tableTollDeviceTransponder',
            name: 'Toll Transponder',
            groupName: 'Toll Device ',
            sortName: 'tollTransponder',
            isPined: false,
            hidden: true,
            width: 150,
            minWidth: 150,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Device No',
            field: 'tableTollDeviceNo',
            name: 'Device Number',
            groupName: 'Toll Device ',
            sortName: 'tollTransponderNo',
            isPined: false,
            hidden: true,
            width: 150,
            minWidth: 150,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Ins Policy',
            field: 'tableInsPolicy',
            name: 'Insurance Policy',
            sortName: 'insurancePolicy',
            isPined: false,
            hidden: true,
            width: 130,
            minWidth: 130,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Mileage',
            field: 'tableMileage',
            name: 'Mileage',
            sortName: 'mileage',
            isPined: false,
            hidden: false,
            width: 80,
            minWidth: 80,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Number  ',
            field: 'tableLicencePlateDetailNumber',
            name: 'Plate Number',
            sortName: 'licensePlate',
            groupName: 'Registration Detail ',
            isPined: false,
            hidden: false,
            width: 100,
            minWidth: 100,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'textState',
            title: 'State',
            field: 'tableLicencePlateDetailST',
            name: 'State Issued',
            groupName: 'Registration Detail ',
            sortName: 'st',
            isPined: false,
            hidden: true,
            width: 60,
            minWidth: 60,
            pdfWidth: 15,
            filter: '',
            isNumeric: false,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: {
                urlStart: '/assets/img/svgs/states/',
                field: 'registrationState',
                urlEnd: '.svg',
            },
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'progress',
            title: 'Expiration',
            field: 'tableLicencePlateDetailExpiration',
            name: 'Expiration',
            groupName: 'Registration Detail ',
            sortName: 'registrationExpiration',
            isPined: false,
            hidden: false,
            width: 130,
            minWidth: 130,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Term',
            field: 'tableFhwaInspectionTerm',
            name: 'Term',
            groupName: 'FHWA Inspection ',
            sortName: 'fhwaInspection',
            isPined: false,
            hidden: false,
            width: 108,
            minWidth: 108,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'progress',
            title: 'Expiration',
            field: 'tableFhwaInspectionExpiration',
            name: 'Expiration',
            groupName: 'FHWA Inspection ',
            sortName: 'fhwaExpiration',
            isPined: false,
            hidden: false,
            width: 130,
            minWidth: 130,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'progress',
            title: 'Issue Date',
            field: 'tableFhwaIssueDate',
            name: 'Issue Date',
            groupName: 'FHWA Inspection ',
            sortName: 'issueDate',
            isPined: false,
            hidden: false,
            width: 130,
            minWidth: 130,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: ' Number',
            field: 'tableTitleNumber',
            name: 'Number',
            groupName: 'Title ',
            sortName: 'titleNumber',
            isPined: false,
            hidden: true,
            width: 120,
            minWidth: 120,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'textState',
            title: 'State',
            field: 'tableTitleST',
            name: 'State Issued',
            groupName: 'Title ',
            sortName: 'titleStateIssued',
            isPined: false,
            hidden: true,
            width: 68,
            minWidth: 68,
            pdfWidth: 15,
            filter: '',
            isNumeric: false,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            filterable: true,
            disabled: false,
            hoverTemplate: {
                urlStart: '/assets/img/svgs/states/',
                field: 'titleState',
                urlEnd: '.svg',
            },
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Purchase',
            field: 'tableTitlePurchase',
            name: 'Purchase Date',
            groupName: 'Title ',
            sortName: 'purchaseDate',
            isPined: false,
            hidden: true,
            width: 88,
            minWidth: 88,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Issue',
            field: 'tableTitleIssued',
            name: 'Issue Date',
            groupName: 'Title ',
            sortName: 'titleIssueDate',
            isPined: false,
            hidden: true,
            width: 88,
            minWidth: 88,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Price',
            field: 'tablePurchasePrice',
            name: 'Price',
            groupName: 'Purchase Detail ',
            sortName: 'purchasePrice',
            isPined: false,
            hidden: true,
            width: 100,
            minWidth: 100,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Date',
            field: 'tablePurchaseDate',
            name: 'Date',
            groupName: 'Purchase Detail ',
            sortName: 'purchaseDate',
            isPined: false,
            hidden: true,
            width: 80,
            minWidth: 80,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Date Deactivated',
            field: 'tableTerminated',
            name: 'Date Deactivated',
            sortName: 'dateDeactivated',
            isPined: false,
            hidden: true,
            width: 100,
            minWidth: 100,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Date Added',
            field: 'tableAdded',
            name: 'Date Added',
            sortName: 'added',
            isPined: false,
            hidden: true,
            width: 80,
            minWidth: 80,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'text',
            title: 'Date Edited',
            field: 'tableEdited',
            name: 'Date Edited',
            sortName: 'edited',
            isPined: false,
            hidden: true,
            width: 80,
            minWidth: 80,
            pdfWidth: 15,
            filter: '',
            isNumeric: true,
            index: 11,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: true,
            linkField: null,
        },
        {
            ngTemplate: 'attachments',
            title: 'Attachments',
            field: 'tableAttachments',
            moveRight: true,
            name: '',
            hidden: false,
            width: 46,
            minWidth: 46,
            filter: '',
            isNumeric: false,
            index: 11,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'note',
            title: 'Note',
            field: 'note',
            name: '',
            hidden: false,
            width: 26,
            minWidth: 26,
            headIconStyle: {
                width: 14,
                height: 14,
                imgPath: 'assets/svg/truckassist-table/note/Note.svg',
            },
            filter: '',
            isNumeric: false,
            index: 11,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: true,
            disabled: false,
            export: true,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            headIconStyle: {
                width: 22,
                height: 6,
                imgPath: '',
            },
            hidden: false,
            width: 26,
            minWidth: 26,
            filter: '',
            isNumeric: false,
            index: 11,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            avatar: null,
            progress: null,
            hoverTemplate: null,
            filterable: false,
            disabled: false,
            export: false,
            resizable: false,
            isAction: true,
        },
    ];
}
