export function getUsersColumnDefinition() {
    return [
        {
            ngTemplate: 'user-checkbox',
            title: 'Checkbox',
            field: 'active',
            thSetCenter: true,
            name: '',
            hidden: false,
            width: 28,
            minWidth: 28,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: true,
            resizable: false,
        },
        {
            ngTemplate: 'user-avatar',
            title: 'Name',
            field: 'tableAvatar',
            name: 'Name',
            sortName: 'name',
            hidden: false,
            isPined: true,
            width: 200,
            minWidth: 100,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            resizable: true,
            link: {
                doesNotHaveRout: true,
                routerLinkStart: '/list/user/',
                routerLinkEnd: '/details',
            },
        },
        {
            ngTemplate: 'text',
            title: 'Department',
            field: 'tableTableDept',
            name: 'Department',
            sortName: 'departmentName',
            hidden: false,
            isPined: false,
            width: 130,
            minWidth: 60,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Office',
            field: 'tableTableOffice',
            name: 'Office',
            groupName: 'Employee Detail',
            sortName: 'companyOfficeName',
            hidden: false,
            isPined: false,
            width: 200,
            minWidth: 100,
            isNumeric: false,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Phone ',
            field: 'tableTablePhone',
            name: 'Phone ',
            groupName: 'Employee Detail',
            sortName: 'phone',
            hidden: false,
            isPined: false,
            width: 180,
            minWidth: 112,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: true,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Email ',
            field: 'email',
            name: 'Email ',
            groupName: 'Employee Detail',
            sortName: 'email',
            isPined: false,
            hidden: false,
            width: 220,
            minWidth: 150,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Phone',
            field: 'tablePersonalDetailsPhone',
            name: 'Phone',
            groupName: 'Personal Detail',
            sortName: 'personalPhone',
            isPined: false,
            hidden: true,
            width: 130,
            minWidth: 112,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Email',
            field: 'tablePersonalDetailsEmail',
            name: 'Email',
            groupName: 'Personal Detail',
            sortName: 'personalEmail',
            isPined: false,
            hidden: true,
            width: 220,
            minWidth: 150,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Address',
            field: 'tablePersonalDetailsAddress',
            name: 'Address',
            groupName: 'Personal Detail',
            sortName: 'address',
            isPined: false,
            hidden: true,
            width: 270,
            minWidth: 150,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            resizable: true,
        },
        {
            ngTemplate: 'user-status',
            title: 'Status',
            field: 'tableTableStatus',
            name: 'Status',
            sortName: 'status',
            isPined: false,
            hidden: false,
            width: 90,
            minWidth: 90,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            resizable: true,
            addFontToTableText: true,
        },
        {
            ngTemplate: 'user-activity',
            title: 'Activity',
            field: 'tableActivity',
            name: 'Activity',
            sortName: 'lastLogin',
            isPined: false,
            hidden: false,
            width: 118,
            minWidth: 118,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            resizable: true,
            addFontToTableText: true,
        },
        {
            ngTemplate: 'text',
            title: 'Bank Name',
            field: 'tableBillingDetailsBankName',
            name: 'Bank Name',
            groupName: 'Bank Detail',
            sortName: 'bankName',
            isPined: false,
            hidden: true,
            width: 120,
            minWidth: 120,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Routing',
            field: 'tableBillingDetailsRouting',
            name: 'Routing',
            groupName: 'Bank Detail',
            sortName: 'routing',
            isPined: false,
            hidden: true,
            width: 70,
            minWidth: 70,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            resizable: true,
        },
        {
            ngTemplate: 'password-account',
            title: 'Account',
            field: 'tableBillingDetailsAccount',
            name: 'Account',
            groupName: 'Bank Detail',
            sortName: 'account',
            isPined: false,
            hidden: true,
            width: 150,
            minWidth: 150,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Pay Type',
            field: 'tablePaymentDetailsType',
            name: 'Pay Type',
            groupName: 'Payroll Detail',
            sortName: 'payType',
            isPined: false,
            hidden: false,
            width: 140,
            minWidth: 92,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Form',
            field: 'formType',
            name: 'Form',
            groupName: 'Payroll Detail',
            sortName: 'is1099',
            fontWeight: '600',
            hidden: true,
            isPined: false,
            width: 60,
            minWidth: 60,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Comm',
            field: 'tablePaymentDetailsComm',
            name: 'Commission',
            groupName: 'Payroll Detail',
            sortName: 'commission',
            fontWeight: '600',
            hidden: false,
            isPined: false,
            width: 60,
            minWidth: 60,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            resizable: true,
        },
        {
            ngTemplate: 'semi-bold-text',
            title: 'Salary',
            field: 'tablePaymentDetailsSalary',
            name: 'Salary',
            groupName: 'Payroll Detail',
            sortName: 'salary',
            hidden: false,
            isPined: false,
            width: 100,
            minWidth: 100,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Hired',
            field: 'tableTableHired',
            name: 'Date Hired',
            sortName: 'hired',
            hidden: true,
            isPined: false,
            width: 80,
            minWidth: 66,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Deact',
            field: 'tableDeactivated',
            name: 'Date Deactivated',
            sortName: 'deactivated',
            hidden: true,
            isPined: false,
            width: 80,
            minWidth: 66,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Added',
            field: 'tableAdded',
            name: 'Date Added',
            sortName: 'added',
            isPined: false,
            hidden: true,
            width: 80,
            minWidth: 66,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            resizable: true,
        },
        {
            ngTemplate: 'text',
            title: 'Edited',
            field: 'tableEdited',
            name: 'Date Edited',
            sortName: 'edited',
            isPined: false,
            hidden: true,
            width: 80,
            minWidth: 66,
            sortable: true,
            isActionColumn: false,
            isSelectColumn: false,
            resizable: true,
        },
        {
            ngTemplate: 'note',
            title: 'Note',
            field: 'note',
            name: '',
            hidden: false,
            moveRight: true,
            width: 40,
            minWidth: 40,
            sortable: false,
            isActionColumn: true,
            isSelectColumn: false,
            resizable: false,
            isAction: true,
        },
        {
            ngTemplate: 'actions',
            title: 'Actions',
            field: 'action',
            name: '',
            hidden: false,
            width: 42,
            minWidth: 42,
            sortable: true,
            isActionColumn: true,
            isSelectColumn: false,
            resizable: false,
            isAction: true,
        },
    ];
}
