export enum DriverModalStringEnum {
    COMMISSION_SOLO = 'commissionSolo',
    COMMISSION_TEAM = 'commissionTeam',
    OFF_DUTY_LOCATION_ITEMS = 'offDutyLocationItems',
    BANK_ID = 'bankId',
    TWIC = 'twic',
    TWIC_EXP_DATE = 'twicExpDate',
    USE_CARRIERA_ACH = 'useCarrieraAch',
    PAYROLL_TYPE = 'payrollType',
    IS_OWNER = 'isOwner',
    OWNER_TYPE = 'ownerType',
    SSN = 'ssn',
    EMAIL = 'email',
    MVR_EXPIRATION = 'mvrExpiration',
    SOLO_DRIVER = 'soloDriver',
    SOLO_EMPTY_MILE = 'soloEmptyMile',
    SOLO_LOADED_MILE = 'soloLoadedMile',
    PER_MILE_SOLO = 'perMileSolo',
    SOLO_PER_STOP = 'soloPerStop',
    FLAT_RATE_SOLO = 'flatRateSolo',
    TEAM_DRIVER = 'teamDriver',
    TEAM_EMPTY_MILE = 'teamEmptyMile',
    TEAM_LOADED_MILE = 'teamLoadedMile',
    PER_MILE_TEAM = 'perMileTeam',
    TEAM_PER_STOP = 'teamPerStop',
    FLAT_RATE_TEAM = 'flatRateTeam',
    SOLO = 'Solo',
    SOLO_2 = 'solo',
    TEAM = 'Team',
    TEAM_2 = 'team',
    COMBINED = 'Combined',
    DRIVER_COMMISSION = 'driverCommission',
    ROUTING = 'routing',
    ACCOUNT = 'account',
    AVATAR = 'avatar',
    OWNER = 'owner',

    PER_MILE = 'Per Mile',
    COMMISSION = 'Commission',
    FLAT_RATE = 'Flat Rate',

    PAY_TYPE = 'paytype',
    BANK = 'bank',

    BASIC = 'Basic',
    ADDITIONAL = 'Additional',
    SOLE_PROPRIETOR = 'Sole Proprietor',
    COMPANY = 'Company',
    COMPANY_DRIVER = 'Company Driver',
    THIRD_PARTY_DRIVER = '3rd Party Driver',
    PROPRIETOR = 'Proprietor',
    SOLE_SPACE = 'Sole ',

    SQUARE = 'square',
    ZERO_PX = '0px',

    FILES = 'files',
    IMAGE = 'image',
    DROPZONE_FILES_URL = 'assets/svg/common/ic_files_dropzone.svg',
    DROPZONE_IMGAGE_URL = 'assets/svg/common/ic_image_dropzone.svg',
    DROPZONE_FILES_EXTENSION = 'application/pdf, image/png, image/jpeg, image/jpg',
    DROPZONE_IMAGE_EXTENSION = 'image/gif, image/jpeg, image/jpg, image/png',

    SAVE_AND_ADD_NEW = 'save and add new',
    ADD = 'add',
    DELETE = 'delete',
    TAG = 'tag',
    TAGS = 'tags',

    SMALL = 'small',
    MEDIUM = 'medium',

    ANIMATION_TWO_TABS_CLASS = '.animation-two-tabs',

    EMPTY_STRING = ' ',
}
