// enums
import { LoadSortBy, MilesStopSortBy } from 'appcoretruckassist';
import { eLoadStatusStringType } from '@pages/new-load/enums';

// interfaces
import { ITableColumn } from '@shared/components/new-table/interfaces';

export class LoadTableColumnsConfig {
    static getLoadTableColumns(
        selectedTab: eLoadStatusStringType
    ): ITableColumn[] {
        if (selectedTab === eLoadStatusStringType.TEMPLATE) {
            return this.templateColumns;
        } else if (selectedTab === eLoadStatusStringType.CLOSED) {
            return this.closedColumns;
        } else {
            return this.pendingOrActiveColumns;
        }
    }

    static templateColumns: ITableColumn[] = [
        {
            id: 1,
            key: 'select',
            label: '',
            pinned: 'left',
            width: 26,
            minWidth: 26,
            maxWidth: 26,
            isResizable: false,
            isDisabled: true,
            isChecked: true,
            hasSort: false,
        },
        {
            id: 2,
            key: 'templateName',
            label: 'Name',
            labelToolbar: 'Template name',
            pinned: 'left',
            width: 154,
            minWidth: 60,
            maxWidth: 250,
            isResizable: true,
            isDisabled: true,
            isChecked: true,
            hasSort: true,
        } /* 
        {
            id: 3,
            key: 'loadType',
            label: 'Type',
            labelToolbar: 'Type',
            pinned: null,
            width: 82,
            minWidth: 82,
            maxWidth: 82,
            isResizable: true,
            isChecked: true,
            hasSort: true,
        },
        {
            id: 4,
            key: 'loadDispatcher',
            label: 'Dispatcher',
            labelToolbar: 'Dispatcher',
            pinned: null,
            width: 208,
            minWidth: 50,
            maxWidth: 1020,
            isResizable: true,
            isChecked: true,
            hasSort: true,
            sortName: LoadSortBy.Dispatcher,
        },
        {
            id: 5,
            key: 'companyName',
            label: 'Company',
            labelToolbar: 'Company',
            pinned: null,
            width: 238,
            minWidth: 50,
            maxWidth: 1020,
            isResizable: true,
            isChecked: true,
            hasSort: true,
        },
        {
            key: 'brokerGroup',
            label: 'Broker',
            labelToolbar: 'Broker Detail',
            pinned: null,
            isChecked: true,
            columns: [
                {
                    id: 6,
                    key: 'brokerBusinessName',
                    label: 'Business Name',
                    labelToolbar: 'Business name',
                    width: 238,
                    minWidth: 50,
                    maxWidth: 1020,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: LoadSortBy.BrokerBusinessName,
                },
                {
                    id: 7,
                    key: 'brokerContact',
                    label: 'Contact',
                    labelToolbar: 'Contact',
                    width: 186,
                    minWidth: 50,
                    maxWidth: 550,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: LoadSortBy.BrokerContactName,
                },
                {
                    id: 8,
                    key: 'brokerPhone',
                    label: 'Phone',
                    labelToolbar: 'Phone',
                    width: 192,
                    minWidth: 154,
                    maxWidth: 224,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: LoadSortBy.BrokerContactPhone,
                },
            ],
        }  */,
        {
            key: 'loadDetailsGroup',
            label: '',
            labelToolbar: '',
            pinned: null,
            isChecked: true,
            columns: [
                {
                    id: 9,
                    key: 'referenceNumber',
                    label: 'REF NO',
                    labelToolbar: 'Ref Number',
                    width: 108,
                    minWidth: 64,
                    maxWidth: 160,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
                {
                    id: 10,
                    key: 'commodity',
                    label: 'Commodity',
                    labelToolbar: 'Commodity',
                    width: 138,
                    minWidth: 100,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
                {
                    id: 11,
                    key: 'weight',
                    label: 'Weight',
                    labelToolbar: 'Weight',
                    width: 88,
                    minWidth: 54,
                    maxWidth: 110,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: LoadSortBy.Weight,
                },
            ],
        } /*  ,
        {
            key: 'assignedGroup',
            label: 'Assigned',
            labelToolbar: 'Assigned',
            pinned: null,
            isChecked: true,
            columns: [
                {
                    id: 12,
                    key: 'assignedDriver',
                    label: 'Driver',
                    labelToolbar: 'Driver',
                    width: 208,
                    minWidth: 50,
                    maxWidth: 1020,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
                {
                    id: 13,
                    key: 'assignedDriverTruckNumber',
                    label: 'Truck',
                    labelToolbar: 'Truck',
                    width: 78,
                    minWidth: 30,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
                {
                    id: 14,
                    key: 'assignedDriverTrailerNumber',
                    label: 'Trailer',
                    labelToolbar: 'Trailer',
                    width: 88,
                    minWidth: 30,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
            ],
        } */,
        {
            key: 'requirementGroup',
            label: 'Req',
            labelToolbar: 'Requirement',
            pinned: null,
            isChecked: true,
            columns: [
                {
                    id: 15,
                    key: 'requirementTruck',
                    label: 'Truck',
                    labelToolbar: 'Truck Type',
                    width: 64,
                    minWidth: 50,
                    maxWidth: 220,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: LoadSortBy.TruckType,
                },
                {
                    id: 16,
                    key: 'requirementTrailer',
                    label: 'Trailer',
                    labelToolbar: 'Trailer Type',
                    width: 64,
                    minWidth: 50,
                    maxWidth: 220,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: LoadSortBy.TrailerType,
                },
                {
                    id: 17,
                    key: 'requirementLength',
                    label: '',
                    labelToolbar: 'Length',
                    width: 52,
                    minWidth: 32,
                    maxWidth: 70,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: LoadSortBy.TrailerLength,
                },
                {
                    id: 18,
                    key: 'requirementDoor',
                    label: 'Door',
                    labelToolbar: 'Door Type',
                    width: 90,
                    minWidth: 52,
                    maxWidth: 110,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
                {
                    id: 19,
                    key: 'requirementSuspension',
                    label: 'Suspension',
                    labelToolbar: 'Suspension',
                    width: 90,
                    minWidth: 45,
                    maxWidth: 110,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: LoadSortBy.Suspension,
                },
                {
                    id: 20,
                    key: 'requirementYear',
                    label: 'Year',
                    labelToolbar: 'Year',
                    width: 58,
                    minWidth: 50,
                    maxWidth: 64,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: LoadSortBy.Year,
                },
                {
                    id: 21,
                    key: 'requirementLiftgate',
                    label: 'Liftgate',
                    labelToolbar: 'Liftgate',
                    width: 72,
                    minWidth: 50,
                    maxWidth: 78,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
            ],
        } /*,
        {
            key: 'driverMessageGroup',
            label: '',
            labelToolbar: '',
            pinned: null,
            isChecked: true,
            columns: [
                {
                    id: 22,
                    key: 'driverMessage',
                    label: 'Driver Message',
                    labelToolbar: 'Driver Message',
                    width: 234,
                    minWidth: 100,
                    maxWidth: 310,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: LoadSortBy.DriverMessage,
                },
            ],
        },
        {
            key: 'milesGroup',
            label: 'Miles',
            labelToolbar: 'Miles',
            pinned: null,
            isChecked: true,
            columns: [
                {
                    id: 23,
                    key: 'milesLoaded',
                    label: 'Loaded',
                    labelToolbar: 'Loaded',
                    width: 78,
                    minWidth: 30,
                    maxWidth: 88,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: MilesStopSortBy.LoadedMiles,
                },
                {
                    id: 24,
                    key: 'milesEmpty',
                    label: 'Empty',
                    labelToolbar: 'Empty',
                    width: 78,
                    minWidth: 30,
                    maxWidth: 88,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: MilesStopSortBy.EmptyMiles,
                },
                {
                    id: 25,
                    key: 'milesTotal',
                    label: 'Total',
                    labelToolbar: 'Total',
                    width: 78,
                    minWidth: 30,
                    maxWidth: 88,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: MilesStopSortBy.TotalMiles,
                },
            ],
        },
        {
            key: 'billingGroup',
            label: 'Billing',
            labelToolbar: 'Billing',
            pinned: null,
            isChecked: true,
            columns: [
                {
                    id: 26,
                    key: 'billingRatePerMile',
                    label: 'RPM',
                    labelToolbar: 'Rate Per Mile',
                    width: 80,
                    minWidth: 50,
                    maxWidth: 80,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
                {
                    id: 27,
                    key: 'billingLayover',
                    label: 'Layover',
                    labelToolbar: 'Layover',
                    width: 101,
                    minWidth: 60,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
                {
                    id: 28,
                    key: 'billinglumper',
                    label: 'Lumper',
                    labelToolbar: 'Lumper',
                    width: 101,
                    minWidth: 60,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
                {
                    id: 29,
                    key: 'billingFuelSurcharge',
                    label: 'Fuel Surch',
                    labelToolbar: 'Fuel Surcharge',
                    width: 101,
                    minWidth: 60,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
                {
                    id: 30,
                    key: 'billingEscort',
                    label: 'Escort',
                    labelToolbar: 'Escort',
                    width: 101,
                    minWidth: 60,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
                {
                    id: 31,
                    key: 'billingDetention',
                    label: 'Detention',
                    labelToolbar: 'Detention',
                    width: 101,
                    minWidth: 60,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
                {
                    id: 32,
                    key: 'billingRate',
                    label: 'Rate',
                    labelToolbar: 'Rate',
                    width: 101,
                    minWidth: 60,
                    maxWidth: 140,
                    isResizable: true,
                    isAlignedRight: true,
                    isChecked: true,
                    hasSort: true,
                },
                {
                    id: 33,
                    key: 'billingPaid',
                    label: 'Paid',
                    labelToolbar: 'Paid',
                    width: 101,
                    minWidth: 60,
                    maxWidth: 140,
                    isResizable: true,
                    isAlignedRight: true,
                    isChecked: true,
                    hasSort: true,
                },
            ],
        },
        {
            id: 34,
            key: 'dateCreated',
            label: 'Created',
            labelToolbar: 'Date Created',
            pinned: null,
            width: 88,
            minWidth: 72,
            maxWidth: 88,
            isResizable: true,
            isChecked: true,
            hasSort: true,
            sortName: LoadSortBy.AddedDate,
        },
        {
            id: 35,
            key: 'dateEdited',
            label: 'Edited',
            labelToolbar: 'Date Edited',
            pinned: null,
            width: 88,
            minWidth: 72,
            maxWidth: 88,
            isResizable: true,
            isChecked: true,
            hasSort: true,
            sortName: LoadSortBy.EditedDate,
        }*/,
        {
            id: 36,
            key: 'note',
            label: '',
            labelToolbar: '',
            pinned: 'right',
            width: 26,
            minWidth: 26,
            isResizable: false,
            isDisabled: true,
            isChecked: true,
            hasSort: false,
        },
        {
            id: 37,
            key: 'action',
            label: '',
            labelToolbar: '',
            pinned: 'right',
            width: 26,
            minWidth: 26,
            isResizable: false,
            isChecked: true,
            isDisabled: true,
            hasSort: false,
        },
    ];

    static pendingOrActiveColumns: ITableColumn[] = [
        {
            id: 1,
            key: 'select',
            label: '',
            pinned: 'left',
            width: 26,
            minWidth: 26,
            maxWidth: 26,
            isResizable: false,
            isDisabled: true,
            isChecked: true,
            hasSort: false,
        },
        {
            id: 2,
            key: 'loadNumber',
            label: 'Load No',
            labelToolbar: 'Load No.',
            pinned: 'left',
            width: 154,
            minWidth: 60,
            maxWidth: 250,
            isResizable: true,
            isDisabled: true,
            isChecked: true,
            hasSort: true,
            sortName: LoadSortBy.LoadNumber,
        } /* ,
        {
            id: 3,
            key: 'loadType',
            label: 'Type',
            labelToolbar: 'Type',
            pinned: null,
            width: 82,
            minWidth: 82,
            maxWidth: 82,
            isResizable: true,
            isChecked: true,
            hasSort: true,
        },
        {
            id: 4,
            key: 'loadDispatcher',
            label: 'Dispatcher',
            labelToolbar: 'Dispatcher',
            pinned: null,
            width: 208,
            minWidth: 50,
            maxWidth: 1020,
            isResizable: true,
            isChecked: true,
            hasSort: true,
            sortName: LoadSortBy.Dispatcher,
        },
        {
            id: 5,
            key: 'companyName',
            label: 'Company',
            labelToolbar: 'Company',
            pinned: null,
            width: 238,
            minWidth: 50,
            maxWidth: 1020,
            isResizable: true,
            isChecked: true,
            hasSort: true,
        },
        {
            key: 'brokerGroup',
            label: 'Broker',
            labelToolbar: 'Broker Detail',
            pinned: null,
            isChecked: true,
            columns: [
                {
                    id: 6,
                    key: 'brokerBusinessName',
                    label: 'Business Name',
                    labelToolbar: 'Business name',
                    width: 238,
                    minWidth: 50,
                    maxWidth: 1020,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: LoadSortBy.BrokerBusinessName,
                },
                {
                    id: 7,
                    key: 'brokerContact',
                    label: 'Contact',
                    labelToolbar: 'Contact',
                    width: 186,
                    minWidth: 50,
                    maxWidth: 550,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: LoadSortBy.BrokerContactName,
                },
                {
                    id: 8,
                    key: 'brokerPhone',
                    label: 'Phone',
                    labelToolbar: 'Phone',
                    width: 192,
                    minWidth: 154,
                    maxWidth: 224,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: LoadSortBy.BrokerContactPhone,
                },
            ],
        },
        {
            key: 'loadDetailsGroup',
            label: '',
            labelToolbar: '',
            pinned: null,
            isChecked: true,
            columns: [
                {
                    id: 9,
                    key: 'referenceNumber',
                    label: 'REF NO',
                    labelToolbar: 'Ref Number',
                    width: 108,
                    minWidth: 64,
                    maxWidth: 160,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
                {
                    id: 10,
                    key: 'commodity',
                    label: 'Commodity',
                    labelToolbar: 'Commodity',
                    width: 138,
                    minWidth: 100,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
                {
                    id: 11,
                    key: 'weight',
                    label: 'Weight',
                    labelToolbar: 'Weight',
                    width: 88,
                    minWidth: 54,
                    maxWidth: 110,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: LoadSortBy.Weight,
                },
            ],
        } ,
        {
            key: 'assignedGroup',
            label: 'Assigned',
            labelToolbar: 'Assigned',
            pinned: null,
            isChecked: true,
            columns: [
                {
                    id: 12,
                    key: 'assignedDriver',
                    label: 'Driver',
                    labelToolbar: 'Driver',
                    width: 208,
                    minWidth: 50,
                    maxWidth: 1020,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
                {
                    id: 13,
                    key: 'assignedDriverTruckNumber',
                    label: 'Truck',
                    labelToolbar: 'Truck',
                    width: 78,
                    minWidth: 30,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
                {
                    id: 14,
                    key: 'assignedDriverTrailerNumber',
                    label: 'Trailer',
                    labelToolbar: 'Trailer',
                    width: 88,
                    minWidth: 30,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
            ],
        },
        {
            key: 'statusGroup',
            label: '',
            labelToolbar: '',
            pinned: null,
            isChecked: true,
            columns: [
                {
                    id: 15,
                    key: 'loadStatus',
                    label: 'Status',
                    labelToolbar: 'Status',
                    width: 138,
                    minWidth: 90,
                    maxWidth: 150,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: LoadSortBy.Status,
                },
            ],
        },
        {
            key: 'requirementGroup',
            label: 'Req',
            labelToolbar: 'Requirement',
            pinned: null,
            isChecked: true,
            columns: [
                {
                    id: 16,
                    key: 'requirementTruck',
                    label: 'Truck',
                    labelToolbar: 'Truck Type',
                    width: 64,
                    minWidth: 50,
                    maxWidth: 220,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: LoadSortBy.TruckType,
                },
                {
                    id: 17,
                    key: 'requirementTrailer',
                    label: 'Trailer',
                    labelToolbar: 'Trailer Type',
                    width: 64,
                    minWidth: 50,
                    maxWidth: 220,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: LoadSortBy.TrailerType,
                },
                {
                    id: 18,
                    key: 'requirementLength',
                    label: '',
                    labelToolbar: 'Length',
                    width: 52,
                    minWidth: 32,
                    maxWidth: 70,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: LoadSortBy.TrailerLength,
                },
                {
                    id: 19,
                    key: 'requirementDoor',
                    label: 'Door',
                    labelToolbar: 'Door Type',
                    width: 90,
                    minWidth: 52,
                    maxWidth: 110,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
                {
                    id: 20,
                    key: 'requirementSuspension',
                    label: 'Suspension',
                    labelToolbar: 'Suspension',
                    width: 90,
                    minWidth: 45,
                    maxWidth: 110,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: LoadSortBy.Suspension,
                },
                {
                    id: 21,
                    key: 'requirementYear',
                    label: 'Year',
                    labelToolbar: 'Year',
                    width: 58,
                    minWidth: 50,
                    maxWidth: 64,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: LoadSortBy.Year,
                },
                {
                    id: 22,
                    key: 'requirementLiftgate',
                    label: 'Liftgate',
                    labelToolbar: 'Liftgate',
                    width: 72,
                    minWidth: 50,
                    maxWidth: 78,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
            ],
        }*/,
        {
            key: 'driverMessageGroup',
            label: '',
            labelToolbar: '',
            pinned: null,
            isChecked: true,
            columns: [
                {
                    id: 23,
                    key: 'driverMessage',
                    label: 'Driver Message',
                    labelToolbar: 'Driver Message',
                    width: 234,
                    minWidth: 100,
                    maxWidth: 310,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: LoadSortBy.DriverMessage,
                },
            ],
        },
        {
            key: 'milesGroup',
            label: 'Miles',
            labelToolbar: 'Miles',
            pinned: null,
            isChecked: true,
            columns: [
                {
                    id: 24,
                    key: 'milesLoaded',
                    label: 'Loaded',
                    labelToolbar: 'Loaded',
                    width: 78,
                    minWidth: 30,
                    maxWidth: 88,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: MilesStopSortBy.LoadedMiles,
                },
                {
                    id: 25,
                    key: 'milesEmpty',
                    label: 'Empty',
                    labelToolbar: 'Empty',
                    width: 78,
                    minWidth: 30,
                    maxWidth: 88,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: MilesStopSortBy.EmptyMiles,
                },
                {
                    id: 26,
                    key: 'milesTotal',
                    label: 'Total',
                    labelToolbar: 'Total',
                    width: 78,
                    minWidth: 30,
                    maxWidth: 88,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: MilesStopSortBy.TotalMiles,
                },
            ],
        },
        {
            key: 'billingGroup',
            label: 'Billing',
            labelToolbar: 'Billing',
            pinned: null,
            isChecked: true,
            columns: [
                {
                    id: 27,
                    key: 'billingRatePerMile',
                    label: 'RPM',
                    labelToolbar: 'Rate Per Mile',
                    width: 80,
                    minWidth: 50,
                    maxWidth: 80,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
                {
                    id: 28,
                    key: 'billingLayover',
                    label: 'Layover',
                    labelToolbar: 'Layover',
                    width: 101,
                    minWidth: 60,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
                {
                    id: 29,
                    key: 'billinglumper',
                    label: 'Lumper',
                    labelToolbar: 'Lumper',
                    width: 101,
                    minWidth: 60,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
                {
                    id: 30,
                    key: 'billingFuelSurcharge',
                    label: 'Fuel Surch',
                    labelToolbar: 'Fuel Surcharge',
                    width: 101,
                    minWidth: 60,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
                {
                    id: 31,
                    key: 'billingEscort',
                    label: 'Escort',
                    labelToolbar: 'Escort',
                    width: 101,
                    minWidth: 60,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
                {
                    id: 32,
                    key: 'billingDetention',
                    label: 'Detention',
                    labelToolbar: 'Detention',
                    width: 101,
                    minWidth: 60,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                },
                {
                    id: 33,
                    key: 'billingRate',
                    label: 'Rate',
                    labelToolbar: 'Rate',
                    width: 101,
                    minWidth: 60,
                    maxWidth: 140,
                    isResizable: true,
                    isAlignedRight: true,
                    isChecked: true,
                    hasSort: true,
                },
                {
                    id: 34,
                    key: 'billingPaid',
                    label: 'Paid',
                    labelToolbar: 'Paid',
                    width: 101,
                    minWidth: 60,
                    maxWidth: 140,
                    isResizable: true,
                    isAlignedRight: true,
                    isChecked: true,
                    hasSort: true,
                },
            ],
        },
        {
            id: 35,
            key: 'dateCreated',
            label: 'Created',
            labelToolbar: 'Date Created',
            pinned: null,
            width: 88,
            minWidth: 72,
            maxWidth: 88,
            isResizable: true,
            isChecked: true,
            hasSort: true,
            sortName: LoadSortBy.AddedDate,
        },
        {
            id: 36,
            key: 'dateEdited',
            label: 'Edited',
            labelToolbar: 'Date Edited',
            pinned: null,
            width: 88,
            minWidth: 72,
            maxWidth: 88,
            isResizable: true,
            isChecked: true,
            hasSort: true,
            sortName: LoadSortBy.EditedDate,
        },
        {
            id: 37,
            key: 'note',
            label: '',
            labelToolbar: '',
            pinned: 'right',
            width: 26,
            minWidth: 26,
            isResizable: false,
            isDisabled: true,
            isChecked: true,
            hasSort: false,
        },
        {
            id: 38,
            key: 'action',
            label: '',
            labelToolbar: '',
            pinned: 'right',
            width: 26,
            minWidth: 26,
            isResizable: false,
            isChecked: true,
            isDisabled: true,
            hasSort: false,
        },
    ];

    static closedColumns: ITableColumn[] = [
        {
            key: 'select',
            label: '',
            pinned: 'left',
            width: 32,
            minWidth: 32,
            maxWidth: 200,
            isResizable: true,
            isDisabled: true,
            isChecked: true,
            hasSort: false,
        },
        {
            key: 'loadNumber',
            label: 'Invoice No',
            labelToolbar: 'Invoice No.',
            width: 146,
            minWidth: 126,
            maxWidth: 156,
            isResizable: true,
            isDisabled: true,
            hasSort: true,
            isChecked: true,
            pinned: 'left',
        },
        {
            key: 'loadType',
            label: 'Type',
            labelToolbar: 'Type',
            width: 82,
            minWidth: 82,
            maxWidth: 100,
            isResizable: true,
            isChecked: false,
            hasSort: true,
        },
        {
            key: 'loadDispatcher',
            label: 'Dispatcher',
            labelToolbar: 'Dispatcher',
            width: 208,
            minWidth: 50,
            maxWidth: 1020,
            isResizable: true,
            isChecked: true,
            hasSort: true,
            sortName: LoadSortBy.Dispatcher,
        },
        {
            key: 'companyName',
            label: 'Company',
            labelToolbar: 'Company',
            width: 238,
            minWidth: 50,
            maxWidth: 1020,
            isResizable: true,
            isChecked: false,
            // hasSort: true,
            // sortName: LoadSortBy.,
        },
        {
            key: 'brokerGroup',
            label: 'Broker',
            labelToolbar: 'Broker Detail',
            columns: [
                {
                    key: 'brokerBusinessName',
                    label: 'Business Name',
                    labelToolbar: 'Business name',
                    width: 238,
                    minWidth: 50,
                    maxWidth: 1020,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: LoadSortBy.BrokerBusinessName,
                },
                {
                    key: 'brokerContact',
                    label: 'Contact',
                    labelToolbar: 'Contact',
                    width: 186,
                    minWidth: 50,
                    maxWidth: 550,
                    isResizable: true,
                    isChecked: false,
                    hasSort: true,
                    sortName: LoadSortBy.BrokerContactName,
                },
                {
                    key: 'brokerPhone',
                    label: 'Phone',
                    labelToolbar: 'Phone',
                    width: 188,
                    minWidth: 150,
                    maxWidth: 220,
                    isResizable: true,
                    isChecked: false,
                    hasSort: true,
                    sortName: LoadSortBy.BrokerContactPhone,
                },
            ],
        },
        {
            key: 'referenceNumberGroup',
            label: '',
            labelToolbar: '',
            columns: [
                {
                    key: 'referenceNumber',
                    label: 'REF NO',
                    labelToolbar: 'Ref Number',
                    width: 108,
                    minWidth: 64,
                    maxWidth: 160,
                    isResizable: true,
                    isChecked: true,
                    // hasSort: true,
                },
            ],
        },
        {
            key: 'commodityGroup',
            label: '',
            labelToolbar: '',
            columns: [
                {
                    key: 'commodity',
                    label: 'Commodity',
                    labelToolbar: 'Commodity',
                    width: 138,
                    minWidth: 100,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: false,
                    // hasSort: true,
                },
            ],
        },
        {
            key: 'weightGroup',
            label: '',
            labelToolbar: '',
            columns: [
                {
                    key: 'weight',
                    label: 'Weight',
                    labelToolbar: 'Weight',
                    width: 88,
                    minWidth: 54,
                    maxWidth: 110,
                    isResizable: true,
                    isChecked: false,
                    hasSort: true,
                    sortName: LoadSortBy.Weight,
                },
            ],
        },
        {
            key: 'assignedGroup',
            label: 'Assigned',
            labelToolbar: 'Assigned',
            hasSort: false,
            columns: [
                {
                    key: 'assignedDriver',
                    label: 'Driver',
                    labelToolbar: 'Driver',
                    width: 208,
                    minWidth: 50,
                    maxWidth: 1020,
                    isResizable: true,
                    isChecked: false,
                    // hasSort: true,
                },
                {
                    key: 'assignedDriverTruckNumber',
                    label: 'Truck',
                    labelToolbar: 'Truck',
                    width: 78,
                    minWidth: 30,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: false,
                    // hasSort: true,
                    // sortName: LoadSortBy,
                },
                {
                    key: 'assignedDriverTrailerNumber',
                    label: 'Trailer',
                    labelToolbar: 'Trailer',
                    width: 88,
                    minWidth: 30,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: false,
                    // hasSort: true,
                },
            ],
        },
        {
            key: 'statusGroup',
            label: '',
            labelToolbar: '',
            columns: [
                {
                    key: 'loadStatus',
                    label: 'Status',
                    labelToolbar: 'Status',
                    width: 138,
                    minWidth: 90,
                    maxWidth: 150,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: LoadSortBy.Status,
                },
            ],
        },
        {
            key: 'requirementGroup',
            label: 'Requirement',
            labelToolbar: 'Requirement',
            hasSort: false,
            columns: [
                {
                    key: 'requirementTruck',
                    label: 'Truck',
                    labelToolbar: 'Truck Type',
                    width: 64,
                    minWidth: 50,
                    maxWidth: 220,
                    isResizable: true,
                    isChecked: false,
                    hasSort: true,
                    sortName: LoadSortBy.TruckType,
                },
                {
                    key: 'requirementTrailer',
                    label: 'Trailer',
                    labelToolbar: 'Trailer Type',
                    width: 64,
                    minWidth: 50,
                    maxWidth: 220,
                    isResizable: true,
                    isChecked: false,
                    hasSort: true,
                    sortName: LoadSortBy.TrailerType,
                },
                {
                    key: 'requirementLength',
                    label: '',
                    labelToolbar: 'Length',
                    width: 52,
                    minWidth: 32,
                    maxWidth: 70,
                    isResizable: true,
                    isChecked: false,
                    hasSort: true,
                    sortName: LoadSortBy.TrailerLength,
                },
                {
                    key: 'requirementDoor',
                    label: 'Door',
                    labelToolbar: 'Door Type',
                    width: 90,
                    minWidth: 52,
                    maxWidth: 110,
                    isResizable: true,
                    isChecked: false,
                    // hasSort: true,
                    // sortName: LoadSortBy.,
                },
                {
                    key: 'requirementSuspension',
                    label: 'Suspension',
                    labelToolbar: 'Suspension',
                    width: 90,
                    minWidth: 45,
                    maxWidth: 110,
                    isResizable: true,
                    isChecked: false,
                    hasSort: true,
                    sortName: LoadSortBy.Suspension,
                },
                {
                    key: 'requirementYear',
                    label: 'Year',
                    labelToolbar: 'Year',
                    width: 58,
                    minWidth: 50,
                    maxWidth: 64,
                    isResizable: true,
                    isChecked: false,
                    hasSort: true,
                    sortName: LoadSortBy.Year,
                },
                {
                    key: 'requirementLiftgate',
                    label: 'Liftgate',
                    labelToolbar: 'Liftgate',
                    width: 72,
                    minWidth: 50,
                    maxWidth: 78,
                    isResizable: true,
                    isChecked: false,
                    // hasSort: true,
                    // sortName: LoadSortBy.,
                },
            ],
        },
        {
            key: 'driverMessageGroup',
            label: '',
            labelToolbar: '',
            columns: [
                {
                    key: 'driverMessage',
                    label: 'Driver Message',
                    labelToolbar: 'Driver Message',
                    width: 234,
                    minWidth: 100,
                    maxWidth: 310,
                    isResizable: true,
                    isChecked: false,
                    hasSort: true,
                    sortName: LoadSortBy.DriverMessage,
                },
            ],
        },
        {
            key: 'milesGroup',
            label: 'Miles',
            labelToolbar: 'Miles',
            hasSort: false,
            columns: [
                {
                    key: 'milesLoaded',
                    label: 'Loaded',
                    labelToolbar: 'Loaded',
                    width: 78,
                    minWidth: 30,
                    maxWidth: 88,
                    isResizable: true,
                    isChecked: false,
                    hasSort: true,
                    sortName: MilesStopSortBy.LoadedMiles,
                },
                {
                    key: 'milesEmpty',
                    label: 'Empty',
                    labelToolbar: 'Empty',
                    width: 78,
                    minWidth: 30,
                    maxWidth: 88,
                    isResizable: true,
                    isChecked: false,
                    hasSort: true,
                    sortName: MilesStopSortBy.EmptyMiles,
                },
                {
                    key: 'milesTotal',
                    label: 'Total',
                    labelToolbar: 'Total',
                    width: 78,
                    minWidth: 30,
                    maxWidth: 88,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: MilesStopSortBy.TotalMiles,
                },
            ],
        },
        {
            key: 'billingGroup',
            label: 'Billing',
            labelToolbar: 'Billing',
            hasSort: false,
            columns: [
                {
                    key: 'textPayTerms',
                    label: 'Term d.',
                    labelToolbar: 'Pay Term',
                    width: 68,
                    minWidth: 30,
                    maxWidth: 68,
                    isResizable: true,
                    isChecked: false,
                    //   hasSort: true,
                    //   sortName: LoadSortBy.,
                },
                {
                    key: 'ageUnpaid',
                    label: 'Age unp.',
                    labelToolbar: 'Age - Unpaid',
                    width: 61,
                    minWidth: 30,
                    maxWidth: 68,
                    isResizable: true,
                    isChecked: true,
                    //   hasSort: true,
                },
                {
                    key: 'agePaid',
                    label: 'Age paid',
                    labelToolbar: 'Age - Paid',
                    width: 61,
                    minWidth: 30,
                    maxWidth: 68,
                    isResizable: true,
                    isChecked: false,
                    //   hasSort: true,
                },
                {
                    key: 'billingRatePerMile',
                    label: 'RPM',
                    labelToolbar: 'Rate Per Mile',
                    width: 80,
                    minWidth: 50,
                    maxWidth: 80,
                    isResizable: true,
                    isChecked: false,
                    // hasSort: true,
                },
                {
                    key: 'billingLayover',
                    label: 'Layover',
                    labelToolbar: 'Layover',
                    width: 101,
                    minWidth: 60,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: false,
                    // hasSort: true,
                },
                {
                    key: 'lumper',
                    label: 'Lumper',
                    labelToolbar: 'Lumper',
                    width: 101,
                    minWidth: 60,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: false,
                    // hasSort: true,
                },
                {
                    key: 'fuelSurcharge',
                    label: 'Fuel Surch',
                    labelToolbar: 'Fuel Surcharge',
                    width: 101,
                    minWidth: 60,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: false,
                    // hasSort: true,
                },
                {
                    key: 'escort',
                    label: 'Escort',
                    labelToolbar: 'Escort',
                    width: 101,
                    minWidth: 60,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: false,
                    // hasSort: true,
                },
                {
                    key: 'detention',
                    label: 'Detention',
                    labelToolbar: 'Detention',
                    width: 101,
                    minWidth: 60,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: false,
                    // hasSort: true,
                },
                {
                    key: 'billingRate',
                    label: 'Rate',
                    labelToolbar: 'Rate',
                    width: 101,
                    minWidth: 60,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: true,
                    // hasSort: true,
                },
                {
                    key: 'paid',
                    label: 'Paid',
                    labelToolbar: 'Paid',
                    width: 101,
                    minWidth: 60,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: true,
                    hasSort: true,
                    sortName: LoadSortBy.PaidDate,
                },
                {
                    key: 'due',
                    label: 'Due',
                    labelToolbar: 'Due',
                    width: 101,
                    minWidth: 60,
                    maxWidth: 140,
                    isResizable: true,
                    isChecked: true,
                    //   hasSort: true,
                },
            ],
        },
        {
            key: 'InvoicedDate',
            label: 'Invoiced',
            labelToolbar: 'Invoiced Date',
            width: 88,
            minWidth: 72,
            maxWidth: 88,
            isResizable: true,
            isChecked: false,
            hasSort: true,
            sortName: LoadSortBy.InvoicedDate,
        },
        {
            key: 'paidDate',
            label: 'Date Paid',
            labelToolbar: 'Paid Date',
            width: 88,
            minWidth: 72,
            maxWidth: 88,
            isResizable: true,
            isChecked: false,
            hasSort: true,
            sortName: LoadSortBy.PaidDate,
        },
        {
            key: 'dateCreated',
            label: 'Created',
            labelToolbar: 'Date Created',
            width: 88,
            minWidth: 72,
            maxWidth: 88,
            isResizable: true,
            isChecked: false,
            hasSort: true,
            sortName: LoadSortBy.AddedDate,
        },
        {
            key: 'dateEdited',
            label: 'Edited',
            labelToolbar: 'Date Edited',
            width: 88,
            minWidth: 72,
            maxWidth: 88,
            isResizable: true,
            isChecked: false,
            hasSort: true,
            sortName: LoadSortBy.EditedDate,
        },
        {
            key: 'note',
            label: 'Note',
            width: 26,
            minWidth: 26,
            isResizable: false,
            isDisabled: false,
            isChecked: true,
            hasSort: false,
        },
        {
            key: 'action',
            label: '',
            width: 26,
            minWidth: 26,
            maxWidth: 26,
            isResizable: false,
            isChecked: true,
            hasSort: false,
        },
    ];
}
